### ISSUE TITLE
A CPU is wasted

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#100]
When I try to deploy matching CPU constraints to available resources I get

```
Error from server (when using cpuset, you must use whole cpu cores, but rack eu-central-1a has 1930m): error when creating "cluster.yaml": admission webhook "validating-create-update-cluster.scylladb.com" denied the request: when using cpuset, you must use whole cpu cores, but rack eu-central-1a has 1930m
```

I assume this is a result of having static cpu manager policy, anyway this is quite wasteful.

**Comment by raphaelsc** [comment]
On Fri, May 29, 2020 at 7:55 AM Michal Jan Matczuk <notifications@github.com>
wrote:

> When I try to deploy matching CPU constraints to available resources I get
>
> Error from server (when using cpuset, you must use whole cpu cores, but rack eu-central-1a has 1930m): error when creating "cluster.yaml": admission webhook "validating-create-update-cluster.scylladb.com" denied the request: when using cpuset, you must use whole cpu cores, but rack eu-central-1a has 1930m
>
> I assume this is a result of having static cpu manager policy, anyway this
> is quite wasteful.
>

IIRC we dedicate a core for interrupt handling (IRQ). Not sure if this is
the case you were handling.

**Comment by mmatczuk** [comment]
If scylla decides to have interrupts on a dedicated shard is not relevant here.
k8s will not schedule pod if you want all cpus on the other hand it calls cpuset 0-1 - needs more investigation.

**Comment by dahankzter** [comment]
But for a production setup we want there to be dedicated whole cores right?

**Comment by mmatczuk** [comment]
We do not want to pay for a CPU that is not utilised. It needs to be checked how it works.

**Comment by dahankzter** [comment]
It's a little bit fun actually: https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/

The values and if requests are greater or smaller than limits and if they are integervalues depend which QoS class the pod enters as well as which cpu pool.

**Comment by mmatczuk** [comment]
It's not wasted, even with static cpu manager policy k8s does not set cpus.
