### ISSUE TITLE
is ScyllaDB certified for Openshift platform(OCP) deployments?

### ISSUE THREAD

**Issue by uguracarED** [scylladb/scylla-operator#1020]
**Describe the bug**
We are considering to deploy our solution to an Openshift cluster. SycllaDB is an element within our backend system. 
We'd like to better understand whether ScyllaDB is OCP certified (https://catalog.redhat.com/platform/red-hat-openstack/software/search) or not. 
In other words,  is OCP a supported platform for ScyllaDB deployments.  

**To Reproduce**
1.  Install ScyllaDB as a container to an OpenShift Cluster (4.8 / 4.10) with a restricted security context

**Expected behavior**
ScyllaDB container should be up and running.  

**Config Files**
N/A

**Logs**
N/A

**Environment:**
 - Platform: Openshift 
 - Opeshift version: 4.8.10 
 - Scylla version: 4.6.3
 - Scylla-operator version: e.g.: master, 8e155d0...

**Additional context**
N/A

**Comment by tnozicka** [comment]
> In other words, is OCP a supported platform for ScyllaDB deployments.

OCP isn't supported yet. At this point, we support (and test) only EKS and GKE.

That said, the operator is written to work on any Kubernetes platform. The difference with OCP is that it's likely gonna need some extra permissions for the more fine-grained levels used by that platform. Maybe some of the tips in https://github.com/scylladb/scylla-operator/issues/424 will help you get it off the ground. Hopefully, we'll get some cycles to support OpenShift soon.
