### ISSUE TITLE
Deployment manifests use too old K8S APIs which are dropped in v1.25

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1023]
**Describe the bug**
Operator's deployment manifests, which install operator and manager, use `policy/v1beta1`  API for the `PodDisruptionBudget` objects.
And the problem with it is that in K8S `v1.25` this API was dropped [1].

Here is how the error looks like if we try to install the operator on the newest K8S:
```
E               Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": \
    no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
E               helm.go:84: [debug] unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```

[1] https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25

**To Reproduce**
1. Install K8S v1.25
2. Try to install operator
3. See error

**Expected behavior**
Deployment manifests must use stable APIs where possible

**Environment:**
 - Platform: any/unrelated
 - Kubernetes version: v1.25
 - Scylla version: any/unrelated
 - Scylla-operator version: all

**Comment by zimnx** [comment]
It will be fixed by https://github.com/scylladb/scylla-operator/pull/1005

**Comment by zimnx** [comment]
Fixed by https://github.com/scylladb/scylla-operator/pull/1005
