### ISSUE TITLE
 no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by omarkad2** [scylladb/scylla-operator#1027]
**Describe the bug**
When installing scylla-operator chart version `1.7.4` on k8s version `1.25.0` I get the error ` no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"`

**To Reproduce**
1. `helm repo add scylla https://scylla-operator-charts.storage.googleapis.com/stable`
2. `helm repo update`
3. `helm install scylla-operator scylla/scylla-operator --create-namespace --namespace scylla-operator`
4. Error

**Expected behavior**
A successful installation

**Environment:**
 - Platform: Custom (Bare-metal kubernetes)
 - Kubernetes version: 1.25.0
 - Scylla-operator version: 1.7.4

**Comment by tnozicka** [comment]
1.7 doesn't support kubernetes 1.25 - see https://github.com/scylladb/scylla-operator/blob/master/docs/source/releases.md#support-matrix

**Comment by tnozicka** [comment]
(this has been fixed on master branch)
