### ISSUE TITLE
Deprecated actions in our CI

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#1063]
CI jobs are issuing a warning about deprecated actions:
 
```
--
Node.js 12 actions are deprecated. For more information see: 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
Please update the following actions to use Node.js 16: actions/checkout, actions/setup-go, actions/upload-artifact, actions/checkout
 ```

**Comment by rjeczalik** [comment]
You can always outsource the task to dependabot - https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot.

Example - https://github.com/scylladb/siren/blob/master/.github/dependabot.yml
