### ISSUE TITLE
Unable to set SCHED_FIFO scheduling policy for timer thread

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#107]
```
WARN  2020-05-29 14:19:04,916 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
WARN  2020-05-29 14:19:05,032 [shard 0] iotune - nomerges for /sys/devices/pci0000:00/0000:00:1e.0/nvme/nvme0/nvme0n1/queue/nomerges set to 0. It is recommend to set it to 2 before evaluation so that merges are disabled. Results can be skewed otherwise.
WARN  2020-05-29 14:21:07,438 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
```

**Comment by gnumoreno** [comment]
In docker-compose this is resolved by using:
```
    cap_add:
      - SYS_NICE
```

on plain docker:
```
--cap-add=sys_nice
```

kubernetes:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/policy/container-capabilities/
https://www.weave.works/blog/container-capabilities-kubernetes/

**Comment by mmatczuk** [comment]
We already run with "SYS_NICE".
Running privileged allows to set nomerges but the warning does not go away.

**Comment by gnumoreno** [comment]
I think nomerges is a scylla problem, not an operator problem.

**Comment by slivne** [comment]
on the AMI I think we set this on the disk whenever scylla starts in
scylla_prepare

you can try and work around this for now by changing this at the Pod level.

**Comment by pgoron** [comment]
Is there any plan to make scylla operator generate following securityContext in pod template of statefulsets:
    securityContext:
      capabilities:
        add:
        - SYS_NICE

Would you accept a contribution in that sense ?

**Comment by pgoron** [comment]
sorry it's already properly generated by the operator but somehow not being effective on my kube installation. I will have to dig more.

**Comment by erszcz** [comment]
I tried creating a test program for sanity checking cloud and container envs wrt to the available capabilities, but have a hard time setting SCHED_FIFO even in a local container. The steps to reproduce are here - https://gist.github.com/erszcz/5ceca0866df5748f9a3dda7654467f2d - is it at all possible to run Seastar based software in a container-based environment yet not get the `Unable to set SCHED_FIFO scheduling policy` warning?

**Comment by zimnx** [comment]
This log message no longer appears in Scylla container logs, and both processes (operator parent and scylla child) have desired capabilities.
 ```
[root@scylla-cluster-us-east1-us-east1-b-0 /]# ps aux | grep scylla
root           1  0.0  0.5 745204 38852 ?        Ssl  10:21   0:00 /mnt/shared/scylla-operator sidecar --service-name=scylla-cluster-us-east1-us-east1-b-0 --cpu-count=1 --loglevel=2
root          14  0.0  0.2  22068 16976 ?        S    10:21   0:00 /opt/scylladb/python3/bin/python3 /opt/scylladb/python3/bin/../libexec/python3.9.bin -s /docker-entrypoint.py --prometheus-address=0.0.0.0 --cpuset=0-1 --broadcast-address=10.203.240.156 --broadcast-rpc-address=10.203.240.156 --seeds=10.203.240.156 --overprovisioned=0 --smp=1 --listen-address=0.0.0.0 --developer-mode=0
root          47  5.2  1.7 17180010732 130372 ?  Sl   10:23   0:31 /usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-1 --smp 1 --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=10.203.240.156 --broadcast-address 10.203.240.156 --broadcast-rpc-address 10.203.240.156 --blocked-reactor-notify-ms 999999999 --prometheus-address=0.0.0.0
[root@scylla-cluster-us-east1-us-east1-b-0 /]# getpcaps 47 | grep nice
Capabilities for `47': = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_nice,cap_mknod,cap_audit_write,cap_setfcap+eip
[root@scylla-cluster-us-east1-us-east1-b-0 /]# getpcaps 1 | grep nice
Capabilities for `1': = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_nice,cap_mknod,cap_audit_write,cap_setfcap+eip
```
