### ISSUE TITLE
Helm upgrade AllowAllAuthenticator to PasswordAuthenticator

### ISSUE THREAD

**Issue by phanngt** [scylladb/scylla-operator#1072]
**Is this a bug report or feature request?**
Feature Request

**What should the feature do:**
I build Scylla by helm, following this tutorial docs https://operator.docs.scylladb.com/stable/helm.html on a private Kubernetes cluster.
After run few months, our team want to expose data for readonly. So I know I have to create user and roles.
However, default, the authenticator value is AllowAllAuthenticator. How can I upgrade helm chart as --authenticator=PasswordAuthenticator.

**What is use case behind this feature:**
Described above.

**Comment by zimnx** [comment]
Helm doesn't allow to set custom scylla configuration. You have to do it by creating ConfigMap, procedure is described here: https://operator.docs.scylladb.com/stable/generic.html#configure-scylla
