### ISSUE TITLE
Official arm64 images in docker hub

### ISSUE THREAD

**Issue by r5sec5cyl** [scylladb/scylla-operator#1078]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Build and deploy arm64 compatible docker images to DockerHub

**What is use case behind this feature:**
This feature would enable using the Scylla Operator to manage Scylla clusters on arm64 Kubernetes nodes.

**Additional Information:**
The Scylla image is available in arm64 and offers performance advantages over running Scylla in x86 environments. Scylla Operator offers operational advantages over directly using StatefulSets to manage Scylla clusters. For those running Scylla in clusters comprised only of nodes using the arm64 architecture or intending to deploy Scylla and Scylla Operator to a single node pool of arm64 instances, this feature would enable both operational and performance advantages.

**Comment by Kavinraja-G** [comment]
Do we have any timeline on this ? or any concers about publishing arm64 images?

**Comment by Givemeurcookies** [comment]
Would like to see the operator available for arm64 as well. There's more and more hosting providers (such as Hetzner and EKS) that now offer arm64 servers and they're perfect for running Kubernetes nodes and keeping down costs.

**Comment by tnozicka** [comment]
arm64 support has shipped with v1.12.0 https://forum.scylladb.com/t/release-scylla-operator-1-12-0/1446
