### ISSUE TITLE
Add option to enable different protocols

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1082]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
It should enable allowing and disabling these protocols:
- Alternator
- Alternator over TLS

**What is use case behind this feature:**
Being able to control the protocols exposed to the user.

**Additional Information:**
The non secure variant need to be disabled by default, at least eventually. For those currently expose we need to design a migration path.

**Comment by mykaul** [comment]
Is that still going to be in 1.9.x?

**Comment by tnozicka** [comment]
nope, just a stuck milestone, we use projects instead these days

**Comment by tnozicka** [comment]
There is no current priority for this one.
Sprint wise, you can see there is no sprint assigned (it's not gonna be worked during the next 2,5 weeks). Long term plans would be manifest on a roadmap which we are currently refreshing given the recent changes.
![Screenshot from 2023-08-16 13-11-41](https://github.com/scylladb/scylla-operator/assets/11869554/36cefa0c-06c3-435e-861a-f4cc045b689b)
