### ISSUE TITLE
Add experimental API that allows creating datacenters in different regions

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1093]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
We need to implement MultiDC support (multiple regions) but k8s clusters are only regional. To create a MultiDC we need to span a ScyllaCluster over multiple k8s clusters where each k8s cluster will represent a datacenter. Our current object (`ScyllaCluster.scylla.scylladb.com/v1) schema allows only for single DC definition.

The first step for this support is to:
- have an API object that allows defining multiple DC / datacenters are represented as an array (it can still be restricted to single DC in validation and loosen up later)
- allow creating those datacenter in remote k8s clusters when given a kubeconfig

**What is use case behind this feature:**
MultiDC support.

**Comment by Pionerd** [comment]
Any ETA on this?

**Comment by tnozicka** [comment]
The manual API for MultiDC is already present and allows for higher level operators to build on top of it. https://operator.docs.scylladb.com/stable/multidc/index.html
We don't have any plans to build the extended APIs in the open source operator at this point.
