### ISSUE TITLE
Unknown Flag --feature-gates after node restart

### ISSUE THREAD

**Issue by scottstaintoncollaboraite** [scylladb/scylla-operator#1100]
**Describe the bug**
After a node restart today some of our scylla pods will no longer start an emit a single log line of:

`Error: unknown flag: --feature-gates`

Some of our pods start fine, some of our pods do not and emit this error.

**To Reproduce**

I am not sure, launch multiple single node Scylla clusters, restart nodes, await pods restarting. 

**Expected behavior**
All pods would error if the flag is truly unknown, or none should error

**Config Files**
Standard generic cluster example with scylla-manager

**Logs**
Single log emitted from pods in error state:

`Error: unknown flag: --feature-gates`

**Environment:**
 - Platform: RKE2 self hosted kubernetes
 - Kubernetes version: 1.24.6
 - Scylla version: 4.6.3, 4.6.9, 5.0.5
 - Scylla-operator version: latest (docker.io/scylladb/scylla-operator@sha256:938eb06dd32ca9ca0a47724fbfdca51ebca94cd231ce217925589754bf64260d)

**Additional context**
The --feature-gates flag is passed via the command spec in the container definition (from the operator)

`/mnt/shared/scylla-operator sidecar --feature-gates=AllAlpha=false,AllBeta=false,AutomaticTLSCertificates=false --service-name=$(SERVICE_NAME)  --cpu-count=$(CPU_COUNT) --loglevel=2`

I think the error must be a red herring, surely there's no way 2 of the same containers can't parse the same flags

**Comment by zimnx** [comment]
Make sure to use stable releases, and not depend on `latest` tag which points to master builds. 
I suspect, in your case your sidecar image and operator image are different (even though they may use same `latest` tag) and it leads to such errors.

**Comment by tnozicka** [comment]
it's because the deployment consists of image+manifest. you can't update only one, which is exactly what using rolling tags like `:latest` is doing and why you should use stable tags (full version), or even better to use use sha.
