### ISSUE TITLE
Failing to connect to a cluster over SNI proxy when two tenant are configured

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-operator#1104]
**Describe the bug**

Connecting to via the AWS load balancer is failing   
```
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR > Traceback (most recent call last):
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 150, in wrapper
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >     return method(*args, **kwargs)
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 116, in inner
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >     res = func(*args, **kwargs)
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 745, in setUp
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >     self.set_system_auth_rf(db_cluster=db_cluster)
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >     return func(*args, **kwargs)
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 816, in set_system_auth_rf
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >     session.execute("ALTER KEYSPACE system_auth WITH replication = "
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1475, in execute_verbose
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >     return execute_orig(*args, **kwargs)
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >   File "cassandra/cluster.py", line 2696, in cassandra.cluster.Session.execute
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR >   File "cassandra/cluster.py", line 4998, in cassandra.cluster.ResponseFuture.result
< t:2022-11-21 21:01:04,357 f:tester.py       l:157  c:sdcm.tester          p:ERROR > cassandra.OperationTimedOut: errors={'Connection defunct by heartbeat': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=a36825d2ec0cc4384b836777bc60aff1-497119317.eu-north-1.elb.amazonaws.com:9142:3cbd5b84-12ec-4567-9f2d-b098c1f38201.cql.sct-cluster.sct.scylladb.com
```

**To Reproduce**
1. create two clusters (tenants) 
2. extract the bundle
3. try to connect to cluster one (sct-cluster namespace:scylla) 

**Expected behavior**
We should be able to connect to a cluster via the ELB, 

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
*Installation details*
Kernel version: `5.4.219-126.411.amzn2.x86_64`
Scylla version (or git commit hash): `5.2.0~dev-0.20221121.2d2034ea28b8 with build-id fecab23294c5676844595639bff8568f50cea06e`
Cluster size: 4 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   sct-cluster-us-east1-b-us-east1-0 (10.0.0.42 | 10.0.1.42): 7 shards
   sct-cluster-us-east1-b-us-east1-1 (10.0.2.143 | 10.0.2.162): 7 shards
   sct-cluster-us-east1-b-us-east1-2 (10.0.1.120 | 10.0.1.103): 7 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (k8s-eks: ['eu-north-1'])

Test: `longevity-scylla-operator-3h-multitenant-eks`
Test name: `longevity_operator_multi_tenant_test.LongevityOperatorMultiTenantTest.test_custom_time`
Test config file(s):
- [longevity-scylla-operator-3h-multitenant.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4c74bd0ec068b0048ff18dcca15bbcb7a04492f4/test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml)

Restore Monitor Stack command: `$ hydra investigate show-monitor 689ffc49-cb71-4f18-92c3-e00a65b20fd1`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=k8s_cloud_bundle&test_id=689ffc49-cb71-4f18-92c3-e00a65b20fd1)
Show all stored logs command: `$ hydra investigate show-logs 689ffc49-cb71-4f18-92c3-e00a65b20fd1`

Test id: `689ffc49-cb71-4f18-92c3-e00a65b20fd1`

db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/db-cluster-689ffc49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/db-cluster-689ffc49.tar.gz)
kubernetes - [https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/kubernetes-689ffc49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/kubernetes-689ffc49.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/loader-set-689ffc49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/loader-set-689ffc49.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/monitor-set-689ffc49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/monitor-set-689ffc49.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/sct-runner-689ffc49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/689ffc49-cb71-4f18-92c3-e00a65b20fd1/20221121_210254/sct-runner-689ffc49.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity-scylla-operator-3h-multitenant-eks/13/)

**Environment:**
 - Platform: EKS
 - Kubernetes version: 1.22 
 - Scylla version: 5.2.0~dev-0.20221121.2d2034ea28b8
 - Scylla-operator version: e.g.: master, 8e155d0...

**Additional context**

**Comment by fruch** [comment]
Capture of wireshark trying to connect with python-driver:

[python-driver-failure_port_9142.zip](https://github.com/scylladb/scylla-operator/files/10066321/python-driver-failure_port_9142.zip)

**Comment by fruch** [comment]
also disabling the shard_aware_port in the python-driver, made this problem go away.

**Comment by zimnx** [comment]
With ingresses we don't support shard aware ports yet, they shall be disabled in the driver if going through SNI proxy.

I don't see any traffic to 19142 in the attached wireshark though

**Comment by fruch** [comment]
> With ingresses we don't support shard aware ports yet, they shall be disabled in the driver if going through SNI proxy.
> 
> I don't see any traffic to 19142 in the attached wireshark though

Well I've captured it before knowing that was the issue. (and filter tcp.port == 9142)

Anyhow, we can disable it in the driver side, 
But shouldn't we at least define an option in bundle to control it ? so we won't need to release new drivers when we'll want to enable it ?

Is the gocql disable it ? does the java driver ?

**Comment by zimnx** [comment]
> But shouldn't we at least define an option in bundle to control it ? so we won't need to release new drivers when we'll want to enable it ?

Current approach (with sourcePort) is not going to work when there's a proxy in the middle, so new one has to implemented, drivers will need to ba changed anyway.

> Is the gocql disable it ?

gocql doesn't enable it, so it's disabled.

> does the java driver ?

I don't know, good question. @avelanarius

**Comment by avelanarius** [comment]
> > does the java driver ?
> 
> I don't know, good question. @avelanarius

Yes, advanced (port-based) shard-awareness is disabled:
https://github.com/scylladb/java-driver/commit/f7cbc11d4e123ece183890a0d37e3329654f0751#diff-25b018445a6d0cea48eb2ae925b87e9bccf60f12f1bbf59d4c3e7d13e85f79a0R1514

**Comment by fruch** [comment]
O.k. seems like I'm the only one that didn't thought about it 

I'll change the python-driver, to disable it by default.

It's mean we'll need to update cqlsh again...
