### ISSUE TITLE
Headless service does not expose the correct Prometheus port if changed from default

### ISSUE THREAD

**Issue by ohlen1** [scylladb/scylla-operator#1110]
**Describe the bug**
Headless service does not expose the correct Prometheus port if changed from default.

**To Reproduce**
1. Create a `scylla-config` config map, with property `prometheus_port` set to `7071`
2. Create a ScyllaCluster CRD. 
3. This will create a Scylla cluster according to configuration, one service for each POD and one headless service named `<cluster_name>-client`

**Expected behavior**
The headless service exposes the default port `9180` instead of port `7071`, which is what I would expect.

**Environment:**
 - Platform: AWS EKS
 - Kubernetes version: 1.21
 - Scylla version: 4.4.8
 - Scylla-operator version: 1.7.4

**Comment by tnozicka** [comment]
The operator reacts only to changes and desired state in the ScyllaCluster CRD. We have allowed passing the extra config to be able to tune ScyllaDB but it can't be used to change the topology. Any changes like that are not supported.
