### ISSUE TITLE
PVC permission issue while installing scylladb operator

### ISSUE THREAD

**Issue by neeldview** [scylladb/scylla-operator#1113]
trying to install [scylla-opeartor](https://github.com/scylladb/scylla-operator/blob/master/docs/source/generic.md#create-and-initialize-a-scylla-cluster) using this link in my already existing EKS cluster,  with 4 node groups (2 t3a.medium, 1 t3.medium, and m6g.medium )
the pods are not coming, on checking can see that the PVC is in Pending state due to the error attached.

to fix it gave nodes the proper IAM role of creating volume and even tried with IRSA permission to service account, still its not coming up
tried restarting , deleting and applying again etc... but still not working

<img width="1717" alt="Screenshot 2022-12-08 at 2 27 10 PM" src="https://user-images.githubusercontent.com/118246710/206402967-7aed3cda-fbcd-4140-b7d0-3d76db06e170.png">

**Comment by mykaul** [comment]
That looks like an EBS CSI issue - can you check if you can create such a request unrelated to Scylla, the operator, etc.?

**Comment by neeldview** [comment]
this is fixed thanks
