### ISSUE TITLE
Support cron in backups and repairs.

### ISSUE THREAD

**Issue by tokyowizard** [scylladb/scylla-operator#1114]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Support `cron` in `backups` and `repairs`. We'd like to use `cron` instead of `startDate`.

**What is use case behind this feature:**
If the `startDate` is set in the past, the controllers will complain with the following error message. So we'd have to update the `startDate` when the scylla-manager-controllers are restarted after the `startDate`.
```
E1212 02:06:31.796710       1 manager/controller.go:141] syncing key 'prod/scylla-cluster' failed: runSync repair tasks: transform to manager task: parse start date: start date cannot be in the past
```

The `sctool` docs mentions that the `--start-date` flag is deprecated and to use `--cron`. 

* ```
   –start-date is deprecated, please use –cron instead 
   ```
   * https://manager.docs.scylladb.com/stable/sctool/repair.html
   * https://manager.docs.scylladb.com/stable/sctool/backup.html
 

**Additional Information:**
Somewhat related issues about `startDate`.
* https://github.com/scylladb/scylla-operator/issues/838
* https://github.com/scylladb/scylla-operator/issues/767

**Comment by rzetelskik** [comment]
Fixed with https://github.com/scylladb/scylla-operator/pull/1851
