### ISSUE TITLE
Missing cpuset setting in docs example for guaranteed QoS

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1129]
**Describe the bug**
In https://operator.docs.scylladb.com/stable/performance.html is mentioned to use static CPU manager policy. To make use of it `cpuset` setting should be enabled. The mentioned example misses that part.

**Comment by zimnx** [comment]
These two aren't related. 
CPU Manager Policy is kubelet configuration option, where `cpuset` in ScyllaCluster is a flag controlling additional validation logic. Not having `cpuset` enabled, doesn't prevent Pod from getting Guaranteed QoS class.

**Comment by mykaul** [comment]
> These two aren't related. CPU Manager Policy is kubelet configuration option, where `cpuset` in ScyllaCluster is a flag controlling additional validation logic. Not having `cpuset` enabled, doesn't prevent Pod from getting Guaranteed QoS class.

Yes, but we do need the CPU manager, to control alignment of nodes to cores, no?
```
The following policy options exist for the static CPUManager policy:

full-pcpus-only (beta, visible by default) (1.22 or higher)
distribute-cpus-across-numa (alpha, hidden by default) (1.23 or higher)
align-by-socket (alpha, hidden by default) (1.25 or higher)
```

We probably need the 1st and 3rd?

**Comment by soyacz** [comment]
According to docs:
```
cpuset: Optional field. If it’s true, then the operator will start Scylla with cpu pinning for maximum performance
```
This setting is not mentioned in performance docs.

Anyway, isn't `cpuset` flag needed to make full benefit of static CPU Manager Policy?

**Comment by zimnx** [comment]
> Yes, but we do need the CPU manager, to control alignment of nodes to cores, no?

We do, but I don't see how `cpuset` is related. It's not a prerequisite for having Guaranteed QoS class, which is required for getting exclusive CPU.  

> We probably need the 1st and 3rd?

Yes.


> According to docs:
> 
> ```
> cpuset: Optional field. If it’s true, then the operator will start Scylla with cpu pinning for maximum performance
> ```
> 
> This setting is not mentioned in performance docs.

This isn't accurate, afaik cpu is pinned even without this setting.

> Anyway, isn't cpuset flag needed to make full benefit of static CPU Manager Policy?

No, Guaranteed QoS class is required.

**Comment by soyacz** [comment]
I also did some training regarding scylla-operator, in Scylla University quiz cpu pinning is explicitly mentioned: 
![k8s-cpu-pinning](https://user-images.githubusercontent.com/18242288/209793561-06595be2-485e-4286-ab06-16519c9c16ee.png)

I'm I misunderstanding something?

**Comment by mykaul** [comment]
Is this going to 1.9?
