### ISSUE TITLE
scylla-operator-1.8.0-alpha.0: promote PodDisruptionBudgets from v1beta1 to v1

### ISSUE THREAD

**Issue by KirillB-ec-ai** [scylladb/scylla-operator#1132]
**Describe the bug**
After updating GKE to the 1.25 version Scylla-Manager can't be deployed via Argo because there is an error with PodDisruptionBudgets.
Helm chart contains a template with old apiVersion. 

**Environment:**
 - Platform: GKE
 - Kubernetes version:  1.25
 - repoURL: https://storage.googleapis.com/scylla-operator-charts/latest
 - targetRevision: v1.8.0-alpha.0-nightly
 - Scylla-Manager: 2.6.5

**Comment by KirillB-ec-ai** [comment]
Also have question about image version, what image should be for scyllaImage and agentImage??

This is what values.yaml has at this moment
```
scylla:
  developerMode: true
  scyllaImage:
    tag: 4.3.0
  agentImage:
    tag: 2.2.1
```
 But If look here https://github.com/scylladb/scylla-operator/blob/master/docs/source/releases.md#support-matrix , it seems that scyllaumage should be 4.6.5

**Comment by Alexandre-P-J** [comment]
policy/v1beta1 was deprecated in k8s v1.21, and is unavailable in v1.25+

**Comment by tnozicka** [comment]
1.25 isn't supported yet as it is documented in our support matrix for 1.7
https://github.com/scylladb/scylla-operator/blob/master/docs/source/releases.md#support-matrix

1.8 will bring support for kubernetes 1.25+

**Comment by tnozicka** [comment]
closing as it's fixed on master

**Comment by vponomaryov** [comment]
> closing as it's fixed on master

Here: https://github.com/scylladb/scylla-operator/pull/1005
