### ISSUE TITLE
Run e2e on newer Kubernetes version

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#1137]
Currenly used 1.23 is approaching EOL, we should bump our Kubernetes version in CI to at least 1.24.

**Comment by mykaul** [comment]
Isn't that what https://github.com/scylladb/scylla-operator/pull/1106 is all about?

**Comment by zimnx** [comment]
> Isn't that what #1106 is all about?

It is, this is an issue above PR will fix. Just needed a pointer.
