### ISSUE TITLE
schema disagreement error attempting to insert data after the Scylla upgrade

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1150]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

User cannot perform some queries.

## How frequently does it reproduce?

It was reproduced 2 times from 2.

## Installation details

Kernel Version: 5.15.0-1020-gke
Scylla version (or git commit hash): `5.0.5-20221009.5a97a1060` with build-id `5009658b834aaf68970135bfc84f964b66ea4dee`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.1/scylla-x86_64-package-5.1.2.0.20221225.4c0f7ea09893.tar.gz
Operator Image: scylladb/scylla-operator:1.8.0-rc.0
Operator Helm Version: 1.8.0-rc.0
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 3 nodes (n1-standard-8)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `N/A` (k8s-gke: us-east1-b)

Test: `upgrade-major-scylla-k8s-gke`
Test id: `207bdbdc-673c-4c52-ac37-44faddabe464`
Test name: `scylla-operator/operator-1.8/upgrade/upgrade-major-scylla-k8s-gke`
Test config file(s):

- [kubernetes-scylla-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/10663945a53627f216a141cedf5d2640f0f814f3/test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml)

&lt;details&gt;
&lt;summary&gt;

Running Scylla upgrade from `5.0.5-0.20221009.5a97a1060 with build-id 5009658b834aaf68970135bfc84f964b66ea4dee` to `5.1.2-0.20221225.4c0f7ea09893 with build-id 4817fe236d57eca203f35b1dbb4bfe43cab72590` on K8S backend (GKE) we faced following problem:

Logs with error:
```
> Executing CQL 'INSERT INTO ks_no_range_ghost_test.users (KEY, password) VALUES ('user1', 'ch@ngem3a')' ... 
> Retrying request after UE. Attempt #0                                                                
> [control connection] Schemas mismatched, trying again                                                
                                                                                                       
... 48 more attempts each 200ms ...                                                                        
                                                                                                       
> [control connection] Schemas mismatched, trying again                                                
G > Node 10.108.5.7:9042 is reporting a schema disagreement: {UUID('8af28221-bae0-35a1-bd3c-7bb3a7caf720'): [<DefaultEndPoint: 10.112.2.191:9042>, <DefaultEndPoint: 10.108.5.7:9042>], UUID('6e637294-2c1e-3fc9-a573-a83a5fc50e8f'): [<DefaultEndPoint: 10.112.9.194:9042>]}
> Skipping schema refresh due to lack of schema agreement                                              
> [control connection] Waiting for schema agreement                                                    
> Retrying request after UE. Attempt scylladb/scylladb#1                                                                
> [control connection] Schemas mismatched, trying again                                                
> Retrying request after UE. Attempt scylladb/scylladb#2                                                                
> Retrying request after UE. Attempt scylladb/scylladb#3                                                                
> Retrying request after UE. Attempt scylladb/scylladb#4                                                                
> INSERT INTO ks_no_range_ghost_test.users (KEY, password) VALUES ('user1', 'ch@ngem3a') < t:2023-01-04 17:37:51,821 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > INSERT INTO ks_no_range_ghost_test.users (KEY, password) VALUES ('user1', 'ch@ngem3a')
> Traceback (most recent call last):                                                                   
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3252, in _run_db_queries       
>     res = session.execute(item['queries'][i])                                                        
>   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1552, in execute_verbose       
>     return execute_orig(*args, **kwargs)                                                             
>   File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute                       
>   File "cassandra/cluster.py", line 5006, in cassandra.cluster.ResponseFuture.result                 
> cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl QUORUM. Requires 1, alive 0" info={'consistency': 'QUORUM', 'required_replicas': 1, 'alive_replicas': 0}
```

We run lots of commands, but the same one failed in the same place in 2 different test runs.

And [second test run](https://jenkins.scylladb.com/view/scylla-operator/job/scylla-operator/job/operator-1.8/job/upgrade/job/upgrade-major-scylla-k8s-gke/2/) was using enterprise Scylla upgrading from the `2021.1.17-0.20221221.5318a7fec with build-id d4378bd13d179b4bbcde7bdc82b92d8cc71c52d8` to the `2022.1.3-0.20220922.539a55e35 with build-id d1fb2faafd95058a04aad30b675ff7d2b930278d` version.

&lt;/summary&gt;

- Restore Monitor Stack command: `$ hydra investigate show-monitor 207bdbdc-673c-4c52-ac37-44faddabe464`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=207bdbdc-673c-4c52-ac37-44faddabe464)
- Show all stored logs command: `$ hydra investigate show-logs 207bdbdc-673c-4c52-ac37-44faddabe464`

## Logs:
- **db-cluster-207bdbdc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/db-cluster-207bdbdc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/db-cluster-207bdbdc.tar.gz)
- **sct-runner-207bdbdc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/sct-runner-207bdbdc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/sct-runner-207bdbdc.tar.gz)
- **monitor-set-207bdbdc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/monitor-set-207bdbdc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/monitor-set-207bdbdc.tar.gz)
- **loader-set-207bdbdc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/loader-set-207bdbdc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/loader-set-207bdbdc.tar.gz)
- **kubernetes-207bdbdc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/kubernetes-207bdbdc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/207bdbdc-673c-4c52-ac37-44faddabe464/20230104_175036/kubernetes-207bdbdc.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.8/job/upgrade/job/upgrade-major-scylla-k8s-gke/4/)
&lt;/details&gt;

**Comment by rzetelskik** [comment]
@fruch #1077 is waiting for the input from the rest of the team and reviews
