### ISSUE TITLE
Add (optional) extended dashboards in ScyllaDBMonitoring and drop the unmanaged setup

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1155]
Having introduced the new API, setup and management for monitoring of our clusters in https://github.com/scylladb/scylla-operator/pull/1111, we should update the monitoring section of our documentation with new deployment instructions and remove the outdated manifests from example files.

**Comment by tnozicka** [comment]
We should also think about exposing some dashboards with infra that are not yet currently present. (The serverless dashboard is limited.)

**Comment by rzetelskik** [comment]
@tnozicka how would you see this done from the UI standpoint? Should the users be able to create their own, custom dashboards? Or should the ScyllaDBMonitoring API be extended with levels/options to choose from the predefined ones?

**Comment by tnozicka** [comment]
The API would define which dashboards are available on a high level, in spec. It should be above GrafanaSpec so in theory we could adjust Prometheus scraping based on it as well someday if we wanted to. Say `spec.spin` with either `SaaS` (default) or `Platform` option. Implementation wise `SaaS` could show extra `Platform` dashboards to admins only.

**Comment by rzetelskik** [comment]
Closing as complete in https://github.com/scylladb/scylla-operator/pull/1161
