### ISSUE TITLE
Issue in page Setting up Monitoring

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-operator#1157]
I would like to report an issue in page https://operator.docs.scylladb.com/v1.8/monitoring

### Problem
The page doesn't mention multiple required packages that need to be installed in order to complete the installation. Examples include 'helm' and 'yq' (the latter doesn't have an RPM for Fedora, for example).

**Comment by tnozicka** [comment]
yeah, that's not the best experience. we intent to drop it when we have an equivalent -  https://github.com/scylladb/scylla-operator/issues/1155

**Comment by rzetelskik** [comment]
Closing as completed in https://github.com/scylladb/scylla-operator/pull/1161
