### ISSUE TITLE
Add server side printers for ScyllaCluster

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1191]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
`kubectl get scyllacluster.scylla.scylladb.com` should print some meaningful info beyond its name and creationTimestamp. Likely `numberOfRacksReady/NumberOfRacks`, `totalMembersReady/totalMembers`, possibly others

**What is use case behind this feature:**
UX, compare e.g. a statefulset
```
$ kubectl get scyllacluster.scylla.scylladb.com,statefulset
NAME                                        AGE
scyllacluster.scylla.scylladb.com/example   33m

NAME                                            READY   AGE
statefulset.apps/example-us-east-1-us-east-1a   3/3     33m
statefulset.apps/prometheus-example             1/1     31m
```

**Additional Information:**

**Comment by mykaul** [comment]
Can we extend kubectl with some information?
https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

**Comment by tnozicka** [comment]
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns
