### ISSUE TITLE
We should set --memory flag

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#120]
In b6cf4f9 we have removed `--memory` flag, scylla should get this flag to indicate how much memory it has. The calculations should be removed and we should save 7% of all available memory for system, that includes kubernetes, node exporter and all side cars.

Scylla has no understanding of memory limits imposed by a 3rd party cgroup.

**Comment by dahankzter** [comment]
This was removed after consulting @nyh and @avi. It was calculated before but it resulted in a set of other issues when values were incorrectly set. Afaik Scylla should obey the cgroup and do a much better job of calculating it on it's own.

**Comment by mmatczuk** [comment]
That depends, typically this needs reading the limit from cgroup, maybe Scylla supports that.

**Comment by dorlaor** [comment]
You can verify it by applying a low limit, I doubt scylla uses the limit, @Avi
Kivity <avi@scylladb.com> ?

**Comment by yanniszark** [comment]
We discussed this a while back with @vladzcloudius a while back in Slack #scylla-operator channel and I remember reading scylla code that checked the cgroup value explicitly.
See: https://github.com/scylladb/seastar/blob/2a76993597db473b423ac927ce2f0cfd74a07e48/src/core/resource.cc#L113

My understanding is that Scylla autodetects the memory limit when inside a container.

**Comment by avikivity** [comment]
Yes, Scylla obeys the container memory limit if it is set.

**Comment by slivne** [comment]
@mmatczuk did you run a test and saw scylla fail to read the memory limit / compute memory incorrectly ?
