### ISSUE TITLE
docs: update theme 1.5

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/scylla-operator#1201]
Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/310

ScyllaDB Sphinx Theme 1.5 is now released 🥳 You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/master/upgrade/CHANGELOG.html#may-2023).

## Upgrade guide

For most repositories, we are sending pull-requests with new updates. Unfortunately, we cannot do this for this project since the [docs workflows](https://github.com/scylladb/sphinx-scylladb-theme/tree/master/.github/workflows) shared between all projects to build the docs [were highly modified](https://github.com/scylladb/scylla-operator/tree/master/.github/workflows).

> **TIP:** If you modify these workflows in your repository, you will need to maintain the changes. So instead, we recommend you to open an issue / pull-request in the [sphinx-scylladb-theme repository](https://github.com/scylladb/sphinx-scylladb-theme) so that all projects can benefit from the improvements you made.

Here you have resources to help you upgrade the docs toolchain to the latest version:

**1.2. to 1.3**
- [Migrating from 1.2 to 1.3](https://sphinx-theme.scylladb.com/stable/upgrade/1-2-to-1-3.html)
- [Sample pull-request 1.2 to 1.3](https://github.com/scylladb/scylla-monitoring/pull/1778)

**1.3 to 1.4**

- [Migrating from 1.3 to 1.4](https://sphinx-theme.scylladb.com/stable/upgrade/1-3-to-1-4.html)
- [Sample pull-request 1.3 to 1.4](https://github.com/scylladb/care-pet/pull/124/files)

**1.4 to 1.5**

- [Migrating from 1.4 to 1.5](https://sphinx-theme.scylladb.com/master/upgrade/1-4-to-1-5.html)
- [Sample pull-request 1.4 to 1.5](https://github.com/scylladb/care-pet/pull/139/files)

Do not hesitate to contact me (@dgarcia360 in Slack) if you face any issues during the process.

**Comment by dgarcia360** [comment]
We've released a new version. Updated the initial issue with the 1.4 to 1.5 migration guide.

**Comment by annastuchlik** [comment]
@tnozicka Could you review and merge this PR?
The Operator documentation is behind the rest of the docs, as it has the Sphinx theme version 1.3.5. The later releases have different fixes that should be applied to all project docs.

**Comment by annastuchlik** [comment]
@tnozicka ping
