### ISSUE TITLE
Pregenerate RSA keys and speed up bootstrap times

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1203]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The operator CPU cycles are limited. It often sits almost idle but when a new ScyllaCluster is created (or other CRs needing certs), it needs to generate a few RSA keys for certificates to represent the trust chains which often hits the CPU limit and takes a while. We can create a buffer of pre-generated keys that will make sure the CPU load is better spread over time and in the ideal case the keys are available right when needed.

**What is use case behind this feature:**
UX, better utilization

**Additional Information:**

**Comment by dorlaor** [comment]
How much time/power does it take to generate a single key?

**Comment by tnozicka** [comment]
> How much time/power does it take to generate a single key?

That quite depends on how much CPU cycles you have for it. IIRC, with 500m cpu it was about 5s for a 4096 bit key - 2048 are about 1/8th of that time but with any this will be concentrated into peaks and then we won't use almost any cpu. You also have to wait for the logic flow to ask for the cert to start generating it. This PR intend to smoothen the peaks and have a standby, so no mater what the constant (time) is, it will allow us to be able to bootstrap more clusters in parallel while paying for the same CPU cores.

**Comment by dorlaor** [comment]
On Wed, Apr 19, 2023 at 1:00 PM Tomáš Nožička ***@***.***>
wrote:

> How much time/power does it take to generate a single key?
>
> That quite depends on how much CPU cycles you have for it. IIRC, with 500m
> cpu it was about 5s for a 4096 bit key - 2048 are about 1/8th of that time
> but with any this will be concentrated into peaks and then we won't use
> almost any cpu. You also have
>
what's 500m cpu? Are those cycles? Single core?

**Comment by mykaul** [comment]
On Wed, Apr 19, 2023 at 1:16 PM Dor Laor ***@***.***> wrote:

> On Wed, Apr 19, 2023 at 1:00 PM Tomáš Nožička ***@***.***>
> wrote:
>
> > How much time/power does it take to generate a single key?
> >
> > That quite depends on how much CPU cycles you have for it. IIRC, with
> 500m
> > cpu it was about 5s for a 4096 bit key - 2048 are about 1/8th of that
> time
> > but with any this will be concentrated into peaks and then we won't use
> > almost any cpu. You also have
> >
> what's 500m cpu? Are those cycles? Single core?
>

Half a core.
 Y.
