### ISSUE TITLE
Operator should run cleanup when cluster is scaled up

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#1207]
According to [ScyllaDB documentation](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-node-to-cluster.html#procedure) about scaling up procedure, Operator should run a so called "cleanup" after scaling up the cluster, in order to remove the data no longer beloning to the node. 
Running it helps with keeping the disk space at minimum.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylla-operator/issues/1316
- [ ] https://github.com/scylladb/scylla-operator/issues/1317
```

**Comment by mykaul** [comment]
> @mykaul is this on of the things you are planing to automate with scylladb itself as it has all the info needed, or do we need to add this to the operator?

Yes, it will be in Scylla core, but it'll take time. I suspect in the mean time, we'll need the operator to do it.

**Comment by zimnx** [comment]
Design doc: https://docs.google.com/document/d/191QLTCCpifYPut6hcGHsh4Z5X0fYz4XBuSZRDFgHNlY/edit?usp=sharing

**Comment by tnozicka** [comment]
landed
