### ISSUE TITLE
Explain `"$cluster|$^"` regex matching used in Grafana dashboards

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1209]
Tracking issue as requested in https://github.com/scylladb/scylla-operator/pull/1199#discussion_r1159335442.

None of our developers seem to understand the logic behind the regexes used in many of the expressions in the Grafana dashboards coming from [scylladb/scylla-monitoring](https://github.com/scylladb/scylla-monitoring), namely `"$cluster|$^"`. We should understand what the purpose of `|$^` and what's event the purpose of using regex matching here.  

Related to https://github.com/scylladb/scylla-operator/pull/1199.

cc @tnozicka

**Comment by rzetelskik** [comment]
Waiting for @amnonh's reply in https://github.com/scylladb/scylla-operator/pull/1199#discussion_r1157479115

**Comment by amnonh** [comment]
It's used to handle a situation that the cluster label is missing
