### ISSUE TITLE
Deprecate old storage setup scripts in favour of new APIs

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1219]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
We should deprecate the old setup scripts like 
https://github.com/scylladb/scylla-operator/blob/d5f04bab76a8f0839d1fda58716eee81df366eca/examples/eks/node-setup-daemonset.yaml#L96
when the new automated storage PRs land and remove those scripts at one release after the new APIs are made available.

**What is use case behind this feature:**
Stability and maintainability.

**Additional Information:**
The old scripts are not managed and has shown to be fragile https://github.com/scylladb/scylla-operator/issues/1218

**Comment by rzetelskik** [comment]
Fixed in https://github.com/scylladb/scylla-operator/pull/1107 and https://github.com/scylladb/scylla-operator/pull/1269.
