### ISSUE TITLE
Use host network

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#122]
Setting host network:

```
diff --git a/pkg/controller/cluster/resource/resource.go b/pkg/controller/cluster/resource/resource.go
index b1820b2..b3fea6d 100644
--- a/pkg/controller/cluster/resource/resource.go
+++ b/pkg/controller/cluster/resource/resource.go
@@ -133,6 +133,7 @@ func StatefulSetForRack(r scyllav1alpha1.RackSpec, c *scyllav1alpha1.Cluster, si
                                        },
                                },
                                Spec: corev1.PodSpec{
+                                       HostNetwork: true,
                                        Volumes: []corev1.Volume{
                                                {
                                                        Name: "shared",
```

has doubled performance in my benchmark.

There should be a switch since running in minikube or other dind env may be affected.

**Comment by dorlaor** [comment]
Amazing that they don't have a middle ground solution between
performance and flexibility

**Comment by dyasny** [comment]
There are options for faster AND flexible networking:
quick and dirty: https://kubernetes.io/docs/concepts/cluster-administration/networking/#l2-networks-and-linux-bridging
and somewhat better: https://kubernetes.io/docs/concepts/cluster-administration/networking/#multus-a-multi-network-plugin

**Comment by dorlaor** [comment]
Wow, there are lots (too many) of possibilities. The CNI integration
with the cloud provider VPC looks interesting -
https://kubernetes.io/docs/concepts/cluster-administration/networking/#aws-vpc-cni-for-kubernetes.
It will be interesting to compare the host network mode with this one,
not just in terms of performance but also for accessing the cluster outside
of k8s

**Comment by slivne** [comment]
I think we should push the additional tests (with other networking options down the line). 
"HostNetwork: true" should be used for the performance eval.

I checked other vendors also recommend using host network for better performance https://www.cockroachlabs.com/docs/stable/kubernetes-performance.html#using-the-hosts-network

So its "common".

**Comment by dahankzter** [comment]
We can easily expose this choice to the end user so they at least can opt out of host networking if they have to.
