### ISSUE TITLE
Ability to disable prometheus and grafana

### ISSUE THREAD

**Issue by Mokto** [scylladb/scylla-operator#1223]
* Feature Request

**What should the feature do:**

Allow to disable both grafana and prometheus, sometimes they are already handled. 

So we would just create service monitor/prometheus rules

**Comment by tnozicka** [comment]
If this is about ScyllaDBMonitoring, you don't have to create it and you can manage it on your own. I don't think we'd go into business of setting up servicemonitors alone as that's fairly setup dependent and connected to the dashboards.
