### ISSUE TITLE
`add node` operation fails if a node with it's name was already `replaced` and `decommissioned`

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1240]
**Describe the bug**
The following `nemesis` scenario was run in the setup:
- Terminate EC2 instance that hosts the last Scylla pod
- Wait for the recreation of the K8S node by the AWS platform
- Decrease the replica number by 1 in the `scyllacluster` object configuration
- Wait for the pod deletion
- Increase the replica number  by 1 in the `scyllacluster` object configuration
- Wait for the pod readiness

So, we see following in the logs:

```
< t:2023-04-30 02:41:39,550 f:__init__.py     l:2471 c:sdcm.cluster_k8s     p:DEBUG > Replace `/spec/datacenter/racks/0/members' with `2' in sct-cluster-2's spec
...
INFO  2023-04-30 02:47:45,637 [shard 3] api - decommission
INFO  2023-04-30 02:47:45,638 [shard 0] storage_service - decommission[2557cfff-74fa-4bdb-8c2c-989da968cd69]: Started decommission operation: node=ce0091e0-f732-48f2-9038-18aaac5c8cee/172.20.114.237
INFO  2023-04-30 02:47:45,638 [shard 0] storage_service - decommission[2557cfff-74fa-4bdb-8c2c-989da968cd69]: sync_nodes=decommission, ignore_nodes=ce0091e0-f732-48f2-9038-18aaac5c8cee
INFO  2023-04-30 02:47:45,649 [shard 0] storage_service - DECOMMISSIONING: starts
...
INFO  2023-04-30 02:48:29,045 [shard 0] gossip - 60000 ms elapsed, 172.20.75.146 gossip quarantine over
INFO  2023-04-30 02:48:29,131 [shard 0] storage_service - Set host_id=5bee7f55-2980-459f-80c2-f2d93ac3a6ea to be owned by node=172.20.75.146
...
INFO  2023-04-30 02:49:38,673 [shard 0] gossip - Node 172.20.114.237 will be removed from gossip at [2023-05-03 02:49:38]
...
INFO  2023-04-30 02:50:09,259 [shard 0] storage_service - DECOMMISSIONING: done
...
< t:2023-04-30 02:50:54,895 f:__init__.py     l:2471 c:sdcm.cluster_k8s     p:DEBUG > Replace `/spec/datacenter/racks/0/members' with `3' in sct-cluster-2's spec
...
< t:2023-04-30 02:51:58,715 f:__init__.py     l:784  c:sdcm.utils.k8s       p:DEBUG > Processing following line: {
"type": "ADDED",
"object": {
    "kind": "Endpoints",
    "apiVersion": "v1",
    "metadata": {
        "name": "sct-cluster-2-us-east1-b-us-east1-2",
        "namespace": "scylla-2",
        "uid": "e232e652-f3b1-4cf2-b524-10aa27e44255",
        "resourceVersion": "22037",
        "creationTimestamp": "2023-04-30T02:51:58Z",
        "labels":{
            "app": "scylla",
            "app.kubernetes.io/managed-by": "scylla-operator",
            "app.kubernetes.io/name": "scylla",
            "scylla-operator.scylladb.com/scylla-service-type": "member",
            "scylla/cluster": "sct-cluster-2",
            "scylla/datacenter": "us-east1-b",
            "scylla/rack": "us-east1",
  -->       "scylla/replace": "172.20.75.146"
        },
        "annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2023-04-30T02:51:58Z"},
        "managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2023-04-30T02:51:58Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:endpoints.kubernetes.io/last-change-trigger-time":{}},"f:labels":{".":{},"f:app":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:scylla-operator.scylladb.com/scylla-service-type":{},"f:scylla/cluster":{},"f:scylla/datacenter":{},"f:scylla/rack":{},"f:scylla/replace":{}}}}}]}}}
```

And the automatic presence of the `replace` label leads to the following results:
```
I0430 02:52:26.030044       1 config/config.go:298] "Scylla entrypoint" Command="/docker-entrypoint.py --enable-sstable-key-validation=1 --listen-address=0.0.0.0 --developer-mode=0 --abort-on-lsa-bad-alloc=1 --abort-on-internal-error=1 --abort-on-ebadf=1 --seeds=172.20.250.151 --smp=7 --cpuset=1-3,8-11 --overprovisioned=0 --replace-address-first-boot=172.20.75.146 --broadcast-address=172.20.76.131 --broadcast-rpc-address=172.20.76.131 --prometheus-address=0.0.0.0"
...
ERROR 2023-04-30 02:54:31,340 [shard 0] init - Startup failed: std::runtime_error (Cannot replace_address 172.20.75.146 because it doesn't exist in gossip)
```

The `172.20.75.146` IP address belongs to the already deleted service.

List of the services in it's namespace:
```
scylla-2        sct-cluster-2-client                   ClusterIP      172.20.134.25    <none>    7000/TCP,7001/TCP,7199/TCP,10001/TCP,9180/TCP,5090/TCP,9100/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,9160/TCP   83m    app.kubernetes.io/managed-by=scylla-operator,app.kubernetes.io/name=scylla,app=scylla,scylla/cluster=sct-cluster-2
scylla-2        sct-cluster-2-us-east1-b-us-east1-0    ClusterIP      172.20.250.151   <none>    7000/TCP,7001/TCP,7199/TCP,10001/TCP,9180/TCP,5090/TCP,9100/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,9160/TCP   83m    statefulset.kubernetes.io/pod-name=sct-cluster-2-us-east1-b-us-east1-0
scylla-2        sct-cluster-2-us-east1-b-us-east1-1    ClusterIP      172.20.79.100    <none>    7000/TCP,7001/TCP,7199/TCP,10001/TCP,9180/TCP,5090/TCP,9100/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,9160/TCP   83m    statefulset.kubernetes.io/pod-name=sct-cluster-2-us-east1-b-us-east1-1
scylla-2        sct-cluster-2-us-east1-b-us-east1-2    ClusterIP      172.20.76.131    <none>    7000/TCP,7001/TCP,7199/TCP,10001/TCP,9180/TCP,5090/TCP,9100/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,9160/TCP   40m    statefulset.kubernetes.io/pod-name=sct-cluster-2-us-east1-b-us-east1-2
```

So, it looks like operator remembers the `replace` label and applies it again for the newly recreated pod with the same name which was decommissioned. And it leads to constant pod addition failure because of the impossibility to `replace` nonexistent Scylla member.

**To Reproduce**
1. Deploy operator
2. Perform the `nemesis` scenario steps described above
3. See error

**Expected behavior**
Scylla-operator should not apply the `replace` label to the member's service which gets created `in addition` to other existing members.

**Logs**
CI-job: https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-multitenant-eks/38
db-logs: https://cloudius-jenkins-test.s3.amazonaws.com/a4ecf954-6cce-4e71-be52-e07450679a12/20230430_034220/db-cluster-a4ecf954.tar.gz
test-runner-logs: https://cloudius-jenkins-test.s3.amazonaws.com/a4ecf954-6cce-4e71-be52-e07450679a12/20230430_034220/sct-a4ecf954.log.tar.gz
kubernetes-logs: https://cloudius-jenkins-test.s3.amazonaws.com/a4ecf954-6cce-4e71-be52-e07450679a12/20230430_034220/kubernetes-a4ecf954.tar.gz
loader-logs: https://cloudius-jenkins-test.s3.amazonaws.com/a4ecf954-6cce-4e71-be52-e07450679a12/20230430_034220/loader-set-a4ecf954.tar.gz

**Environment:**
 - Platform: EKS
 - Kubernetes version: v1.24.12-eks-ec5523e
 - Scylla version: 5.3.0~dev-20230426.a29b8cd02ba2
 - Scylla-operator version: v1.9.0-alpha.2-30-g696c50b

**Comment by fruch** [comment]
noticed again in our weekly run:

## Installation details

Kernel Version: 5.10.186-179.751.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.0~rc8-20230731.b6f7c5a6910c` with build-id `f6e718548e76ccf3564ed2387b6582ba8d37793c`


Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.11.0-alpha.0-58-g6b310ee
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-basic-12h-eks`
Test id: `2988f6cc-ed06-451b-ac3c-3841826d7aac`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-basic-12h-eks`
Test config file(s):

- [longevity-scylla-operator-basic-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/bbe1e2913943746105dc13872eced316af68ef0c/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 2988f6cc-ed06-451b-ac3c-3841826d7aac`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2988f6cc-ed06-451b-ac3c-3841826d7aac)
- Show all stored logs command: `$ hydra investigate show-logs 2988f6cc-ed06-451b-ac3c-3841826d7aac`


## Logs:
- **kubernetes-2988f6cc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/kubernetes-2988f6cc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/kubernetes-2988f6cc.tar.gz)
- **db-cluster-2988f6cc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/db-cluster-2988f6cc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/db-cluster-2988f6cc.tar.gz)
- **sct-runner-events-2988f6cc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/sct-runner-events-2988f6cc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/sct-runner-events-2988f6cc.tar.gz)
- **sct-2988f6cc.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/sct-2988f6cc.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/sct-2988f6cc.log.tar.gz)
- **loader-set-2988f6cc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/loader-set-2988f6cc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/loader-set-2988f6cc.tar.gz)
- **monitor-set-2988f6cc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/monitor-set-2988f6cc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2988f6cc-ed06-451b-ac3c-3841826d7aac/20230903_023647/monitor-set-2988f6cc.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-basic-12h-eks/79/)
[Argus](https://argus.scylladb.com/test/c3f68ac3-b7cf-4ac8-8cf4-270db06f0e14/runs?additionalRuns[]=2988f6cc-ed06-451b-ac3c-3841826d7aac)
</details>

**Comment by rzetelskik** [comment]
Looking at the logs it seems like @vponomaryov got it pretty much spot on. After the initial replacement and decommission, it looks like the replace label is carried over to the newly created service. It doesn't look like the label is applied again by orphanedpv controller but more like the label is copied over from the old service, but I'll have to double check that. Of course that's not an expected behavior, so I'll definitely look into that.

**Comment by rzetelskik** [comment]
Just to confirm the run posted by Israel contained the recent changes in the replacement procedure:
```
$ skopeo inspect docker://docker.io/scylladb/scylla-operator@sha256:3a18eb4f4667f55d8a56877ff536a1ee463114cbfe614a75c47b7ec867bed5ad
{
    "Name": "docker.io/scylladb/scylla-operator",
    "Digest": "sha256:3a18eb4f4667f55d8a56877ff536a1ee463114cbfe614a75c47b7ec867bed5ad",
    "RepoTags": [
        ...
        "1.11.0-alpha.0",
        ...
    ],
    "Created": "2023-09-01T13:15:21.651507887Z",
    ...

$ git tag --contains 627410282d60f1b6f2fb16dd908fa2210d76a29d
v1.10.0
v1.10.0-beta.0
v1.10.0-rc.0
v1.11.0-alpha.0
```

**Comment by rzetelskik** [comment]
```console
$ cat kubernetes-2988f6cc/longevity-scylla-operator-basic-3h--2988f6cc/namespaces/scylla-operator/pods/scylla-operator-6c7564dcbb-w5cnz/scylla-operator.log
...
I0903 01:21:44.527145       1 scyllacluster/sync_services.go:241] "Replacing node using ClusterIP" ScyllaCluster="scyl
la/sct-cluster" Service="scylla/sct-cluster-us-east1-b-us-east1-2"
I0903 01:21:44.527164       1 scyllacluster/sync_services.go:508] "Pod has not been recreated by the StatefulSet contr
oller yet" ScyllaCluster="scylla/sct-cluster" Pod="scylla/sct-cluster-us-east1-b-us-east1-2"
...
I0903 01:22:04.660705       1 scyllacluster/sync_services.go:216] "Node is labelled with replacement label and will be replaced" ScyllaCluster="scylla/sct-cluster" Service="scylla/sct-cluster-us-east1-b-us-east1-2"
I0903 01:22:04.660745       1 scyllacluster/sync_services.go:241] "Replacing node using ClusterIP" ScyllaCluster="scylla/sct-cluster" Service="scylla/sct-cluster-us-east1-b-us-east1-2"
I0903 01:22:04.660769       1 scyllacluster/sync_services.go:543] "Pod isn't ready yet" ScyllaCluster="scylla/sct-cluster" Pod="scylla/sct-cluster-us-east1-b-us-east1-2"
...
```

```console
$ cat db-cluster-2988f6cc/sct-cluster-us-east1-b-us-east1-2/system.log
...
I0903 01:14:59.220513       1 config/config.go:310] "Scylla entrypoint" Command="/docker-entrypoint.py --listen-address=0.0.0.0 --broadcast-rpc-address=172.20.37.10 --seeds=172.20.106.13 --enable-sstable-key-validation=1 --abort-on-internal-error=1 --broadcast-address=172.20.37.10 --prometheus-address=0.0.0.0 --cpuset=1-7,9-15 --abort-on-ebadf=1 --developer-mode=0 --overprovisioned=0 --smp=14 --replace-address-first-boot=172.20.8.76 --abort-on-lsa-bad-alloc=1"
...
INFO  2023-09-03 01:20:59,260 [shard  0] storage_service - DECOMMISSIONING: starts
...
INFO  2023-09-03 01:21:31,568 [shard  0] storage_service - DECOMMISSIONING: done
...
I0903 01:22:16.551477       1 operator/sidecar.go:360] "Starting scylla"
...
I0903 01:22:16.580142       1 config/config.go:310] "Scylla entrypoint" Command="/docker-entrypoint.py --broadcast-address=172.20.196.145 --developer-mode=0 --overprovisioned=0 --prometheus-address=0.0.0.0 --broadcast-rpc-address=172.20.196.145 --smp=14 --replace-address-first-boot=172.20.8.76 --cpuset=1-7,9-15 --abort-on-ebadf=1 --abort-on-internal-error=1 --enable-sstable-key-validation=1 --listen-address=0.0.0.0 --seeds=172.20.106.13 --abort-on-lsa-bad-alloc=1"
```

```console
$ yq ea -oj '{"name": .metadata.name, "clusterIP": .spec.clusterIP, "creationTimestamp": .metadata.creationTimestamp, "replace": .metadata.labels."scylla/replace"}' kubernetes-2988f6cc/longevity-scylla-operator-basic-3h--2988f6cc/namespaces/scylla/services/sct-cluster-us-east1-b-us-east1-*.yaml 
{
  "name": "sct-cluster-us-east1-b-us-east1-0",
  "clusterIP": "172.20.106.13",
  "creationTimestamp": "2023-09-02T23:35:33Z",
  "replace": null
}
{
  "name": "sct-cluster-us-east1-b-us-east1-1",
  "clusterIP": "172.20.31.159",
  "creationTimestamp": "2023-09-02T23:35:33Z",
  "replace": null
}
{
  "name": "sct-cluster-us-east1-b-us-east1-2",
  "clusterIP": "172.20.196.145",
  "creationTimestamp": "2023-09-03T01:21:54Z",
  "replace": "172.20.8.76"
}
```

Looks like the service never got updated https://github.com/scylladb/scylla-operator/blob/b694aae7cd31cc1cd6245f2de860d51f700717ff/pkg/controller/scyllacluster/sync_services.go#L557 and replace label was copied over to the new service after it was decommissioned and scaled out again. I"m not exactly sure what to do with this particular scenario - should we maybe not propagate the replace label further if the service is pruned due to the node being decommissioned?
cc @tnozicka @zimnx

**Comment by tnozicka** [comment]
should we just check the UID matches before copying? (otherwise the old service is essentially nil)

**Comment by rzetelskik** [comment]
@vponomaryov what's the approximate reproduction rate of this issue?
Also, have you hit it with the new replacement procedure, i.e. with enterprise version >=2023.1.0 or OS >=5.2.6?

**Comment by vponomaryov** [comment]
> @vponomaryov what's the approximate reproduction rate of this issue? Also, have you hit it with the new replacement procedure, i.e. with enterprise version >=2023.1.0 or OS >=5.2.6?

I haven't calculated it.
But it happens.
See @fruch 's above comment.

**Comment by tnozicka** [comment]
> @tnozicka also mentioned that merging the labels is something we'll generally want to move away from, but it seems to be a larger effort and I personally can't say if it won't break other operations.

https://github.com/scylladb/scylla-operator/issues/1440

> @tnozicka @zimnx the question is also whether fixing this just for the new procedure would be good enough, given this doesn't seem particularly rare?

to me, given the complexity, the time seems best spent at removing the races from the new flow

**Comment by rzetelskik** [comment]
#1442 should fix the issue for the new procedure (ScyllaDB Enterprise >=2023.1.0 or ScyllaDB OS >=5.2.6).
