### ISSUE TITLE
c-s drop QUORUM after kill scylla

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1254]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

In EKS 12h longevity test, after killing scylla, write quorum errors appeared in c-s workload:
``
java.io.IOException: Operation x10 on key(s) [4c364d3333504d4e3630]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)`
``
There was only one node down and the others were looking fine (load is quite small 5kops, logs look ok).
One thing to note, 5 minutes before this another `kill_scylla` nemesis was running (but recovered without issues before this error).

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.10.178-162.673.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.0~rc5-20230429.a47bcb26e42e` with build-id `d2644a8364f13d14d25be6b9d3c69f84612192bd`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.9.0-alpha.3-5-g34369da
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-basic-12h-eks`
Test id: `867964c1-eb15-4cad-812b-35a5efda3379`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-basic-12h-eks`
Test config file(s):

- [longevity-scylla-operator-basic-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/08f927dd885ce1fc5ad7b712138146d4434d1451/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 867964c1-eb15-4cad-812b-35a5efda3379`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=867964c1-eb15-4cad-812b-35a5efda3379)
- Show all stored logs command: `$ hydra investigate show-logs 867964c1-eb15-4cad-812b-35a5efda3379`

## Logs:
- **db-cluster-867964c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/db-cluster-867964c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/db-cluster-867964c1.tar.gz)
- **sct-runner-events-867964c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/sct-runner-events-867964c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/sct-runner-events-867964c1.tar.gz)
- **sct-867964c1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/sct-867964c1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/sct-867964c1.log.tar.gz)
- **monitor-set-867964c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/monitor-set-867964c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/monitor-set-867964c1.tar.gz)
- **loader-set-867964c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/loader-set-867964c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/loader-set-867964c1.tar.gz)
- **kubernetes-867964c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/kubernetes-867964c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/867964c1-eb15-4cad-812b-35a5efda3379/20230514_110843/kubernetes-867964c1.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-basic-12h-eks/63/)
[Argus](https://argus.scylladb.com/test/c3f68ac3-b7cf-4ac8-8cf4-270db06f0e14/runs?additionalRuns[]=867964c1-eb15-4cad-812b-35a5efda3379)
</details>

**Comment by tnozicka** [comment]
Closing this as stale.

This is too old to look into and we are aware of traffic and quorum issues that are already tracked, some fixed already. Let's see if we hit again or not.
