### ISSUE TITLE
dashboards.sh: wrong shebang line

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla-operator#126]
**Environment:**

Ubuntu 18.04 LTS

**Description:**

```shell
examples$ ./dashboards.sh -t generic
-bash: ./dashboards.sh: /usr/bin/bash: bad interpreter: No such file or directory
```
It's common to have `#! /bin/bash` shebang line for bash scripts

**Workaround:**

```
bash ./dashboards.sh -t generic
```

**Comment by dahankzter** [comment]
I have bash at that location:
```console
➜  gke git:(master) ✗ ls -al /usr/bin/bash
-rwxr-xr-x 1 root root 928016 26 maj 21.32 /usr/bin/bash
```

**Comment by dahankzter** [comment]
On the other hand I also have it at `/bin/bash`....

**Comment by rjeczalik** [comment]
> It's common to have #! /bin/bash shebang line for bash scripts

Eventually you can use `#!/usr/bin/env bash`
