### ISSUE TITLE
examples/generic: insufficient memory to run 3 scylla nodes

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla-operator#127]
Starting minikube with `--memory=6144` creates a cluster with not enough memory to run 3 scylla nodes with 2GiB of RAM each.

It's maybe not visible with docker driver, but when you use kvm2 (or any other driver which spin up VMs) it become a problem.

It looks like you need 370MiB+512MiB+6GiB of memory, or just set it to `--memory=8g` for simplicity.

**Comment by dahankzter** [comment]
This is an example and especially so wet minikube which is mostly for
development purposes. Perhaps we can settle for an extra comment about it?

**Comment by mmatczuk** [comment]
Since minikube uses docker I'd suggest we drop this flag from example and add 1G memory limit to scylla in resources.
