### ISSUE TITLE
Create an enhancment proposal for configuring different IP types for ScyllaDB nodes

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1277]
We need to create an  enhancement proposal for exposing ScyllaDB on different IPs then the currently use ClusterIPs that are not routable outside of the same cluster. The feature itself is described in https://github.com/scylladb/scylla-operator/issues/1270

**Comment by zimnx** [comment]
https://docs.google.com/document/d/1ShTqLFDk3SPxUGOHsfyk-iEHFbzXvFHmQV1FjiTf5tI/edit

**Comment by tnozicka** [comment]
Reopening it to use it as a tracker to land an enhancement into this repo as the [initial proposal](https://docs.google.com/document/d/1Q-AzdbD-sIiY9nQewf53QyVltuknmeABOATAi6KB5rQ/edit) is being followed by changes in https://docs.google.com/document/d/1Q-AzdbD-sIiY9nQewf53QyVltuknmeABOATAi6KB5rQ/edit
