### ISSUE TITLE
Installation on Microk8s leads to errors

### ISSUE THREAD

**Issue by AlexWeinstein92** [scylladb/scylla-operator#1280]
Steps to Reproduce:
- Using scylla-operator docs for installation for kubernetes https://operator.docs.scylladb.com/stable/generic.html

- on step `kubectl apply -f examples/common/operator.yaml`
  - hangs at `Waiting for deployment "scylla-operator" rollout to finish: 0 of 2 updated replicas are available...`
  
```
% microk8s kubectl get pod -n scylla-operator
NAME                               READY   STATUS             RESTARTS        AGE
webhook-server-6fc89cbffb-88lx7    0/1     CrashLoopBackOff   7 (3m41s ago)   24m
webhook-server-6fc89cbffb-lvw89    0/1     CrashLoopBackOff   7 (3m35s ago)   24m
scylla-operator-6b568cdb85-g6hv2   0/1     CrashLoopBackOff   7 (3m42s ago)   24m
scylla-operator-6b568cdb85-m2mfp   0/1     CrashLoopBackOff   7 (3m38s ago)   24m
```

**Expected behavior**
Pods run successfully, can move on to creating scylla cluster

**Environment:**
 - Platform: microk8s, M1 Macbook Pro (2022)
 - Scylla-operator version: master

**Comment by zimnx** [comment]
We don't ship arm images. You can build it manually if you need it.
Dup #1216

**Comment by AlexWeinstein92** [comment]
I've tried digging into your github pipeline, but have no experience with Go and can't seem to figure out how I would build manually for arm. Please advise.

**Comment by zimnx** [comment]
I don't have any experience with Mac tooling, but on Linux it's as easy as `docker build -t docker.io/scylladb/scylla-operator:latest .` executed in the root of the repository.

**Comment by AlexWeinstein92** [comment]
I don't think this is possible as when I try to specify `--platform arm64` I get an error `image type not supported`. A colleague suggested using `aarch64`, which gave the same result.

I am trying an alternative option of running my Scylla container in docker locally & connecting it to my kubernetes service containers.
