### ISSUE TITLE
Tuning fails (as the container is not privileged) 

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-operator#1292]
The following warning:
```
tuning: /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/queue/nomerges to 2
```

means that we are not really tuning the OS. I don't know if we need to, or we can skip tuning.

**Comment by tnozicka** [comment]
what's the platform + OS and the operator version you've used? Can you please upload the full log file?

**Comment by tnozicka** [comment]
> what's the platform + OS and the operator version you've used? Can you please upload the full log file?

it's been a while, I doubt you have the info anymore
/close
