### ISSUE TITLE
`perftune-containers` pods hang in `ContainerCreating` state if non-operator disk setup is used without scylladb dynamic PV provisioner

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1296]
**Describe the bug**
When we deploy a Scylla cluster using custom disk setup tools (not scylla-operator's `disk setup`) and static local volume provisioner (not scylladb's `dynamic provisioner`) we get following situation with the perf pods:
```
perftune-containers-42e8939d-f987-4487-954d-afa3615ac794-xrs8f   0/1     ContainerCreating   0       65m     10.142.0.29   gke-longevit-scylla-opera-scylla-pool-8744843c-9qp2
perftune-containers-505028ab-5131-4cf9-8d3d-a9bf663ef91e-swnmx   0/1     ContainerCreating   0       20m     10.142.0.21   gke-longevit-scylla-opera-scylla-pool-8744843c-7w47
perftune-containers-c0b35c04-380c-41a3-abeb-8c0a3432918a-9zmhb   0/1     ContainerCreating   0       117m    10.142.0.45   gke-longevit-scylla-opera-scylla-pool-8744843c-tc3w
perftune-containers-d4975063-b4b4-4936-b61d-25334c84d4f9-zf2gr   0/1     ContainerCreating   0       3h4m    10.142.0.46   gke-longevit-scylla-opera-scylla-pool-8744843c-6bpp
perftune-containers-f48a1e7c-900a-4a8a-b3bd-7958bdcfc36c-hxwh9   0/1     ContainerCreating   0       42m     10.142.0.21   gke-longevit-scylla-opera-scylla-pool-8744843c-7w47
perftune-node-505028ab-5131-4cf9-8d3d-a9bf663ef91e-28rsv         0/1     Completed           0       42m     10.142.0.21   gke-longevit-scylla-opera-scylla-pool-8744843c-7w47
perftune-node-83540971-bc14-440e-9abf-d69d63cbc228-rrcr7         0/1     Completed           0       65m     10.142.0.29   gke-longevit-scylla-opera-scylla-pool-8744843c-9qp2
perftune-node-c0b35c04-380c-41a3-abeb-8c0a3432918a-bn4sr         0/1     Completed           0       3h33m   10.142.0.45   gke-longevit-scylla-opera-scylla-pool-8744843c-tc3w
perftune-node-d4975063-b4b4-4936-b61d-25334c84d4f9-xgpg6         0/1     Completed           0       3h33m   10.142.0.46   gke-longevit-scylla-opera-scylla-pool-8744843c-6bpp
scylla-layout-nodes-tuning-node-setup-7b7zz                      1/1     Running             0       3h33m   10.142.0.46   gke-longevit-scylla-opera-scylla-pool-8744843c-6bpp
scylla-layout-nodes-tuning-node-setup-9jlrp                      1/1     Running             0       42m     10.142.0.21   gke-longevit-scylla-opera-scylla-pool-8744843c-7w47
scylla-layout-nodes-tuning-node-setup-nlwxt                      1/1     Running             0       3h33m   10.142.0.45   gke-longevit-scylla-opera-scylla-pool-8744843c-tc3w
scylla-layout-nodes-tuning-node-setup-z5fns                      1/1     Running             0       66m     10.142.0.29   gke-longevit-scylla-opera-scylla-pool-8744843c-9qp2
```

Events for one of those pods:
```
scylla-operator-node-tuning   43s     Warning   FailedMount    pod/perftune-containers-42e8939d-f987-4487-954d-afa3615ac794-xrs8f               kubelet, gke-longevit-scylla-opera-scylla-pool-8744843c-9qp2  \
    MountVolume.SetUp failed for volume "etc-sysconfig-irqbalance" : hostPath type check failed: /etc/sysconfig/irqbalance is not a file                                                                                                                                                                                     65m          40      perftune-containers-42e8939d-f987-4487-954d-afa3615ac794-xrs8f.176ec344cef9e646
scylla-operator-node-tuning   4m59s   Warning   FailedMount    pod/perftune-containers-42e8939d-f987-4487-954d-afa3615ac794-xrs8f               kubelet, gke-longevit-scylla-opera-scylla-pool-8744843c-9qp2   \
    Unable to attach or mount volumes: unmounted volumes=[etc-sysconfig-irqbalance], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition                                                                                                                                                63m          27      perftune-containers-42e8939d-f987-4487-954d-afa3615ac794-xrs8f.176ec36163353a36
```

It gets reproduced in 100% cases with `1.9.0-rc.2` as well as with `1.8.1` scylla-operator versions.

Scylla pods work ok:
```
scylla    sct-cluster-us-east1-b-us-east1-0    2/2     Running     0               3h4m    10.84.5.7     gke-longevit-scylla-opera-scylla-pool-8744843c-6bpp
scylla    sct-cluster-us-east1-b-us-east1-1    2/2     Running     0               117m    10.84.4.7     gke-longevit-scylla-opera-scylla-pool-8744843c-tc3w
scylla    sct-cluster-us-east1-b-us-east1-2    2/2     Running     1 (18m ago)     20m     10.84.7.7     gke-longevit-scylla-opera-scylla-pool-8744843c-7w47
```

**To Reproduce**
1. Deploy scylla-operator
2. Provision a 3-member Scylla cluster using custom disk setup tools and static local volume provisioner enabling the perf tuning.
3. See error

**Expected behavior**
All the perf tune pods must work correctly.

**Logs**
- **db-cluster-b2387860.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/db-cluster-b2387860.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/db-cluster-b2387860.tar.gz)
- **sct-runner-events-b2387860.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/sct-runner-events-b2387860.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/sct-runner-events-b2387860.tar.gz)
- **sct-b2387860.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/sct-b2387860.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/sct-b2387860.log.tar.gz)
- **monitor-set-b2387860.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/monitor-set-b2387860.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/monitor-set-b2387860.tar.gz)
- **loader-set-b2387860.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/loader-set-b2387860.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/loader-set-b2387860.tar.gz)
- **kubernetes-b2387860.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/kubernetes-b2387860.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b2387860-1f7c-42a8-8704-fdc53654691e/20230704_213221/kubernetes-b2387860.tar.gz)
- [CI job](https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-gke/110)

**Environment:**
 - Platform: GKE
 - Kubernetes version: v1.27.2-gke.2100
 - Scylla version: 2022.2.9-20230618.843304f9f734
 - Scylla-operator version: e.g.: `1.9.0-rc.2` and `1.8.1`

**Comment by rzetelskik** [comment]
@vponomaryov what exactly are the "custom disk setup tools" used?

**Comment by rzetelskik** [comment]
Does that only happen with the above disk setup? Have you tried local static volume provisioner with NodeConfig for disk setup instead? Also are you running that with `local-nvme-ssd-block` or `ephemeral-storage-local-ssd`?

**Comment by vponomaryov** [comment]
> Does that only happen with the above disk setup? 

I have only this one not counting the dynamic provisioning.
The old one we had was `xfs-formatter` and we didn't use perf tuning with it.

> Have you tried local static volume provisioner with NodeConfig for disk setup instead? 

```
scylla-operator-node-tuning   scylla-layout-nodes-tuning-node-setup-7b7zz                      1/1     Running             0               3h33m   10.142.0.46   gke-longevit-scylla-opera-scylla-pool-8744843c-6bpp   <none>           <none>
scylla-operator-node-tuning   scylla-layout-nodes-tuning-node-setup-9jlrp                      1/1     Running             0               42m     10.142.0.21   gke-longevit-scylla-opera-scylla-pool-8744843c-7w47   <none>           <none>
scylla-operator-node-tuning   scylla-layout-nodes-tuning-node-setup-nlwxt                      1/1     Running             0               3h33m   10.142.0.45   gke-longevit-scylla-opera-scylla-pool-8744843c-tc3w   <none>           <none>
scylla-operator-node-tuning   scylla-layout-nodes-tuning-node-setup-z5fns                      1/1     Running             0               66m     10.142.0.29   gke-longevit-scylla-opera-scylla-pool-8744843c-9qp2   <none>           <none>
```

> Also are you running that with `local-nvme-ssd-block` or `ephemeral-storage-local-ssd`?

```
< t:2023-07-04 17:42:54,528 f:gce_utils.py    l:173  c:sdcm.utils.gce_utils p:DEBUG > Execute \
    `gcloud container --project sct-project-1 node-pools create scylla-pool --region us-east1 --node-locations us-east1-b \
    --cluster longevit-scylla-operator-3h-dev-b2387860 --num-nodes 4 --machine-type n1-standard-8 \
    --image-type UBUNTU_CONTAINERD --system-config-from-file /tmp/system_config.yaml --no-enable-autoupgrade \
    --no-enable-autorepair --disk-type pd-ssd --disk-size 50 \
    --local-nvme-ssd-block count="3" \
    --node-taints role=scylla-clusters:NoSchedule --metadata RunByUser=vponomaryov,TestName=longevity_test.LongevityTest.test_custom_time,TestId=b2387860-1f7c-42a8-8704-fdc53654691e,version=scylla-staging,CreatedBy=SCT,JenkinsJobTag=jenkins-scylla-staging-valerii-vp-longevity-scylla-operator-3h-gke-110,keep=alive'
```

**Comment by rzetelskik** [comment]
> > Have you tried local static volume provisioner with NodeConfig for disk setup instead?
> 
> scylla-operator-node-tuning   scylla-layout-nodes-tuning-node-setup-7b7zz                      1/1     Running             0               3h33m   10.142.0.46   gke-longevit-scylla-opera-scylla-pool-8744843c-6bpp   <none>           <none>
> scylla-operator-node-tuning   scylla-layout-nodes-tuning-node-setup-9jlrp                      1/1     Running             0               42m     10.142.0.21   gke-longevit-scylla-opera-scylla-pool-8744843c-7w47   <none>           <none>
> scylla-operator-node-tuning   scylla-layout-nodes-tuning-node-setup-nlwxt                      1/1     Running             0               3h33m   10.142.0.45   gke-longevit-scylla-opera-scylla-pool-8744843c-tc3w   <none>           <none>
> scylla-operator-node-tuning   scylla-layout-nodes-tuning-node-setup-z5fns                      1/1     Running             0               66m     10.142.0.29   gke-longevit-scylla-opera-scylla-pool-8744843c-9qp2   <none>           <none>

This doesn't answer the question. Having NodeConfig deployed doesn't necessarily mean you use it for disk setup. See `kubectl explain nodeconfig.spec.localDiskSetup`. So my question was whether you've tried local static volume provisioner with NodeConfig used for disk setup - I know you haven't used this in this run since obviously you ran it with your own set of scripts, but maybe you've tried this configuration before. And I don't recall us having any issues with NodeConfig + local static volume provisioner. I'm trying to narrow the issue down.

**Comment by vponomaryov** [comment]
It turns out that it cannot be reproduced anymore.
Probably was the cloud platform problem.
Closing before it appears again
