### ISSUE TITLE
ScyllaCluster Orphaned PV controller test needs to support more than one node

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1303]
Historically, `ScyllaCluster Orphaned PV controller` is skipped when there is more then one node.
https://github.com/scylladb/scylla-operator/blame/afc059575c7d607d388b97155d6a8f4f857d327c/test/e2e/set/scyllacluster/scyllacluster_pv.go#L82-L87

This is unfortunately true even if there is only one node that it can be scheduled to but an extra infra node with taints.

We should look into removing the node length limitation or at least checking scheduling constrains as a backup.

(Otherwise this test will be skipped by our new CI.)

**Comment by rzetelskik** [comment]
Skipping the test caused a regression to be overlooked and break master - see https://github.com/scylladb/scylla-operator/issues/1390. We should consider prioritizing.
