### ISSUE TITLE
cannot set a custom namespace in scylladb chart values

### ISSUE THREAD

**Issue by sorushsaghari** [scylladb/scylla-operator#1305]
**Describe the bug**
in scylladb helm chart and scylla manager, namespace is hardcoded to __scylla-operator__ and __scylla-manager__.
i need to set the namespace to a custom value

**Config Files**
```
metadata:
  name: scylla-operator
  namespace: scylla-operator
```
**Environment:**
 - Platform: custom
 - Kubernetes version: 1.22

**Comment by tnozicka** [comment]
dupe of https://github.com/scylladb/scylla-operator/issues/987
