### ISSUE TITLE
Outdated example ScyllaCluster in documentation can't be run on latest operator

### ISSUE THREAD

**Issue by guitcastro** [scylladb/scylla-operator#1307]
After installing the Operator and create a CRD the pod is falling with:

`docker-entrypoint.py: error: unrecognized arguments: --prometheus-address=0.0.0.0`

**To Reproduce**
1. Install the operator
2. Apply [this](https://operator.docs.scylladb.com/stable/scylla_cluster_crd.html) example CRD

**Expected behavior**

Pod should have started

**Logs**```

I0802 19:13:51.671379       1 config/config.go:298] "Scylla entrypoint" Command="/docker-entrypoint.py --broadcast-rpc-address=10.1.9.185 --seeds=10.1.9.185 --developer-mode=0 --overprovisioned=1 --smp=2 --prometheus-address=0.0.0.0 --listen-address=0.0.0.0 --broadcast-address=10.1.9.185"
I0802 19:13:51.671569       1 cache/shared_informer.go:311] Waiting for caches to sync for Prober
I0802 19:13:51.671600       1 cache/shared_informer.go:318] Caches are synced for Prober
I0802 19:13:51.671612       1 operator/sidecar.go:389] "Starting Prober server"
I0802 19:13:51.671716       1 sidecar/controller.go:157] "Starting controller" Controller="SidecarController"
I0802 19:13:51.671728       1 cache/shared_informer.go:311] Waiting for caches to sync for SidecarController
I0802 19:13:51.671736       1 cache/shared_informer.go:318] Caches are synced for SidecarController
E0802 19:13:51.673047       1 sidecar/controller.go:141] syncing key 'scylla/scylla-cluster-us-central-1-us-central-1-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: dial tcp 127.0.0.1:10000: connect: connection refused
E0802 19:13:51.678931       1 sidecar/controller.go:141] syncing key 'scylla/scylla-cluster-us-central-1-us-central-1-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: dial tcp 127.0.0.1:10000: connect: connection refused
E0802 19:13:51.690114       1 sidecar/controller.go:141] syncing key 'scylla/scylla-cluster-us-central-1-us-central-1-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: dial tcp 127.0.0.1:10000: connect: connection refused
E0802 19:13:51.712739       1 sidecar/controller.go:141] syncing key 'scylla/scylla-cluster-us-central-1-us-central-1-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: dial tcp 127.0.0.1:10000: connect: connection refused
E0802 19:13:51.753784       1 sidecar/controller.go:141] syncing key 'scylla/scylla-cluster-us-central-1-us-central-1-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: dial tcp 127.0.0.1:10000: connect: connection refused
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 11, in <module>
    arguments = commandlineparser.parse()
  File "/commandlineparser.py", line 21, in parse
    return parser.parse_args()
  File "/usr/lib64/python3.4/argparse.py", line 1731, in parse_args
    self.error(msg % ' '.join(argv))

```

**Environment:**
 - Platform: GKE
 - Kubernetes version:  1.25

**Comment by zimnx** [comment]
Example in documentation is quite outdated. To workaround it change Scylla version to [supported one](https://operator.docs.scylladb.com/stable/releases.html#support-matrix).

**Comment by tnozicka** [comment]
https://operator.docs.scylladb.com/stable/scylla_cluster_crd.html is not present anymore
