### ISSUE TITLE
ScyllaCluster doesn't support image references with registry port

### ISSUE THREAD

**Issue by mandreasik** [scylladb/scylla-operator#1310]
**Describe the bug**
Operator fails to transition cluster into Available state when registry contains host port.

Consider a scenario where you have a `scyllaCluster`, and instead of pulling images from the official image hub, you pull them through `someproxy:1234/proxy`:

```
kind: ScyllaCluster
(...)
  spec:
  (...)
  repository: someproxy:1234/proxy/scylladb/scylla
  tag: 5.1.8
```

Even though operator starts all scylladb nodes (pods are in running state) it does not transition to correct state due to following error
`E0720 23:49:19.448247       1 scyllacluster/status.go:86] "Can't get scylla version" err="parse scylla container version: Invalid image name:  someproxy:1234/proxy/scylladb/scylla:5.1.8" ScyllaCluster="scylladb/default"`

scyllaCluster status
```
(...)
- lastTransitionTime: "2023-07-21T11:09:37Z"
    message: 'StatefulSetControllerAvailable: Racks "db-0, db-1, db-2" are not in
      the desired version'
    observedGeneration: 1
    reason: StatefulSetControllerAvailable_RacksNotAtDesiredVersion
    status: "False"
    type: Available
(...)
```

**Additional context**
Upon investigating the operator's code, it appears that the function at https://github.com/scylladb/scylla-operator/blob/master/pkg/naming/names.go#L103 needs to be modified to fully support the Docker image naming convention.

As per the official Docker documentation (https://docs.docker.com/engine/reference/commandline/tag/), it is allowed to have a port in the image name:
`[HOST[:PORT_NUMBER]/]PATH`

I propose the following code modification:
```
func ImageToVersion(image string) (string, error) {
	parts := strings.Split(image, ":")
	if len(parts) < 2 {
		return "", errors.New(fmt.Sprintf("Invalid image name: %s", image))
	}
	version := parts[len(parts)-1]
	if len(version) == 0 {
		return "", errors.New(fmt.Sprintf("Image version is empty: %s", image))
	}

	return parts[len(parts)-1], nil
}
```
I trust you understand the concept.

**Comment by tnozicka** [comment]
In general the image version (tag) parsing should go away with https://github.com/scylladb/scylla-operator/issues/821 I guess we can enhance the version parsing in the meantime to support registry ports
