### ISSUE TITLE
Scylla service Startup control.

### ISSUE THREAD

**Issue by Saikumarn78** [scylladb/scylla-operator#132]
Hi,

Assume 4 node Scylla cluster up and functional and due to some underlying hardware issue one of the nodes might go down and after a day that node is removed from the cluster using nodetool remove node as were needed to rectify hardware issue on the pod which is completely down. Now the cluster has only 3 node and someday maybe after a week or more the hardware which has to be rectified on pod 4 which was out of the cluster is rectified and when it is booted back it will have a persistent volume with data already in it and this node will join the cluster without bootstrapping as this node already has the old data.
Now this means that my cluster has got old/stale data which was part of it before the removal of the node.
We were able to handle this same situation in bare-metal & VM's by tweaking the scylla-service script.  The Scylla service will check for the journalctl log last line timestamp and try to match it will current time and if this doesn't fall under the given threshold the Scylla service will not be started. But how do we achieve it in the K8s?

**Comment by dahankzter** [comment]
If you just want to discard the old data you can tear the down the pod? I guess it depends on the replication factor if the strategy works. We need to support or at least help the user in these sort of disaster scenarios but there is unfortunately much left to do.

**Comment by dahankzter** [comment]
What did you do in the case when the old node comes up and tries to start but your script doesn't let it so the server doesn't start? Do you by hand (or script) delete the data and let it start after that?

**Comment by Saikumarn78** [comment]
Hi,
I will clean up the old data dir and bootstrap it as a new node. Also, there is one more case I would like to bring it your attention. Assume that 4 Scylla node was part of the cluster and one node was removed from the cluster due to hardware issues and now we have an only three-node cluster. Here we would upgrade the Scylla version as per regular practice but the pod which was out of the ring is still on the old version and now when someone boots up the hardware of node 4 though it is on the different version it will join the cluster and now i have a cluster with two different versions. In case, if its a minor version difference probably it might be okay but not a major difference. 

By having control on the Scylla startup we can handle these sort of things in a bigger environments like ours. eg : 300+ Scylla nodes

**Comment by dahankzter** [comment]
Thank you @Saikumarn78 this is valuable input. I am not sure about the proper solution for this but simply removing the broken pod should work.
