### ISSUE TITLE
Create periodic job executing an e2e test for MultiDC between regions in different VPC

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1320]
To test the multiDC setup works we should have a test that creates 2 clusters in different Kubernetes clusters and VPCs to be sure all the pieces for MultiDC and networking fall together. It should be a periodic to keep costs reasonable compared to presubmits.

Ideally a new suite in e2e.

Note that this needs CI changes to get the necessary infra.

**Comment by rzetelskik** [comment]
For the record this is currently blocked on https://github.com/scylladb/scylla-operator-release/pull/146#discussion_r1528820260 - everything is ready but the periodic and the e2e test suite which can't be run without it.
