### ISSUE TITLE
Implementing pod level logging.

### ISSUE THREAD

**Issue by Saikumarn78** [scylladb/scylla-operator#133]
Hi,

Right now after we deploy Scylla in K8s to check the log we need to execute the following command "kubectl -n scylla logs simple-cluster-us-east-1-us-east-1a-0" but we have a requirement to send all the logs to the centralized location. 
Using kubectl we cannot ship the logs and we need a way to pipe the logs to pod and from each pod will ship the logs to centralized location using Kafka or filebeat or custom way of doing it.

**Comment by dahankzter** [comment]
Can't you configure a node level logging agent? https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level perhaps using Filebeat like you suggested? https://www.elastic.co/blog/shipping-kubernetes-logs-to-elasticsearch-with-filebeat .
This shouldn't require any changes here right?

**Comment by Saikumarn78** [comment]
Hi 
As we spoke, need the location of the log written on the pod, and this logs per pod will be shipped to the centralized location.

**Comment by dahankzter** [comment]
Scylla is configured to write to `/dev/stdout` and `/dev/stderr`. Does that work for you?

**Comment by Saikumarn78** [comment]
Not sure about this if I understand it. But if this inside the pod can we do a tail on this and see the log inside pod?

**Comment by gnumoreno** [comment]
@dahankzter let me explain the use case a little better. 

As you stated, the logs are being directed to stdout/stderr. This allow us to get the logs with `kubectl logs`. 

What the user would like is to have an option in the operator to avoid that and instead have the logs in a file inside the pod. The reason behind it is that companies use log aggregators with agents that collect logs into a centralized location. So if we have an option to not redirect the scylla logs to stdout/stderr but instead put the logs into a file inside the pod, the centralized logs solutions would work out of the box.

Let me know if you have any questions.

**Comment by eliransin** [comment]
@gnumoreno / @dahankzter are you using official docker images? If so what versions are in question here?
Thanks,

**Comment by eliransin** [comment]
@Saikumarn78 I have a workaround to suggest (actually two), both of them involves re configuring docker in two different ways.
The solution is to build a new docker image using the scylla image as a base (all is implemented and explained in the file below).
I am attaching here the README.md file which is also in the solution tar so you can first see if the solution is good enough for 
you.
This solution can also serve as a conceptual base to demonstrate is is possible even without affecting the ability stated by @dahankzter [here](https://github.com/scylladb/scylla-operator/issues/133#issuecomment-646110949)


[README.txt](https://github.com/scylladb/scylla-operator/files/6028810/README.txt)
[scylla_log_to_file.tar.gz](https://github.com/scylladb/scylla-operator/files/6028811/scylla_log_to_file.tar.gz)

Please let me know if this helped you guys.
