### ISSUE TITLE
Cleanup pods may stay for `3h+` blocking Scylla pods provisioning using `large-collections` load

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1347]
## Issue description

During the `12h` test run were applied following disruptions/nemesis:
![Screenshot from 2023-08-22 19-25-03](https://github.com/scylladb/scylla-operator/assets/3796058/1a772421-d5fb-4b12-8251-2aa74802c550)

During the `disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node` one we do following steps:
- terminate K8S node hosting a Scylla pod
- wait for it's auto-recreation
- wait for pod appearence
- decommission the affected pod
- add new Scylla node/pod

In parallel to the disruption there was running `large-collections` kind of load against the Scylla cluster.

And new node scheduling got blocked by the long-running `cleanup` pods:

```
scylla                        cleanup-sct-cluster-us-east1-b-us-east1-1-pgt8w                  1/1     Running     0              3h2m    10.3.6.76    ip-10-3-7-76.eu-west-2.compute.internal    <none>           <none>
scylla                        cleanup-sct-cluster-us-east1-b-us-east1-2-w844j                  1/1     Running     0              3h2m    10.3.4.80    ip-10-3-4-177.eu-west-2.compute.internal   <none>           <none>
scylla                        sct-cluster-us-east1-b-us-east1-0                                1/2     Running     1 (109m ago)   112m    10.3.5.146   ip-10-3-7-31.eu-west-2.compute.internal    <none>           <none>
scylla                        sct-cluster-us-east1-b-us-east1-1                                2/2     Running     0              8h      10.3.7.252   ip-10-3-4-109.eu-west-2.compute.internal   <none>           <none>
scylla                        sct-cluster-us-east1-b-us-east1-2                                2/2     Running     0              8h      10.3.5.41    ip-10-3-6-134.eu-west-2.compute.internal   <none>           <none>
scylla                        sct-cluster-us-east1-b-us-east1-3                                0/2     Pending     0              3h2m    <none>       <none>                                     <none>           <none>
```

Event:
```
2023-08-18T04:05:17Z   2023-08-18T07:01:22Z   38      default-scheduler             \
    Warning   FailedScheduling      
    0/9 nodes are available: 2 node(s) didn't match pod anti-affinity rules, 3 Insufficient cpu, 3 Insufficient memory, \
        4 node(s) didn't match Pod's node affinity/selector. preemption: 0/9 nodes are available: \
            4 Preemption is not helpful for scheduling, 5 No preemption victims found for incoming pod..
```

Cleanup pods logs:
```
I0818 04:05:10.830686       1 operator/cleanupjob.go:110] "Starting the node cleanup" version="\"v1.10.0-beta.0-0-g1d6849c\""
I0818 04:05:10.835782       1 operator/cleanupjob.go:131] "Discovered keyspaces for cleanup" keyspaces=["drop_table_during_repair_ks_3","system_distributed_everywhere","drop_table_during_repair_ks_8","ks_truncate","drop_table_during_repair_ks_9","drop_table_during_repair_ks_5","system","drop_table_during_repair_ks_1","system_traces","drop_table_during_repair_ks_0","system_schema","large_collection_test","drop_table_during_repair_ks_2","drop_table_during_repair_ks_4","drop_table_during_repair_ks_7","system_auth","system_replicated_keys","drop_table_during_repair_ks_6","system_distributed"]
I0818 04:05:10.835800       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="drop_table_during_repair_ks_3"
I0818 04:05:10.842555       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="drop_table_during_repair_ks_3" duration="6.740638ms"
I0818 04:05:10.842567       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="system_distributed_everywhere"
I0818 04:05:48.336955       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="system_distributed_everywhere" duration="37.494365488s"
I0818 04:05:48.336978       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="drop_table_during_repair_ks_8"
I0818 04:05:48.339609       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="drop_table_during_repair_ks_8" duration="2.614032ms"
I0818 04:05:48.339623       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="ks_truncate"
I0818 04:06:27.720344       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="ks_truncate" duration="39.380699924s"
I0818 04:06:27.720372       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="drop_table_during_repair_ks_9"
I0818 04:06:27.722527       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="drop_table_during_repair_ks_9" duration="2.144159ms"
I0818 04:06:27.722537       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="drop_table_during_repair_ks_5"
I0818 04:06:27.724292       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="drop_table_during_repair_ks_5" duration="1.737451ms"
I0818 04:06:27.724318       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="system"
I0818 04:07:08.761055       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="system" duration="41.036716688s"
I0818 04:07:08.761077       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="drop_table_during_repair_ks_1"
I0818 04:07:08.764213       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="drop_table_during_repair_ks_1" duration="3.118497ms"
I0818 04:07:08.764230       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="system_traces"
I0818 04:07:49.497016       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="system_traces" duration="40.732756551s"
I0818 04:07:49.497042       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="drop_table_during_repair_ks_0"
I0818 04:07:49.503160       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="drop_table_during_repair_ks_0" duration="6.104255ms"
I0818 04:07:49.503175       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="system_schema"
I0818 04:07:57.154461       1 operator/cleanupjob.go:145] "Finished keyspace cleanup" keyspace="system_schema" duration="7.651266458s"
I0818 04:07:57.154479       1 operator/cleanupjob.go:135] "Starting a keyspace cleanup" keyspace="large_collection_test"
```

Test ended in 3 hours after last message of the cleanup pod:
```
2023-08-18 07:06:13,038 f:tester.py       l:2830 c:LongevityTest        p:INFO  > TearDown is starting...
```

## Impact

Busy cleanup pods, which may run for hours, block Scylla pods scheduling by the `pod-anti-affinity` rules.

## How frequently does it reproduce?

Gets reproduced easily using `large-collections` load against a Scylla cluster.

## Installation details

Kernel Version: 5.10.184-175.749.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.0-20230813.68e9cef1baf7` with build-id `c7f9855620b984af24957d7ab0bd8054306d182e`

Operator Image: scylladb/scylla-operator:1.10.0-rc.0
Operator Helm Version: 1.10.0-rc.0
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 5 K8S nodes (i3en.3xlarge) and 4 Scylla pods

OS / Image: `` (k8s-eks: `eu-west-2`)

Test: `longevity-scylla-operator-large-collections-12h`
Test id: `7563c1d0-fb61-4549-ab85-c34011105fef`
Test name: `scylla-operator/operator-1.10/eks/longevity-scylla-operator-large-collections-12h`
Test config file(s):

- [longevity-large-collections-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/498a18599a7e05a16e1190f4ff07bdb919c95785/test-cases/longevity/longevity-large-collections-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7563c1d0-fb61-4549-ab85-c34011105fef`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7563c1d0-fb61-4549-ab85-c34011105fef)
- Show all stored logs command: `$ hydra investigate show-logs 7563c1d0-fb61-4549-ab85-c34011105fef`

## Logs:
- **kubernetes-7563c1d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/kubernetes-7563c1d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/kubernetes-7563c1d0.tar.gz)
- **db-cluster-7563c1d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/db-cluster-7563c1d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/db-cluster-7563c1d0.tar.gz)
- **sct-runner-events-7563c1d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/sct-runner-events-7563c1d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/sct-runner-events-7563c1d0.tar.gz)
- **sct-7563c1d0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/sct-7563c1d0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/sct-7563c1d0.log.tar.gz)
- **loader-set-7563c1d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/loader-set-7563c1d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/loader-set-7563c1d0.tar.gz)
- **monitor-set-7563c1d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/monitor-set-7563c1d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7563c1d0-fb61-4549-ab85-c34011105fef/20230818_072119/monitor-set-7563c1d0.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.10/job/eks/job/longevity-scylla-operator-large-collections-12h/2/)
[Argus](https://argus.scylladb.com/test/b1c69248-48be-460a-ab6d-e8df31b74155/runs?additionalRuns[]=7563c1d0-fb61-4549-ab85-c34011105fef)
</details>

**Comment by zimnx** [comment]
You have your ScyllaCluster pod anti affinity set to prevent having any two Pods related to given ScyllaCluster running on the same node.
```

**Comment by zimnx** [comment]
You have your ScyllaCluster pod anti affinity set to prevent having any two Pods related to given ScyllaCluster running on the same node.
```
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: scylla/cluster
                operator: In
                values:
                - sct-cluster
            topologyKey: kubernetes.io/hostname
        tolerations:
```
Because cleanup needs execution, it's run as a Pod, bound to your ScyllaCluster, so it has `scylla/cluster: sct-cluster` label. 

If cleanup takes longer than your test timeout we cannot do anything about it.

**Comment by vponomaryov** [comment]
@zimnx the reason for `pending` state is mentioned in the `impact` section, so it is not point of the bug report.

Here are following unclear questions:
- Why `cleanup` pods take THAT long?
- Is it really ok to run Scylla pods in parallel to the cleanup ones? 
- What is the perf penalty running `cleanup` and `scylla` pods on same K8S node? Especially when it may take hours?

**Comment by zimnx** [comment]
> the reason for pending state is mentioned in the impact section, so it is not point of the bug report.

It's misconfiguration, you need to run cleanup, but your configuration prevents it if you don't have more k8s nodes than scylla nodes. Changing the pod anti affinity would solve your issue with Pending Scylla Pod.

> Why cleanup pods take THAT long?

Scylla goes over every sstable, and compacts it to get rid of stale data. If your dataset is huge, it will take time.

> Is it really ok to run Scylla pods in parallel to the cleanup ones?

Yes, cleanup Pods are essentially triggering the cleanup, and then waiting until it's completed. They are not performing actual cleanup.

> What is the perf penalty running cleanup and scylla pods on same K8S node? Especially when it may take hours?

There's none. Cleanup Pod sends single HTTP request for every keyspace and waits until Scylla responds, that's all it does. 

---

I looked at Scylla logs of nodes being cleaned up, and they are filled with these warnings:
1.
```
WARN  2023-08-18 07:02:31,247 [shard  7] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
```
2.
```
WARN  2023-08-18 07:02:29,670 [shard  2] direct_failure_detector - unexpected exception when pinging ff47d1b7-6185-4e22-86c0-785665831e0d: seastar::rpc::unknown_verb_error (unknown verb)
```

First one suggest something might be off with load, second one has a potential to Scylla bug.

**Comment by vponomaryov** [comment]
@zimnx 
Thanks for the info.
I will update our automation.
