### ISSUE TITLE
Changes to some of the config values do not trigger a rolling restart

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1389]
**Describe the bug**
Some of the config values are currently computed in the sidecar by getting the ScyllaCluster object using scylla client and extracting them from spec, e.g. the developer mode: https://github.com/scylladb/scylla-operator/blob/75a39bf4b973d789833b761d5c284c36adf07703/pkg/sidecar/config/config.go#L220.
For this reason, changes to these fields in ScyllaCluster do not trigger a rolling restart.
Passing these config values to sidecar in a different way could trigger a rolling restart, while also allowing us to get rid of using the scyllaClient in sidecar.

**To Reproduce**
1. Deploy a ScyllaCluster and wait for it to roll out
2. Change one of the fields extracted from ScyllaCluster in sidecar, .e.g developer mode

**Expected behavior**
The cluster should undergo a rolling restart.

**Additional context**
This issue can be resolved as a part of a bigger effort https://github.com/scylladb/scylla-operator/issues/604

**Comment by tnozicka** [comment]
yep, when sidecar just get the finished configs it will trigger fine
