### ISSUE TITLE
Build dedicated containers for kubernetes

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#139]
Currently the Scylla container uses supervisord to run a bunch of services.
Each needed process should run in it's own container.
This would allow to resource separation of the processes, not [all of them](https://github.com/scylladb/scylla/tree/master/dist/docker/redhat/etc) are actually needed.
Also, this would simplify configuration management.

**Comment by tnozicka** [comment]
tracked in https://github.com/scylladb/scylla-operator/issues/1769
