### ISSUE TITLE
CI artifacts doesn't contain the dump of all namespaces

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#1394]
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1359/pull-scylla-operator-e2e-gke-parallel/1701563256667115520/artifacts/namespaces/

Couple of namespaces are missing, including `scylla-operator` which prevents from debugging an issue which happened in the webhook.

**Comment by tnozicka** [comment]
weird, hopefully we can wait few days for https://github.com/scylladb/scylla-operator/pull/1368 to fix this

**Comment by tnozicka** [comment]
should be fixed with https://github.com/scylladb/scylla-operator/pull/1368
