### ISSUE TITLE
Setup a periodic job running e2e suite on arm64

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1410]
We should make sure our `arm64` images work. Ideally a Prow periodic on EKS or GKE with fully arm64 cluster running our e2e suites.

### Requires
- [x] https://github.com/scylladb/scylla-operator-release/issues/74

**Comment by rzetelskik** [comment]
For the record this is currently blocked on https://github.com/scylladb/scylla-operator-release/pull/146#discussion_r1528820260.
