### ISSUE TITLE
Document arm64 support

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1411]
We should document using `arm64` based images with at least a mention of it. In the end it will be pushed to the same location using a manifest list.

**Comment by tnozicka** [comment]
done in #2188

**Comment by rzetelskik** [comment]
> done in https://github.com/scylladb/scylla-operator/pull/2188

@tnozicka where in the docs is it mentioned? I don't recall seeing it anywhere when reviewing the PR

**Comment by tnozicka** [comment]
https://github.com/scylladb/scylla-operator/blame/b2b22b8ee51a3f0001af49b1d15516dda7496938/docs/source/support/releases.md#L75
https://operator.docs.scylladb.com/master/support/releases.html#architectures
