### ISSUE TITLE
Flake: NodeConfig Optimizations [It] should correctly project state for each scylla pod [Serial]

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1426]
```
• [FAILED] [1252.316 seconds]
NodeConfig Optimizations [It] should correctly project state for each scylla pod [Serial]
github.com/scylladb/scylla-operator/test/e2e/set/nodeconfig/nodeconfig_optimizations.go:145
  [FAILED] Unexpected error:
      <wait.errInterrupted>: 
      timed out waiting for the condition
      {
          cause: <*errors.errorString | 0xc0003b7000>{
              s: "timed out waiting for the condition",
          },
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/nodeconfig/nodeconfig_optimizations.go:262 @ 09/26/23 10:16:46.865
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/nodeconfig.glob..func2.4()
    	github.com/scylladb/scylla-operator/test/e2e/set/nodeconfig/nodeconfig_optimizations.go:262 +0x140f
```

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1423/pull-scylla-operator-e2e-gke-serial/1706604188068220928#1:test-build-log.txt%3A615
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1423/pull-scylla-operator-e2e-gke-serial/1706604188068220928/

**Comment by tnozicka** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1494/pull-scylla-operator-e2e-gke-serial/1714952752070660096#1:test-build-log.txt%3A645

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1508/pull-scylla-operator-e2e-gke-serial/1738219481697619968#1:test-build-log.txt%3A586

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1717/pull-scylla-operator-master-e2e-gke-serial/1757049657621483520

**Comment by rzetelskik** [comment]
Hasn't happened for 4 months.
/close

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2062/pull-scylla-operator-master-e2e-gke-serial/1821111561859633152#1:test-build-log.txt%3A728
