### ISSUE TITLE
operator gets k8s errors while attempting to update scylla sts

### ISSUE THREAD

**Issue by viggin543** [scylladb/scylla-operator#1428]
**Describe the bug**
After upgrading scylla operator from v1.7 to 1.9 
I get the following log errors in log

```
E0927 14:31:25.312209       1 scyllacluster/controller.go:263] syncing key 'scylla/staging-scylladb' failed: can't sync stateful sets: can't apply statefulset to set partition: can't update apps/v1, Kind=StatefulSet "scylla/staging-scylladb-manager-dc-stg": StatefulSet.apps "staging-scylladb-manager-dc-stg" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

I0927 14:31:25.313092       1 record/event.go:307] "Event occurred" object="scylla/staging-scylladb-manager-dc-stg" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Warning" reason="UpdateStatefulSetFailed" message="Failed to update StatefulSet scylla/staging-scylladb-manager-dc-stg: StatefulSet.apps \"staging-scylladb-manager-dc-stg\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden"
```

seems as the operator attempts to update an existing scylla STS , and k8s does not allow it

**To Reproduce**
run scylla operator 1.7
create scylla cluster
upgrade operator to 1.9

**Expected behavior**
operator should not attempt a forbidden k8s operation

**Config Files**

**Logs**
see above

**Environment:**
 - Platform: GKE
 - Kubernetes version:  1.24
 - Scylla version: 5.2
 - Scylla-operator version: 1.9

**Comment by tnozicka** [comment]
> After upgrading scylla operator from v1.7 to 1.9

we support only N+1 upgrades, please try again with a supported path

**Comment by schnapsidee** [comment]
I'm running into the same issue after updating from 1.10 to 1.11

` Can't apply statefulset update: can't update apps/v1, Kind=StatefulSet "scylla-manager/scylla-manager-manager-dc-manager-rack": StatefulSet.apps "scylla-manager-manager-dc-manager-rack" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden `

**Comment by tnozicka** [comment]
this seems to mix issues without proper descriptions or steps to reproduce. I think the best path forward is to close this one as that was doing the unsupported upgrade and didn't get any info after that.

@schnapsidee please file a dedicated issue with the exact steps that you took and how to reproduce it + attach must-gather https://operator.docs.scylladb.com/stable/support/must-gather.html

**Comment by ArjanSchouten** [comment]
I had the same problem today. I don't know yet what caused the issue but what I did:

Delete the statefulset with `--cascade=false`. Then scylla-operator will create the sts again.
After that delete the pods one by one and the pods will be created again without downtime.
