### ISSUE TITLE
Flake: Scylla Manager integration [It] should discover cluster and sync tasks

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1433]
```console
• [FAILED] [3599.606 seconds]
Scylla Manager integration [It] should discover cluster and sync tasks
...
  [FAILED] Unexpected error:
      <wait.errInterrupted>: 
      timed out waiting for the condition
      {
          cause: <*errors.errorString | 0xc00033d280>{
              s: "timed out waiting for the condition",
          },
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 @ 09/30/23 00:42:37.578

  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func18.1()
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 +0x8e4
```

https://github.com/scylladb/scylla-operator/actions/runs/6358101136/job/17270108645#step:3:3867
https://github.com/scylladb/scylla-operator/suites/16722273178/artifacts/955646400

**Comment by rzetelskik** [comment]
https://github.com/scylladb/scylla-operator/actions/runs/6393053431/job/17351713133#step:3:3743

**Comment by rzetelskik** [comment]
https://github.com/scylladb/scylla-operator/actions/runs/6450497728/job/17510002339#step:3:3515

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1461/pull-scylla-operator-e2e-gke-parallel/1712738453705199616

**Comment by tnozicka** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1532/pull-scylla-operator-e2e-gke-parallel/1722928563918737408

**Comment by tnozicka** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1603/pull-scylla-operator-e2e-gke-parallel/1729895420869480448

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1603/pull-scylla-operator-e2e-gke-parallel/1729916195047477248
