### ISSUE TITLE
operator uses deprecated `replace_address_first_boot` option

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1438]
**Describe the bug**
operator uses deprecated `replace_address_first_boot` when replacing a node. Scylla shows warning:
```
WARN  2023-10-01 02:56:58,715 [shard  0] storage_service - The replace_address_first_boot=172.20.237.141 option is deprecated. Please use the replace_node_first_boot option
```
**To Reproduce**
replace node using Scylla operator.

**Expected behavior**
No deprecation warning

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.0~rc8-20230731.b6f7c5a6910c` with build-id `f6e718548e76ccf3564ed2387b6582ba8d37793c`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.11.0-alpha.0-114-g8ac0a21
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `functional-eks`
Test id: `040a6c7d-9a4d-4ae5-826b-46801962ae58`
Test name: `scylla-operator/operator-master/functional/functional-eks`
Test config file(s):

- [functional.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fa73cde2127567560e3cf64260f55b3275a86a24/test-cases/scylla-operator/functional.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 040a6c7d-9a4d-4ae5-826b-46801962ae58`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=040a6c7d-9a4d-4ae5-826b-46801962ae58)
- Show all stored logs command: `$ hydra investigate show-logs 040a6c7d-9a4d-4ae5-826b-46801962ae58`

## Logs:
- **kubernetes-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/kubernetes-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/kubernetes-040a6c7d.tar.gz)
- **db-cluster-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/db-cluster-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/db-cluster-040a6c7d.tar.gz)
- **sct-runner-events-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/sct-runner-events-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/sct-runner-events-040a6c7d.tar.gz)
- **sct-040a6c7d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/sct-040a6c7d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/sct-040a6c7d.log.tar.gz)
- **loader-set-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/loader-set-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/loader-set-040a6c7d.tar.gz)
- **parallel-timelines-report-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/parallel-timelines-report-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/parallel-timelines-report-040a6c7d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-eks/120/)
[Argus](https://argus.scylladb.com/test/89fdaa2f-5255-4696-a268-90cb7090482e/runs?additionalRuns[]=040a6c7d-9a4d-4ae5-826b-46801962ae58)
</details>

**Comment by zimnx** [comment]
We use old parameter when Scylla version is semantically lower than `2023.1.0` where `2023.1.0-rc8` is. Lower versions doesn't support new parameter, so this is expected.

**Comment by soyacz** [comment]
> We use old parameter when ScyllaDB version is semantically lower than `2023.1.0` where `2023.1.0-rc8` is. Lower versions doesn't support new parameter, so this is expected. Bump your ScyllaDB version to final `2023.1.0` and it should be gone.

Yes, we should test with 2023.1.0 (or .1 as it's released already). I fixed the trigger.
