### ISSUE TITLE
C-S failure during rolling restart (during certs reload)

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1447]
## Issue description

- [X] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

During rolling restart c-s failed with:
```
2023-10-01 03:03:26.042: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=fd792d83-c314-478f-9e19-7869cc9008ee during_nemesis=RollingRestartCluster: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=5263 node=Node sct-loaders-0 [None | None] (seed: False)
java.io.IOException: Operation x10 on key(s) [4f384e4e3333364c4f30]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (no host was tried)
```
Seems also during that time certs were being reloaded by operator:
```
INFO  2023-10-01 03:02:15,917 [shard 13] cql_server - Reloaded {/var/run/secrets/scylla-operator.scylladb.com/scylladb/serving-certs/tls.key, /var/run/secrets/scylla-operator.scylladb.com/scylladb/serving-certs/tls.crt}
```
But I'm not sure if it could have impact.
## Impact

Fail the load, possibly closing all connections

## How frequently does it reproduce?

The most recent EKS longevities

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.1-20230929.ab1244950a66` with build-id `76e3b93b8680c6c33674b897652b61ff9da1d4d7`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.11.0-alpha.0-114-g8ac0a21
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-3h-eks`
Test id: `85e460ce-52dc-4f36-a93d-0636def0bd0e`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-eks`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fa73cde2127567560e3cf64260f55b3275a86a24/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 85e460ce-52dc-4f36-a93d-0636def0bd0e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=85e460ce-52dc-4f36-a93d-0636def0bd0e)
- Show all stored logs command: `$ hydra investigate show-logs 85e460ce-52dc-4f36-a93d-0636def0bd0e`

## Logs:
- **kubernetes-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/kubernetes-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/kubernetes-85e460ce.tar.gz)
- **db-cluster-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/db-cluster-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/db-cluster-85e460ce.tar.gz)
- **sct-runner-events-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/sct-runner-events-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/sct-runner-events-85e460ce.tar.gz)
- **sct-85e460ce.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/sct-85e460ce.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/sct-85e460ce.log.tar.gz)
- **loader-set-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/loader-set-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/loader-set-85e460ce.tar.gz)
- **monitor-set-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/monitor-set-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/monitor-set-85e460ce.tar.gz)
- **parallel-timelines-report-85e460ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/parallel-timelines-report-85e460ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/85e460ce-52dc-4f36-a93d-0636def0bd0e/20231001_031700/parallel-timelines-report-85e460ce.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/124/)
[Argus](https://argus.scylladb.com/test/028aa2df-5ce5-4883-a4a8-16bfbbe8dcc8/runs?additionalRuns[]=85e460ce-52dc-4f36-a93d-0636def0bd0e)
</details>

**Comment by tnozicka** [comment]
this should be already fixed with https://github.com/scylladb/scylla-operator/pull/1450

**Comment by soyacz** [comment]
similar issue happened in multitenant EKS recently: https://argus.scylladb.com/test/7774c24a-b749-4528-97a4-22785e7e5b6f/runs?additionalRuns[]=b14de382-c46c-460e-8c7c-7c764dccd5a0

Is there something that needs to be fixed in multitenant setup, or different issue?

**Comment by tnozicka** [comment]
not sure, you can choose to file a new issue and attach must-gather but there are still open issues with rolling restarts like #1077
