### ISSUE TITLE
Usage of the `kind load docker-image %image%` breaks init containers of Scylla pods

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1448]
**Describe the bug**
If we run `scylla-operator` using the all-in-one K8S tool called `KinD` and cache images with it's `kind load docker-image %image%` functionality.
Then we get following error in `init` containers spinning up a Scylla pod:

```
scylla-manager       9m15s       Warning   Failed                       \
    pod/scylla-manager-manager-dc-manager-rack-0                          \
    spec.initContainers{sidecar-injection}       kubelet, kind-worker2      \
    Failed to pull image "docker.io/library/import-2023-10-05@sha256:988185511194c722507b78ab12aa181c0ac07cbf574a871fbd6e69975b88d928": \
        rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/import-2023-10-05@sha256:988185511194c722507b78ab12aa181c0ac07cbf574a871fbd6e69975b88d928": \
        failed to resolve reference "docker.io/library/import-2023-10-05@sha256:988185511194c722507b78ab12aa181c0ac07cbf574a871fbd6e69975b88d928": \
        pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed   \
    10m          4       scylla-manager-manager-dc-manager-rack-0.178b2d8345702401
```

If we remove that cache step for that image in our automation this error goes away.

**To Reproduce**
1. Deploy all-in-one K8S tool `KinD`
2. Cache operator's image using `kind load docker-image %image%` command
3. Create a Scylla pod

**Expected behavior**
Scylla pods must start up without errors even if we cache images.

**Logs**
- **kubernetes-69cc0f3c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/kubernetes-69cc0f3c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/kubernetes-69cc0f3c.tar.gz)
- **kubernetes-apiserver-69cc0f3c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/kubernetes-apiserver-69cc0f3c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/kubernetes-apiserver-69cc0f3c.tar.gz)
- **sct-runner-events-69cc0f3c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/sct-runner-events-69cc0f3c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/sct-runner-events-69cc0f3c.tar.gz)
- **sct-69cc0f3c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/sct-69cc0f3c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/sct-69cc0f3c.log.tar.gz)
- **parallel-timelines-report-69cc0f3c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/parallel-timelines-report-69cc0f3c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/69cc0f3c-7450-46b6-93af-e213291598d3/20231005_100730/parallel-timelines-report-69cc0f3c.tar.gz)

**Environment:**
 - Platform: [KinD](https://kind.sigs.k8s.io)
 - Kubernetes version: v1.25
 - Scylla version: `5.2.9`
 - Scylla-operator version: e.g.: `1.11.0-rc.0`

**Comment by tnozicka** [comment]
`Failed to pull image "docker.io/library/import-2023-10-05@sha256:988185511194c722507b78ab12aa181c0ac07cbf574a871fbd6e69975b88d928`

If the kind cache can't resolve its own image, it seems to be an issue with the kind cache.

Even so, the autodetection can be disabled on the scylla-operator deployment with
```yaml
env:
- name: SCYLLA_OPERATOR_IMAGE
  value: <container-image-ref>
```

**Comment by rzetelskik** [comment]
@tnozicka this https://github.com/scylladb/scylla-operator/issues/1441 looks like it could be related
