### ISSUE TITLE
"Setting up nodes for ScyllaDB" in "Deploying Scylla on EKS" uses wrong example file

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1464]
[Setting up nodes for ScyllaDB](https://operator.docs.scylladb.com/stable/eks.html#setting-up-nodes-for-scylladb )in [Deploying Scylla on EKS](https://operator.docs.scylladb.com/stable/eks.html) uses a wrong command `kubectl apply --server-side -f examples/gke/nodeconfig-alpha.yaml` pointing to a yaml prepared for GKE instead of EKS. Deploying it causes the volumes to never be prepared correctly.

**Comment by tnozicka** [comment]
best to address it inline

**Comment by rzetelskik** [comment]
agreed to sending a hotfix
@tnozicka shall we have a separate issue for inlining the manifests? It should apply globally, if we want to start going that way

**Comment by tnozicka** [comment]
if you want, we probably need to do a revamp at some point...
