### ISSUE TITLE
Problem with configuring Scylla Manager Agent

### ISSUE THREAD

**Issue by peske** [scylladb/scylla-operator#147]
[The documentation](https://github.com/scylladb/scylla-operator/blob/master/docs/generic.md#configure-scylla-manager-agent) says that we need to create a _Secret_ in order to configure Scylla Manager Agent:
```
kubectl create secret -n scylla generic scylla-agent-config-secret --from-file scylla-manager-agent.yaml
```
But such secret doesn't get mounted ever. After some investigation, I've discovered in several places in code (like [here](https://github.com/scylladb/scylla-operator/blob/6e4dcc588eaf3a6d445a530974b22626f7ee5de5/config/crds/scylla_v1alpha1_cluster.yaml#L83)) that actually it should be a _ConfigMap_.

So you need to change either documentation or the implementation.

**Comment by peske** [comment]
Update: it doesn't work even if I create ConfigMap. I'll open a new issue (bug).

**Comment by dahankzter** [comment]
I can't reproduce this error. When I run it according to the docs in `docs/generic.md` it works as intended:
Before:
```json
{
  "L": "INFO",
  "T": "2020-07-23T10:45:00.892Z",
  "M": "Using config",
  "config": {
    "AuthToken": "",
    "HTTPS": "172.18.0.9:10001",
    "TLSCertFile": "/var/lib/scylla-manager/scylla_manager.crt",
    "TLSKeyFile": "/var/lib/scylla-manager/scylla_manager.key",
    "Prometheus": ":56090",
    "Debug": "127.0.0.1:56112",
    "CPU": -1,
    "Logger": {
      "Mode": "stderr",
      "Level": "info",
      "Development": false
    },
    "Scylla": {
      "APIAddress": "0.0.0.0",
      "APIPort": "10000",
      "ListenAddress": "172.18.0.9",
      "PrometheusAddress": "0.0.0.0",
      "PrometheusPort": "9180",
      "DataDirectory": "/var/lib/scylla/data"
    },
    "S3": {
      "AccessKeyID": "",
      "SecretAccessKey": "",
      "Region": "",
      "Endpoint": "",
      "ServerSideEncryption": "",
      "SSEKMSKeyID": "",
      "UploadConcurrency": "",
      "ChunkSize": "",
      "MaxRetries": "",
      "UseAccelerateEndpoint": "",
      "ListChunkSize": ""
    }
  },
  "config_file": [
    "/etc/scylla-manager-agent/scylla-manager-agent.yaml",
    "/mnt/scylla-agent-config/scylla-manager-agent.yaml"
  ],
  "_trace_id": "Se7XVIb-RBahhhA4doygXA"
}
```
```json
{
  "L": "INFO",
  "T": "2020-07-23T10:43:02.022Z",
  "M": "WARNING! Scylla data may be exposed on IP 172.18.0.7, protect it by specifying auth_token in config file",
  "config_file": [
    "/etc/scylla-manager-agent/scylla-manager-agent.yaml",
    "/mnt/scylla-agent-config/scylla-manager-agent.yaml"
  ],
  "_trace_id": "Q60KCnnNSauy_Nqzmbq3PA"
}
```
Are present in the logs. Once I apply the secrets as given in the docs:
```bash
kubectl create secret -n scylla generic scylla-agent-config-secret --from-file /tmp/scylla-manager-agent.yaml
kubectl create secret -n scylla generic scylla-client-config-secret --from-file /tmp/scylla-client.yaml
```
The logs change into:
```json
{
  "L": "INFO",
  "T": "2020-07-23T10:48:14.479Z",
  "M": "Using config",
  "config": {
    "AuthToken": "*****",
    "HTTPS": "172.18.0.9:10001",
    "TLSCertFile": "/var/lib/scylla-manager/scylla_manager.crt",
    "TLSKeyFile": "/var/lib/scylla-manager/scylla_manager.key",
    "Prometheus": ":56090",
    "Debug": "127.0.0.1:56112",
    "CPU": -1,
    "Logger": {
      "Mode": "stderr",
      "Level": "info",
      "Development": false
    },
    "Scylla": {
      "APIAddress": "0.0.0.0",
      "APIPort": "10000",
      "ListenAddress": "172.18.0.9",
      "PrometheusAddress": "0.0.0.0",
      "PrometheusPort": "9180",
      "DataDirectory": "/var/lib/scylla/data"
    },
    "S3": {
      "AccessKeyID": "",
      "SecretAccessKey": "",
      "Region": "",
      "Endpoint": "",
      "ServerSideEncryption": "",
      "SSEKMSKeyID": "",
      "UploadConcurrency": "",
      "ChunkSize": "",
      "MaxRetries": "",
      "UseAccelerateEndpoint": "",
      "ListChunkSize": ""
    }
  },
  "config_file": [
    "/etc/scylla-manager-agent/scylla-manager-agent.yaml",
    "/mnt/scylla-agent-config/scylla-manager-agent.yaml"
  ],
  "_trace_id": "dfOkjUyoSzSlvYSLQz95Aw"
}
```
And the warning goes away.

**Comment by zimnx** [comment]
I can't reproduce neither.

**Comment by wskibum** [comment]
following latest instructions:
there is no kubectl create secret -n scylla generic scylla-client-config-secret --from-file /tmp/scylla-client.yaml in the document
there is no scylla-client.yaml provided or available via docker

kubectl -n scylla describe ScyllaCluster simple-cluster

Warning  InvalidManagerAgentConfig  4m39s (x31 over 14m)  scyllacluster-controller  Can't gent agent token: can't get agent token: can't get secret scylla/scylla-agent-config: secret "scylla-agent-config" not found

kubectl get secret -n scylla-manager
NAME                                        TYPE                                  DATA   AGE
default-token-lh58x                         kubernetes.io/service-account-token   3      67m
scylla-manager-cluster-auth-token           Opaque                                1      67m
scylla-manager-cluster-member-token-2msfs   kubernetes.io/service-account-token   3      67m
scylla-manager-controller-token-29mx7       kubernetes.io/service-account-token   3      67m
scylla-manager-token-rz925                  kubernetes.io/service-account-token   3      67m

**Comment by lordphnx** [comment]
> 

Also running into this issue.

**Comment by jaredmorrow** [comment]
This was also reported in #1140   I also ran into the issue following the documentation.

**Comment by debuggerpk** [comment]
did we get a resolution to this ?

**Comment by OloBo-MSK** [comment]
Any news ??
