### ISSUE TITLE
`scylla-agent-config-secret`  not mounted in the sidecar container

### ISSUE THREAD

**Issue by peske** [scylladb/scylla-operator#148]
**Describe the bug**
`scylla-agent-config` secret doesn't get mounted to `/etc/scylla-manager-agent/scylla-manager-agent.yaml` in the `scylla-manager-agent` sidecar container.

**To Reproduce**
1. Create a `scylla-manager-agent.yaml` file, and set `auth_token` to some value (i.e. `auth_token: xxx`)
2. Create a secret by executing:
```
kubectl create secret -n scylla generic scylla-agent-config-secret --from-file scylla-manager-agent.yaml
```
Note: I've tried with two different secret names (`scylla-agent-config-secret` and `scylla-agent-config`), but it doesn't work anyway.
3. Wait a while, then restart the cluster by executing something like:
```
kubectl rollout restart -n scylla statefulset/simple-cluster-us-east-1-us-east-1a
```
4. Wait for all the pods to restart
5. Check content of `/etc/scylla-manager-agent/scylla-manager-agent.yaml` file in any pod, in a aidecar container `scylla-manager-agent` by executing something like:
```
kubectl -n scylla exec -it simple-cluster-us-east-1-us-east-1a-0 --container=scylla-manager-agent \
    -- cat /etc/scylla-manager-agent/scylla-manager-agent.yaml
```
6. The `auth_token` line in the output is still empty and commented out.

**Expected behavior**
Content of `/etc/scylla-manager-agent/scylla-manager-agent.yaml` file in all sidecar containers `scylla-manager-agent` should be the same as the content of the original file `scylla-manager-agent.yaml` we've created in the first step above, and based on which we've created the secret.

**Config Files**
In the input `scylla-manager-agent.yaml` file everything is commented out except for `auth_token: xxx` line. 
In `/etc/scylla-manager-agent/scylla-manager-agent.yaml` file in sidecar containers everything is commented out.

**Logs**
`kubectl get events -n scylla` doesn't show anything interesting; only starting/stopping containers due to the restart in the third step above.
Nothing relevant in `kubectl logs` neither.

**Environment:**
 - Platform: custom, `kubeadm`
 - Kubernetes version: 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
 - Scylla version: 4
 - Scylla-operator version: master, 8dd89e90b97204247119b382b7b4067efb1fb6f5, installed 07/06/2020

**Additional context**
Initially, I've thought that it's confusion ConfigMap / Secret, as explained at https://github.com/scylladb/scylla-operator/issues/147. But I've tried with both Secret and ConfigMap, it always fails.

**Comment by peske** [comment]
I've forgotten to mention that my `Cluster` definition contains the following lines:
```
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
```
It looks that `scylla-config` works as expected, but `scylla-agent-config` doesn't.

**Comment by zimnx** [comment]
`/etc/scylla-manager/scylla-manager-agent.yaml` is a default config shipped with image which is being overwritten by the `/mnt/scylla-agent-config/scylla-manager-agent.yaml` handled by the secret.
You can see that agent container uses these two files in pod description:
```
    Image:         scylladb/scylla-manager-agent:2.0.2                                                                                                                                                                                                                                                            [0/333]
    Image ID:      docker-pullable://scylladb/scylla-manager-agent@sha256:171e662cc5b036fc178e5acf44263316dab1e28a1ce4d0b8e745d9444fd72c0c                  
    Port:          10001/TCP                                                                                                                                
    Host Port:     0/TCP                 
    Args:                             
      -c                                                                                                                                                    
      /etc/scylla-manager-agent/scylla-manager-agent.yaml
      -c                                      
      /mnt/scylla-agent-config/scylla-manager-agent.yaml
```
I tried creating my own `scylla-agent-config-secret` and it did modified `/mnt/scylla-agent-config/scylla-manager-agent.yaml`.

```
$ kubectl exec -n scylla -ti pods/simple-cluster-us-east-1-us-east-1a-2 -c scylla-manager-agent -- cat /mnt/scylla-agent-config/scylla-manager-agent.yaml
auth_token: xxx123
```

Although this revealed different bug. #166
Closing this in favor of 166.

**Comment by debuggerpk** [comment]
@zimnx can you please point in the right direction ?

**Comment by zimnx** [comment]
@debuggerpk If you face any issues with it, please report new issue with `must-gather` attached: https://operator.docs.scylladb.com/stable/support/must-gather.html
