### ISSUE TITLE
`exited: scylla (terminated by SIGKILL; not expected)` error when `cqlsh select` command gets executed on Scylla pod which is part of manual MultiDC cluster

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1503]
**Describe the bug**

Scenario:
- Deploy Single EKS cluster with dedicated nodes for Scylla pods
- Perf-tune those dedicated Scylla K8S nodes
- Provision scylla-operator `v1.11.0-rc.4`
- Provision `local-csi-driver` on all the dedicated nodes for Scylla pods
- Provision 2 ScyllaCluster objects with 3 pods each of them combined into 1 ScyllaDB cluster using new `externalSeeds` config option.
- Run `kubectl exec %pod_name% -- /bin/cqlsh -e "SELECT JSON peer, data_center, rack, rpc_address FROM system.peers;"` command.

So, if the target Scylla pod is the first one on it's host Scylla K8S node then we get following error as a result for the command:

```
Command: 'kubectl --cache-dir=/home/ubuntu/sct-results/20231020-094309-926503/.kube/http-cache --namespace=t-podip-quasi-multidc exec t-podip-quasi-multidc-quasi-dc-1-us-east1-0 -- /bin/cqlsh -e "SELECT JSON peer, data_center, rack, rpc_address FROM system.peers;"'

Exit code: 1

Stdout:

Stderr:

Defaulted container "scylla" out of: scylla, scylla-manager-agent, sidecar-injection (init)
Connection error: ('Unable to connect to any servers', {'0.0.0.0:9042': error(111, "Tried connecting to [('0.0.0.0', 9042)]. Last error: Connection refused")})
command terminated with exit code 1
```

It makes the target node to crash:
```
2023-10-20 10:34:07,259 INFO exited: scylla (terminated by SIGKILL; not expected)
2023-10-20 10:34:08,262 INFO spawned: 'scylla' with pid 117
Scylla version 2023.1.2-0.20231001.646df23cc4b3 with build-id 367fcf1672d44f5cbddc88f946cf272e2551b85a starting ...
```

Reaction of other 5 nodes is as following:
```
ERROR 2023-10-20 10:34:07,258 [shard 0] rpc - client 10.0.8.40:7000: client connection dropped: recv: Connection reset by peer
INFO  2023-10-20 10:34:08,087 [shard 0] raft_group_registry - marking Raft server 8256a1c7-b408-47e4-a9d1-20167c52da0f as dead for raft groups
WARN  2023-10-20 10:34:08,353 [shard 0] gossip - failure_detector_loop: Send echo to node 10.0.8.40, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-10-20 10:34:10,353 [shard 0] gossip - failure_detector_loop: Send echo to node 10.0.8.40, status = failed: seastar::rpc::closed_error (connection is closed)
INFO  2023-10-20 10:34:12,188 [shard 0] raft_group_registry - marking Raft server 8256a1c7-b408-47e4-a9d1-20167c52da0f as alive for raft groups
INFO  2023-10-20 10:34:13,213 [shard 0] storage_service - Node 10.0.8.40 state jump to normal
```

**Notes**
- Bug is 100% reproducible
- Notes from multiple runs on the local K8S setup (`kind`):
  - If the target pod is second on the K8S node, then the command passes and that first neighbor pod fails (Scylla crash).
  - If the target pod runs on some other kind of K8S node where we do not have Scylla-specific pods such as `local-csi-driver` then problem is absent.

**Expected behavior**
Call of the `cqlsh` command must work and must not make Scylla pods to fail when those pods are part of the manual MultiDC setup.

**Logs**
- **kubernetes-53354d26.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/kubernetes-53354d26.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/kubernetes-53354d26.tar.gz)
- **db-cluster-53354d26.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/db-cluster-53354d26.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/db-cluster-53354d26.tar.gz)
- **sct-runner-events-53354d26.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/sct-runner-events-53354d26.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/sct-runner-events-53354d26.tar.gz)
- **sct-53354d26.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/sct-53354d26.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/sct-53354d26.log.tar.gz)
- **parallel-timelines-report-53354d26.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/parallel-timelines-report-53354d26.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53354d26-2d74-43b4-856f-de849e762f91/20231020_104813/parallel-timelines-report-53354d26.tar.gz)

**Jenkins/CI**
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-functional-eks/16/consoleFull

**Environment:**
 - Platform: `EKS`, `Kind` (K8s-in-Docker, all-in-one)
 - Kubernetes version: `v1.27.6-eks-f8587cb`
 - Scylla version: `2023.1.2`
 - Scylla-operator version: e.g.: `v1.11.0-rc.4`

**Comment by vponomaryov** [comment]
After running dozens of the test runs and hitting this bug with various config combinations I have following assumption:

This crash happens to the older Scylla pod on a K8S node if the `local-csi-driver` pod is running there and the target pod doesn't use it and uses some standard/EBS storage-class.

**Comment by rzetelskik** [comment]
I've tried to reproduce it in EKS following the steps and haven't been able to. I've configured the nodes with NodeConfig and deployed k8s-local-volume-provisioner in all of them. The multi-datacenter cluster running with gp2 (EBS) storage handled the query without any issues. I've also tried it while running another tenant with scylladb-local-xfs storage class on some of the nodes. The issue didn't reproduce in either scenario.
@vponomaryov if there is an issue, there needs to be another variable introducing it. If you want, you can have a look at my setup to see if I'm missing anything - I'm attaching the must-gather artifacts.
[must-gather.tar.gz](https://github.com/scylladb/scylla-operator/files/13064025/must-gather.tar.gz)

**Comment by vponomaryov** [comment]
@rzetelskik 

The `must-gather` lacks the info about
- nodes hosting pods mapping (`kubectl describe nodes`).
- General list of objects (pods) for whole picture (`kubectl get pods -A -o wide`)

Above 2 problems make me either craft some wrapper or do a lot of manual actions to achieve my goal - `match nodes and pods, and their resources`.

So, I will reproduce the bug tomorrow keeping the K8S cluster alive with all the resources in place.

The config that leads to failure is here: https://github.com/scylladb/scylla-cluster-tests/pull/6691/files#diff-d2b2d23a0e4f23b0087a2bc70ac49a2512f9f82090cc83a76476131a566216c1R108-R129

From first sight I see following diff:
- My RAM is smaller (both mgmt agent and scylla)
- My storage is smaller
- I have 3 external seeds, not 1

You may say that RAM is too small `200Mi`, but it is enough on nodes without `local-csi-driver` which, in current case, only existing neighbor and not involved in the Scylla pods.

**Comment by zimnx** [comment]
```
[14037.086796] Tasks state (memory values in pages):
[14037.090732] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[14037.098092] [  12480]     0 12480  1241796     7381   249856        0           974 scylla-operator
[14037.105539] [  12602]     0 12602     5556     4766    73728        0           974 ld.so
[14037.213048] [  12637]     0 12637     8578     6907   106496        0           974 supervisord
[14037.220379] [  12645]   105 12645    38704     1186    73728        0           974 rsyslogd
[14037.227632] [  12647]     0 12647     1196      892    49152        0           974 scylla-housekee
[14037.235090] [  12648]     0 12648   703553    17283   360448        0           974 scylla-jmx
[14037.242363] [  12649]     0 12649   181212     3048   110592        0           974 node_exporter
[14037.249741] [  12653]     0 12653     1196      799    40960        0           974 sshd-service.sh
[14037.257259] [  12665]     0 12665     3858     2217    77824        0           974 sshd
[14037.264310] [  12784]     0 12784      803      249    49152        0           974 sleep
[14037.271459] [  17034]     0 17034 4295009395    33346   421888        0           974 scylla
[14037.278653] [  85267]     0 85267     1262     1025    53248        0           974 bash
[14037.285720] [  85275]     0 85275    15228    14085   167936        0           974 python2.7
[14037.292947] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=cri-containerd-f9a2324eb27feb7c4963d2c7915910d4ce805d81ae8ec45a0161cf5908753442.scope,mems_allowed=0,oom_memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod14aaf165_a09b_4e84_9b14_5c949b5f2641.slice/cri-containerd-f9a2324eb27feb7c4963d2c7915910d4ce805d81ae8ec45a0161cf5908753442.scope,task_memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod14aaf165_a09b_4e84_9b14_5c949b5f2641.slice/cri-containerd-f9a2324eb27feb7c4963d2c7915910d4ce805d81ae8ec45a0161cf5908753442.scope,task=scylla,pid=17034,uid=0
[14037.329892] Memory cgroup out of memory: Killed process 17034 (scylla) total-vm:17180037580kB, anon-rss:54196kB, file-rss:78664kB, shmem-rss:0kB, UID:0 pgtables:412kB oom_score_adj:974
```

Scylla is killed by oom-killer when cqlsh connects, you need to give ScyllaCluster more memory.
Please reopen if it reproduce with higher memory limit.

**Comment by rzetelskik** [comment]
@zimnx thanks for looking into the live cluster
