### ISSUE TITLE
Update ScyllaDBMonitoring

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1505]
With ScyllaDB Monitoring 4.5.0 out, we should update operator dashboards and required grafana + prometheus versions.

https://forum.scylladb.com/t/release-scylladb-monitoring-stack-4-5-0/933

@amnonh can you please update the SaaS dashboard and bring in the rest?

fyi, the assets live in
https://github.com/scylladb/scylla-operator/tree/
59ff82e/assets/monitoring

**Comment by tnozicka** [comment]
@amnonh ping

**Comment by tnozicka** [comment]
@amnonh will you be able to update the monitoring version?

**Comment by mykaul** [comment]
4.6 should be released this week or so.

**Comment by tnozicka** [comment]
@mykaul how do we approach this? IIRC you've mentioned that the monitoring team should be updating the dashboards and metrics configs but this has been lingering for a while

**Comment by tnozicka** [comment]
> @mykaul how do we approach this? IIRC you've mentioned that the monitoring team should be updating the dashboards and metrics configs but this has been lingering for a while

@mykaul I feel like this is long overdue and lacks a clear ownership. Any input would be helpful here.

**Comment by ylebi** [comment]
@mykaul @amnonh who can assist with updating? I see that we already have 4.7 and we are quite behind.

**Comment by amnonh** [comment]
Technically I am, but I know what need to be done on the monitor side, I
don't know how it reflects in the operator

**Comment by ylebi** [comment]
@tnozicka can you please assist @amnonh?

**Comment by tnozicka** [comment]
the assets (deployment manifests and definitions) live in
https://github.com/scylladb/scylla-operator/tree/d0ccf5553e72d5ecf1a8a60a66c66b14cc9de8c0/assets/monitoring
the corresponding loops are 
https://github.com/scylladb/scylla-operator/blob/ef4406fd838ed8db3eec6dd87786218ee265b88a/pkg/controller/scylladbmonitoring/sync_grafana.go#L200-L528
https://github.com/scylladb/scylla-operator/blob/39756855e103172e4cea71cb3f6ba36c8a3b8453/pkg/controller/scylladbmonitoring/sync_prometheus.go#L174-L545

If it goes well, you may just need to update the rules and such in 
https://github.com/scylladb/scylla-operator/blob/ef4406fd838ed8db3eec6dd87786218ee265b88a/assets/monitoring/prometheus/v1/alerts.prometheusrule.yaml#L10
and Grafana and Prometheus versions to match, e.g.
https://github.com/scylladb/scylla-operator/blob/d0ccf5553e72d5ecf1a8a60a66c66b14cc9de8c0/assets/monitoring/grafana/v1alpha1/deployment.yaml#L50

**Comment by tnozicka** [comment]
we also need to consider whether we can make 1 bump or multiple - maybe grafana or prometheus require to bump by 1 release to run migration scripts

**Comment by batazor** [comment]
Are there any ready-made dashboards that I can import to my main grafana?

**Comment by batazor** [comment]
@amnonh Can you tell me where I can find them? I checked the entire repository but couldn't find them.

**Comment by amnonh** [comment]
@batazor for example, here are the dashboards from branch 4.7:
https://github.com/scylladb/scylla-monitoring/tree/branch-4.7/grafana/build
