### ISSUE TITLE
Broken generic operator example in the last 0.1.9 (kubebuilder v2) ?

### ISSUE THREAD

**Issue by scorsi** [scylladb/scylla-operator#151]
**Describe the bug**
Failed to start `scylla-operator-controller-manager`. Got error:
```
 Error: failed to start container "manager": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/scylla-operator\": stat /scylla-operator: no such file or directory": unknown
Back-off restarting failed container
```

**To Reproduce**
1. kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
2. kubectl apply -f https://raw.githubusercontent.com/scylladb/scylla-operator/master/examples/generic/operator.yaml

_Btw, you should add the install of cert-manager also in the guide :)_

**Expected behavior**
Works :) 

We I run with this version of the operator generic (basically the 0.1.8) : https://raw.githubusercontent.com/scylladb/scylla-operator/123be99a110ae03031cf580259c8cdf941740cad/examples/generic/operator.yaml it works
This one (0.1.9) is also working: https://raw.githubusercontent.com/scylladb/scylla-operator/c81156999105ae719b04afa1ec6c39f9b9376348/examples/generic/operator.yaml

This commit adds a fail: 5ae79fe61ee9dc31d2d7f4736f3ed7068d1d5733
What about this: https://github.com/scylladb/scylla-operator/blob/4335e637141377891e9d136fcb9107ca38ed1842/examples/generic/operator.yaml#L1081

**Logs**
No logs

**Environment:**
 - Platform: AWS EKS
 - Kubernetes version: client: v1.16.6-beta.0, server: v1.17.6-eks-4e7f64
 - Scylla version: None
 - Scylla-operator version: 0.1.9

**Comment by scorsi** [comment]
By removing the `command: - /scylla-operator` I have a new error: `MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found`.

Keeping the investigation. :)

**Comment by scorsi** [comment]
Removing the `/scylla-operator` did the trick. The other error is because the `webhook-server-cert` resource wasn't available yet.
Look here : https://hub.docker.com/layers/scylladb/scylla-operator/v0.1.9/images/sha256-048510695144b3ca51d93ea0dfae9dad08c5df7f45dda08a0679a91ac7a271c0?context=explore the entrypoint is not the same as in the master branch : https://github.com/scylladb/scylla-operator/blob/4335e637141377891e9d136fcb9107ca38ed1842/Dockerfile#L22

**Comment by scorsi** [comment]
By restarting manually the pod, it starts successfully. The `webhook-server-cert` wasn't created in time for the pod to launch. But the pod did failed to start.

Now I have some log:
```
kubectl logs -n scylla-operator-system scylla-operator-controller-manager-0
{"L":"INFO","T":"2020-07-16T23:49:08.539Z","M":"Operator started","version":"0.1.9","build_date":"2020-07-10T08:08:42Z","commit":"c81156999105ae719b04afa1ec6c39f9b9376348","built_by":"goreleaser","go_version":"go version go1.14.4 linux/amd64","options":{"Name":"scylla-operator-controller-manager-0","Namespace":"scylla-operator-system","LogLevel":"debug","Image":"","EnableAdmissionWebhook":true},"_trace_id":"sElPCksDS5SzbOO7zrEvGg"}
{"L":"INFO","T":"2020-07-16T23:49:08.935Z","M":"Registering Components.","_trace_id":"sElPCksDS5SzbOO7zrEvGg"}
{"L":"INFO","T":"2020-07-16T23:49:09.237Z","M":"Starting the operator...","_trace_id":"sElPCksDS5SzbOO7zrEvGg"}
{"L":"FATAL","T":"2020-07-16T23:49:09.771Z","M":"error launching manager","mode":"operator","error":"open /tmp/cert/cert.pem: no such file or directory","_trace_id":"sElPCksDS5SzbOO7zrEvGg"}
```
It didn't found the `/tmp/cert/cert.pem`. We can see that the mounts is not correct: https://github.com/scylladb/scylla-operator/blob/4335e637141377891e9d136fcb9107ca38ed1842/examples/generic/operator.yaml#L1106
Fixing the mountvolume to `/tmp/cert/` didn't solves the issue...

**Comment by dahankzter** [comment]
The docs seems to be missing cert manager instructions and yes it takes quite some time sometimes to bring it up. Can you add something about this @zimnx ?

**Comment by zimnx** [comment]
@scorsi Cert manager is indeed needed for latest master. You have to spawn it on your own or use `make cert-manager`. It needs few seconds to initialize.
I see you're using c8115699 image (v0.1.9), which isn't compatible with master. 
I'll align install guide with mention about cert manager and we will release new Docker image to Docker Hub which works with latest scripts.

**Comment by zimnx** [comment]
@scorsi Please try with v0.2.2 which was released today.
