### ISSUE TITLE
Repair is triggered repeatedly

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1510]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In db logs we can find multiple repair requests (one node had 2249 occurrences over 12h test, see they appear in similar time):
```
INFO  2023-10-22 09:31:43,020 [shard  0] repair - repair[a8e797a8-5a76-48c3-8fbe-9b233b313883]: starting user-requested repair for keyspace keyspace1, repair id 789, options {{ hosts -> 172.20.36.24,172.20.25.170,172.20.67.101}, { columnFamilies -> standard1}, { ranges -> 9124434549921316097:9188838734908371860}}
INFO  2023-10-22 09:31:43,021 [shard  0] repair - repair[d5bb0e4c-4c45-4b64-820c-1ac88ed45851]: starting user-requested repair for keyspace keyspace1, repair id 790, options {{ hosts -> 172.20.25.170,172.20.67.101,172.20.36.24}, { columnFamilies -> standard1}, { ranges -> 9188838734908371860:9200963077934155553}}
INFO  2023-10-22 09:31:43,022 [shard  0] repair - repair[cebeb019-affe-4e55-9a5e-698c7752037d]: starting user-requested repair for keyspace keyspace1, repair id 791, options {{ hosts -> 172.20.36.24,172.20.67.101,172.20.25.170}, { columnFamilies -> standard1}, { ranges -> 9007611882491243037:9035715497213732394}}
WARN  2023-10-22 09:41:21,936 [shard  2] repair - repair[2839ee20-302a-415e-bfc1-0751e6eb31cd]: shard=2, keyspace=keyspace1, cf=standard1, range=(6451000176190542289, 6456358479733657758], got error in row level repair: std::system_error (No route to host)
WARN  2023-10-22 09:41:21,942 [shard  0] repair - repair[2839ee20-302a-415e-bfc1-0751e6eb31cd]: repair_tracker run failed: std::runtime_error ({shard 2: std::runtime_error (Failed to repair for keyspace=keyspace1, cf=standard1, range=(6451000176190542289, 6456358479733657758])})
```

## Impact

Repair is triggered over and over again

## How frequently does it reproduce?

don't know yet

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.1-20230906.f4633ec973b0` with build-id `b454e7a22f80cf71a33b2f39e47127225e8fbc13`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-13-g4bc44d9
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `longevity-scylla-operator-basic-12h-eks`
Test id: `0f64cf29-5ef7-45a7-98fe-e8c03223bf96`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-basic-12h-eks`
Test config file(s):

- [longevity-scylla-operator-basic-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d60806e7b31f0e9351674ba718a5cdac8df07b86/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0f64cf29-5ef7-45a7-98fe-e8c03223bf96`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0f64cf29-5ef7-45a7-98fe-e8c03223bf96)
- Show all stored logs command: `$ hydra investigate show-logs 0f64cf29-5ef7-45a7-98fe-e8c03223bf96`

## Logs:
- **kubernetes-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/kubernetes-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/kubernetes-0f64cf29.tar.gz)
- **db-cluster-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/db-cluster-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/db-cluster-0f64cf29.tar.gz)
- **sct-runner-events-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/sct-runner-events-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/sct-runner-events-0f64cf29.tar.gz)
- **sct-0f64cf29.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/sct-0f64cf29.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/sct-0f64cf29.log.tar.gz)
- **loader-set-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/loader-set-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/loader-set-0f64cf29.tar.gz)
- **monitor-set-0f64cf29.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/monitor-set-0f64cf29.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0f64cf29-5ef7-45a7-98fe-e8c03223bf96/20231022_121853/monitor-set-0f64cf29.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-basic-12h-eks/86/)
[Argus](https://argus.scylladb.com/test/c3f68ac3-b7cf-4ac8-8cf4-270db06f0e14/runs?additionalRuns[]=0f64cf29-5ef7-45a7-98fe-e8c03223bf96)
</details>

**Comment by fruch** [comment]
@soyacz 

I think this is cause of https://github.com/scylladb/scylla-operator/issues/838

**Comment by vponomaryov** [comment]
The `scylla-manager-controller` logs have following:

```
E1022 08:53:56.048887       1 manager/sync.go:137] "Failed to execute action" err="[PUT /cluster/{cluster_id}/task/{task_type}/{task_id}][500] PutClusterClusterIDTaskTaskTypeTaskID default  &{Message:create repair target: get client: agent [HTTP 404] Not found TraceID:Z_wNXaPlQ2SKXyLjFWrRmQ}" action="update task &{ClusterID: Enabled:true ID:63ca898c-6ee8-4b9b-897b-a4d230929ec9 Name:default-repair-task-name Properties:map[intensity:1 parallel:0 small_table_threshold:1073741824] Schedule:0xc000b16660 Tags:[] Type:repair}"
E1022 08:53:56.085522       1 manager/controller.go:150] syncing key 'scylla/sct-cluster' failed: [PUT /cluster/{cluster_id}/task/{task_type}/{task_id}][500] PutClusterClusterIDTaskTaskTypeTaskID default  &{Message:create repair target: get client: agent [HTTP 404] Not found TraceID:Z_wNXaPlQ2SKXyLjFWrRmQ}
E1022 08:53:56.102716       1 manager/sync.go:137] "Failed to execute action" err="[PUT /cluster/{cluster_id}/task/{task_type}/{task_id}][500] PutClusterClusterIDTaskTaskTypeTaskID default  &{Message:create repair target: read datacenters: agent [HTTP 404] Not found TraceID:H_1gUj7oRgCG-0EHvBr5Eg}" action="update task &{ClusterID: Enabled:true ID:63ca898c-6ee8-4b9b-897b-a4d230929ec9 Name:default-repair-task-name Properties:map[intensity:1 parallel:0 small_table_threshold:1073741824] Schedule:0xc0006b4f90 Tags:[] Type:repair}"
E1022 08:53:56.124764       1 manager/controller.go:150] syncing key 'scylla/sct-cluster' failed: [PUT /cluster/{cluster_id}/task/{task_type}/{task_id}][500] PutClusterClusterIDTaskTaskTypeTaskID default  &{Message:create repair target: read datacenters: agent [HTTP 404] Not found TraceID:H_1gUj7oRgCG-0EHvBr5Eg}
...
E1022 08:53:58.248140       1 manager/controller.go:150] syncing key 'scylla/sct-cluster' failed: [PUT /cluster/{cluster_id}/task/{task_type}/{task_id}][500] PutClusterClusterIDTaskTaskTypeTaskID default  &{Message:create repair target: get client: agent [HTTP 404] Not found TraceID:P6kw_LjOSXCf4nveVmP5YQ}
E1022 08:53:58.268039       1 manager/sync.go:137] "Failed to execute action" err="[PUT /cluster/{cluster_id}/task/{task_type}/{task_id}][500] PutClusterClusterIDTaskTaskTypeTaskID default  &{Message:create repair target: get client: agent [HTTP 404] Not found TraceID:ioBONfZpQB6j_zvfcwKXfg}" action="update task &{ClusterID: Enabled:true ID:63ca898c-6ee8-4b9b-897b-a4d230929ec9 Name:default-repair-task-name Properties:map[intensity:1 parallel:0 small_table_threshold:1073741824] Schedule:0xc00055b3b0 Tags:[] Type:repair}"
E1022 08:53:58.268185       1 manager/controller.go:150] syncing key 'scylla/sct-cluster' failed: [PUT /cluster/{cluster_id}/task/{task_type}/{task_id}][500] PutClusterClusterIDTaskTaskTypeTaskID default  &{Message:create repair target: get client: agent [HTTP 404] Not found TraceID:ioBONfZpQB6j_zvfcwKXfg}
```

**Comment by tnozicka** [comment]
@zimnx please take a look to assess the severity
