### ISSUE TITLE
Flake: ScyllaCluster [It] nodes are cleaned up after horizontal scaling

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1525]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1524/pull-scylla-operator-e2e-gke-parallel/1720397617084502016#1:test-build-log.txt%3A1594
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1524/pull-scylla-operator-e2e-gke-parallel/1720397617084502016/

```console
• [FAILED] [771.623 seconds]
ScyllaCluster [It] nodes are cleaned up after horizontal scaling
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_cleanup.go:29
...
[FAILED] Expected
      <[]utils.ObserverEvent[*k8s.io/api/batch/v1.Job] | len:3, cap:15>: [
...
      ]
  to have length 2
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_cleanup.go:109 @ 11/03/23 11:31:40.032
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func2.1()
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_cleanup.go:109 +0xd45
```

/kind flake
/priority important-longterm

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1552/pull-scylla-operator-e2e-gke-parallel/1722988328061505536#1:test-build-log.txt%3A1565

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/841/pull-scylla-operator-e2e-gke-parallel/1729123170528530432

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/841/pull-scylla-operator-e2e-gke-parallel/1729135508577062912

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1595/pull-scylla-operator-e2e-gke-parallel/1729109565250736128#1:test-build-log.txt%3A1506

**Comment by tnozicka** [comment]
linking the dupe and its failure https://github.com/scylladb/scylla-operator/issues/1621

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1649/pull-scylla-operator-e2e-gke-parallel/1737480701286027264

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1650/pull-scylla-operator-e2e-gke-parallel/1737483855834648576

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1660/pull-scylla-operator-e2e-gke-parallel/1738221325165531136

**Comment by zimnx** [comment]
Not seen it in a month.

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1691/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1750118539001335808

**Comment by tnozicka** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1730/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1758405700255485952

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1740/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1759923994686918656

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1784/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1764966891048144896

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1824/pull-scylla-operator-master-e2e-gke-parallel/1775154091148709888

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1881/pull-scylla-operator-master-e2e-gke-parallel/1775852196760391680#1:test-build-log.txt%3A1270

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1850/pull-scylla-operator-master-e2e-gke-parallel/1784902334371860480#1:test-build-log.txt%3A1545

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1908/pull-scylla-operator-master-e2e-gke-parallel/1798341703963250688#1:test-build-log.txt%3A1466

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1991/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1806704978857824256
