### ISSUE TITLE
Generate API reference in docs

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1526]
At this point, our docs have [an outdated example of ScyllaCluster API](https://operator.docs.scylladb.com/stable/scylla-cluster-crd.html). This is historical, manually written and outdated. We also have more APIs / CRs then just ScyllaClusters.

Doing this manually is unmaintainable. But there is a way to generate the API docs automatically, as many sites do, like
- [OpenShift API reference](https://docs.openshift.com/container-platform/4.14/rest_api/index.html)
- [Kubernetes API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/)

With some effort we can get swagger / openapi for our CRDs which can be used with an existing API docs generator. Given we use shpinx, https://github.com/sphinx-contrib/openapi would seem like a natural choice but it didn't work when I tried (see https://github.com/sphinx-contrib/openapi/issues/144) for details.

If that doesn't get fixed we could generate markdown, like kube does https://github.com/kubernetes/website/blob/5c744748410a7f1d4ebaa03800ace6c2c4f672e2/content/en/blog/_posts/2020-12-04-gsod-2020-improving-api-reference-experience.md#markdown-pages

**Comment by tnozicka** [comment]
@dgarcia360 @annastuchlik do you know whether we generate API reference docs from OpenAPI anywhere else with our sphinx theme?

**Comment by dgarcia360** [comment]
Hi @tnozicka,

We are generating OpenAPI docs for the [Scylla Cloud Docs](https://cloud.docs.scylladb.com/stable/api.html) project with a [custom extension](https://github.com/scylladb/scylla-cloud-doc/blob/master/docs/source/_ext/scylladb_openapi.py) we could reuse. It's based on [Redocly](https://redocly.com/).

During the following weeks, we are working with https://github.com/scylladb/scylladb to generate API Reference docs based on an OpenAPI v3 spec too. I think it might be a good time to make this extension as part of the theme (https://github.com/scylladb/sphinx-scylladb-theme/issues/722)

Could you define the API for scylla-operator using OpenAPI v3? In the meantime, I can help set up the tooling for generating the docs.
