### ISSUE TITLE
Problem upgrading from 1.7.4 to 1.10.0 using helm

### ISSUE THREAD

**Issue by FarhadF** [scylladb/scylla-operator#1542]
**Describe the bug**
When using prometheus stack (node_exporter daemonset) and host networking on scylla, operator version 1.10 will fail to bring up the scylla nodes as the port 9100 is already allocated. Is there a way to instruct operator to skip port 9100 and just use external node_exporter which is already deployed?

**To Reproduce**
1. Deploy prometheus stack using helm on EKS ( This will allocate port 9100 for node_exporter demonset)
2. Deploy v1.7.4 operator using helm on EKS
3. Deploy a 3 node scylla cluster (v5.2.9). (this will be successful)
4. Apply CRDs for v1.10.0 operator
5. Upgrade Operator to v1.10.0 using helm
6. Operator will terminate the first pod, The new pod will fail to come up as port 9100 is already allocated on the host.

**Expected behavior**
There should be a way to disable prepackaged node_exporter or config option to change the port.

**Comment by tnozicka** [comment]
Upgrades are only supported in N+1steps, please try again in steps.

/close
(unsupported upgrade flow)

Also note that helm doesn't upgrade CRDs so you have to do it manually every time - https://operator.docs.scylladb.com/stable/upgrade.html#upgrade-via-helm
(I'd avoid using hostNetworking.)

**Comment by FarhadF** [comment]
Thanks for the info @tnozicka , Upgraded the operator from 1.7.4 to 1.8.0 and the same issue occurred, is that what you mean by n+1 steps (1 minor version at the time)? 

I also removed host networking and it resolved the issue as expected (dynamic port on host for node_exporter instead of 9100).

Question: It is stated in the [documentation](https://operator.docs.scylladb.com/stable/generic.html#configure-host-networking) that set hostnetworking for more performance, is this outdated? because you mentioned you would avoid using it.

**Comment by tnozicka** [comment]
I think ScyllaDB wants n+1 upgrades as well to maintain the schema (on upgrades) but it's controlled by the user, not the operator (if you supply your own image it doesn't know which ones are in between or what's the correct z version.)

> It is stated in the [documentation](https://operator.docs.scylladb.com/stable/generic.html#configure-host-networking) that set hostnetworking for more performance, is this outdated? because you mentioned you would avoid using it.

outdated, see https://github.com/scylladb/scylla-operator/issues/1378
