### ISSUE TITLE
Upgrade from 1.10 to 1.11 results in error "Can't apply statefulset update"

### ISSUE THREAD

**Issue by schnapsidee** [scylladb/scylla-operator#1548]
**To Reproduce**
1. Install Operator version 1.10 with helm
2. Install scylla Cluster (in my case with scylla-manager, but any cluster should work)
3. Upgrade Operator to 1.11 with helm
4. See error in operator logs and status of scyllaCluster object

**Expected behavior**
Operator shouldn't attempt to change StatefulSet fields that cannot be changed.

**Logs**
CR Status: 
```yaml
      message: >-
        StatefulSetControllerDegraded: can't apply statefulset update: can't
        update apps/v1, Kind=StatefulSet
        "scylla-manager/scylla-manager-manager-dc-manager-rack":
        StatefulSet.apps "scylla-manager-manager-dc-manager-rack" is invalid:
        spec: Forbidden: updates to statefulset spec for fields other than
        'replicas', 'ordinals', 'template', 'updateStrategy',
        'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are
        forbidden
```

Operator Logs:
> "Event occurred" object="scylla-manager/scylla-manager-manager-dc-manager-rack" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Warning" reason="UpdateStatefulSetFailed" message="Failed to update StatefulSet scylla-manager/scylla-manager-manager-dc-manager-rack: StatefulSet.apps \"scylla-manager-manager-dc-manager-rack\" is invalid: spec: Forbidden: updates to statefulset spec 

**Environment:**
 - Platform: RKE2 on-prem
 - Kubernetes version: 1.26.7
 - Scylla version: 5.2.5
 - Scylla-operator version: e.g.: 1.11

**Additional Info**
Must-gather is attached. I removed sensitive secrets, but they shouldn't be relevant.
I'm using linkerd service-mesh sidecars which returns some errors in the must-gather logs but they shouldn't be relevant to the issue.

[must-gather.zip](https://github.com/scylladb/scylla-operator/files/13309183/must-gather.zip)

**Comment by tnozicka** [comment]
> Must-gather is attached. I removed sensitive secrets, but they shouldn't be relevant.

May I ask which ones had sensitive content? Asking because must-gather redacts them so either it's a bug or misunderstanding.

**Comment by schnapsidee** [comment]
> > Must-gather is attached. I removed sensitive secrets, but they shouldn't be relevant.
> 
> May I ask which ones had sensitive content? Asking because must-gather redacts them so either it's a bug or misunderstanding.

Ahh... My bad. I saw that a certificate secret was present and thought it contained the keys, but I just checked, and you're right, the private key is redacted and only the public key is still present. 

Either way, as I said, the secret itself shouldn't be relevant to the issue.

**Comment by tnozicka** [comment]
the issue usually is that it may not be the only thing that got deleted, say logs complain about an error with namespace `bimplan-scylla` that is missing in the dump as well

Is this a new cluster that was always upgraded in n+1 fashion? I have tried to sping up v1.10.0 and upgrade it to v1.11.0 and it went fine?

Are you able to reproduce it on fresh 1.10.0 cluster with v1.11.0 upgrade?

**Comment by tnozicka** [comment]
I'd also recommend raising the operator loglevel to 4 or looking into kube apiserver audit logs to see which field it is trying to change.

**Comment by schnapsidee** [comment]
> Is this a new cluster that was always upgraded in n+1 fashion?

I'm not the person that set this cluster up originally, so I can't say, but I found the issue.

Turns out, after the initial setup, the StatefulSet was changed manually. 

AutomaticTLSCertificates was set to false in the container command. (I assume because we have TLS being handled by linkerd and do not want to deal with manual certificate management). This wasn't documented internally, so I missed it initially. 

The operator however wasn't aware of this change, set the value back to true and thereafter attempted to mount the certificates as volumes, which I assume is where it failed.

The error could have been avoided if there was a way to disable AutomaticTLSCertificates during cluster setup, but I skimmed the scyllaCluster CRD and don't see any way to do this. Is this intentional, or did I miss something?

**Comment by tnozicka** [comment]
> I assume because we have TLS being handled by linkerd 

I don't think that covers localhost when someone hacks the node

> and do not want to deal with manual certificate management

it's managed, not manual - that's the whole point :)

> AutomaticTLSCertificates was set to false in the container command. 

The feature gate applies to the operator deployment, not for sidecar through statefulset.

**Comment by tnozicka** [comment]
The error could have been avoided if there was a way to disable AutomaticTLSCertificates during cluster setup, but I skimmed the scyllaCluster CRD and don't see any way to do this. Is this intentional, or did I miss something?

There isn't one. (You could supply your own certs though.)

The feature gate will eventually become GA and the option to disable it gone.

**Comment by schnapsidee** [comment]
> it's managed, not manual - that's the whole point :)

You still have to get the client to trust the CA, no? 

Either way, as I said, it's not a decision I made, but if the option to disable it is being removed anyway, I'll have to look into changing our setup anyway, so I'll do that :)

Thanks for your help!

**Comment by tnozicka** [comment]
yw

> You still have to get the client to trust the CA, no?

yeah, you are right about distributing to clients, but we can handle it for node to node + give you long lived client CA while still having short lived serving CAs
