### ISSUE TITLE
Update of the `spec.externalSeeds` option for `ScyllaCluster` triggers redundant pod-rollout breaking `QUORUM` having 2 pods.

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1570]
### What happened?

Scenario:
- Provision 2 EKS K8S clusters in 2 different regions (1:`eu-north-1` , 2:`eu-west-1`)
- Deploy 3 pods in the first region/K8S
- Deploy 3 more pods in the second region specifying the `spec.externalSeeds` field.
- Wait for the readiness of the DB cluster
- Run 2 stress commands with `LOCAL_QUORUM` - 1 per region
- Do some stuff with Scylla pods from first region which cause pod recreation making it change IP addresses
- Decommission last pod in the second region (at the end of the step we have 2 pods and QUORUM=2)
- Update the `spec.externalSeeds` field of the second `ScyllaCluster` object with the new IPs from the first region planning to add a new node
- Update the `spec.datacenter.racks.0.members` with the `3` value making it trigger a `add_node` operation with the idea of using the new/actual seed IP addresses
- **>>> FAILURE**: Scylla-operator starts roll-out of the existing pods breaking the `QUORUM`
- Wait for the DB cluster extention

Logs from the test runner:
```
2023-11-15 17:38:58,912 f:__init__.py     l:2553 c:sdcm.cluster_k8s     p:DEBUG > eu-west-1: Replace `/spec/externalSeeds' with `['10.0.11.107', '10.0.10.255', '10.0.11.205']' in sct-cluster's spec
2023-11-15 17:38:59,068 f:__init__.py     l:2553 c:sdcm.cluster_k8s     p:DEBUG > eu-west-1: Replace `/spec/datacenter/racks/0/members' with `3' in sct-cluster's spec
...
2023-11-15 17:39:09,465 f:__init__.py     l:936  c:sdcm.utils.k8s       p:INFO  > eu-west-1: 'scylla/sct-cluster-eu-west-1-rack-1-1' node has changed it's pod IP address from '10.4.8.73' to '10.4.8.104'. All old IPs: 10.4.9.133, 10.4.8.98, 10.4.8.147, 10.4.8.98, 10.4.8.104, 10.4.8.147, 10.4.8.104, 10.4.8.98, 10.4.8.73
...
023-11-15 17:39:51,143 f:__init__.py     l:936  c:sdcm.utils.k8s       p:INFO  > eu-west-1: 'scylla/sct-cluster-eu-west-1-rack-1-2' node has changed it's pod IP address from '10.4.10.176' to '10.4.11.50'. All old IPs: 10.4.8.142, 10.4.11.219, 10.4.10.176
...
2023-11-15 17:44:21,635 f:__init__.py     l:936  c:sdcm.utils.k8s       p:INFO  > eu-west-1: 'scylla/sct-cluster-eu-west-1-rack-1-0' node has changed it's pod IP address from '10.4.9.30' to '10.4.10.226'. All old IPs: 10.4.9.183, 10.4.9.246, 10.4.9.30
```

Node logs which was roll-outed first:
```
INFO  2023-11-15 17:38:55,782 [shard  0] gossip - 60000 ms elapsed, 10.4.11.219 gossip quarantine over
2023-11-15 17:38:59,527 INFO waiting for scylla to stop
INFO  2023-11-15 17:38:59,527 [shard  0] compaction_manager - Asked to stop
INFO  2023-11-15 17:38:59,527 [shard  0] compaction_manager - Stopping 1 tasks for 1 ongoing compactions due to shutdown
INFO  2023-11-15 17:38:59,527 [shard  0] init - Signal received; shutting down
INFO  2023-11-15 17:38:59,527 [shard  0] init - Shutting down view builder ops
INFO  2023-11-15 17:38:59,527 [shard  0] view - Draining view builder
```

Loader failure due to the breakage of the `QUORUM`:
```
loader-west-1
WARN  17:38:51,966 Error creating netty channel to 10-4-9-133.sct-cluster-eu-west-1-rack-1-1.scylla.svc.cluster.local/10.4.9.133:9042
com.datastax.shaded.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: 10-4-9-133.sct-cluster-eu-west-1-rack-1-1.scylla.svc.cluster.local/10.4.9.133:9042
Caused by: java.net.NoRouteToHostException: No route to host
...
com.datastax.driver.core.exceptions.ReadFailureException: Cassandra failure during read query at consistency LOCAL_QUORUM (2 responses were required but only 1 replica responded, 1 failed)
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency LOCAL_QUORUM (2 responses were required but only 1 replica responded, 1 failed)
```

So, update of the `spec.externalSeeds` field must not trigger roll-outs for the existing pods.
It makes no sense because the `seed` values are used only during the bootstrap.
So, when a pod reaches the time to roll-out it will pick up this value correctly anyway.

### What did you expect to happen?

I did expect that update of the `spec.externalSeeds` field doesn't trigger roll-outs.
Never.

### How can we reproduce it (as minimally and precisely as possible)?

Update the `spec.externalSeeds` field having 1-2 pods to get QUORUM breakage or update with any number of pods to get redundant roll-out.

### Scylla Operator version

v1.11.0

### Kubernetes platform name and version

<details>
Kubernetes platform info:

```
Client Version: version.Info{
    Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", 
    GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{
    Major:"1", Minor:"27+", GitVersion:"v1.27.7-eks-4f4795d", GitCommit:"3719c8491f81867f591e895a43b4f5aab4145794", 
    GitTreeState:"clean", BuildDate:"2023-10-20T23:21:04Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Please attach the must-gather archive.

- **kubernetes-181576c2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/kubernetes-181576c2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/kubernetes-181576c2.tar.gz)
- **db-cluster-181576c2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/db-cluster-181576c2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/db-cluster-181576c2.tar.gz)
- **sct-runner-events-181576c2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/sct-runner-events-181576c2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/sct-runner-events-181576c2.tar.gz)
- **sct-181576c2.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/sct-181576c2.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/sct-181576c2.log.tar.gz)
- **loader-set-181576c2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/loader-set-181576c2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/loader-set-181576c2.tar.gz)
- **monitor-set-181576c2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/monitor-set-181576c2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/181576c2-fca5-483c-a520-ce2108b9874a/20231115_174733/monitor-set-181576c2.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-multidc-12h-eks/4/)
[Argus](https://argus.scylladb.com/test/e9f07277-fc10-4a28-9f2a-cec9e662b5e9/runs?additionalRuns[]=181576c2-fca5-483c-a520-ce2108b9874a)

**Comment by rzetelskik** [comment]
> triggers redundant pod-rollout

why do you consider it redundant?

> It makes no sense because the seed values are used only during the bootstrap.

They are not, although the documentation claims otherwise. See https://github.com/scylladb/scylladb/blob/39ca07c49b257d37856164ea5b845f7b98224b98/gms/gossiper.cc#L1013. It's also described in the proposal https://github.com/scylladb/scylla-operator/blob/master/enhancements/proposals/1304-external-seeds/README.md#current-role-of-seeds-in-scylladb.

**Comment by rzetelskik** [comment]
@zimnx does breaking quorum part fall under https://github.com/scylladb/scylla-operator/issues/1077? The test is using PodIPs for broadcast addresses.

**Comment by zimnx** [comment]
PodIP setup are also affected due to Scylla not shutting down gracefully https://github.com/scylladb/scylladb/issues/15899

**Comment by vponomaryov** [comment]
> > triggers redundant pod-rollout
> 
> why do you consider it redundant?
> 
> > It makes no sense because the seed values are used only during the bootstrap.
> 
> They are not, although the documentation claims otherwise. See https://github.com/scylladb/scylladb/blob/master/gms/gossiper.cc#L1037. It's also described in the proposal https://github.com/scylladb/scylla-operator/blob/master/enhancements/proposals/1304-external-seeds/README.md#current-role-of-seeds-in-scylladb.

It is totally ok to use the `<std::vector<inet_address>>(_live_endpoints)` because those live nodes are part of the DB cluster we have.

> > I did expect that update of the spec.externalSeeds field doesn't trigger roll-outs.
> 
> Any changes to the manifest that affect the ScyllaDB config should be reflected there, and so should trigger a rolling restart. It's actually a bug that some of the fields don't, not that some do: #1389.

Any changes to the manifest which get used only during the bootstrap `must not` trigger the pod rollout.
The `seeds` list is one of such options.

**Comment by rzetelskik** [comment]
Sorry, wrong line from the gossiper code: https://github.com/scylladb/scylladb/blob/12f4f9f4812a52a5fc3415c6ec137b096093103c/gms/gossiper.cc#L1065.
In case gossiper can't reach any of the nodes, it uses initial seed nodes *past bootstrap*. So no, it's not true that the seeds are only used during bootstrap.

> Any changes to the manifest which get used only during the bootstrap must not trigger the pod rollout.

I disagree. If you want to change e.g. a domain name in the external seeds, you should be able to do so, and it should update the config the moment you do it, not at an arbitrary later time.
If you don't want the cluster to start a rolling restart, why update the seeds in the manifest in the first place?

**Comment by vponomaryov** [comment]
> Sorry, wrong line from the gossiper code: https://github.com/scylladb/scylladb/blob/12f4f9f4812a52a5fc3415c6ec137b096093103c/gms/gossiper.cc#L1065. In case gossiper can't reach any of the nodes, it uses initial seed nodes _past bootstrap_. So no, it's not true that the seeds are only used during bootstrap.
> 
> > Any changes to the manifest which get used only during the bootstrap must not trigger the pod rollout.
> 
> I disagree. If you want to change e.g. a domain name in the external seeds, you should be able to do so, and it should update the config the moment you do it, not at an arbitrary later time. 

What exactly we achieve triggering the rollout right away?

> If you don't want the cluster to start a rolling restart, why update the seeds in the manifest in the first place?

In our case it is done by default without knowledge of the redundant roll-outs.
So, yes, it turns out that we will need to work-around it if this bugreport doesn't get considered a `true bug`.

Having run lots of the K8S jobs which use Scylla pod IPs (in our QA automation we were doing it even before it ~became mainstream~ `started supporting manual multi-DC`) I can say that with time this option will contain only dead pod IPs because  pod IPs get changed easily.
It means that as less we depend on the `spec.externalSeeds` config option, which stores ephemeral data, as more stable we have Scylla clusters.

I would expect the `spec.externalSeeds` to be used only by the very first pod in the ScyllaCluster.
Real users/admins won't update the `spec.externalSeeds` manually each time Scylla pods from the first region get recreated.
So, as a result, in real production, at some point in time, new node will fail to be added due to having only dead IPs in this config option. But it could spin up totally ok using pods of the same `ScyllaCluster` as seeds.

**Comment by rzetelskik** [comment]
> So, as a result, in real production, at some point in time, new node will fail to be added due to having only dead IPs in this config option. But it could spin up totally ok using pods of the same ScyllaCluster as seeds.

The algorithm we use appends nodes from local DC for all nodes other than the first one joining the cluster - see https://github.com/scylladb/scylla-operator/blob/master/enhancements/proposals/1304-external-seeds/README.md#design-details. So it meets your expectations and rolling the cluster out on update of external seeds doesn't affect it.

**Comment by vponomaryov** [comment]
Ok, if it is `not a bug, but feature` from your point of view, then feel free to close it.

**Comment by rzetelskik** [comment]
There're two:
1. not rolling the cluster out on the manifest change - this we don't agree with and believe that config should be in sync with the manifest at all times, and we actually aim to make it work that way for the entire manifest: https://github.com/scylladb/scylla-operator/issues/1389.
2. the rolling restart, whatever triggered it, should not cause the loss of quorum - this is handled in https://github.com/scylladb/scylladb/issues/15899.

**Comment by vponomaryov** [comment]
> There're two:
> 
> 1. not rolling the cluster out on the manifest change - this we don't agree with and believe that config should be in sync with the manifest at all times, and we actually aim to make it work that way for the entire manifest: [Changes to some of the config values do not trigger a rolling restart #1389](https://github.com/scylladb/scylla-operator/issues/1389).
> 2. the rolling restart, whatever triggered it, should not cause the loss of quorum - this is handled in [Loss of availability below required consistency level during node shutdown scylladb#15899](https://github.com/scylladb/scylladb/issues/15899).

`2` is not possible without violation of the `1` when we have just 2 pods.

**Comment by tnozicka** [comment]
you should not run with 2 nodes :)

**Comment by vponomaryov** [comment]
> you should not run with 2 nodes :)

In our case it is temporary state where we simulate disruptions.
And it is `2` pods in one region from multiple.

**Comment by tnozicka** [comment]
ok, if you have a 3 node cluster with disruption and only 2 nodes available, a rolling update should wait, modulo #1077

**Comment by vponomaryov** [comment]
> ok, if you have a 3 node cluster with disruption and only 2 nodes available, a rolling update should wait, modulo #1077

As described in the bugreport, we `decommission` disrupted pod and then add new one.

**Comment by zimnx** [comment]
> As described in the bugreport, we decommission disrupted pod and then add new one.

decomission means you set number of nodes to 2. It's not a 3 node cluster then.

**Comment by rzetelskik** [comment]
> decomission means you set number of nodes from 3 to 2. It's not a 3 node cluster then.

In which case it's not possible to maintain a quorum during a rolling restart. So instead of decommissioning a node and then changing the manifest, you should either adjust the manifest first, or set the external seeds to a non-ephemeral IP or a domain name to avoid adjusting it altogether.

**Comment by vponomaryov** [comment]
The workaround fix for automation has already been completed and tested: https://github.com/scylladb/scylla-cluster-tests/pull/6820

**Comment by fruch** [comment]
@tnozicka is this checked out with anyone from core team, or @tzach  ?

**Comment by tnozicka** [comment]
@fruch can you be more specific?

**Comment by vponomaryov** [comment]
> > @tnozicka is this checked out with anyone from core team, or @tzach ?
> 
> @fruch can you be more specific?

Was the `forced rollout on any config option change` agreed with the Scylla core team and product owner?

**Comment by tnozicka** [comment]
> Was the forced rollout on any config option change agreed with the Scylla core team and product owner?

I don't see how it applies to scylla core team, they don't have the concept at all, this is operator level. We force rollouts for any config change that is not live reloaded, or is inside a structure that's not live reloaded as a whole. That's a general rule, not specific to this value.

**Comment by rzetelskik** [comment]
Also afaik a config drift between Scylla nodes is undesirable, isn't it?
