### ISSUE TITLE
Generated Scylla clusters refer to an invalid service name

### ISSUE THREAD

**Issue by NoiSek** [scylladb/scylla-operator#158]
**Describe the bug**
Using the default (generic) examples from the repo tagged at `v0.1.9` and `v0.1.8`, clusters will fail with the following error during pod creation:

```
> Error from server (InternalError): error when creating "test/scylla-cluster.yaml": Internal error occurred: failed calling webhook "vcluster.kb.io": Post https://scylla-operator-webhook-service.scylla-operator-system.svc:443/validate-scylla-scylladb-com-v1alpha1-cluster?timeout=30s: service "scylla-operator-webhook-service" not found
```

The service it refers to doesn't exist under that name.

Actual list of services generated by the Scylla Operator:

```
$ kubectl get services -n scylla-operator-system
> NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
> scylla-operator-controller-manager-service   ClusterIP   10.152.183.174   <none>        443/TCP   22m
> webhook-server-service                       ClusterIP   10.152.183.151   <none>        443/TCP   22m
```

So it appears that Scylla clusters look for `scylla-operator-webhook-service` rather than the actual name of `webhook-server-service`.

**To Reproduce**
1. Initialize a generic K8s environment
2. Bring up a cluster using the generic K8s samples 
3. Observe the error visible with `kubectl describe pod scylla-0 -n scylla`
4. Observe the actual service it refers to with `kubectl get services -n scylla-operator-system`

**Expected behavior**
Scylla clusters should refer to the correct service name and initialize properly.

**Config Files**
https://github.com/scylladb/scylla-operator/blob/v0.1.9/examples/generic/cluster.yaml
https://github.com/scylladb/scylla-operator/blob/v0.1.9/examples/generic/operator.yaml

**Environment:**
 - Platform: microk8s
 - Kubernetes version: `1.18.4`
 - Scylla version: `4.0.0`
 - Scylla-operator version: Tagged at `v0.1.9`

**Comment by dahankzter** [comment]
Can you test using minikube or k3d as well?
It's the first time I see this issue so perhaps it's related to microk8s?

**Comment by NoiSek** [comment]
I was able to reproduce the error consistently with Minikube as well, but that error seems to have been occurring as a result of multiple containers running on Scylla instances (linkerd sidecar).

When the operator itself has more than one container running, the operator throws an explicit error akin to: "Scylla manager must have only one container running". The `service "scylla-operator-webhook-service" not found` error seems to occur when child clusters created by the operator have injected sidecars but the operators themselves do not.

I can say that after removing linkerd from both (undesirable, but functional) everything functions as expected. The Scylla operator still seems to generate a service that doesn't match the rest of the naming scheme as `webhook-server-service`, and I do still see the `service "scylla-operator-webhook-service" not found` error on initialization, but it resolves itself and then proceeds as normal for unknown reasons.

Very uneducated guess: Since the `scylla-operator-webhook-service` service really does not exist, adding linkerd as a proxy between inbound / outbound requests causes it to fail when routing where normally some sort of Operator request interception trickery makes that work.

Where exactly does the `webhook-server-service` name even come from? There's no string like that in the entire codebase as far as I can see.

**Comment by dahankzter** [comment]
The operator itself doesn't handle multiple concurrent instances. It would be nice to have but hasn't been considered yet. As for the webhook it is the operator that uses the name `scylla-operator-webhook-service` defined in the operator.yaml for it's admission webhook. How linkerd plays into the whole thing I can not even begin to speculate.

**Comment by NoiSek** [comment]
Right, `scylla-operator-webhook-service` is defined but where is the name `webhook-server-service` coming from?

How one resolves to the other is a mystery, but I'm curious how that name comes into place to begin with. Is that unusual, or or is it expected to see the `webhook-server-service` ClusterIP?

**Comment by dahankzter** [comment]
I don't see any service with that name:
```sh
➜  generic git:(master) kubectl get services --all-namespaces
NAMESPACE                NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                           AGE
cert-manager             cert-manager                            ClusterIP   10.104.249.36    <none>        9402/TCP                                                          22h
cert-manager             cert-manager-webhook                    ClusterIP   10.101.104.203   <none>        443/TCP                                                           22h
default                  kubernetes                              ClusterIP   10.96.0.1        <none>        443/TCP                                                           22h
kube-system              kube-dns                                ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP                                            22h
scylla-operator-system   scylla-operator-webhook-service         ClusterIP   10.104.122.114   <none>        443/TCP                                                           22h
scylla                   simple-cluster-client                   ClusterIP   None             <none>        9180/TCP                                                          22h
scylla                   simple-cluster-us-east-1-us-east-1a-0   ClusterIP   10.96.245.209    <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9042/TCP,9142/TCP,9160/TCP   22h
scylla                   simple-cluster-us-east-1-us-east-1a-1   ClusterIP   10.107.132.100   <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9042/TCP,9142/TCP,9160/TCP   22h
scylla                   simple-cluster-us-east-1-us-east-1a-2   ClusterIP   10.97.226.137    <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9042/TCP,9142/TCP,9160/TCP   22h
```
Did you update to the latest version? Make any changes?

**Comment by NoiSek** [comment]
Those results were all against the stable, tagged version of `0.1.9`. 

That said, I haven't been able to reproduce that issue as of today on `0.1.8`, `0.1.9`, or even the latest from master suddenly with no changes whatsoever made. Couldn't possibly explain why.

As of today, that `webhook-server-service` has disappeared and I'm no longer seeing any errors:
```
$ kubectl get services -n scylla-operator-system
NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
scylla-operator-webhook-service   ClusterIP   10.110.152.59   <none>        443/TCP   25m
```

Baffled. But I'm closing this out since this is no longer reproducible.
