### ISSUE TITLE
Boolean argument for replace-address-first-boot missing

### ISSUE THREAD

**Issue by lordphnx** [scylladb/scylla-operator#1580]
### What happened?

```
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --smp 1 --overprovisioned --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=10.245.169.101 --broadcast-address 10.245.7.69 --broadcast-rpc-address 10.245.7.69 --alternator-address 0.0.0.0 --replace-address-first-boot --blocked-reactor-notify-ms 999999999 --prometheus-address=0.0.0.0"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, io-properties-file: /etc/scylla.d/io_properties.yaml, smp, (positional) 1, overprovisioned, listen-address: 0.0.0.0, rpc-address: 0.0.0.0, seed-provider-parameters: seeds=10.245.169.101, broadcast-address: 10.245.7.69, broadcast-rpc-address: 10.245.7.69, alternator-address: 0.0.0.0, replace-address-first-boot: --blocked-reactor-notify-ms, (positional) 999999999, prometheus-address: 0.0.0.0]
error: too many positional options have been specified on the command line
```

### What did you expect to happen?

After discussion on slack, it appears the arugment

```
replace-address-first-boot
```

Should be 
```
replace-address-first-boot true
```

### How can we reproduce it (as minimally and precisely as possible)?

I followed the https://operator.docs.scylladb.com/stable/nodeoperations/replace-node.html guide and 
used scylla/replace="" label

### Scylla Operator version

1.11

### Kubernetes platform name and version

<details>
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.4

```

Kubernetes platform info:
Digital Ocean
</details>

### Please attach the must-gather archive.

Corporate policy prevents me from exporting a bunch of data about our infrastructure, apologies for this. I would be happy to answer individual questions

**Comment by rzetelskik** [comment]
> Corporate policy prevents me from exporting a bunch of data about our infrastructure, apologies for this. I would be happy to answer individual questions.

The purpose of having the archive is so that we don't have to ask the individual questions. ;)
You can always gather the dumps from an individual namespace and manually redact whatever you consider confidential. See https://operator.docs.scylladb.com/stable/support/must-gather.html for reference.

/priority awaiting-more-evidence

**Comment by tnozicka** [comment]
more than half a year without supplying the required information
