### ISSUE TITLE
Upgrade Manager - to 3.2.5

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-operator#1588]
### What should the feature do?

It's important, as we have critical fixes in >3.2.

### What is the use case behind this feature?

Repair functionality, but also some backup/restore fixes.

**Comment by tnozicka** [comment]
I've created https://github.com/scylladb/scylla-operator/pull/1603
but this is blocked on manager API that broke backwards API compatibility https://github.com/scylladb/scylla-manager/issues/3649

**Comment by tnozicka** [comment]
3.2.5 snapshot has passed with our CI, waiting for the official tag
