### ISSUE TITLE
Need to upgrade container OS packages during Docker image creation

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-operator#1608]
### What happened?

Similar to https://github.com/scylladb/scylladb/issues/16222 , we need to run 'apt-get upgrade' on container creation to get the latest-greatest available packages.

### What did you expect to happen?

More up-to-date OS packages are available in the Docker image.

### How can we reproduce it (as minimally and precisely as possible)?

I run ```trivy image  --timeout 30m  scylladb/scylla-operator:nightly```

### Scylla Operator version

nightly

### Kubernetes platform name and version

<details>
```console
$ kubectl version
# paste output here
```

Kubernetes platform info:
</details>
 

### Please attach the must-gather archive.

a

### Anything else we need to know?

a

**Comment by mykaul** [comment]
Although https://github.com/scylladb/scylla-operator-images/blob/master/base/ubuntu/22.04/Dockerfile seems to have it - so do we need to re-generate them more regularly?

**Comment by tnozicka** [comment]
`scylladb/scylla-operator:nightly` this is also not used anymore but I am not sure we can delete the repo

**Comment by mykaul** [comment]
I think it's now done on a regular basis (weekly) - we could do it just before a release, but I don't think it matters that much - closing.
