### ISSUE TITLE
Error installing scylla-manager using Helm

### ISSUE THREAD

**Issue by bipul-baishya** [scylladb/scylla-operator#1623]
### What happened?

Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": Post "[https://scylla-operator-webhook.scylla-operator.svc:443/validate?timeout=10s](https://scylla-operator-webhook.scylla-operator.svc/validate?timeout=10s)": x509: certificate signed by unknown authority

### What did you expect to happen?

Syclla-manager should come UP

### How can we reproduce it (as minimally and precisely as possible)?

Deployed Scylla Operator with default configuration using helm.
Next tried deploying Scylla Manager with default values, during which encountered this issue.

### Scylla Operator version

1.11.0

### Kubernetes platform name and version

<details>
```console
$ kubectl version
# paste output here
```

Kubernetes platform info:
</details>
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Please attach the must-gather archive.

kubectl config view --minify
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

### Anything else we need to know?

https://github.com/scylladb/scylla-manager/issues/3657

**Comment by tnozicka** [comment]
> Please attach the must-gather archive.
> kubectl config view --minify
> apiVersion: v1
> clusters:

you are posting your redacted kubeconfig, not must-gather archive, please follow https://operator.docs.scylladb.com/stable/support/must-gather.html

> Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": Post "[https://scylla-operator-webhook.scylla-operator.svc:443/validate?timeout=10s](https://scylla-operator-webhook.scylla-operator.svc/validate?timeout=10s)": x509: certificate signed by unknown authority

this means the operator deployment failed. do you have cert-manager running?

**Comment by tnozicka** [comment]
without a response for over half a year, closing
