### ISSUE TITLE
Upgrade procedure over PodIPs gets clusters stuck in a degraded state

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1638]
### What happened?

If you try to upgrade a ScyllaCluster exposed over PodIPs, it will get stuck in a degraded state.
See e.g. https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1508/pull-scylla-operator-e2e-gke-parallel/1734923770008702976#1:test-build-log.txt%3A2515.

Example conditions from a local run:
```
  - lastTransitionTime: "2023-12-12T17:08:32Z"
    message: 'StatefulSetControllerDegraded: service e2e-test-scyllacluster-jfc9h-l7xbw/basic-qs2p2-us-east-1-rack-0-0
      doesn''t have a ClusterIP'
    observedGeneration: 2
    reason: StatefulSetControllerDegraded_Error
    status: "True"
    type: Degraded
```

### What did you expect to happen?

The upgrade procedure should support ScyllaClusters exposed over PodIPs.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a ScyllaCluster exposed over PodIPs and wait for it to roll out.
- Upgrade Scylla version.

### Scylla Operator version

master

### Kubernetes platform name and version

<details>
```console
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

Kubernetes platform info:
n/a
</details>

### Please attach the must-gather archive.

https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1508/pull-scylla-operator-e2e-gke-parallel/1734923770008702976/

**Comment by zimnx** [comment]
Note:
Only major and minor ScyllaDB version upgrades are affected. 
Patch version upgrades are not.
