### ISSUE TITLE
Scylla-manager (3.2.5) fails to create `repair` task with `create repair target: calculate intensity limits: 172.20.36.130: get shard count: context canceled"` error

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1648]
### What happened?

Triggering the `scylla-manager repair` task on the EKS backend leads to the following errors in the `scylla-manager` logs:

```
{"L":"INFO","T":"2023-12-17T01:24:28.005Z","N":"cluster.client","M":"HTTP retry now","operation":"GossiperEndpointLiveGet","error":"after 30s: context deadline exceeded","_trace_id":"hou5bXBzQ8SjmJP2_4EWXg"}
...
{"L":"INFO","T":"2023-12-17T01:26:00.713Z","N":"repair","M":"No cluster credentials, couldn't ensure repairing base table before its views","error":"get client: discover cluster topology: context canceled","_trace_id":"RPmCnTHpQo-5J0tR8MJvgw"}
{"L":"INFO","T":"2023-12-17T01:26:00.714Z","N":"http","M":"POST /api/v1/cluster/c21743b1-7e0c-4712-8875-3e709fe6b733/tasks","from":"10.0.2.57:37528","status":500,"bytes":162,"duration":"15002ms","error":"create repair target: calculate intensity limits: 172.20.36.130: get shard count: context canceled","_trace_id":"RPmCnTHpQo-5J0tR8MJvgw"}
```

And in test runner logs we see no `repair` task:
```
2023-12-17 01:24:18,641 f:remote_base.py  l:521  c:KubernetesCmdRunner  p:DEBUG > Running command "sctool tasks -c c21743b1-7e0c-4712-8875-3e709fe6b733"...
2023-12-17 01:24:18,736 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > +------------------------+-------------+--------+----------+---------+-------+------------------------+------------+---------+-----------------       -------+
2023-12-17 01:24:18,736 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | Task                   | Schedule    | Window | Timezone | Success | Error | Last Success           | Last Error | Status  | Next                          |
2023-12-17 01:24:18,737 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > +------------------------+-------------+--------+----------+---------+-------+------------------------+------------+---------+-----------------       -------+
2023-12-17 01:24:18,737 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | healthcheck/cql        | @every 15s  |        | UTC      | 138     | 0     | 17 Dec 23 01:24:14 UTC |            | DONE    | 17 Dec 23 01:24:       29 UTC |
2023-12-17 01:24:18,737 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | healthcheck/rest       | @every 1m0s |        | UTC      | 35      | 0     | 17 Dec 23 01:23:39 UTC |            | DONE    | 17 Dec 23 01:24:       39 UTC |
2023-12-17 01:24:18,737 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | healthcheck/alternator | @every 15s  |        | UTC      | 133     | 0     | 17 Dec 23 01:23:43 UTC |            | RUNNING |                               |
2023-12-17 01:24:18,737 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > +------------------------+-------------+--------+----------+---------+-------+------------------------+------------+---------+-----------------       -------+
2023-12-17 01:24:18,751 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "sctool tasks -c c21743b1-7e0c-4712-8875-3e709fe6b733" finished with status 0

```

### What did you expect to happen?

The `repair` task must be created successfully without any errors in the `scylla-manager` logs

### How can we reproduce it (as minimally and precisely as possible)?

- Deploy EKS cluster
- Deploy there `latest` scylla-operator which includes the https://github.com/scylladb/scylla-operator/pull/841
- Deploy the `3.2.5` scylla-manager
- Deploy 3-node DB cluster
- Trigger the `scylla-manager repair` task creation
- See errors

### Scylla Operator version

`v1.12.0-alpha.0-144-g60f7824`

### Kubernetes platform name and version
`EKS`, `v1.27.8-eks-8cb36c9`

## Logs:
- **kubernetes-58be8dee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/kubernetes-58be8dee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/kubernetes-58be8dee.tar.gz)
- **kubernetes-must-gather-58be8dee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/kubernetes-must-gather-58be8dee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/kubernetes-must-gather-58be8dee.tar.gz)
- **db-cluster-58be8dee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/db-cluster-58be8dee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/db-cluster-58be8dee.tar.gz)
- **sct-runner-events-58be8dee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/sct-runner-events-58be8dee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/sct-runner-events-58be8dee.tar.gz)
- **sct-58be8dee.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/sct-58be8dee.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/sct-58be8dee.log.tar.gz)
- **loader-set-58be8dee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/loader-set-58be8dee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/loader-set-58be8dee.tar.gz)
- **parallel-timelines-report-58be8dee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/parallel-timelines-report-58be8dee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/parallel-timelines-report-58be8dee.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-eks/141/)
[Argus](https://argus.scylladb.com/test/89fdaa2f-5255-4696-a268-90cb7090482e/runs?additionalRuns[]=58be8dee-4c43-48f5-85ee-9433752f3d99)

**Comment by vponomaryov** [comment]
It works on the `local K8S`. So, probably related to the platform-specific stuff.

**Comment by vponomaryov** [comment]
Another repro of this bug with logs gathered right after the failed test:

## Installation details

Kernel Version: 5.10.199-190.747.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.2-20231001.646df23cc4b3` with build-id `367fcf1672d44f5cbddc88f946cf272e2551b85a`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-144-g60f7824
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: `eu-north-1`)

Test: `vp-functional-eks`
Test id: `f478119b-56d1-4009-8492-9da3ea65c63d`
Test name: `scylla-staging/valerii/vp-functional-eks`
Test config file(s):

- [functional.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/618807aaaee29e7432fc786328118af1743959b2/test-cases/scylla-operator/functional.yaml)

<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor f478119b-56d1-4009-8492-9da3ea65c63d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f478119b-56d1-4009-8492-9da3ea65c63d)
- Show all stored logs command: `$ hydra investigate show-logs f478119b-56d1-4009-8492-9da3ea65c63d`

## Logs:
- **kubernetes-f478119b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/kubernetes-f478119b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/kubernetes-f478119b.tar.gz)
- **kubernetes-must-gather-f478119b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/kubernetes-must-gather-f478119b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/kubernetes-must-gather-f478119b.tar.gz)
- **db-cluster-f478119b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/db-cluster-f478119b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/db-cluster-f478119b.tar.gz)
- **sct-runner-events-f478119b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/sct-runner-events-f478119b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/sct-runner-events-f478119b.tar.gz)
- **sct-f478119b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/sct-f478119b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/sct-f478119b.log.tar.gz)
- **parallel-timelines-report-f478119b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/parallel-timelines-report-f478119b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f478119b-56d1-4009-8492-9da3ea65c63d/20231218_124942/parallel-timelines-report-f478119b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-functional-eks/48/)
[Argus](https://argus.scylladb.com/test/e9294e61-0380-4232-9945-04f8d9837037/runs?additionalRuns[]=f478119b-56d1-4009-8492-9da3ea65c63d)
</details>

**Comment by zimnx** [comment]
This seems like a Manager issue, not Operator one. Operator tried to register repair task, but Manager is not able to do it.

**Comment by tnozicka** [comment]
or the scyllacluster the manager talks to had a hickup, unfortunately the logs for `sct-cluster-eu-north-1-rack-1-1` start over an hour later (`2023-12-17T02:37:41.764997586Z`)

**Comment by vponomaryov** [comment]
> or the scyllacluster the manager talks to had a hickup, unfortunately the logs for `scylla/sct-cluster-eu-north-1-rack-1-1` start over an hour later (`2023-12-17T02:37:41.764997586Z`)

The full (streamed) Scylla pods logs are here: https://cloudius-jenkins-test.s3.amazonaws.com/58be8dee-4c43-48f5-85ee-9433752f3d99/20231217_024128/db-cluster-58be8dee.tar.gz (it is attached in the bygreport)

**Comment by tnozicka** [comment]
A lot has changed since, and we use manager 3.3.0. Please open a new issue, if see it again.
