### ISSUE TITLE
Support Annotations on PVC's

### ISSUE THREAD

**Issue by steve-gray** [scylladb/scylla-operator#1668]
### What should the feature do?

When creating the PVC's to claim volumes, the custom resource specification should support passing annotations/labels to the claims. For example:

```
    "ebs.csi.aws.com/volumeType": "gp3"
    "ebs.csi.aws.com/iops": "5000"
    "ebs.csi.aws.com/throughput": "250"
```

### What is the use case behind this feature?

Allows people to pass annotations to the cloud provider CSI that's responsible for provisioning the disks. This is useful across all cloud providers generally where disks can be provisioned with various classes of capability.

**Comment by tnozicka** [comment]
sounds reasonable, I'll try to include it in #1665

**Comment by tnozicka** [comment]
although this can only be set once and not updated because Kubernetes statefulsets don't reconcile PVCs

**Comment by steve-gray** [comment]
Yeah, it cuts both ways. Today we rely on the fact its never updated to allow us to adjust form the defaults in the AWS console post-deployment. :)

**Comment by tnozicka** [comment]
Be aware that it might get reconciled eventually. I recall Kubernetes was moving towards eventually supporting the reconciliation or we'd if we ever replace StatefulSets we'd reconcile it as well. It's important to reconcile so you can expand storage.

**Comment by tnozicka** [comment]
done in #1664
