### ISSUE TITLE
Init: InvalidImageName Status

### ISSUE THREAD

**Issue by kocic11** [scylladb/scylla-operator#1669]
### What happened?

I am trying to deploy the Scylla DB cluster following the [documentation](https://operator.docs.scylladb.com/stable/generic.html). However, the cluster deployment fails with the error below, and the pod is in the Init: InvalidImageName status.

`Failed to apply default image tag "e2db9873c2f758d1dbb6dd808dc821b56ee58fe5dd1105115f94477f9b281f41": couldn't parse image name "e2db9873c2f758d1dbb6dd808dc821b56ee58fe5dd1105115f94477f9b281f41": invalid repository name (e2db9873c2f758d1dbb6dd808dc821b56ee58fe5dd1105115f94477f9b281f41), cannot specify 64-byte hexadecimal strings`

From the operator logs, it is the operator image ID:
`I0102 20:07:53.779838       1 operator/operator.go:282] "Successfully introspected its own image" OperatorImage="e2db9873c2f758d1dbb6dd808dc821b56ee58fe5dd1105115f94477f9b281f41"`
`I0102 20:07:53.779864       1 operator/operator.go:289] operator version "v1.11.0-rc.5-0-gca030a9"`

### What did you expect to happen?

The cluster is deployed.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy cluster following the documentation.

### Scylla Operator version

v1.11.0-rc.5-0-gca030a9

### Kubernetes platform name and version

<details>
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.11-dispatcher", GitCommit:"bb1bff031c9872d3d4c0a97871ae1a8d4882950a", GitTreeState:"clean", BuildDate:"2023-06-28T14:50:51Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.2", GitCommit:"6f3fcf83109204e359ca38144405293dbeec2200", GitTreeState:"clean", BuildDate:"2023-10-20T09:33:45Z", GoVersion:"go1.20.8 4493 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

Kubernetes platform info:
</details>

### Please attach the must-gather archive.

[scylla-operator-must-gather-dmnpzxft4btv.zip](https://github.com/scylladb/scylla-operator/files/13813909/scylla-operator-must-gather-dmnpzxft4btv.zip)

**Comment by tnozicka** [comment]
```
  - containerID: cri-o://fd3dfdc05413c177a8eaf1e038c2ceaa2e692c6c7f91169e9d15b6e79d2b48a0
    image: docker.io/scylladb/scylla-operator:1.11.0
    imageID: e2db9873c2f758d1dbb6dd808dc821b56ee58fe5dd1105115f94477f9b281f41
```
the container runtime has published an imageID that can't be used as a sidecar image and our autodetection has used it for the scylladb sidecar

https://github.com/scylladb/scylla-operator/blob/3611a8ecd4c34d7ba8a44da66de3f57a38fd5ba4/pkg/cmd/operator/operator.go#L209-L289

Can you please provide the Kubernetes platform, OS and crio version?

You can disable the autodetection by setting `--image=<operator_image_sha_ref>` to the operator binary. That should make this work for you. Just make sure the operator image used by the operator pod is always identical with the `--image` flag and that the image preferably uses sha, so it is always identical image even in case of different pull times.

**Comment by kocic11** [comment]
I added the --image flag to the operator "args" section:
```
args:
- operator
- --loglevel=2
- --image="sha256:e2db9873c2f758d1dbb6dd808dc821b56ee58fe5dd1105115f94477f9b281f41"
```

However, it didn't help:

**Comment by kocic11** [comment]
This is the Oracle OKE Kubernetes platform:
`crio version 1.28.2-169.el8`
```
NAME="Oracle Linux Server"
VERSION="8.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.8"
```

**Comment by kocic11** [comment]
The operator rolling restart didn't work. However, deleting the operator and creating it again with the following image value worked:

**Comment by tnozicka** [comment]
> - --image="sha256:e2db9873c2f758d1dbb6dd808dc821b56ee58fe5dd1105115f94477f9b281f41"

this isn't valid (missing repo part) + I don't think this takes quotes, it's not in shell context

**Comment by tnozicka** [comment]
I'll make a fix for the introspection / or a fallback. For now you should be good with the workaround.

**Comment by comsky** [comment]
Experiencing the same issue with Helm chart version:
scylla/scylla-operator v1.11.1
scylla/scylla v1.11.1
scylla/scylla-manager v1.11.1

`Failed to apply default image tag "700e229ca87ed53658a8bfa7fd162d8ebffda86dc7a45edc5e2b92089c84af36": couldn't parse image name "700e229ca87ed53658a8bfa7fd162d8ebffda86dc7a45edc5e2b92089c84af36": invalid repository name (700e229ca87ed53658a8bfa7fd162d8ebffda86dc7a45edc5e2b92089c84af36), cannot specify 64-byte hexadecimal strings`

After manually updating the image tag of StatefulSet, it started working somehow.
StatefulSet => scylla-default-default, scylla-manager-manager-dc-manager-rack
```
spec:
  initContainers:
    - name: sidecar-injection
       image: 700e229ca87ed53658a8bfa7fd162d8ebffda86dc7a45edc5e2b92089c84af36 => scylladb/scylla-operator:1.11.1
```

**Comment by comsky** [comment]
Version v1.10.0 is working perfectly fine. However, the issue seems to have arisen since version v1.11.

**Comment by tnozicka** [comment]
> After manually updating the image tag of StatefulSet, it started working somehow.

that's fragile and won't hold on the next update. The workaround is to give the operator binary and explicit `--image` flag (`--image=docker.io/scylladb/scylla-operator:1.11.0`)

**Comment by rzetelskik** [comment]
Hit the same issue:
```
$ kubectl logs -n scylla-operator deployments/scylla-operator
...
I0112 11:15:04.180246       1 operator/operator.go:210] "No explicit operator image specified - starting auto detection from Pod status"
I0112 11:15:04.189348       1 operator/operator.go:228] "Waiting for Pod status to be updated" Timeout="5m0s"
I0112 11:15:04.194062       1 operator/operator.go:288] "Successfully introspected its own image" OperatorImage="700e229ca87ed53658a8bfa7fd162d8ebffda86dc7a45edc5e2b92089c84af36"
```

```
$ kubectl get pod -n scylla-operator scylla-operator-6bcf48f54c-927ws -oyaml
...
  containerStatuses:
  - containerID: cri-o://13c6641f6b922ade121c2e97a12fc94299f325fe0d69a1a4fc9c7839b8d327f2
    image: docker.io/scylladb/scylla-operator:1.11.1
    imageID: 700e229ca87ed53658a8bfa7fd162d8ebffda86dc7a45edc5e2b92089c84af36
    lastState:
      terminated:
        containerID: cri-o://d87ef566bda347883e7ef5e1810e0032ca22fb9607f40a1b4ed9bd0d309d44ac
        exitCode: 1
        finishedAt: "2024-01-12T11:15:03Z"
        reason: Error
        startedAt: "2024-01-12T11:15:03Z"
    name: scylla-operator
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-01-12T11:15:04Z"
...
```

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

```
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```

```
$ crio version
INFO[2024-01-12 11:37:05.691618873Z] Starting CRI-O, version: 1.28.2, git: unknown(clean)
Version:        1.28.2
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-12-08T17:14:13Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  apparmor
  seccomp
  containers_image_ostree_stub
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  containers_image_openpgp
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/version.buildDate=2023-12-08T17:14:13Z
SeccompEnabled:   true
AppArmorEnabled:  true
```

From a quick search it looks like the introspection logic was based on a faulty behaviour, which was fixed since: https://github.com/cri-o/cri-o/pull/7149. It looks like at this point there is no way for us to retrieve the digest from container runtime if an image tag was provided?
