### ISSUE TITLE
'Restore from backup' documentation section is confusing and unclear

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1670]
### What happened?

I tried to follow the procedure described in [Restore from backup](https://operator.docs.scylladb.com/stable/nodeoperations/restore.html) section of our documentation and found it very confusing and full of errors:

- `sctool backup files -c <CLUSTER_ID> -L <BACKUP_LOCATION> -T <SNAPSHOT_TAG>`
This line is missing `--all-clusters` flag. Without it, it doesn't list any files.

- The document advises users to copy and import each schema file from the archive found in the backup. The import command fails for `system_schema`.

```
$ kubectl -n scylla exec scylla-us-east-1-us-east-1a-0 -c scylla -- cqlsh -f /tmp/system_schema.cql
/tmp/system_schema.cql:4:InvalidRequest: Error from server: code=2200 [Invalid query] message="system keyspace is not user-modifiable"
/tmp/system_schema.cql:30:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:53:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:72:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:91:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:114:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:136:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:158:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:184:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:224:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:250:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:272:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:298:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:321:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:345:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
/tmp/system_schema.cql:382:Unauthorized: Error from server: code=2100 [Unauthorized] message="system_schema keyspace is not user-modifiable."
command terminated with exit code 2
```

The document doesn't mention whether this is expected, so I assume it's not. 

- `kubectl -n scylla-manager exec deployment.apps/scylla-manager-controller -- sctool backup files -c simple-cluster -L s3:backups -T sm_20201228145917UTC > backup_files.out`

The scylla-manager-controller pods are missing `sctool` binary. I assume this was supposed to target scylla-manager deployment instead.

- The `sstableloader` section is completely unclear as to where the users are supposed to run these commands. The use of `sstableloader` implies they should be run in a Scylla pod, but Scylla image is missing s3 utils.

### What did you expect to happen?

The steps should be understandable and shouldn't produce any errors.

### How can we reproduce it (as minimally and precisely as possible)?

Run the steps as described in the doc.

### Scylla Operator version

Scylla Operator: 1.11.1
Scylla: scylla-enterprise 2023.1.3
Scylla Manager: 3.2.5

### Kubernetes platform name and version

n/a

### Please attach the must-gather archive.

n/a

**Comment by rzetelskik** [comment]
@tnozicka we need to evaluate whether this procedure is still ok to use, especially given the failed import for system keyspaces, and if we should just correct these mistakes, or if we should advise a manual procedure using  `sctool restore`.

**Comment by tnozicka** [comment]
Whatever is less work for the immediate fix and we need to followup with something more conceptual / changing the approach.

adding Maciek to assist you on hot fixing the procedure
/assign @zimnx
