### ISSUE TITLE
Explicitly disable CQL over TLS (that never worked but breaks backups)

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1674]
We need to disable CQL over TLS for scylla-manager as is falsely detects that is should be used instead of regular CQL even though it doesn't have the TLS certs. This breaks backup flow, probably pings and something else in the manager.

### Requires
- [x] https://github.com/scylladb/scylla-manager/issues/3698
- [x] https://github.com/scylladb/scylla-manager/issues/3679

It needs to be backported to v1.11 where the automatic ScyllaCluster certs got enabled by default

**Comment by zimnx** [comment]
We might fix https://github.com/scylladb/scylla-operator/issues/1673 instead
