### ISSUE TITLE
Webhook timeout

### ISSUE THREAD

**Issue by Martyzaum** [scylladb/scylla-operator#1709]
### What happened?

Im tring to deploy a simple scylla cluster, but every time i get this error when i apply de cluster

Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": failed to call webhook: Post "https:/
deadline exceeded

i tried with helm, and with manifestes, get the same error

im using a eks cluster with i4i intances

### What did you expect to happen?

I want help to solve this problem

### How can we reproduce it (as minimally and precisely as possible)?

helm repo add scylla https://scylla-operator-charts.storage.googleapis.com/stable
helm repo update
kubectl apply -f examples/common/cert-manager.yaml 
helm install scylla-operator scylla/scylla-operator --create-namespace --namespace scylla-operator
helm install scylla scylla/scylla --create-namespace --namespace scylla

### Scylla Operator version

latest

### Kubernetes platform name and version

Kubectl version:
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0-eks-c417bb3

Kubernetes platform info:
EKS, kubernetes 1.29

### Please attach the must-gather archive.

.

**Comment by zimnx** [comment]
Most likely your firewall rules forbids traffic from master nodes to worker nodes on 443 port where webhook is running.

**Comment by Martyzaum** [comment]
@zimnx, how i can do this correctly? i tried something but nothing works
