### ISSUE TITLE
docs: Issue in page Releases

### ISSUE THREAD

**Issue by andre-lfa** [scylladb/scylla-operator#1710]
I would like to report an issue in page https://operator.docs.scylladb.com/v1.11/releases

### Problem

This page is outdated, we already released operator version 1.11 and need to update the Support Matrix and related fields -> https://forum.scylladb.com/t/release-scylla-operator-1-11-0/989. 

###  Suggest a fix

Update the page with the latest information.

**Comment by tnozicka** [comment]
Take a look at the latest version of this page for "master" which is up to date. Unfortunately, given how our docs is structured, we can't have unversioned pages and doing backports there is just not realistic.
