### ISSUE TITLE
`.spec.forceRedeploymentReason` field is no longer mutable leading to regression in the user-facing APIs

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1711]
### What happened?

Latest `v1.12.0-alpha.1-94-gfb3a2aa-latest` Scylla-operator started failing to update ScyllaCluster pods with the following error:
```
I0204 05:50:12.430367       1 record/event.go:376] "Event occurred" \
    object="scylla/sct-cluster-local-dc-1-rack-1" fieldPath="" kind="StatefulSet" \
    apiVersion="apps/v1" type="Warning" reason="UpdateStatefulSetFailed"  \
    message="Failed to update StatefulSet scylla/sct-cluster-local-dc-1-rack-1: \
    StatefulSet.apps \"sct-cluster-local-dc-1-rack-1\" is invalid: spec: \
    Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden"
```

It appears when we try to change the mutable field by design - `.spec.forceRedeploymentReason`.
There may be some other fields.

### What did you expect to happen?

I expected all the mutable fields be really mutable.

### How can we reproduce it (as minimally and precisely as possible)?

Update the `.spec.forceRedeploymentReason` field of any ScyllaCluster and see the error in the scylla operator logs and no rolling restart of Scylla pods.

### Scylla Operator version

`v1.12.0-alpha.1-94-gfb3a2aa-latest`

### Kubernetes platform name and version

Any

## Logs:
- **kubernetes-4c35c2d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/kubernetes-4c35c2d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/kubernetes-4c35c2d7.tar.gz)
- **kubernetes-must-gather-4c35c2d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/kubernetes-must-gather-4c35c2d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/kubernetes-must-gather-4c35c2d7.tar.gz)
- **kubernetes-apiserver-4c35c2d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/kubernetes-apiserver-4c35c2d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/kubernetes-apiserver-4c35c2d7.tar.gz)
- **db-cluster-4c35c2d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/db-cluster-4c35c2d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/db-cluster-4c35c2d7.tar.gz)
- **sct-runner-events-4c35c2d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/sct-runner-events-4c35c2d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/sct-runner-events-4c35c2d7.tar.gz)
- **sct-4c35c2d7.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/sct-4c35c2d7.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/sct-4c35c2d7.log.tar.gz)
- **parallel-timelines-report-4c35c2d7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/parallel-timelines-report-4c35c2d7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4c35c2d7-2422-4027-8637-b2324e15c271/20240204_092249/parallel-timelines-report-4c35c2d7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-k8s-local-kind-aws/163/)
[Argus](https://argus.scylladb.com/test/cc4d518c-2e17-4251-83c2-0bbf7f70ca1c/runs?additionalRuns[]=4c35c2d7-2422-4027-8637-b2324e15c271)

**Comment by tnozicka** [comment]
> .spec.forceRedeploymentReason field is no longer mutable

This seems misleading as the mutation happens when you make the API call to a ScyllaCluster. If you are able to update the ScyllaCluster object itself, then mutation works.

Although it seems like something else has changed so it wants to change the sts. Is this an upgrade test?
