### ISSUE TITLE
[Flake] ScyllaCluster should replace a node [It] using HostID based procedure when version of ScyllaDB is "docker.io/scylladb/scylla:5.2.6"

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#1718]
### Link to the job that flaked.

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1717/pull-scylla-operator-master-e2e-gke-parallel/1755196864698781696

### Snippet of what failed.

```
   Timeline >>
  STEP: Creating a new namespace @ 02/07/24 12:05:12.369
  Feb  7 12:05:12.397: INFO: Created namespace "e2e-test-scyllacluster-h5xbt-wx8d6".
  STEP: Waiting for service account token Secret "e2e-user-token" in namespace "e2e-test-scyllacluster-h5xbt-wx8d6". @ 02/07/24 12:05:12.545
  STEP: Waiting for default ServiceAccount in namespace "e2e-test-scyllacluster-h5xbt-wx8d6". @ 02/07/24 12:05:12.669
  STEP: Waiting for kube-root-ca.crt in namespace "e2e-test-scyllacluster-h5xbt-wx8d6". @ 02/07/24 12:05:12.768
  STEP: Creating a ScyllaCluster @ 02/07/24 12:05:12.856
  STEP: Waiting for the ScyllaCluster to rollout (RV=6008) @ 02/07/24 12:05:13.048
  [FAILED] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_replace.go:94 @ 02/07/24 12:30:43.048

**Comment by tnozicka** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1713/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1755900594435919872#1:test-build-log.txt%3A2548

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1810/pull-scylla-operator-v1.11-e2e-gke-parallel/1767235207611551744#1:test-build-log.txt%3A2004

**Comment by tnozicka** [comment]
not seen in months
