### ISSUE TITLE
scylla-manager-controller does harmful loop of repair task creations and deletions just failing to update ScyllaCluster's spec emitting `Hit conflict, will retry in a bit` error

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1729]
### What happened?

We triggered creation of a manager repair task.

Logs in scylla-manager:

```
{"L":"INFO","T":"2024-02-04T03:14:15.419Z","N":"scheduler","M":"PutTask","task":"repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","schedule":{"cron":"","window":null,"timezone":"","start_date":"0001-01-01T00:00:00Z","interval":"","num_retries":3,"retry_wait":""},"properties":{"intensity":1,"parallel":0,"small_table_threshold":1073741824},"create":true,"_trace_id":"ACrHtMx0TMybPomMXW0nRw"}
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"scheduler.2bb2ce80","M":"Schedule","task":"repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","in":"0s","begin":"2024-02-04T03:14:15.425Z","retry":0,"_trace_id":"ACrHtMx0TMybPomMXW0nRw"}
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"http","M":"POST /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/tasks","from":"10.112.1.26:55958","status":201,"bytes":0,"duration":"1083ms","_trace_id":"ACrHtMx0TMybPomMXW0nRw"}
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"scheduler.2bb2ce80","M":"Run started","task":"repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","retry":0,"_trace_id":"ZuGtwS_dRD2vo21xBorgQw"}
I0204 03:14:15.442877       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
{"L":"INFO","T":"2024-02-04T03:14:15.447Z","N":"http","M":"GET /api/v1/clusters","from":"10.112.1.26:55958","status":200,"bytes":553,"duration":"4ms","_trace_id":"uDnGOBTHS-OP7gv5tEwHDA"}
{"L":"INFO","T":"2024-02-04T03:14:15.451Z","N":"http","M":"GET /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/tasks?all=true&type=repair","from":"10.112.1.26:55958","status":200,"bytes":520,"duration":"3ms","_trace_id":"4Vye-kEnSAWfKH3b2zUbYA"}
{"L":"INFO","T":"2024-02-04T03:14:15.453Z","N":"http","M":"GET /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/tasks?all=true&type=backup","from":"10.112.1.26:55958","status":200,"bytes":5,"duration":"1ms","_trace_id":"lrPBAfXmQPKmPhbAGTIdGg"}
{"L":"INFO","T":"2024-02-04T03:14:15.465Z","N":"scheduler","M":"Task deleted","cluster_id":"2bb2ce80-7cf9-4db2-b23c-28cf01684f35","task_type":"repair","task_id":"799b3ca6-7cf8-4437-aef6-5e917cd08a10","_trace_id":"GkrvnTU9Rk2yf7SbPcfjnw"}
{"L":"INFO","T":"2024-02-04T03:14:15.465Z","N":"http","M":"DELETE /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/task/repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","from":"10.112.1.26:55958","status":0,"bytes":0,"duration":"11ms","_trace_id":"GkrvnTU9Rk2yf7SbPcfjnw"}
```

Just `46ms` pass between creation and deletion of the mgmt `repair` task.
The caller of the `Delete` API is `10.112.1.26:55958`.

And the `10.112.1.26` IP address belongs to the `scylla-manager-controller` (one of two) provisioned by the `scylla-operator`:
```
...
scylla-manager            scylla-manager-controller-845cd4749d-4gg6x                   1/1     Running     0 \
                  3h45m   10.112.1.26   gke-longev-scylla-operat-default-pool-efb3d2c6-z8fc   <none>           <none>
scylla-manager            scylla-manager-controller-845cd4749d-txpsj                   1/1     Running     0 \
                  3h45m   10.112.0.21   gke-longev-scylla-operat-default-pool-efb3d2c6-vmt0   <none>           <none>
scylla-manager            scylla-manager-ff7c6ffcf-ztp9l                               1/1     Running     0 \
                  3h45m   10.112.1.25   gke-longev-scylla-operat-default-pool-efb3d2c6-z8fc   <none>           <none>
scylla-manager            scylla-manager-manager-dc-manager-rack-0                     2/2     Running     0 \
                  3h45m   10.112.0.22   gke-longev-scylla-operat-default-pool-efb3d2c6-vmt0   <none>           <none>
...
```

Logs from that controller at that time:
```
I0204 03:14:15.442877       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
I0204 03:14:18.998063       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
```

We know that `ScyllaCluster` K8S object has `backups` and `repairs` fields which get updated each time new appropriate mgmt task gets created.
Example:
```
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  annotations:
    meta.helm.sh/release-name: scylla
    meta.helm.sh/release-namespace: scylla
  creationTimestamp: "2024-02-04T00:42:47Z"
  generation: 16
  labels:
    app.kubernetes.io/managed-by: Helm
  name: sct-cluster
  namespace: scylla
  resourceVersion: "151064"
  uid: 944aa1a8-0c0e-4cd2-a94d-b1f4a8edd7f5
spec:
...
  repairs:
  - intensity: "1"
    interval: "0"
    name: default-repair-task-name
    numRetries: 3
    parallel: 0
    smallTableThreshold: 1GiB
    startDate: now
...
```

So, from scylla-operator point of view it is `retry` on failure to update the `ScyllaCluster` K8S object, 
but from the scylla-manager point of view it is loop of task creations and deletions.

And the problem with it is that second+ task fails with the following error:
```
{"L":"INFO","T":"2024-02-04T03:14:17.684Z","N":"scheduler.2bb2ce80","M":"Run ended with ERROR","task":"repair/562394a7-442f-4bc8-b753-dff50dcaf24d","status":"ERROR","cause":"another task is running","duration":"3.605711ms","_trace_id":"-oUKq6smR0ysFRguwzn5jg"}
```

In the result we have confusing information about mgmt tasks given by it:
```
2024-02-04 03:15:21,271 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > +---------------------------------+-------------+--------+----------+---------+-------+------------------------+------------------------+--------+------------------------+
2024-02-04 03:15:21,271 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | Task                            | Schedule    | Window | Timezone | Success | Error | Last Success           | Last Error             | Status | Next                   |
2024-02-04 03:15:21,271 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > +---------------------------------+-------------+--------+----------+---------+-------+------------------------+------------------------+--------+------------------------+
2024-02-04 03:15:21,271 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | healthcheck/rest                | @every 1m0s |        | UTC      | 141     | 0     | 04 Feb 24 03:15:02 UTC |                        | DONE   | 04 Feb 24 03:16:02 UTC |
2024-02-04 03:15:21,271 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | healthcheck/alternator          | @every 15s  |        | UTC      | 563     | 0     | 04 Feb 24 03:15:17 UTC |                        | DONE   | 04 Feb 24 03:15:32 UTC |
2024-02-04 03:15:21,271 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | healthcheck/cql                 | @every 15s  |        | UTC      | 555     | 0     | 04 Feb 24 03:15:15 UTC |                        | DONE   | 04 Feb 24 03:15:30 UTC |
2024-02-04 03:15:21,271 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > | repair/default-repair-task-name |             |        |          | 0       | 1     |                        | 04 Feb 24 03:14:20 UTC | ERROR  |                        |
2024-02-04 03:15:21,271 f:base.py         l:222  c:KubernetesCmdRunner  p:DEBUG > +---------------------------------+-------------+--------+----------+---------+-------+------------------------+------------------------+--------+------------------------+
```

### What did you expect to happen?

Scylla-manager repair task must be created just once and not re-created lots of times in scope of milliseconds.

### How can we reproduce it (as minimally and precisely as possible)?

Trigger scylla-manager repair task using `latest` scylla-operator.

### Scylla Operator version

`v1.12.0-alpha.1-94-gfb3a2aa-latest`

### Kubernetes platform name and version

`v1.27.10-gke.1055000`

## Logs:
- **kubernetes-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/kubernetes-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/kubernetes-d32afd01.tar.gz)
- **kubernetes-must-gather-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/kubernetes-must-gather-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/kubernetes-must-gather-d32afd01.tar.gz)
- **db-cluster-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/db-cluster-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/db-cluster-d32afd01.tar.gz)
- **sct-runner-events-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/sct-runner-events-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/sct-runner-events-d32afd01.tar.gz)
- **sct-d32afd01.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/sct-d32afd01.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/sct-d32afd01.log.tar.gz)
- **loader-set-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/loader-set-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/loader-set-d32afd01.tar.gz)
- **monitor-set-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/monitor-set-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/monitor-set-d32afd01.tar.gz)
- **parallel-timelines-report-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/parallel-timelines-report-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/parallel-timelines-report-d32afd01.tar.gz)

**Comment by zimnx** [comment]
We are synchronizing two systems, ScyllaCluster Spec into Scylla Manager and we report back with tasks IDs generated by Scylla Manager into ScyllaCluster Status. If storing in Status of these IDs fails due to conflict, we retry.
Since ID of a task in Manager wasn't stored in Status, we consider such task as foreign, so we deleted it and then synchronize spec into manager by creating another repair task.

As this was an ad-hoc repair, and we don't have any support for failed tasks it stays in error state forever.
It was always like that, so it's not a regression.

We could stop the task before we delete it, which should solve what is happening. I'll see whether it's trivial.
