### ISSUE TITLE
Examples: extract common elements to separate folder

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#173]
We should be doing more DRY there is no need to copy grafana and provisioner dir in each example.
It makes updating those resources more difficult. The concrete examples should have helm value files only.

We could try to go even further and split the examples to 

* prepare stage - different content for different providers
* deploy stage - common core, possibly decorated with helm chart to allow for easy setting of limits

**Comment by mmatczuk** [comment]
When I think about it we should remove the Grafana dashboards from here and download them or use a docker image that has them.

**Comment by zimnx** [comment]
Already done.
