### ISSUE TITLE
Generated pods fail when injected with Linkerd sidecars

### ISSUE THREAD

**Issue by NoiSek** [scylladb/scylla-operator#176]
**Describe the bug**
Pods generated by the Scylla operator cause runtime errors in linkerd sidecars. This appears to be a result of a control plane conflict specific to this operator, and may apply to injected sidecars as a whole rather than specifically to linkerd sidecars.

Given that many service meshes (all?) use sidecars, this issue may preclude the operator from being used in many real-world Kubernetes environments.

**To Reproduce**
1. Begin with a Minikube environment
2. Install the linkerd-cli (`brew install linkerd` for OS X users)
3. Install the Linkerd control plane
4. Use `linkerd inject` to add a sidecar hook to Pods created by the Scylla operator
5. Apply injected resources to the cluster
6. Observe that Scylla pods restart exactly once, and never come to full readiness.

Script to Reproduce:
```
#!/usr/bin/env bash

# Alias Linkerd Edge (There is no difference between using this and stable, but this rules out an outdated changeset)
alias ld="./linkerd2-cli-edge-20.7.5-darwin"

# Start our VM
minikube start --cpus=6 --memory='6144m' --disk-size='40000mb'
eval $(minikube docker-env)

# Install Linkerd, wait for full deployment readiness.
ld install | kubectl apply -f -
ld check

# Install our cert-manager for Scylla, wait for full readiness.
kubectl apply -f https://raw.githubusercontent.com/scylladb/scylla-operator/master/examples/generic/cert-manager.yaml
kubectl wait -n cert-manager --for=condition=ready pod -l app=cert-manager --timeout=60s
sleep 5

# Install our Scylla operator, wait for full readiness.
kubectl apply -f https://raw.githubusercontent.com/scylladb/scylla-operator/master/examples/generic/operator.yaml
kubectl get statefulset --output name -n scylla-operator-system | xargs -n1 -P10 -t kubectl rollout status -n scylla-operator-system
sleep 5

# Start our cluster, injecting the pods that the Scylla operator creates.
ld inject https://raw.githubusercontent.com/scylladb/scylla-operator/master/examples/generic/cluster.yaml | kubectl apply -f -

# Wait, then observe the logs.
sleep 90
kubectl describe pod/simple-cluster-us-east-1-us-east-1a-0 -n scylla
kubectl logs pod/simple-cluster-us-east-1-us-east-1a-0 -n scylla -c linkerd-proxy --follow
```

**Expected behavior**
Given that Linkerd is a transparent proxy that only observes and forwards traffic, Scylla pods should come up as normal and have their traffic observable by Linkerd.

**Config Files**
(See above)

**Logs**
https://gist.github.com/NoiSek/47392a0eb8b8a6af154300a5bf38f2c0

**Environment:**
 - Platform: Minikube `1.12.2`
 - Kubernetes version:  Client `1.18.6` / Server `1.18.3`
 - Scylla version: `4.0.0`
 - Scylla-operator version: `master`

**Additional context**
It's unclear whether this is an issue originating from Linkerd, from the Scylla operator, or from the specific combination of Linkerd and Scylla. I'm inclined to believe that this is a CNI conflict originating from Scylla however due to the fact that:

- Linkerd has a proven history of working transparently with other, similar services and operators
- In my own experience, this operator tends to fail when almost any other tool that uses sidecars is involved (I have experienced this primarily with Linkerd and Gloo)
- The failures experienced when using sidecars tend to be fairly diverse, which makes the operator itself the common denominator rather than a specific brand of error

**Comment by ezbz** [comment]
resolved by #257
