### ISSUE TITLE
Disable unused sshd service

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1763]
ScyllaDB manager no longer needs ssh so we can finally drop the ssh service run within the ScyllaDB container.

This will help security as well as future container split.

**Comment by tnozicka** [comment]
@karol-kokoszka can you please share what is the minimal version of ScyllaDB Manager that doesn't need `ssh` anymore?

**Comment by karol-kokoszka** [comment]
@tnozicka looks that `ssh` is not needed since 2.0 when the scylla-manager-agent was introduced.
https://www.scylladb.com/product/release-notes/scylla-manager-2-0-1/

**Comment by tnozicka** [comment]
great, thanks @karol-kokoszka
