### ISSUE TITLE
[Flake] ScyllaCluster [It] should rotate TLS certificates before they expire

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1802]
### Link to the job that flaked.

[should rotate TLS certificates before they expire](https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1795/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1765714974254043136#1:test-build-log.txt%3A863)

### Snippet of what failed.

   << Timeline
  [FAILED] Unexpected error:
      <*fmt.wrapError | 0xc0004fcbe0>: 
      can't create keyspace: gocql: no response received from cassandra within timeout period
      {
          msg: "can't create keyspace: gocql: no response received from cassandra within timeout period",
          err: <*errors.errorString | 0x391a300>{
              s: "gocql: no response received from cassandra within timeout period",
          },
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:312 @ 03/07/24 12:46:44.1
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.insertAndVerifyCQLDataUsingDataInserter({0x2643940, 0xc0005d82a0}, 0x399b540?)
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:312 +0x78
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.insertAndVerifyCQLData({0x2643940, 0xc0005d82a0}, {0xc000976430, 0x1, 0x1}, {0x0?, 0x7fa3a270bec0?, 0xc0005927e0?})
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/verify.go:297 +0x174
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func17.2(0xc000579350)
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllacluster_upgrades.go:74 +0xab9
    reflect.Value.call({0x1da61c0?, 0xc000426f90?, 0x13?}, {0x22c9d6b, 0x4}, {0xc0005f6300, 0x1, 0x1?})
    	reflect/value.go:596 +0xce7
    reflect.Value.Call({0x1da61c0?, 0xc000426f90?, 0x265b030?}, {0xc0005f6300?, 0x0?, 0x0?})
    	reflect/value.go:380 +0xb9

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1857/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1773351748295987200
