### ISSUE TITLE
can't set up scylla

### ISSUE THREAD

**Issue by mjamaah** [scylladb/scylla-operator#1809]
I have Deployed Scylla Helm Chart version 1.10.0 using Scylla Operator a few months ago, 
recently, I had a maintenance so i have started to Drain Kubernetes Nodes one by one.

the first Scylla Node failed to start on the new Kubernetes Node with this error:

`Error: can't set up scylla: can't setup scylla.yaml: can't make scylladb config overrides: open /var/run/configmaps/scylla-operator.scylladb.com/scylladb/managed-config/scylladb-managed-config.yaml: no such file or directory
`
i have been through the documentation, there is no mention for such file "scylladb-managed-config.yaml" 

can anyone describe me what does this error supposed to mean? and how can I bypass this?

**Comment by tnozicka** [comment]
why have you not followed the bug template and supplied must-gather?

my guess is that you've put `latest` tag somewhere and this pulls the latest code not the image for the version you mention

**Comment by mjamaah** [comment]
@tnozicka i am sorry for this, you want me to close this and reopen it using the template ?

and i am using this Images tags in the values file:

```
scyllaImage:
  tag: 5.2.7
agentImage:
  tag: 3.1.2
```
