### ISSUE TITLE
Customize Grafana Config

### ISSUE THREAD

**Issue by yaronworldwide** [scylladb/scylla-operator#181]
Hey,
I am trying to load grafana dashboard via provided json files .
I would like to clarify we are using our prometheus/grafana servers (not the one provided by scylla Project)
I am able to get all metrics but could not build dashboards based on json files from 
https://github.com/scylladb/scylla-operator/blob/master/examples/generic/grafana/dashboards/scylla-overview.4.0.json
Any idea on how to customize provided json files so it could be displayed on my grafana server ?

**Comment by mmatczuk** [comment]
@amnonh could you please take a look.

**Comment by yaronworldwide** [comment]
Issue was fixed
