### ISSUE TITLE
scylla-operator can't delete decomissioned node

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#182]
**Describe the bug**

**To Reproduce**
1. Deploy minikube
2. Create Operator
3. Create scylla cluster:
cat <<EOF | kubectl apply -f -
apiVersion: scylla.scylladb.com/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sct-cluster
  namespace: scylla
spec:
  version: 4.0.0
  agentVersion: 2.0.2
  developerMode: true
  datacenter:
    name: gce
    racks:
      - name: minikube
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 3
        storage:
          capacity: 30Gi
        resources:
          requests:
            cpu: 2
            memory: 8Gi
          limits:
            cpu: 2
            memory: 8Gi
EOF
4. Find scylla node from 2nd pod:
 docker ps --filter "label=io.kubernetes.pod.name=sct-cluster-gce-minikube-1" --filter "label=io.kubernetes.container.name=scylla" -q
5. Execute nodetool decomission on it:
docker exec -ti {docker_id} nodetool decomission
6. Drop members count to 1:
cat <<EOF | kubectl apply -f -
apiVersion: scylla.scylladb.com/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sct-cluster
  namespace: scylla
spec:
  version: 4.0.0
  agentVersion: 2.0.2
  developerMode: true
  datacenter:
    name: gce
    racks:
      - name: minikube
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          capacity: 30Gi
        resources:
          requests:
            cpu: 2
            memory: 8Gi
          limits:
            cpu: 2
            memory: 8Gi
EOF
7. See that scylla operator does not cleanup 2nd pod:
kubectl get pods -n scylla
NAME                         READY   STATUS    RESTARTS   AGE
sct-cluster-gce-minikube-0   2/2     Running   0          121m
sct-cluster-gce-minikube-1   1/2     Running   0          89m

**Expected behavior**
Node is cleaned

**Config Files**
apiVersion: scylla.scylladb.com/v1alpha1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sct-cluster
  namespace: scylla
spec:
  version: 4.0.0
  agentVersion: 2.0.2
  developerMode: true
  datacenter:
    name: gce
    racks:
      - name: minikube
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 1
        storage:
          capacity: 30Gi
        resources:
          requests:
            cpu: 2
            memory: 8Gi
          limits:
            cpu: 2
            memory: 8Gi

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.

kubectl get events -n scylla
LAST SEEN   TYPE      REASON                  OBJECT                                                             MESSAGE
47m         Normal    ExternalProvisioning    persistentvolumeclaim/data-simple-cluster-us-east-1-us-east-1a-0   waiting for a volume to be created, either by external provisioner "k8s.io/minikube-hostpath" or manually created by system administrator
47m         Normal    Provisioning            persistentvolumeclaim/data-simple-cluster-us-east-1-us-east-1a-0   External provisioner is provisioning volume for claim "scylla/data-simple-cluster-us-east-1-us-east-1a-0"
47m         Normal    ProvisioningSucceeded   persistentvolumeclaim/data-simple-cluster-us-east-1-us-east-1a-0   Successfully provisioned volume pvc-7ef7a9ec-18dd-4946-a478-435bfecce3ca
2m          Warning   Unhealthy               pod/sct-cluster-gce-minikube-1                                     Readiness probe failed: HTTP probe failed with statuscode: 503

**Environment:**
 - Platform: minikube
 - Kubernetes version: 
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
 - Scylla version: 4.0.0
 - Scylla-operator version: 2.0.2

**Additional context**

**Comment by zimnx** [comment]
Problem lies in manual `nodetool decomission`. 
Node decommission is part of scale down procedure so simply scale down ScyllaCluster, and node will be first decomissioned and then Pod will be deleted.
Sidecar logic expects some labels to be available in member service, and in this case labels aren't there. 

@tzach @ezbz do we want to support manual node operations?

**Comment by tzach** [comment]
To validate my understanding, the operations executed are:
- manual decommission
- K8s cluster downscale (how do you know it will downscale the right node?)

Not sure what is the expected result here.
We can not support any combination of manual and Operator operation.

**Comment by zimnx** [comment]
> the operations executed are:
> 
> * manual decommission
> * K8s cluster downscale (how do you know it will downscale the right node?)

Yes

> (how do you know it will downscale the right node?)

Operator always remove last available node one by one: N-1, N-2 etc.

> We can not support any combination of manual and Operator operation.

I agree. So I guess we should tell users to not execute operations manually if the same operation is supported by the Operator.

**Comment by dkropachev** [comment]
It is resolved by https://github.com/scylladb/scylla-operator/pull/225

**Comment by tzach** [comment]
@zimnx please add this restriction to the docs
