### ISSUE TITLE
`scylla-operator-node-tuning` pods constantly fail with `[Errno 2] No such file or directory: 'systemctl'. Your system can't be tuned until the issue is fixed.` error

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1826]
### What happened?

Just installing latest scylla-operator with enabled node tuning on EKS all the `scylla-operator-node-tuning` pods fail with the following error:
```
Saving the original irqbalance configuration is in /etc/sysconfig/irqbalance.scylla.orig
Restarting irqbalance: going to ban the following IRQ numbers: 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45, 46, 47, 48, 49, 50, 51, 52 ...
Restarting irqbalance via systemctl...
ERROR: [Errno 2] No such file or directory: 'systemctl'. Your system can't be tuned until the issue is fixed.
```

### What did you expect to happen?

All of the perf tune pods must work.

### How can we reproduce it (as minimally and precisely as possible)?

Just install latest scylla operator on EKS enabling perf tuning.

### Scylla Operator version

v1.13.0-alpha.0-39-gf2336ee-latest

### Kubernetes platform name and version

`v1.27.10-eks-508b6b3`

### Please attach the must-gather archive.

- **kubernetes-62db6660.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/kubernetes-62db6660.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/kubernetes-62db6660.tar.gz)
- **kubernetes-must-gather-62db6660.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/kubernetes-must-gather-62db6660.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/kubernetes-must-gather-62db6660.tar.gz)
- **db-cluster-62db6660.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/db-cluster-62db6660.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/db-cluster-62db6660.tar.gz)
- **sct-runner-events-62db6660.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/sct-runner-events-62db6660.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/sct-runner-events-62db6660.tar.gz)
- **sct-62db6660.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/sct-62db6660.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/sct-62db6660.log.tar.gz)
- **monitor-set-62db6660.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/monitor-set-62db6660.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/monitor-set-62db6660.tar.gz)
- **parallel-timelines-report-62db6660.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/parallel-timelines-report-62db6660.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/62db6660-d634-4037-a692-bd9823c030a4/20240312_204033/parallel-timelines-report-62db6660.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/long-alternator-1h-eks-test/15/)
[Argus](https://argus.scylladb.com/test/93ebbd59-50fc-408e-84b4-3e22ecfe98b1/runs?additionalRuns[]=62db6660-d634-4037-a692-bd9823c030a4)

**Comment by zimnx** [comment]
Looks like Scylla image no longer has `systemctl` in it, while `perftune.py` script which comes with the image still uses it. 
5.4.0 works fine, while 5.4.1 and onwards is broken.

**Comment by zimnx** [comment]
We bumped Scylla utils image to 5.4.2 in #1725

**Comment by tnozicka** [comment]
please file a high prio bug for scylla core to fix the image.

I suppose we can rollback only the utils image, right?

**Comment by zimnx** [comment]
https://github.com/scylladb/scylladb/issues/17787
