### ISSUE TITLE
Scylla Grafana Metrics

### ISSUE THREAD

**Issue by yaronworldwide** [scylladb/scylla-operator#183]
Hey ,
I am currently working on integrating Scylla Grafana Metrics (which is pretty straight forward)
As for now my cluster has 2 nodes (but they are displayed  with same IP - LBA IP) which implies that all the graphs for overview dashboard only display the same ip .
I would like to display two distinct metrics (one per node) and not one as currently displayed.
Any idea on how to achieve this ?
I have tried to modify the [[node]] variable to
label_values(scylla_reactor_utilization{cluster=~"$cluster|$^", dc=~"$dc"}, kubernetes_pod_name)
But in this case no data could be retrieved

**Comment by gnumoreno** [comment]
@amnonh

**Comment by amnonh** [comment]
@yaronworldwide 
How the Prometheus query them if they have the same IP?

**Comment by dyasny** [comment]
If each scylla pod has an internal IP, and the prometheus pod accesses the host IP and not the pod IP, then this is what will happen.

**Comment by amnonh** [comment]
@yaronworldwide how prometheus connect to the two different scylla?
can you upload the prometheus targets?
(http://{your-ip}:9090/targets)

**Comment by yaronworldwide** [comment]
@amnonh because all instances ip are identical while selecting By "Instance" only one instance is displayed .
Would you recommend add another variable or modifying the query ?

**Comment by amnonh** [comment]
@yaronworldwide can I please see the Prometheus targets? (see my previous comment)

**Comment by yaronworldwide** [comment]
@amnonh we haven't deployed a dedicated prometheus server for scylla (we are using our production one) meaning we have a tons of targets.

**Comment by amnonh** [comment]
what I don't understand is how the Prometheus server finds the different Scylla servers if they are sharing the same IP?
I would expect that you would use the container ip address and not the host address, but you are doing something else which I don't understand.

**Comment by amnonh** [comment]
@yaronworldwide can you capture two scylla targets from the same IP address?
