### ISSUE TITLE
scylla pods fail with `unmounted volumes=[scylladb-alternator-serving-certs]` error when `.spec.alternator` is not `nil/None` and TLS feature of scylla-operator is disabled

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1838]
### What happened?

The idea was to enable alternator and use only insecure port with authentication on the alternator level.

The TLS feature of the scylla-operator was disabled intentionally:
```
I0315 13:26:26.280540       1 featuregate/feature_gate.go:249] feature gates: &{map[AutomaticTLSCertificates:false]}
```

The `ScyllaCluster` spec part related to the `alternator` which we define as part of the helm chart is following:
```
> alternator:
>   enabled: true
>   insecureDisableAuthorization: false
>   insecureEnableHTTP: true
```

It then gets transformed to the following object spec in K8S:
```
spec:
  ...
  alternator:
    insecureDisableAuthorization: false
    insecureEnableHTTP: true
    servingCertificate:
      type: OperatorManaged
    writeIsolation: always
  automaticOrphanedNodeCleanup: true
  ...
```

This combination leads to the following error:
```
NAMESPACE   NAME                               READY   STATUS      RESTARTS      AGE   IP           NODE
scylla      sct-cluster-eu-north-1-rack-1-0    0/2     Init:0/2    0             60m   <none>       ip-10-0-7-207.eu-north-1.compute.internal
```

The very first and the only scylla pod was blocked with the following error:
```
Warning  FailedMount  3m54s (x27 over 62m)  kubelet  \
  Unable to attach or mount volumes: unmounted volumes=[scylladb-alternator-serving-certs], \
  unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
```

It's volumes spec has following part:
```
  volumes:
  ...
  - name: scylladb-alternator-serving-certs
    secret:
      defaultMode: 420
      optional: false
      secretName: sct-cluster-alternator-local-serving-certs
```

Scylla-operator code (`pkg/controller/scyllacluster/resource.go`):
```
if c.Spec.Alternator != nil {
    volumes = append(volumes, corev1.Volume{
        Name: scylladbAlternatorServingCertsVolumeName,
        VolumeSource: corev1.VolumeSource{
            Secret: &corev1.SecretVolumeSource{
                SecretName: naming.GetScyllaClusterAlternatorLocalServingCertName(c.Name),
                Optional:   pointer.Ptr(false),
            },
        },
    })
}
```

So, looks like any non-nil value in the `.Spec.Alternator` spec part blocks us from disabling non-required TLS feature.

### What did you expect to happen?

1) Scylla pods must start up even if scylla-operator TLS feature is enabled
2) We should be able to use alternator without TLS the same way as CQL.

### How can we reproduce it (as minimally and precisely as possible)?

- Start scylla-operator with disabled `TLS` feature
- Create ScyllaCluster with some value in the `scpe.alternator` field

### Scylla Operator version

`v1.13.0-alpha.0-47-g0ef90d9f-latest`

### Kubernetes platform name and version

`v1.27.11-eks-b9c9ed7`

### Please attach the must-gather archive.

- **kubernetes-cea31138.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/kubernetes-cea31138.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/kubernetes-cea31138.tar.gz)
- **kubernetes-must-gather-cea31138.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/kubernetes-must-gather-cea31138.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/kubernetes-must-gather-cea31138.tar.gz)
- **sct-runner-events-cea31138.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/sct-runner-events-cea31138.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/sct-runner-events-cea31138.tar.gz)
- **sct-cea31138.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/sct-cea31138.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/sct-cea31138.log.tar.gz)
- **parallel-timelines-report-cea31138.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/parallel-timelines-report-cea31138.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cea31138-9b40-4a0b-b9d4-da0f2556255e/20240315_143232/parallel-timelines-report-cea31138.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-alternator-http-3h-eks/2/)
[Argus](https://argus.scylladb.com/test/e4cc95e2-d0c2-424f-9a5d-1a16668401bd/runs?additionalRuns[]=cea31138-9b40-4a0b-b9d4-da0f2556255e)

### Anything else we need to know?

If we enable TLS feature in scylla-operator then scylla pods start up as expected.

**Comment by tnozicka** [comment]
> The idea was to enable alternator and use only insecure port with authentication on the alternator level.

This is not supported.

> The TLS feature of the scylla-operator was disabled intentionally:

This feature gate controls CQL TLS certificates (for backwards compatibility), not Alternator ones.

**Comment by tnozicka** [comment]
Sorry, I misread this (as I was coming from Slack). It shouldn't cause mount issues.

**Comment by tnozicka** [comment]
I initially didn't want the feature gate to control these but now I see it's wired to the whole loop, so it will. (It's going away anyways in 1.13.)
