### ISSUE TITLE
Move all manager task validation to validating webhook

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1867]
### What should the feature do?

Currently only some of the manager task fields are validated by the validating webhook, while the others are validated at runtime. We should move all validation to the validating webhook, instead of failing during scheduling.
Unit tests should also cover the validation.

/priority important-longterm
/kind feature
/assign

### What is the use case behind this feature?

https://github.com/scylladb/scylla-operator/pull/1851#discussion_r1539259781

**Comment by tnozicka** [comment]
> while the others are validated at runtime
> We should move all validation to the validating webhook, instead of failing during scheduling.

this sounds like restricting validation which is forbidden in the same API version
