### ISSUE TITLE
Editing scyllaArgs should trigger an automatic rollout

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1874]
When you edit scyllacluster.spec.scyllaArgs a new rollout isn't triggered automatically because it's not part of the statefulset definition and is handled in a sidecar only on init.

**Comment by rzetelskik** [comment]
@tnozicka https://github.com/scylladb/scylla-operator/issues/1389

**Comment by zimnx** [comment]
Done in https://github.com/scylladb/scylla-operator/pull/2137
