### ISSUE TITLE
operator image can't be empty

### ISSUE THREAD

**Issue by pyhp2017** [scylladb/scylla-operator#1890]
### What happened?

After a while opeartor went into error state and the only log was this:

`Error: operator image can't be empty`

which is wired because it is a log inside of a container which uses "operator image"!

### What did you expect to happen?

To run properly

### How can we reproduce it (as minimally and precisely as possible)?

Not happened anywhere else

### Scylla Operator version

1.11

### Kubernetes platform name and version

<details>
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:49:08Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"
```

### Please attach the must-gather archive.

-

### Anything else we need to know?

I fixed this issue by creating an env variable inside of the deployment manually:

```
          - name: SCYLLA_OPERATOR_IMAGE
            value: scylladb/scylla-operator:1.11
```

**Comment by rzetelskik** [comment]
Please attach the must-gather archive.

https://github.com/scylladb/scylla-operator/blob/f3561383a75b394bc7688363767db1a38c5bf308/.github/ISSUE_TEMPLATE/bug-report.yaml?plain=1#L57

https://operator.docs.scylladb.com/stable/support/must-gather.html

/priority awaiting-more-evidence

**Comment by rliskunov** [comment]
+1. I had the same problem

**Comment by harchuk** [comment]
+1. same problem

**Comment by tnozicka** [comment]
closing as stale for the lack of supplied information
