### ISSUE TITLE
scylla node randomly dies

### ISSUE THREAD

**Issue by jwnx** [scylladb/scylla-operator#19]
**Describe the bug**
Scylla node went down after regular usage. `kubectl` and scylla logs follow.

**Logs**
[Nodetool_commands.txt](https://github.com/scylladb/scylla-operator/files/3403661/Nodetool_commands.txt)
[Node_Down_logs.txt](https://github.com/scylladb/scylla-operator/files/3403665/Node_Down_logs.txt)

**Comment by tzach** [comment]
Thanks for reporting
I see many warning in the logs:
 
```
WARN  2019-07-10 11:25:36,357 [shard 2] BatchStatement - Batch of prepared statements for utss.numeric_data is of size 13956, exceeding specified WARN threshold of 5120 by 8836.
```

Are you using batch statements with as many as 8K statements?
Even if you do, its a Scylla bug, as Scylla should gracefully handle this.
