### ISSUE TITLE
Extend node tune controller with status conditions

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1920]
### What should the feature do?

Currently, the node tune controller only updates NodeConfig's NodeStatuses on reconciliation. It should be extended with conditions so that they can be propagated to NodeConfig.

/kind feature
/needs-priority

### What is the use case behind this feature?

Being able to query NodeConfig conditions, instead of checking NodeStatuses.

**Comment by rzetelskik** [comment]
@tnozicka should this go as a part of https://github.com/scylladb/scylla-operator/issues/1557? If not, should it precede or follow it?

**Comment by tnozicka** [comment]
follow up is fine
