### ISSUE TITLE
Passing a configMap with endpoint_snitch, this property is ignored and not overridden

### ISSUE THREAD

**Issue by nbenaglia** [scylladb/scylla-operator#193]
**Describe the bug**
with scyllaOperator v.0.2.4, I am trying to pass a configMap with two parameters to override (as described at https://github.com/scylladb/scylla-operator/blob/master/docs/generic.md#configure-scylla):
```
endpoint_snitch: Ec2MultiRegionSnitch
storage_port: 7000
```
ConfigMap is called scylla-config, but the pod shows no changes:
```
[on_my_pod]>cat /etc/scylla/scylla.yaml
…
endpoint_snitch: GossipingPropertyFileSnitch
storage_port: 7000
… 
```

**To Reproduce**
1. Create file /tmp/scylla.yaml with content:
```
endpoint_snitch: Ec2MultiRegionSnitch
storage_port: 7000
```
2. Deploy configMap in K8S:
`kubectl create configmap scylla-config --from-file=/tmp/scylla.yaml -o yaml --dry-run | kubectl create -f -`

3. Rollout existing pods:
`kubectl rollout restart sts/cluster1-dc1-us-east-1a`

**Expected behavior**
File at /etc/scylla/scylla.yaml should shown overridden values. But `endpoint_snitch` is not overriden.

**Comment by ItachGal** [comment]
@nbenaglia PR is pending review.
The issue was the overriding order of the configurations.

Gal

**Comment by nbenaglia** [comment]
Yes, I am applying your PR locally and testing it. Thx.

**Comment by nbenaglia** [comment]
The PR is still not working, I added the correct code here: https://github.com/scylladb/scylla-operator/pull/194#discussion_r502341856
