### ISSUE TITLE
Scylla Manager controller not able to connect to scylla manager. 

### ISSUE THREAD

**Issue by Ganoes-Paran** [scylladb/scylla-operator#1967]
I have deployed 2 scylla-manager scylla-cluster pair with the difference in their names. First scylla cluster is up and find with manager and controller working as expected, but second scylla manager is not working. 

2nd Scylla controller tries to connect to a service with name of `scylla-manager` which is the name of the first deployment, it connects to its and registers the second cluster in the first manager which I can confirm using `sctool cluster list`. The same commands return nothing in the 2nd manager. 

I can see in the controller there are environment variables that define what host and port to connect, like these 
`SCYLLA_MANAGER_PORT_80_TCP_PROTO`
`SCYLLA_MANAGER_SERVICE_HOST`

but when defining the scylla manager with new name some additional variables are there
`SCYLLA_MANAGER_TEST_SCYLLA_PORT_80_TCP_PROTO`
`SCYLLA_MANAGER_TEST_SCYLLA_SERVICE_HOST`

Is there a way to configure the actual env variables, or make the scylla manager controller use the new env vars.

The first scylla manager controller registers the 2nd scylla clusters to first scylla manager

**Comment by Ganoes-Paran** [comment]
same issues persists when only single scylla-cluster and manager is deployed if the service name of scylla manager is changed to something else from scylla-manager.

**Comment by tnozicka** [comment]
sorry, we can't help you if you don't follow the GitHub template and provide the necessary information, like must-gather https://github.com/scylladb/scylla-operator/blob/master/.github/ISSUE_TEMPLATE/bug-report.yaml
