### ISSUE TITLE
Not able to deploy dedicated Scylla manager Scylla Cluster pair in different namespaces.

### ISSUE THREAD

**Issue by Ganoes-Paran** [scylladb/scylla-operator#1968]
### What happened?

Tried deploying scylla manager-cluster in two different namespaces. Both the pairs were up, but issue was with manager. The manager keep on switching registered clusters. 

For some time Manager-1 would register Cluster-1 and Cluster-2, and Manager-2 will only register Cluster-2. Then this registration pattern would switch up Manager-2 now registering both the Clusters while Manager-1 register cluster-1.

I observed the logs of manager controller, I can see that both the controllers are trying to connect to both the existing clusters. 

Both the scylla cluster nodes, share the same namespace, but the managers are in different. There are total of three namespaces involved. 

The questions that I would like to ask is whether is it possible to deploy multiple scylla manager-cluster pair with dedicated manager to a cluster, with each manager confined to a specific namespace. 

### What did you expect to happen?

I expected that Manager-1 will register only to Cluster-1 and Manager-2 will only register to Cluster-2.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy scylla manager-cluster, pair in two different namespaces. 

### Scylla Operator version

Latest

### Kubernetes platform name and version

<details>
```console
$ kubectl version
# paste output here
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.26.15

Kubernetes platform info:
</details>

### Please attach the must-gather archive.

NA

**Comment by tnozicka** [comment]
> Please attach the must-gather archive.
> NA

Must-gather archive is required and has already been asked for on your previous issue https://github.com/scylladb/scylla-operator/issues/1967#issuecomment-2162707184
/close

https://operator.docs.scylladb.com/v1.12/support/overview.html#gather-data-about-your-cluster
