### ISSUE TITLE
Cluster deployment failure

### ISSUE THREAD

**Issue by prasus** [scylladb/scylla-operator#197]
I am attempting to provision Scylla operator based deployment on a minikube (K8s - v1.18.8) environment by following the steps at https://docs.scylladb.com/operating-scylla/scylla-operator/generic/, but the cluster deployment fails with `failed calling webhook "webhook.scylla.scylladb.com"` messages as described below, This behaviour remains the same on my on-premise Kubernetes cluster running K8s v1.18.8

**To Reproduce**
Steps to reproduce the behaviour:
1. Install minikube:  `minikube start --container-runtime=cri-o --memory=7000 --kubernetes-version v1.18.8`
2. Clone the repo : `git clone https://github.com/scylladb/scylla-operator`
3. Deploy cert manager: `kubectl apply -f scylla-operator/examples/generic/cert-manager.yaml`
4. Deploy scylla-operator: `kubectl apply -f scylla-operator/examples/generic/operator.yaml`
5. Deploy scylla cluster: `kubectl apply -f scylla-operator/examples/generic/cluster.yaml` 

The cluster creation (`Step #5`) fails with the below messages.

```
namespace/scylla created
clusterrole.rbac.authorization.k8s.io/simple-cluster-member created
serviceaccount/simple-cluster-member created
clusterrolebinding.rbac.authorization.k8s.io/simple-cluster-member created
Error from server (InternalError): error when creating "cluster.yaml": Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": the server could not find the requested resource
```

**Expected behavior**
The cluster deployment should work fine without errors.

**Logs**
```
kubectl -n scylla-operator-system logs scylla-operator-controller-manager-0         
{"L":"INFO","T":"2020-10-12T11:01:36.918Z","M":"Operator started","version":"","build_date":"","commit":"","built_by":"","go_version":"","options":{"Name":"scylla-operator-controller-manager-0","Namespace":"scylla-operator-system","LogLevel":"debug","Image":"","EnableAdmissionWebhook":true},"_trace_id":"1RPoApDIQ56sib68u9DAtQ"}
{"L":"INFO","T":"2020-10-12T11:01:37.468Z","M":"Registering Components.","_trace_id":"1RPoApDIQ56sib68u9DAtQ"}
{"L":"INFO","T":"2020-10-12T11:01:37.980Z","M":"Starting the operator...","_trace_id":"NovN_uELT-mH4L1N-mQMjQ"}
```
**Environment:**
 - Platform:  Minikube
 - Kubernetes version: 1.18.8
 - Scylla-operator version: master

**Comment by prasus** [comment]
I just figured out that it works fine with operator `v0.2.3`. but the latest release (`v0.2.4`) fails with the above issues. The `MutatingWebhookConfiguration` has been added on v0.2.4 and it looks like something related to it is causing the errors. Thanks.

**Comment by ItachGal** [comment]
Hey @prasus , I don't have an environment at the moment but this could be related:
https://github.com/scylladb/scylla-operator/issues/169#issuecomment-668613781

I'll hop back in here when I'm available with an environment to try and help out.
Thanks

**Comment by prasus** [comment]
Hey @ItachGal thanks! 👍🏿  let me know if you need any further details. This issue exists on Minkube, On-premise deployments and can be verified by following the above-mentioned reproducer steps. `v0.2.3` works fine w/o any issues 🙂

**Comment by prasus** [comment]
@ItachGal I did a bit more testing and figured out that we could make it work if we delete the `MutatingWebhookConfiguration` (unlike https://github.com/scylladb/scylla-operator/issues/169#issuecomment-668613781 in which the `ValidatingWebhookConfiguration` is causing issues) before deploying cluster as seen below.
  
```
$git clone https://github.com/scylladb/scylla-operator
$cd scylla-operator/examples/generic
$ kubectl apply -f operator.yaml 
namespace/scylla-operator-system created
customresourcedefinition.apiextensions.k8s.io/clusters.scylla.scylladb.com created
mutatingwebhookconfiguration.admissionregistration.k8s.io/scylla-operator-cluster-webhook created
clusterrole.rbac.authorization.k8s.io/scylla-operator-manager-role created
clusterrolebinding.rbac.authorization.k8s.io/scylla-operator-manager-rolebinding created
service/scylla-operator-webhook-service created
statefulset.apps/scylla-operator-controller-manager created
certificate.cert-manager.io/scylla-operator-serving-cert created
issuer.cert-manager.io/scylla-operator-selfsigned-issuer created
validatingwebhookconfiguration.admissionregistration.k8s.io/scylla-operator-cluster-webhook created

$kubectl apply -f cluster.yaml 
namespace/scylla created
clusterrole.rbac.authorization.k8s.io/simple-cluster-member created
serviceaccount/simple-cluster-member created
clusterrolebinding.rbac.authorization.k8s.io/simple-cluster-member created
Error from server (InternalError): error when creating "cluster.yaml": Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": the server could not find the requested resource

Workaround:

$ kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io scylla-operator-cluster-webhook 
mutatingwebhookconfiguration.admissionregistration.k8s.io "scylla-operator-cluster-webhook" deleted
$ kubectl apply -f cluster.yaml 
namespace/scylla unchanged
clusterrole.rbac.authorization.k8s.io/simple-cluster-member unchanged
serviceaccount/simple-cluster-member unchanged
clusterrolebinding.rbac.authorization.k8s.io/simple-cluster-member unchanged
cluster.scylla.scylladb.com/simple-cluster created

**Comment by zimnx** [comment]
@prasus Mutating webhook was added to master version Operator which is not yet released. Please use 0.2.4 image together with 0.2.4 yamls. Using non-master image with master yaml is not going to work.

**Comment by prasus** [comment]
@zimnx thank you, the latest release v0.3.0` works fine without any issues.
