### ISSUE TITLE
docs: Issue on page Scylla Operator Documentation

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla-operator#1981]
I would like to report an issue on page https://github.com/scylladb/scylla-operator/blob/master/release.md

### Problem

> Announce the new RC with the link to the GitHub release on:
> 
> #scylla-operator channel in ScyllaDB-Users Slack
> users mailing list (https://groups.google.com/g/scylladb-users)

The ScyllaDB Users group is no longer active. 

###  Suggest a fix

The reference to the mailing list should be removed and replaced with a link to the community forum https://forum.scylladb.com/

**Comment by tnozicka** [comment]
fixed in https://github.com/scylladb/scylla-operator/pull/1871
