### ISSUE TITLE
E2E conformance suite needs to work with storage on EKS

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1988]
By default e2e tests run tests that require objects storage. All tests in the conformance suite have to work on all supported platforms or go to a different suite. The conformance suite should be able to validate existing (pre)production clusters.

Our tests with object storage fail when not run on GKE.

https://github.com/scylladb/scylla-operator/blob/8ec06d651f956bae0a0b159249ef3f32a9905e67/test/e2e/set/scyllacluster/scyllamanager_object_storage.go#L42-L51

We have to add support for EKS, or move this out of the conformance suite. Given this is already done, adding EKS support seems to be the most beneficial at this point.

Note: We should backport the fix.

**Comment by rzetelskik** [comment]
We already discussed this internally but for the record "Our tests with object storage fail when not run on GKE." is not true - for instance you can run the suite locally, as long as you provide GCS bucket name and credentials.
For to operator test suite it is enough to wire it to support S3 storage, it doesn't need to go together with EKS support.

@tnozicka regarding filing the issues - should I create a separate one for supporting S3 buckets (not necessarily in EKS), or should we convert this one?

**Comment by tnozicka** [comment]
> "Our tests with object storage fail when not run on GKE." is not true - for instance you can run the suite locally, as long as you provide GCS bucket name and credentials.

Still true, when you run on EC2, you may not have a GCP account at all.

> For the operator test suite it is enough to wire it to support S3 storage, it doesn't need to go together with EKS support.
+1

> should I create a separate one for supporting S3 buckets (not necessarily in EKS)

let's use this one for the flags to `scylla-operator-tests`, but please create dedicated issues for CI bucket support and so on

**Comment by rzetelskik** [comment]
Closed in https://github.com/scylladb/scylla-operator/pull/2050.
