### ISSUE TITLE
run-e2e-gke-release script has no default storage class

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1989]
### What happened?

Running `run-e2e-gke-release.sh` script results in majority of our tests failing due to there being no default StorageClass.

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/ci-scylla-operator-latest-e2e-gke-arm64-parallel/1805118759006900224#1:test-build-log.txt%3A2729

 Contrary to `ci-deploy` script, `ci-deploy-release` used here creates local-csi-driver from manifests generated from `/examples/common/local-volme-provisioner/local-csi-driver`. The StorageClass manifest there is missing the `storageclass.kubernetes.io/is-default-class: "true"` annotation. 
 `SO_CSI_DRIVER_PATH` is not taken into account, contrary to `ci-deploy.sh` script.
 
 /kind bug
 /priority important-soon

### What did you expect to happen?

There should be a default StorageClass or we should wire the scripts to explicitly set StorageClasses to all PVCs created.

### How can we reproduce it (as minimally and precisely as possible)?

ditto

### Scylla Operator version

master

### Kubernetes platform name and version

n/a

### Please attach the must-gather archive.

n/a

**Comment by tnozicka** [comment]
I am leaning towards wiring all the examples and manifest with an explicit storageclass so it can't accidentally use a different one. Also changing the default storageclass is not something we should encourage in production , so people end up setting the storage class anyways

**Comment by tnozicka** [comment]
xref https://github.com/scylladb/scylla-operator/issues/1990

**Comment by rzetelskik** [comment]
Fixed in https://github.com/scylladb/scylla-operator/pull/2009
