### ISSUE TITLE
`forceRedeploymentReason` is not picked up from values in the Helm chart

### ISSUE THREAD

**Issue by gdubicki** [scylladb/scylla-operator#2007]
### What happened?

I edited our `values.scylla.yaml` to include:

```
forceRedeploymentReason: foobar
```

...and that file is passed to our Helm deployment of Scylla like this:

```
helm upgrade \
                scylla \
                scylla/scylla \
                --install \
                --namespace scylla \
                --values values.scylla.yaml \
                --version 1.12.2
```

...but even the helm diff (using https://github.com/databus23/helm-diff) didn't show that anything will be changed and in fact it was not.

### What did you expect to happen?

Value should be picked up and a rolling restart should be triggered.

### How can we reproduce it (as minimally and precisely as possible)?

See "What happened?".

### Scylla Operator version

1.12.2

### Kubernetes platform name and version

```
$ kubectl version
Client Version: v1.29.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5-gke.1192000
```

### Please attach the must-gather archive.

I don't think it's applicable, please correct me if I am wrong

**Comment by gdubicki** [comment]
I wanted to do this because I did a changed the `scylla.yaml` and - if I am getting it right - because of https://github.com/scylladb/scylla-operator/issues/1389 / https://github.com/scylladb/scylla-operator/issues/604 that did not trigger a restart by itself.

**Comment by zimnx** [comment]
Support for it is missing in the helm template: https://github.com/scylladb/scylla-operator/blob/a8730d98b7be7a2ed434e6565216363ac26f7a6f/helm/scylla/templates/scyllacluster.yaml

Feel free to submit a PR adding it.

**Comment by zimnx** [comment]
Fixed by https://github.com/scylladb/scylla-operator/pull/2008
