### ISSUE TITLE
"Performance tuning" docs should be changed to prevent users from having performance-related incidents

### ISSUE THREAD

**Issue by gdubicki** [scylladb/scylla-operator#2017]
### What happened?

We have tried following "[Performance tuning](https://operator.docs.scylladb.com/stable/performance.html)" docs to optimize our cluster and after doing it our cluster performance has become very, very bad.

In particular, the average write times have increased from ~500ms to ~3000ms (so became about 6 x higher) while the 95 percentile has increased from ~2500ms to ~17500ms (about 7 x higher)!

The read times have been affected as well, although less painfully.

Please see the screenshot from our metrics. The "optimizations" have been applied a bit before 21:00 here. 

<img width="1134" alt="Screenshot 2024-07-13 at 10 59 10" src="https://github.com/user-attachments/assets/260fbf19-7752-46c1-b24c-ef680c9df6f8">

This has led to a multiple days-long performance incident that took hours to revert. 

We don't want anyone else to run into this problem ever again.

### What did you expect to happen?

1. The Performance tuning docs should be prepended with a big callout warning that would state, that in some cases the tuning works very badly, possibly breaking performance and that it's hard to revert (basically you have to restart your nodes, which is a hacky procedure to keep the data in some cases, f.e. when using local SSDs in GKE).

I am talking about this style warning:

<img width="789" alt="Screenshot 2024-07-14 at 12 43 29" src="https://github.com/user-attachments/assets/4bab01fc-8b91-4e81-9e09-589e4282635b">

<br/>

2. What `perftune.py` does should become easily revertible, see https://github.com/scylladb/seastar/issues/2350, if the "Performace tuning" should become a non-experimental feature. Preferably, the Scylla operator should then enable running it in revert mode.

### How can we reproduce it (as minimally and precisely as possible)?

Read the docs https://operator.docs.scylladb.com/stable/performance.html

### Scylla Operator version

1.13.0

### Kubernetes platform name and version

```
$ kubectl version
Client Version: v1.29.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5-gke.1192000
```

### Please attach the must-gather archive.

I don't think it matters here, because the perftune.py performance reduction itself is being looked into in https://github.com/scylladb/seastar/issues/2350, but here it is, if needed:

[scylla-operator-must-gather-9zqx6hqsn6zb.zip](https://github.com/user-attachments/files/16230838/scylla-operator-must-gather-9zqx6hqsn6zb.zip)

This is from **after** the revert of the perftune settings. For more info about what perftune did, please see https://github.com/scylladb/seastar/issues/2350.

### Anything else we need to know?

See also https://github.com/scylladb/seastar/issues/2350 for some more info about our setup.

**Comment by gdubicki** [comment]
> > Please attach the must-gather archive.
> 
> > Doesn't apply
> 
> The template specifically says it is **required** and helps us identify the platform and settings that led to the case you describe. We can't commit cycles to debug you issue when you don't invest time into collecting the data.
> 
> https://operator.docs.scylladb.com/stable/support/must-gather.html

Got it, sorry. Attached!

**Comment by zimnx** [comment]
For GCP local SSDs it's important to disable disk writeback cache, otherwise disks are not capable of handling optimized load. Operator only does it when Scylla Enterprise is used as utility image. If you have a license, switch image in `scyllaoperatorconfig.spec.scyllaUtilsImage` to Enterprise one. 
Or do change the cache settings manually on all your nodes.

**Comment by gdubicki** [comment]
Thanks @zimnx!

But do you mean we should apply the perftune **and** disable disk writeback cache for the tuning to work as expected?

**Comment by zimnx** [comment]
yes

**Comment by gdubicki** [comment]
In my opinion, now if https://github.com/scylladb/seastar/issues/2350 would be implemented, the "experimental" and the warning could be removed.

**Comment by mykaul** [comment]
@gdubicki - can you clarify if the issue was indeed the writeback cache?

**Comment by gdubicki** [comment]
> @gdubicki - can you clarify if the issue was indeed the writeback cache?

We don't have the Enterprise license to be able to test that...
