### ISSUE TITLE
HAProxy's default backend deployment image shouldn't be replaced in deploy scripts

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#2063]
### What happened?

ci-deploy script used in our presubmits replaces images matching `docker.io/scylladb/scylla-operator(:|@sha256:)[^ ]*`.
https://github.com/scylladb/scylla-operator/blob/master/hack/ci-deploy.sh#L33-L35

It causes ingress-default-backend Deployment's image to be replaced as well.
https://github.com/scylladb/scylla-operator/blob/master/examples/third-party/haproxy-ingress/10_ingress-default-backend.deploy.yaml#L17

Which in turn causes the deployment to fail

```sh
$ kuebctl get -n haproxy-ingress deployments.apps ingress-default-backend -oyaml | yq -e '.status.conditions'
- lastTransitionTime: "2024-08-06T17:55:49Z"
  lastUpdateTime: "2024-08-06T17:55:49Z"
  message: Deployment does not have minimum availability.
  reason: MinimumReplicasUnavailable
  status: "False"
  type: Available
- lastTransitionTime: "2024-08-07T09:13:42Z"
  lastUpdateTime: "2024-08-07T09:13:42Z"
  message: ReplicaSet "ingress-default-backend-7d478474b6" has timed out progressing.
  reason: ProgressDeadlineExceeded
  status: "False"
  type: Progressing
```

```
$ kubectl logs -n haproxy-ingress pod/ingress-default-backend-7d478474b6-l9ml2
Usage:
   [command]

Available Commands:
  cleanup-job        Runs a cleanup procedure against a node.
  completion         Generate the autocompletion script for the specified shell
  gather             Run the scylla gather.
  help               Help about any command
  manager-controller Run the scylla manager controller.
  must-gather        Run the scylla must-gather.
  node-setup-daemon  Runs a controller that configures this machine.
  operator           Run the scylla operator.
  run-webhook-server Run webhook server.
  sidecar            Run the scylla sidecar.
  version            Prints version.

Flags:
      --feature-gates mapStringBool   A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
                                      AllAlpha=true|false (ALPHA - default=false)
                                      AllBeta=true|false (BETA - default=false)
                                      AutomaticTLSCertificates=true|false (BETA - default=true)
  -h, --help                          help for this command
      --loglevel int32                Set the level of log output (0-10).

Use " [command] --help" for more information about a command.
```

/kind bug

### What did you expect to happen?

HAProxy's default backend deployment image shouldn't be replaced.

### How can we reproduce it (as minimally and precisely as possible)?

Simply deploy our stack with hack/ci-deploy.sh script.

### Scylla Operator version

master

### Kubernetes platform name and version

<details>
```console
$ kubectl version
# paste output here
```

Kubernetes platform info:
</details>

### Please attach the must-gather archive.

Take any of our presubmit's artifacts: https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1934/pull-scylla-operator-master-e2e-gke-parallel/1820821779778637824/.

### Anything else we need to know?

Reproduces in our presubmits.

**Comment by tnozicka** [comment]
I have a fix somewhere in one of my branches
/assign tnozicka
