### ISSUE TITLE
Supporting Scylla Operator disconnected install

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylla-operator#2069]
### What should the feature do?

Supporting deployment of Scylla Operator in an air-gaped environment. At least ScyllaDBMonitoring doesn't allow adjusting the image source at this point.

### What is the use case behind this feature?

Operator deployment in an air-gaped env.

**Comment by tnozicka** [comment]
thx, I've converted this into an epic https://github.com/scylladb/scylla-operator/issues/2072
