### ISSUE TITLE
Change ScyllaDB configuration via operator

### ISSUE THREAD

**Issue by teran** [scylladb/scylla-operator#21]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Operator should be able to configure ScyllaDB with user-provided options, like `batch_size_warn_threshold_in_kb` or any other ones supported by ScyllaDB.

**What is use case behind this feature:**
Now it's impossible to setup ScyllaDB deployed with operator. The feature should fix that and add flexibility on using ScyllaDB in Kubernetes.

**Additional Information:**

**Comment by dahankzter** [comment]
This is something we definitely want to do both on cluster provisioning and at a later time as your needs shift.

**Comment by dahankzter** [comment]
Currently support for changing `scylla.yaml` and `cassandra-rackdc.properties` has been implemented in #35 and #37.

**Comment by dahankzter** [comment]
Is this sufficient for you @teran? have you tried it?

**Comment by teran** [comment]
@dahankzter Oh, missed that... changes to `scylla.yaml` should be enough, I'll try to check it out this week. I believe this issue could be closed since any further changes will be more specific and not related directly to the subject. Thanks!
