### ISSUE TITLE
CustomResourceDefinition too long error with latest Scylla Operator version

### ISSUE THREAD

**Issue by susiesolis** [scylladb/scylla-operator#2157]
### What happened?

While following the Scylla Operator guide to deploy Scylla on Kubernetes, I encountered an error when applying the latest version of the Scylla Operator CRD file. The error message was as follows:

```
The CustomResourceDefinition "[scylladbdatacenters.scylla.scylladb.com](http://scylladbdatacenters.scylla.scylladb.com)" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

Switching to version 1.12.1 of the Scylla Operator resolved the issue. It seems like the CRD file in the latest version exceeds a size limitation.

### What did you expect to happen?

The Scylla Operator should have been deployed without encountering any size-related errors when applying the CRD file.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the [Scylla Operator deployment guide](https://github.com/scylladb/scylla-operator/blob/master/docs/source/generic.md).
Use the latest version of the Scylla Operator.

Run the command:

`kubectl apply -f deploy/operator.yaml`

Observe the error related to the CRD size being too long.

### Scylla Operator version

Latest 1.14.1

### Kubernetes platform name and version

``` 
$ kubectl version
kubectl version --client
Client Version: v1.31.1
Kustomize Version: v5.4.2
```

Kubernetes platform info:
Used an AWS ec2 instance with minikube

### Please attach the must-gather archive.

N/A

**Comment by swasik** [comment]
I can confirm the issue - same problem in my case.
