### ISSUE TITLE
Flake -  Scylla Manager integration should register cluster, sync backup tasks and support manual restore procedure [It] using default ScyllaDB version [RequiresObjectStorage]

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#2161]
### Link to the job that flaked.

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2160/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1848739148916068352

### Snippet of what failed.

```
   [FAILED] %!(EXTRA string=Error: malformed request: missing cluster ID
  Trace ID: IvM4TlOOQ1GAxawtZO0qMw (grep in scylla-manager logs)
  )
  Unexpected error:
      <exec.CodeExitError>: 
      command terminated with exit code 1
      {
          Err: <*errors.errorString | 0xc000b2b770>{
              s: "command terminated with exit code 1",
          },
          Code: 1,
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager_object_storage.go:370 @ 10/22/24 15:20:07.957
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.init.func21.1({{0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0})
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager_object_storage.go:370 +0x4de7
    reflect.Value.call({0x1e5d220?, 0xc000c66f80?, 0x18?}, {0x23912e8, 0x4}, {0xc0000100a8, 0x1, 0xc0000100a8?})
    	reflect/value.go:596 +0xca6
    reflect.Value.Call({0x1e5d220?, 0xc000c66f80?, 0x3570b10?}, {0xc0000100a8?, 0x2020202020202020?, 0x20202020200a2c7d?})
    	reflect/value.go:380 +0xb9 
```

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2168/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1851192187115540480

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/ci-scylla-operator-latest-e2e-gke-arm64-parallel/1850828910783107072#1:test-build-log.txt%3A1185

**Comment by rzetelskik** [comment]
Most likely introduced in https://github.com/scylladb/scylla-operator/pull/2156.

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2168/pull-scylla-operator-master-e2e-gke-parallel/1851235610283479040

**Comment by zimnx** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2169/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1851685077096861696

**Comment by tnozicka** [comment]
failed a periodic here too
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/logs/ci-scylla-operator-latest-e2e-gke-arm64-parallel/1853316297647984640#1:test-build-log.txt%3A1101
