### ISSUE TITLE
docs: Issue on page Monitoring

### ISSUE THREAD

**Issue by edermarlon** [scylladb/scylla-operator#2166]
I would like to report an issue on page https://operator.docs.scylladb.com/v1.14/monitoring

### Problem
All commands on the sections bellow are missing the namespace (`-n scylla`):

https://operator.docs.scylladb.com/stable/monitoring.html#wait-for-scylladbmonitoring-to-roll-out
https://operator.docs.scylladb.com/stable/monitoring.html#wait-for-prometheus-to-roll-out
https://operator.docs.scylladb.com/stable/monitoring.html#wait-for-grafana-to-roll-out

###  Suggest a fix

Add `-n scylla` to those commands. E.g.:
```
$ kubectl wait --for='condition=Progressing=False' scylladbmonitorings.scylla.scylladb.com/example
Error from server (NotFound): scylladbmonitorings.scylla.scylladb.com "example" not found

$ kubectl wait --for='condition=Progressing=False' scylladbmonitorings.scylla.scylladb.com/example -n scylla
scylladbmonitoring.scylla.scylladb.com/example condition met
```

Or, save the namespace for all subsequent kubectl commands in that context:

```
$ kubectl config set-context --current --namespace=scylla
Context "minikube" modified.

$ kubectl wait --for='condition=Progressing=False' scylladbmonitorings.scylla.scylladb.com/example
scylladbmonitoring.scylla.scylladb.com/example condition met```

**Comment by tnozicka** [comment]
The explicit namespace has been removed in https://github.com/scylladb/scylla-operator/pull/2188 so it all runs in the same (current) namespace.
