### ISSUE TITLE
When scylla-operator is bringing cluster up on GKE it can raise "Failed to update cluster status, Operation cannot be fulfilled on"

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#217]
**Describe the bug**
When scylla-operator is bringing cluster up on GKE it can raise "Failed to update cluster status, Operation cannot be fulfilled on"

Error body:

```
2020-10-27 11:57:49.304: (ScyllaOperatorLogEvent Severity.ERROR) 4aSlXUw2TOulhY9gLe_UZg cluster-controller/scylla/sct-cluster: Failed to update cluster status, Operation cannot be fulfilled on clusters.scylla.scylladb.com "sct-cluster": the object has been modified; please apply your changes to the latest version and try again
```

**To Reproduce**
1. Deploy operator on GKE
2. Deploy scylla cluster via operator
3. Look at scylla-operator logs

**Expected behavior**
No errors

**Config Files**

**Logs**
[long-10gb-3h-jenkins-k8s-gke-ea765da9.zip](https://github.com/scylladb/scylla-operator/files/5450493/long-10gb-3h-jenkins-k8s-gke-ea765da9.zip)

**Environment:**
 - Platform: GKE
 - Kubernetes version: 1.15.12-gke.20
 - Scylla version: 4.1.7
 - Scylla-operator version: 0.2.4

**Comment by zimnx** [comment]
This is natural in k8s env that objects are changed by multiple actors. These conflicts must be retried, and they are. What we can do, is to log this kind of error on Info level.

**Comment by dkropachev** [comment]
Totally make sense.
