### ISSUE TITLE
Scylla cluster gets rolling restarted right after it finishes initial boot

### ISSUE THREAD

**Issue by grzywin** [scylladb/scylla-operator#2223]
### What happened?

SCT tests for Operator are failing during setUp stage while attempting to execute first CQL call. That indicates that there are some connection issues with scylla pods (maybe timeout?). 
To investigate this problem further I reran some simple SCT test for Operator locally and I noticed that right after scylla cluster gets up, for some reason it immediately gets rolling restarted.
When I executed the same test with Operator 1.14 it did not do that.

### What did you expect to happen?

Operator should not do rolling restart of scylla cluster for no reason.

### How can we reproduce it (as minimally and precisely as possible)?

The easiest way would be to rerun some simple SCT functional test like - test_single_operator_image_tag_is_everywhere. 

### Scylla Operator version

It was tested with latest version of Operator:
`v1.16.0-alpha.0-22-g66630b2-latest`

### Kubernetes platform name and version

>kubectl version

Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.27.3

### Please attach the must-gather archive.

Failed run from Jenkins:
https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/upgrade/job/upgrade-major-scylla-k8s-eks-test/8/consoleFull
Must gather logs can be found in the [bottom](https://cloudius-jenkins-test.s3.amazonaws.com/0da9cee0-0818-444f-8a00-e2957f221bbb/20241202_192713/kubernetes-must-gather-0da9cee0.tar.gz) of Jenkins test results

I was unable to generate must-gather logs from my local SCT run where I observed "live" that scylla cluster gets restarted, but I have kubectl `logs` and `describe` from operator pods. [Here](https://github.com/user-attachments/files/17989586/localdata.zip) they are. If it helps, restart happened around 20:15:30.

EDIT: I was able to generate must-gather from my local run [scylla-operator-must-gather-6hkf47s6ttvn.zip](https://github.com/user-attachments/files/17993203/scylla-operator-must-gather-6hkf47s6ttvn.zip)

### Anything else we need to know?

This bug is blocking SCT test runs for 1.15.

**Comment by tnozicka** [comment]
> I noticed that right after scylla cluster gets up, for some reason it immediately gets rebooted.

which node got rebooted?

> bserved "live" that scylla cluster gets restarted, but I have kubectl logs and describe from operator pods. [Here](https://github.com/user-attachments/files/17989586/localdata.zip) they are.

for the record, if scylla restart the relevant logs are scylla logs, not the operator

> I was able to generate must-gather from my local run [scylla-operator-must-gather-6hkf47s6ttvn.zip](https://github.com/user-attachments/files/17993203/scylla-operator-must-gather-6hkf47s6ttvn.zip)

none of 3 scylladb nodes there has a container restartCount>0, nor "previous" logs - please be specific which one is causing the issue

**Comment by tnozicka** [comment]
I've also send a PR to see if we hit an "outside" restart https://github.com/scylladb/scylla-operator/pull/2229 - but it's not clear to me whether you've hit a container restart or scylla process restart (within supervisord) or on which node.

**Comment by tnozicka** [comment]
> Failed run from Jenkins:
https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/upgrade/job/upgrade-major-scylla-k8s-eks-test/8/consoleFull

also please always write the issue so any resource is open and/or provide enough info here on this issue to cover what you describe

**Comment by grzywin** [comment]
> > I noticed that right after scylla cluster gets up, for some reason it immediately gets rebooted.
> 
> which node got rebooted?

All nodes got rebooted.

> > bserved "live" that scylla cluster gets restarted, but I have kubectl logs and describe from operator pods. [Here](https://github.com/user-attachments/files/17989586/localdata.zip) they are.
> 
> for the record, if scylladb restarts the relevant logs are scylladb logs, not the operator

Noted

> > I was able to generate must-gather from my local run [scylla-operator-must-gather-6hkf47s6ttvn.zip](https://github.com/user-attachments/files/17993203/scylla-operator-must-gather-6hkf47s6ttvn.zip)
> 
> none of 3 scylladb nodes there has a container restartCount>0, nor "previous" logs - please be specific which one is causing the issue

I don't know why restartCount is not increased. I recorded some short video from my local machine to show you what is happening.
https://github.com/user-attachments/assets/2f421052-e0ed-43d4-af21-7950cca31513

> also please always write the issue so any resource is open and/or provide enough info here on this issue to cover what you describe

Do you mean here to write issue in Argus to the provided test run? If yes, then I added it now. If no, can you please elaborate it a bit more cause I am not sure I know what you mean.

**Comment by tnozicka** [comment]
> All nodes got rebooted.

I went through `/scylla-operator-must-gather-6hkf47s6ttvn/namespaces/scylla/pods/sct-cluster-local-dc-1-rack-1-0/scylla.current` and saw no scylladb restart - can you pleas point to the relevant logs where you saw the restart?

> I don't know why restartCount is not increased. I recorded some short video from my local machine to show you what is happening.
https://github.com/user-attachments/assets/2f421052-e0ed-43d4-af21-7950cca31513

Because this is not "container restart". You video shows pod is getting **deleted** and recreated. If that happens for all the pods, that seem like a rollout is happening for a reason. Your ScyllaCluster generation is 3 - which means at least 2 changes happened that could trigger a rollout - and even if you stop your script, a rollout may already be queued and waiting for the previous one to finish.

I am not sure whether there is something wrong or not. I'd advise to find a reproducer and limit it to a kubectl and a yaml file.
Or just wait for all rollouts to finish (if you drop too early there is something wrong with the wait instructions).

> Do you mean here to write issue in Argus to the provided test run? If yes, then I added it now. If no, can you please elaborate it a bit more cause I am not sure I know what you mean.

Assume this issue should be self contained and accessible for the community. Don't rely on references to third party tools or systems. (It's fine to have an extra context but the issue should be self contained and understandable and debugable without accessing them.)

**Comment by zimnx** [comment]
I can confirm there's an issue. Scenario I tried is 
1. Create ScyllaCluster
2. Add node by increasing rack member count
3. Observe new node being added and once it's fully ready, cluster is rolling restarted.

**Comment by tnozicka** [comment]
@grzywin also make sure you wait for the ScyllaCluster correctly - while we fix it, the extra rollout shouldn't affect you
```
# Wait for it to deploy.
kubectl wait --for='condition=Progressing=False' scyllacluster.scylla.scylladb.com/scylladb
kubectl wait --for='condition=Degraded=False' scyllacluster.scylla.scylladb.com/scylladb
kubectl wait --for='condition=Available=True' scyllacluster.scylla.scylladb.com/scylladb
```
https://operator.docs.scylladb.com/v1.15/resources/scyllaclusters/basics.html

**Comment by zimnx** [comment]
Looks like we have two PEBKAC's :) 

In QA case, test created ScyllaCluster which got later updated with additional ScyllaDB arguments.
```
scylla-operator-must-gather-6hkf47s6ttvn/namespaces/scylla/controllerrevisions.apps
$ diff sct-cluster-local-dc-1-rack-1-5bc9b64f47.yaml sct-cluster-local-dc-1-rack-1-7cf8dc6686.yaml
68c68,75
<           - ""
---
>           - --abort-on-lsa-bad-alloc
>           - "1"
>           - --abort-on-internal-error
>           - "1"
>           - --abort-on-ebadf
>           - "1"
>           - --enable-sstable-key-validation
>           - "1"
```

It means after first rollout, there's a second one to adjust the parameters and is expected.

In my case, I used non-server-side apply which resulted in kubectl annotation `last-applied-configuration` being upated which triggered a rollout after scaling. 

@grzywin please confirm it's the case.

**Comment by tnozicka** [comment]
> Could you clarify this for me?

The rollouts depend on the timing. If a rollout manages to progress beyond a certain point, then the next update has to be queued, otherwise it has a chance to be applied right away.

**Comment by grzywin** [comment]
@tnozicka Thank you for the explanation. However, I still find it concerning that we never experienced this issue with SCT tests before the 1.15 alpha versions, and now it occurs regularly.

**Comment by grzywin** [comment]
My concern is that, although I’ve identified the issue in the test code, I’m still worried whether this problem could also be a symptom of degraded performance elsewhere in the system. If 'something else got faster or was ordered differently,' then we’re good. However, if 'something else got slower,' then it might be something to be concerned about.

Anyway, I don't want to be stubborn as it is not the point, I just wanted to make sure that we are on the same page and my concerns are addressed. Once my SCT fix be merged I will continue running the tests on EKS.

**Comment by tnozicka** [comment]
Ok, I get that but this can be milliseconds either way and not related. We should validate performance separately. (We have fixed slow ignition in the meantime but those are not generally traceable from "something changed its timing on an unrelated issue".)
