### ISSUE TITLE
Fatal error during installing scylla-operator

### ISSUE THREAD

**Issue by c0ffeec0der** [scylladb/scylla-operator#227]
**Describe the bug**

Install using
kubectl apply -f examples/generic/operator.yaml

Error in log
{"L":"FATAL","T":"2020-11-05T08:35:34.215Z","M":"error launching manager","mode":"operator","error":"no matches for kind \"Cluster\" 
in version \"scylla.scylladb.com/v1alpha1\"","_trace_id":"Jp0fL1bbTE2pCPlH9jO-gg"}

**To Reproduce**
1. Create Operator
2. Perform this action
    see the log in the pods
3. See error

**Expected behavior**
Operator pod running

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.
{"L":"FATAL","T":"2020-11-05T08:35:34.215Z","M":"error launching manager","mode":"operator","error":"no matches for kind \"Cluster\" 
in version \"scylla.scylladb.com/v1alpha1\"","_trace_id":"Jp0fL1bbTE2pCPlH9jO-gg"}

**Environment:**
 - Platform: docker desktop
 - Kubernetes version: 1.19
 - Scylla version: 
 - Scylla-operator version: e.g.: 0.3.0

**Additional context**

**Comment by zimnx** [comment]
We recently changed Kind name on master branch as a part of #144. Make sure to use operator.yaml from master branch only when you use master operator image. v0.3.0 image is not compatible with master examples.

**Comment by c0ffeec0der** [comment]
Hello @zimnx 

Thank you for the update, I'll use the yaml from branch-0.3 for 0.3.0 image for the time being 👍

**Comment by te4336** [comment]
When using the operator, and using the Master branch as suggested, I also get the same error.

{"L":"FATAL","T":"2020-11-19T07:02:26.056Z","M":"error launching manager","mode":"operator","error":"no matches for kind \"Cluster\" in version \"scylla.scylladb.com/v1alpha1\"","_trace_id":"GyNEAbwQSGScLlEyMaQ5Ng"}

**Comment by c0ffeec0der** [comment]
> When using the operator, and using the Master branch as suggested, I also get the same error.
> 
> {"L":"FATAL","T":"2020-11-19T07:02:26.056Z","M":"error launching manager","mode":"operator","error":"no matches for kind "Cluster" in version "scylla.scylladb.com/v1alpha1"","_trace_id":"GyNEAbwQSGScLlEyMaQ5Ng"}

Use the yaml from branch-0.3 for 0.3.0 image
