### ISSUE TITLE
Quick cluster launch

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-operator#230]
When starting a new, fresh cluster, all nodes can start in parallel, significantly reducing the launch time
This is **not** the case, when adding nodes, or if there is already data in the cluster.

**Comment by slivne** [comment]
This is impossible in Scylla (especially with CDC) we even have a very strong error message to users NOT TO DO THAT.

We have elasticity in the plan - this is not implemented and may depend on Raft for toplogy changes so we are looking at 1 year+ at this point to even consider this.

So for now this is not possible .

**Comment by gcarmin** [comment]
@slivne  - We are talking here about new cluster - where there is no data/schema yet.

**Comment by slivne** [comment]
@gcarmin the limitation stands - user should not start multiple nodes at once - one after the other - we need to generate stream ids for token ranges and it implies nodes should be added one by one.

**Comment by eyalgutkind** [comment]
If the cluster is new. Can we, knowing the number of nodes in the cluster, define the tokens per node with initial_token: setting?

**Comment by rjeczalik** [comment]
@eyalgutkind The issue here is with CDC, it generates stream ids assuming empty cluster if formed by adding nodes **one by one**.
