### ISSUE TITLE
Consolidate logging

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#24]
Right now we have att least three different loggers:

```
github.com/sirupsen/logrus
sigs.k8s.io/controller-runtime/pkg/runtime/log
github.com/prometheus/common/log
```

We should switch to only use `github.com/scylladb/go-log` which will soon be open sourced.
Unless there is specific reasons for using these loggers of course.

**Comment by yanniszark** [comment]
Great catch, I hadn't realized that.
The initial intention was to use logrus.
The requirements I personally have from a logger are:
* Able to log `<key>:<value>` pairs alongside each message (eg log Cluster Object namespace/name/resourceversion for which the reconcile is done).
* JSON logging.

I'm sure that the scylla go-logger will be able to do both.

**Comment by dahankzter** [comment]
It can indeed @yanniszark ! :)
