### ISSUE TITLE
Kubernetes is draining nodes more than one time on rollout restart

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#241]
**Describe the bug**
We bring cluster up, ammend config map and do rollout restart
Time to time we see that some of the nodes are drained multiple times

**To Reproduce**
1. Deploy s-o
2. Deploy scylla cluster of 3 nodes
3. Run: "kubectl rollout restart statefulset -n scylla"
4. Go over all logs to see how many drains each node have got

**Expected behavior**

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
Example test-id: fe81a706-fe0b-4283-9065-52886c7bf344
scylla pod logs: https://cloudius-jenkins-test.s3.amazonaws.com/fe81a706-fe0b-4283-9065-52886c7bf344/20201105_121713/db-cluster-fe81a706.zip
sct log: https://cloudius-jenkins-test.s3.amazonaws.com/fe81a706-fe0b-4283-9065-52886c7bf344/20201105_121713/db-cluster-fe81a706.zip

node-2
```
INFO  2020-11-05 08:33:23,302 [shard 0] iotune - /var/lib/scylla/data passed sanity checks
INFO  2020-11-05 08:35:26,103 [shard 0] init - starting gossip
INFO  2020-11-05 08:35:36,829 [shard 0] messaging_service - Starting Messaging Service on port 7000
INFO  2020-11-05 08:35:38,779 [shard 0] gossip - InetAddress 10.7.240.139 is now UP, status = NORMAL
INFO  2020-11-05 08:38:40,263 [shard 0] gossip - InetAddress 10.7.254.21 is now UP, status = UNKNOWN
INFO  2020-11-05 08:40:02,391 [shard 0] storage_service - DRAINING: starting drain process
INFO  2020-11-05 08:40:02,391 [shard 0] storage_service - Shutting down native transport
INFO  2020-11-05 08:40:02,392 [shard 0] storage_service - Shutting down native transport was successful
INFO  2020-11-05 08:40:05,596 [shard 0] storage_service - DRAINED: 
INFO  2020-11-05 08:40:22,830 [shard 0] iotune - /var/lib/scylla/view_hints passed sanity checks
INFO  2020-11-05 08:42:25,469 [shard 0] init - starting gossip
INFO  2020-11-05 08:42:37,710 [shard 0] gossip - InetAddress 10.7.254.21 is now UP, status = BOOT
INFO  2020-11-05 08:42:37,710 [shard 0] gossip - InetAddress 10.7.240.139 is now UP, status = NORMAL
INFO  2020-11-05 08:43:30,796 [shard 0] gossip - InetAddress 10.7.254.21 is now DOWN, status = shutdown
INFO  2020-11-05 08:45:55,929 [shard 0] gossip - InetAddress 10.7.254.21 is now UP, status = NORMAL
INFO  2020-11-05 08:46:22,048 [shard 0] storage_service - DRAINING: starting drain process
INFO  2020-11-05 08:46:22,048 [shard 0] storage_service - Shutting down native transport
INFO  2020-11-05 08:46:22,049 [shard 0] storage_service - Shutting down native transport was successful
INFO  2020-11-05 08:46:25,289 [shard 0] storage_service - DRAINED: 
```

**Environment:**
 - Platform: GKE
 - Kubernetes version: 1.15.12-gke.20
 - Scylla version: 4.1.5
 - Scylla-operator version: 0.3.0

**Comment by zimnx** [comment]
Fixed in https://github.com/scylladb/scylla-operator/pull/244
