### ISSUE TITLE
testing: add CI testing

### ISSUE THREAD

**Issue by yanniszark** [scylladb/scylla-operator#25]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add CI testing before merging PRs.

**What is use case behind this feature:**
* Merge with confidence.
* Prevent regressions.

/cc @dahankzter

**Comment by dahankzter** [comment]
I think we can simply start with something like TravisCI for this and evolve as we go.

**Comment by yanniszark** [comment]
@dahankzter I've never set up Travis (or any CI for that matter) before, so it would be a great learning exercise.
I don't know if you have some guidelines to follow (eg where to deploy Travis) or should I just follow the documentation.

**Comment by dahankzter** [comment]
We are waiting for Github Actions to be enabled. Several other projects also want to use it so I think that's the way to go as well unless it delays a lot. What do you think?
