### ISSUE TITLE
Implement interface for encryption options

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#252]
* Feature Request
Scylla has set of encryption related options, such as server_encryption_options, client_encryption_options, kmip_hosts, server_encryption_options and system_info_encryption

Currently s-o enables them via configmap, volumeMount and volumes, but it requeres following steps:

- put certificate/key into secret
- define a volume of the secret
- define VolumeMount for the volume 
- keeping in memory what path within secret each certificate/key has, reconstruct it's path in the docker and put it into the configmap

Not quite userfriendly right ?

Let's design solution to make it simplier via s-o api.

**Comment by tnozicka** [comment]
we have decided to do this on a higher level and provide the certificates as well, so I'll close the low level API
