### ISSUE TITLE
Repair and Backup tasks have no status

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#272]
**Describe the bug**
I submitted the task and can't get whether it is scheduled, running, done or failed.
We need to have a status field that will reflect following states:

1. Not scheduled - when task can't be scheduled due to the wrong configuration
2. Scheduled - scheduled, but have not been ran yet
3. Running - is currently running
4. Success - Completed successfully
5. Failed - Failed on last run

Error field to be populated in both cases: 'Not scheduled' and 'Failed'

**To Reproduce**
1. Deploy scylla operator, scylla manager and scylla
2. kubectl patch scyllacluster simple-cluster -n scylla --type='json' "[{"op": "replace","path": '/spec/repairs',"value": [{'name': 'tmprepair1','dc': ['dc'],'keyspace': ['*']}]}]"
3. kubectl get scyllacluster simple-cluster  -n scylla -o yaml
4. kubectl patch scyllacluster simple-cluster -n scylla --type='json' "[{"op": "replace","path": '/spec/repairs',"value": [{'name': 'tmprepair1','keyspace': ['*']}]}]"
5. kubectl get scyllacluster simple-cluster  -n scylla -o yaml
etc..

**Comment by tzach** [comment]
Is this a manager or operator issue?

**Comment by dkropachev** [comment]
> Is this a manager or operator issue?

Operator
