### ISSUE TITLE
Interact with the Scylla API directly

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#28]
This ties into #5 and requires the Agent to be available on the nodes. We also need to generate clients from the Scylla API Swagger definitions and possibly create some easy to use wrapper code for the operations we need to use.

**Comment by tzach** [comment]
This will be very good and remove the dependency on both nodetool and JMX

**Comment by tzach** [comment]
Look like only `nodetool drain` and `nodetool decommission` are in use.

As fast as I can see `nodetool drain` just call `/storage_service/drain`[1], and `nodetool decommission` call `/storage_service/decommission`[2]

@amnonh please correct me if any of this operation is doing more than that (like wait for the result)

[1] https://github.com/scylladb/scylla-jmx/blob/04ea3ab7e02dbbb37eeb696f55ca4c5fe2a1ee5b/src/main/java/org/apache/cassandra/service/StorageService.java#L1036
[2] https://github.com/scylladb/scylla-jmx/blob/04ea3ab7e02dbbb37eeb696f55ca4c5fe2a1ee5b/src/main/java/org/apache/cassandra/service/StorageService.java#L916

**Comment by tzach** [comment]
Two more use case to replace (both use `nodetool status`)
1. livenessCheck
https://github.com/scylladb/scylla-operator/blob/master/pkg/sidecar/checks.go#L31

2. readinessCheck
https://github.com/scylladb/scylla-operator/blob/master/pkg/sidecar/checks.go#L45

**Comment by dahankzter** [comment]
Indeed @tzach we need these calls as well.

**Comment by asias** [comment]
I do not think we have any node operations that are not possible without jmx. We can do everything with the restful api.  if there is any that we can't, it is "bug" we should fix it.

**Comment by dahankzter** [comment]
Thx @asias then we are good to go!

**Comment by dahankzter** [comment]
And with the manager installed we can do it with encrypted traffic as well.
