### ISSUE TITLE
Do we need to start scylla with --overprovisioned ?

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#281]
Since k8s environment, even when scylla is only pod on the host, is highly shared it might be adequate to run it there with --overprovisioned option to make it more stable there

**Comment by slivne** [comment]
On Tue, Dec 1, 2020 at 10:59 AM Dmitry Kropachev <notifications@github.com>
wrote:

> Since k8s environment, even when scylla is only pod on the host, is highly
> shared it might be adequate to run it there with --overprovisioned option
> to make it more stable there
>

We haven't done the work on performance to optimize deployments in operator
to get to non K8 deployments performance.

Once we do that we will pin threads allocate dedicated CPU's, distribute
interrupts etc.

**Comment by tnozicka** [comment]
closing as stale
