### ISSUE TITLE
Create Cluster watcher for Scylla Manager

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#29]
The cluster watcher should watch the Kubernetes API for new clusters and add them as needed to the Scylla Manager. I think it is better to talk via the Scylla Manager API than using sctool so we need to generate a client from the Scylla Manager Swagger. This task is essentially a part of #5 and needs to be completed before release.

**Comment by dahankzter** [comment]
The client is available now so that's out of the way.

**Comment by gnumoreno** [comment]
I don't understand the problem statement or the comment. Can you please elaborate, @dahankzter

**Comment by dahankzter** [comment]
This is to automatically add the cluster to Scylla manager when it's added.

**Comment by zimnx** [comment]
Fixed by #188
