### ISSUE TITLE
Two first nodes of every rack are seed ones

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#292]
**Describe the bug**
Currently we have following logic on setting seed flag on the nodes:
```
	if strings.HasSuffix(pod.Name, "-0") || strings.HasSuffix(pod.Name, "-1") {
		labels[naming.SeedLabel] = ""
	}
```

It leads to marking two first nodes of every rack as seed nodes.
As result you can't replace them.

**Comment by gnumoreno** [comment]
@dkropachev that's because scylla's official recommendation is to have 2 seeds per DC and it probably got confused with Rack.
