### ISSUE TITLE
ScyllaConfigAgent secret name is ignored

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#298]
**Describe the bug**

Value of ScyllaConfigAgent from CRD is ignored, and hardcoded value is passed to as a VolumeSource:
https://github.com/scylladb/scylla-operator/blob/629e325a75ce5a70ec82adea4c4e60d424ad7058/pkg/controllers/cluster/resource/resource.go#L171

**Comment by flecno** [comment]
It also ignores the field `ScyllaConfig`/`scylla-client-config-secret`
