### ISSUE TITLE
Inject Scylla Manager Agent into Scylla container

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#30]
The Scylla Manager Agent needs to run on the the same host as it's corresponding Scylla instance. That means we have to inject it via a shared volume and make sure it runs accordingly.
We can use Supervisord to ensure this since the Scylla images already have it installed.
We also need to generate or capture the auth token that the agent needs to function securely.

Required by: #5

**Comment by dahankzter** [comment]
Building a new Scylla docker with the Agent installed works fine but requires some hacky things. First we need to set the Agent HTTPS config in it's config file or the Agent will default to Scylla broadcast address which is not a local interface but networking defined by Kubernetes and only usable for outside clients calling in.
We need to generate tls certificate files and potentially even a certificate authority file. There is also the token key that needs to be generated and written to the Agent config file. Perhaps it is best to share this file via a mount?
What do you think @yanniszark ?
The alternative seems to be complete sidecar injection where we generate and copy over everything we need.

**Comment by yanniszark** [comment]
@dahankzter we already have a sidecar binary which is injected via an initContainer with a shared volume.
Here is the config setup code: https://github.com/scylladb/scylla-operator/blob/master/pkg/sidecar/config/config.go#L49

Maybe you can use that to inject the agent or set it up.
In addition, can you enumerate what options are needed in the agent HTTPS config and what they are used for?
Maybe we can expose the necessary settings via environment variables.

**Comment by dahankzter** [comment]
Yes if Scylla doesn't come with the agent installed this is a way to do it. We just need a way to get hold of the binary.

There are basically two primary things that needs to be injected.

1. A tls certificate. The agent installation package comes with this bundled so if we inject ourselves we need to provide it.
2. A shared token that is used for extra security. It works without it but att a decreased level of security. All the agents need to have the same token and the user of the operator should provide it I think at least.

An extra problem I discovered yesterday is that the Agent will make some clever guessing on which interface to bind to by inspecting what scylla.yaml contains. It can be set in it's config file but if it isn't then it will first try the broadcast address (which isn't available on the host....) and if this isn't set it will take the listen address. So we probably need to provide it in some clever way and put it in the agent config file.

**Comment by dahankzter** [comment]
If we can run the agent as a "normal" sidecar in it's own container that would be great. It's my understanding it can invoke scylla rest api over localhost in that case as well and we need to make the scylla data directory available and possibly also some of scyllas config.

**Comment by dahankzter** [comment]
I think we don't need to inject it but rather just start a new scylla-managet-agent container. Giving it access to Scylla data directory seems to work fine. More extensive testing is needed but it looks promising and the config turned out very simple.

**Comment by dahankzter** [comment]
We may need to limit the resources of the agent as per: https://github.com/scylladb/mermaid/issues/1654

**Comment by dahankzter** [comment]
Fixed by #54
