### ISSUE TITLE
Allow for configuring all the scylla.yaml config options

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#31]
Not sure how we are going to do this but extending `docker-entrypoint.py` is one option.

**Comment by dahankzter** [comment]
We have at least one user that needs to inject `batch_size_fail_threshold_in_kb` so we might as well allow for all of them to be injected.

**Comment by penberg** [comment]
It would be interesting to know what other Docker images do. Perhaps there's some established convention?

That said, you could introduce a generic `--server-opts` command line argument that looks something like this:

```sh
docker run scylladb/scylla --server-opts "batch_size_fail_threshold_in_kb=1024" "listen-address=0"
```

You can then either modify the YAML or pass these options to the `scylla` executable.

**Comment by dahankzter** [comment]
Actually we have hooks to write scylla.yaml before the `docker-entrypoint.py` is run so that bypasses the problem I think. It doesn't help for a generic docker user but for the operator it should suffice.

**Comment by dahankzter** [comment]
Is it a good idea to put this on the cluster spec @yanniszark ? That way we can set the properties in the cluster yaml and just pass it down to the scylla.yaml.

**Comment by dahankzter** [comment]
I tested it and it seems to work fine. The question is if there is some aspect of lifecycle management or other that gets complicated or broken by doing this.

**Comment by dahankzter** [comment]
Applying it again to change it doesn't work. I guess the reconciliation loop also needs this check and take appropriate action.

**Comment by yanniszark** [comment]
@dahankzter my original idea was:

1. Add a userConfigMap field in the RackSpec.
    * The ConfigMap will contain certain well-known keys (eg scylla.yaml).
2. The ConfigMap is mounted on a temp location inside the scylla pod (eg /etc/scylla/userconfig/{files}).
3. The sidecar performs a 3-way merge of the original file (eg scylla.yaml) the user-provided file and the fields we know must have a certain value (eg we can't let the user define the broadcast_address, else things won't work correctly). So the operation is merge(merge(original, user-provided), certain-values) for every config file we support (scylla.yaml for starters).

This way the user can overwrite only the fields they want, without having to provide the whole scylla.yaml.

Now for updating:
We have 2 kinds of updates:
1. Changing the ConfigMap content. This requires us to do a rolling update, one Pod at a time. We can achieve that by keeping a label with the sha256 hash of the ConfigMap in each StatefulSet's PodSpec. Changing the value will make the StatefulSet controller trigger a rolling restart on that StatefulSet. (we can skip supporting this if we don't want it at first).
2. Changing the userConfigMap field to a different value. This requires us to update the underlying StatefulSets, which will then do a rolling restart to propagate the change. (we should support this, it's a very common case for a user to start with an empty userConfigMap field and then specify one).

@dahankzter the general pattern that the operator follows is to coordinate StatefulSets (Rack by Rack) and let the StatefulSet controller do the heavy lifting.

**Comment by dahankzter** [comment]
Cool! I did it like this for the first case:

1. Config (type created in `cluster_types.go`) with selected scylla.yaml fields directly in the spec. Do we need it to be different for the different racks?
2. Merge them in `ScyllaConfig::setupScyllaYAML` method by simply reading the cluster using the available client. Precaution for the "forbidden" fields not needed since we can simply omit them from the config. I think at least. This way we don't need a mount right? Perhaps I am missing something, it is quite possible.

I haven't tried Updates much but starting with 2 sounds good if you think it's the best way. Can you point me in the proper direction as to where to put the logic?

**Comment by dahankzter** [comment]
Ill drop off a PR we can discuss details around @yanniszark. It is always good when there are details to sort out.

**Comment by yanniszark** [comment]
I was actually thinking of using a ConfigMap and doing blind YAML merging.
You can read more about ConfigMaps here: https://cloud.google.com/kubernetes-engine/docs/concepts/configmap

Essentially they are Kubernetes Objects for managing configuration files.
You can mount them on Pods.

**Comment by dahankzter** [comment]
That sounds like the way to go then. :) I have much kubernetes practice to catth up on I guess. Was mostly just happy that it worked.

**Comment by tzach** [comment]
There is more configuration file in addition to scylla.yaml, like:

- cassandra-rackdc.properties 
- housekeeping.cfg.
- dev-mode.conf 
- io.conf

**Comment by mailmahee** [comment]
IMU Config maps and secrets should be handled in the same way -
https://opensource.com/article/19/6/introduction-kubernetes-secrets-and-configmaps

this is how confleunt operator handles them -https://docs.confluent.io/current/tutorials/examples/kubernetes/gke-base/docs/index.html#client-configurations

**Comment by dahankzter** [comment]
Thats more or less how the PR #35 handles scylla.yaml @mailmahee now. Please take a look.

**Comment by dahankzter** [comment]
Do we really want to allow configuration of all these @tzach ? We generate rackdc from the `cluster.yaml` but perhaps tweaking it is possible.
i need to check how we handle the others if at all at the moment.

**Comment by dahankzter** [comment]
We need to be able to tweak `cassandra-rackdc.properties` as well but ill make another issue for it @tzach.
