### ISSUE TITLE
CRD version control

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#311]
* Feature Request

**What should the feature do:**
s-o is highly dependant on CRD, but does not control which CRD is currently deployed which can lead to the unpredictible behavior.
Example of it is https://github.com/scylladb/scylla-operator/issues/307, where s-o does following thing:

```
c := &scyllav1alpha1.ScyllaCluster{}
err := cc.UncachedClient.Get(ctx, request.NamespacedName, c)
copy := c.DeepCopy()
a.pollInterval = copy.Cluster.Spec.GenericUpgrade.PollInterval.Duration
```
Where we assume that since we have GenericUpgrade in Default(), it will be present in copy

```
	if c.Spec.GenericUpgrade == nil {
		c.Spec.GenericUpgrade = &GenericUpgradeSpec{}
	}
```
Which is not the case if CRD does not have GenericUpgrade at all.
As result s-o endup in panic.

**Comment by zimnx** [comment]
We should instead support converting between CRD versions. Currenly we only support v1, v1alpha1 is not supported.
