### ISSUE TITLE
Scylla doesn't boot after node drain, uncordon: node does not get replace_address

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#312]
**Describe the bug**
automaticOrphanedNodeCleanup does not work after node drain, uncordon

**To Reproduce**
1. Deploy Operator on GKE 
2. Deploy scylla cluster of 3 pods with automaticOrphanedNodeCleanup set to true
3. Get node of the last pod and drain it: `kubectl drain <nodename> --ignore-daemonsets --delete-local-data`
4. Uncordon node right away: `kubectl uncordon <nodename>`
5. Wait till last pod got into ready state: `kubectl wait --for=condition=Ready pod <podname>`
See that it is never become ready

**Expected behavior**
Node is ready

**Logs**
db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/a7fcf9f1-41cf-4a74-aebb-73c50511e1c1/20201223_114435/db-cluster-a7fcf9f1.zip  |
monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/a7fcf9f1-41cf-4a74-aebb-73c50511e1c1/20201223_114435/monitor-set-a7fcf9f1.zip |
loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/a7fcf9f1-41cf-4a74-aebb-73c50511e1c1/20201223_114435/loader-set-a7fcf9f1.zip  |
kubernetes  | https://cloudius-jenkins-test.s3.amazonaws.com/a7fcf9f1-41cf-4a74-aebb-73c50511e1c1/20201223_114435/kubernetes-a7fcf9f1.zip  |
sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/a7fcf9f1-41cf-4a74-aebb-73c50511e1c1/20201223_114435/sct-runner-a7fcf9f1.zip  

s-o:
```
{"L":"DEBUG","T":"2020-12-23T10:53:39.623Z","N":"cluster-controller","M":"Found nodes","len":7,"_trace_id":"sxtTURPoT36C3Id1lVkPiQ"}
{"L":"DEBUG","T":"2020-12-23T10:53:39.623Z","N":"cluster-controller","M":"PVC attachment found","pvc":"data-sct-cluster-us-east1-b-us-east1-2","node":"gke-lon-scy-ope-3h-gke-j-default-pool-bfd54b3c-gbqq","_trace_id":"sxtTURPoT36C3Id1lVkPiQ"}
{"L":"DEBUG","T":"2020-12-23T10:53:39.624Z","N":"cluster-controller","M":"PVC attachment found","pvc":"data-sct-cluster-us-east1-b-us-east1-0","node":"gke-lon-scy-ope-3h-gke-j-default-pool-bfd54b3c-jdbr","_trace_id":"sxtTURPoT36C3Id1lVkPiQ"}
{"L":"DEBUG","T":"2020-12-23T10:53:39.624Z","N":"cluster-controller","M":"PVC attachment found","pvc":"data-sct-cluster-us-east1-b-us-east1-1","node":"gke-lon-scy-ope-3h-gke-j-default-pool-bfd54b3c-dn89","_trace_id":"sxtTURPoT36C3Id1lVkPiQ"}
{"L":"INFO","T":"2020-12-23T10:53:39.624Z","N":"cluster-controller","M":"Calculating cluster status...","cluster":"scylla/sct-cluster","resourceVersion":"21207","_trace_id":"sxtTURPoT36C3Id1lVkPiQ"}
{"L":"INFO","T":"2020-12-23T10:53:39.624Z","N":"cluster-controller","M":"Writing cluster status.","cluster":"scylla/sct-cluster","resourceVersion":"21207","_trace_id":"zT0y5cTyQ26-oOmPVwxVoA"}
{"L":"INFO","T":"2020-12-23T10:53:39.631Z","N":"cluster-controller","M":"Reconciliation successful","cluster":"scylla/sct-cluster","resourceVersion":"21207","_trace_id":"zT0y5cTyQ26-oOmPVwxVoA"}
```

events:
```
53m         Warning   Unhealthy                pod/sct-cluster-us-east1-b-us-east1-2         Readiness probe failed: Get http://10.142.0.90:8080/readyz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
47m         Warning   FailedMount              pod/sct-cluster-us-east1-b-us-east1-2         MountVolume.NewMounter initialization failed for volume "local-pv-821250a7" : path "/mnt/raid-disks/disk0" does not exist
47m         Warning   FailedToUpdateEndpoint   endpoints/sct-cluster-us-east1-b-us-east1-2   Failed to update endpoint scylla/sct-cluster-us-east1-b-us-east1-2: Operation cannot be fulfilled on endpoints "sct-cluster-us-east1-b-us-east1-2": the object has been modified; please apply your changes to the latest version and try again
47m         Normal    Scheduled                pod/sct-cluster-us-east1-b-us-east1-2         Successfully assigned scylla/sct-cluster-us-east1-b-us-east1-2 to gke-lon-scy-ope-3h-gke-j-default-pool-bfd54b3c-gbqq
47m         Warning   FailedMount              pod/sct-cluster-us-east1-b-us-east1-2         MountVolume.NewMounter initialization failed for volume "local-pv-821250a7" : path "/mnt/raid-disks/disk0" does not exist
46m         Normal    Pulling                  pod/sct-cluster-us-east1-b-us-east1-2         Pulling image "scylladb/scylla-operator:nightly"
46m         Normal    Pulled                   pod/sct-cluster-us-east1-b-us-east1-2         Successfully pulled image "scylladb/scylla-operator:nightly"
46m         Normal    Created                  pod/sct-cluster-us-east1-b-us-east1-2         Created container sidecar-injection
46m         Normal    Started                  pod/sct-cluster-us-east1-b-us-east1-2         Started container sidecar-injection
46m         Normal    Pulling                  pod/sct-cluster-us-east1-b-us-east1-2         Pulling image "busybox:1.31.1"
46m         Normal    Pulled                   pod/sct-cluster-us-east1-b-us-east1-2         Successfully pulled image "busybox:1.31.1"
46m         Normal    Created                  pod/sct-cluster-us-east1-b-us-east1-2         Created container sysctl-buddy
46m         Normal    Started                  pod/sct-cluster-us-east1-b-us-east1-2         Started container sysctl-buddy
46m         Normal    Pulling                  pod/sct-cluster-us-east1-b-us-east1-2         Pulling image "busybox:1.32.0"
46m         Normal    Pulled                   pod/sct-cluster-us-east1-b-us-east1-2         Successfully pulled image "busybox:1.32.0"
46m         Normal    Created                  pod/sct-cluster-us-east1-b-us-east1-2         Created container injected-busybox-sidecar
46m         Normal    Started                  pod/sct-cluster-us-east1-b-us-east1-2         Started container injected-busybox-sidecar
46m         Normal    Pulling                  pod/sct-cluster-us-east1-b-us-east1-2         Pulling image "scylladb/scylla:4.2.1"
46m         Normal    Pulled                   pod/sct-cluster-us-east1-b-us-east1-2         Successfully pulled image "scylladb/scylla:4.2.1"
46m         Normal    Created                  pod/sct-cluster-us-east1-b-us-east1-2         Created container scylla
46m         Normal    Started                  pod/sct-cluster-us-east1-b-us-east1-2         Started container scylla
46m         Normal    Pulling                  pod/sct-cluster-us-east1-b-us-east1-2         Pulling image "scylladb/scylla-manager-agent:2.2.0"
46m         Normal    Pulled                   pod/sct-cluster-us-east1-b-us-east1-2         Successfully pulled image "scylladb/scylla-manager-agent:2.2.0"
46m         Normal    Created                  pod/sct-cluster-us-east1-b-us-east1-2         Created container scylla-manager-agent
46m         Normal    Started                  pod/sct-cluster-us-east1-b-us-east1-2         Started container scylla-manager-agent
45m         Warning   Unhealthy                pod/sct-cluster-us-east1-b-us-east1-2         Readiness probe failed: Get http://10.142.0.81:8080/readyz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2m2s        Warning   Unhealthy                pod/sct-cluster-us-east1-b-us-east1-2         Readiness probe failed: HTTP probe failed with statuscode: 503
47m         Normal    SuccessfulCreate         statefulset/sct-cluster-us-east1-b-us-east1   create Pod sct-cluster-us-east1-b-us-east1-2 in StatefulSet sct-cluster-us-east1-b-us-east1 successful
0s          Warning   Unhealthy                pod/sct-cluster-us-east1-b-us-east1-2         Readiness probe failed: HTTP probe failed with statuscode: 503
```

node:
```
ERROR 2020-12-23 11:42:45,594 [shard 0] init - Startup failed: std::runtime_error (A node with address 10.115.246.5 already exists, cancelling join. Use replace_address if you want to replace this node.)
```

**Environment:**
 - Platform: GKE 
 - Kubernetes version: 1.15 
 - Scylla version: 4.2.0
 - Scylla-operator version: nigthly

**Comment by dkropachev** [comment]
From what I see node did not get it's replace_address option

**Comment by zimnx** [comment]
@dkropachev automaticOrphanedNodeCleanup works only when node is removed from k8s cluster. Instead draining, you should delete node using `kubectl delete node` and operator should find out. 

But clearly there's some bug with bootstraping. I tried several times to drain and uncordon node couple of times and Scylla boots up just fine.
Do you do something with a local drive before uncordon?

**Comment by dkropachev** [comment]
> @dkropachev automaticOrphanedNodeCleanup works only when node is removed from k8s cluster. Instead draining, you should delete node using `kubectl delete node` and operator should find out.
We have such test too, does it mean that we should remove drain + uncordon case from test plan ?

> But clearly there's some bug with bootstraping. I tried several times to drain and uncordon node couple of times and Scylla boots up just fine.

> Do you do something with a local drive before uncordon?
Nope, only drain + uncordon

**Comment by zimnx** [comment]
> We have such test too, does it mean that we should remove drain + uncordon case from test plan ?
> 
> >

It revealed this issue, so let's keep it.


I noticed these events around when pod is getting scheduled to uncordoned node:
```
47m         Normal    Scheduled                pod/sct-cluster-us-east1-b-us-east1-2         Successfully assigned scylla/sct-cluster-us-east1-b-us-east1-2 to gke-lon-scy-ope-3h-gke-j-default-pool-bfd54b3c-gbqq
47m         Warning   FailedMount              pod/sct-cluster-us-east1-b-us-east1-2         MountVolume.NewMounter initialization failed for volume "local-pv-821250a7" : path "/mnt/raid-disks/disk0" does not exist
```

so looks like you're loosing drive, which isn't the same when I'm manually trying to do the same. Maybe our setup is different. Are you using script from GKE example from repo?

**Comment by dkropachev** [comment]
> > We have such test too, does it mean that we should remove drain + uncordon case from test plan ?
> > >
> 
> It revealed this issue, so let's keep it.
> 
> I noticed these events around when pod is getting scheduled to uncordoned node:
> 
> ```
> 47m         Normal    Scheduled                pod/sct-cluster-us-east1-b-us-east1-2         Successfully assigned scylla/sct-cluster-us-east1-b-us-east1-2 to gke-lon-scy-ope-3h-gke-j-default-pool-bfd54b3c-gbqq
> 47m         Warning   FailedMount              pod/sct-cluster-us-east1-b-us-east1-2         MountVolume.NewMounter initialization failed for volume "local-pv-821250a7" : path "/mnt/raid-disks/disk0" does not exist
> ```
> 
> so looks like you're loosing drive, which isn't the same when I'm manually trying to do the same. Maybe our setup is different. Are you using script from GKE example from repo?

Depends on what script you are referring to.

**Comment by zimnx** [comment]
> Depends on what script you are referring to.

`examples/gke/gke.sh` I already checked and SCT use the same script, there're some minor differences like local-provisioner version. 

I tried with the same local-provisioner version and simillar setup 20 times and it didn't reproduce. 

I'll try to debug it live using Jenkins job.

**Comment by dkropachev** [comment]
Looks like latest changes fixed the problem, three last runs of recover job did not hit any s-o issue.
