### ISSUE TITLE
Doc: Master Branch is not older than 1.0

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-operator#333]
Our current logic is to mark every release which is not the stable as older, and add tjhe following warning to it:

> CAUTION
> You're reading an old version of this documentation. If you want up-to-date information, please have a look at v1.0 .

This is not true for Master, which should have the following:

> CAUTION
> You're reading an unstable this documentation. If you want up-to-date information, please have a look at v1.0 .

**Comment by tzach** [comment]
@dgarcia360 @lauranovich please comment

**Comment by lauranovich** [comment]
The latest version should be in a folder marked latest / stable something like that. this makes it easier to link from project to project.

**Comment by tzach** [comment]
@lauranovich latest stable is marked correctly - 1.0 in this case
The (minor) problem is Master, unlike other version is *ahead* or the official stable release not *behind* 
The make the warning in Master wrong
