### ISSUE TITLE
Set annotations with storageClass configuration

### ISSUE THREAD

**Issue by osaluden** [scylladb/scylla-operator#334]
Hi there

The K8S storageClass I use is configurable thank to annotations. The FS type or the encryption key ID for ex. are set thanks to annotation at  PersistentVolumeClaimSpec level.
In order to benefit from these settings, could it be possible to add annotations in the storageClass configuration section of the operator ?

Thanks in advance for you help.

**Comment by tnozicka** [comment]
already there https://operator.docs.scylladb.com/v1.12/api-reference/groups/scylla.scylladb.com/scyllaclusters.html#api-scylla-scylladb-com-scyllaclusters-v1-spec-datacenter-racks-storage-metadata
