### ISSUE TITLE
Scylla Monitoring 3.6 needs additional container and configuration

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-operator#339]
Scylla Monitoring now uses loki (with promtail) beside adding those containers need to configure:
1. promtail target point to loki
2. loki alert point to the alert manager
3. loki as a data source for grafana
4. loki as prometheus target
5. configure Scylla rsyslog to point to promtail

**Comment by tnozicka** [comment]
we are well beyond 3.6, but an update is tracked in https://github.com/scylladb/scylla-operator/issues/1505
