### ISSUE TITLE
Node replacement after GCE instance got terminated fails with 'Cannot replace_address x.x.x.x because it doesn't exist in gossip'

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#345]
**Describe the bug**
Node replacement after GCE instance got terminated fails with 'Cannot replace_address x.x.x.x because it doesn't exist in gossip'

**To Reproduce**
1. Deploy scylla-operator on GKE
2. Terminate one of the nodes via GCE API
3. Mark it to be replaced: `label svc {pod_service} scylla/replace="" --overwrite`
4. Wait till pod is up: `kubectl --namespace=scylla wait --timeout=10m --for=condition=Ready pod {pod_name}`
5. When it is failed take a look at logs: `kubectl logs -n scylla {pod_name}`

**Expected behavior**
Step N4 succeeded, pod is up and running

**Logs**

```
INFO  2021-01-26 10:50:51,120 [shard 0] init - Shutting down database: waiting for background jobs...
INFO  2021-01-26 10:50:51,120 [shard 0] init - Shutting down database was successful
INFO  2021-01-26 10:50:51,120 [shard 0] init - Shutting down migration manager notifier
INFO  2021-01-26 10:50:51,120 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2021-01-26 10:50:51,120 [shard 0] init - Shutting down prometheus API server
INFO  2021-01-26 10:50:51,121 [shard 0] init - Shutting down prometheus API server was successful
INFO  2021-01-26 10:50:51,121 [shard 0] init - Shutting down sighup
INFO  2021-01-26 10:50:51,121 [shard 0] init - Shutting down sighup was successful
ERROR 2021-01-26 10:50:51,121 [shard 0] init - Startup failed: std::runtime_error (Cannot replace_address 10.3.250.193 because it doesn't exist in gossip)
2021-01-26 10:50:51,170 INFO exited: scylla (exit status 1; not expected)
```

**Environment:**
 - Platform: GKE
 - Kubernetes version: 1.17.15-gke.800
 - Scylla version: 4.2.1-0.20201108.4fb8ebccff with build-id d19a95fd85a8e7df2928ccd8c729941f263e8adc
 - Scylla-operator version: nightly

**Comment by zimnx** [comment]
Please attach logs from operator and scyllas.

**Comment by dkropachev** [comment]
Logs:
db-cluster: https://cloudius-jenkins-test.s3.amazonaws.com/e7fdf661-d3fa-448c-8076-f623405fcf92/20210126_110415/db-cluster-e7fdf661.zip
monitor-set: https://cloudius-jenkins-test.s3.amazonaws.com/e7fdf661-d3fa-448c-8076-f623405fcf92/20210126_110415/monitor-set-e7fdf661.zip
loader-set: https://cloudius-jenkins-test.s3.amazonaws.com/e7fdf661-d3fa-448c-8076-f623405fcf92/20210126_110415/loader-set-e7fdf661.zip
kubernetes: https://cloudius-jenkins-test.s3.amazonaws.com/e7fdf661-d3fa-448c-8076-f623405fcf92/20210126_110415/kubernetes-e7fdf661.zip
sct-runner: https://cloudius-jenkins-test.s3.amazonaws.com/e7fdf661-d3fa-448c-8076-f623405fcf92/20210126_110415/sct-runner-e7fdf661.zip

**Comment by zimnx** [comment]
You're using automatic orphaned node cleanup and you're initiating a replacement via command line with --overwrite parameter.
This leads to following scenario:
1. Node is terminated
1. Operator detects that and starts replacing `10.3.254.211`
1. Pod doesn't exists, PVC and old service is removed
1. New pod and service `10.3.250.193` is created
1. Scylla starts joining the cluster with intent to replace `10.3.254.211`
1. Manual replacement is triggered with --overwrite flag
1. Operator find outs that `10.3.250.193` needs replacement
1. Pod, PVC and Service is deleted
1. New pod and service is created
1. Scylla starts joining the cluster with intent to replace `10.3.250.193`

It fails with above error because previous bootstrap did not finish, so address is not avaialble in gossip.

If you remove `--overwrite` flag from kubectl, this shouldn't happen because manual replacement wouldn't be scheduled until current one finishes.

Logs:
```
$ grep -E "(Adding member address to replace address list)|(Replace member Pod ready)|(Found orphaned)" scylla_operator.log
# First replacement
{"L":"DEBUG","T":"2021-01-26T10:03:33.051Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"28066","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.252.109","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.252.109"},"_trace_id":"txmuGWNsTjuDcZPYzDndxQ"}
{"L":"DEBUG","T":"2021-01-26T10:03:34.075Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"28230","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.252.109","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.252.109"},"_trace_id":"K52zox-GRkKrxL4MQoTnyA"}
# Finished
{"L":"INFO","T":"2021-01-26T10:09:30.292Z","N":"cluster-controller.replace","M":"Replace member Pod ready, removing replace label","cluster":"scylla/sct-cluster","resourceVersion":"28271","member":"sct-cluster-us-east1-b-us-east1-2","replace_address":"10.3.252.109","_trace_id":"ze2-ZcB8RUySapYguzZqXQ"}

# Automatic replacement
{"L":"INFO","T":"2021-01-26T10:12:50.371Z","N":"cluster-controller","M":"Found orphaned PVC, triggering replace node","member":"sct-cluster-us-east1-b-us-east1-2","_trace_id":"K09-q5Z3TseBaWdZ9REtag"}
{"L":"DEBUG","T":"2021-01-26T10:12:50.385Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"31567","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.254.211","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.254.211"},"_trace_id":"K09-q5Z3TseBaWdZ9REtag"}
{"L":"INFO","T":"2021-01-26T10:12:50.481Z","N":"cluster-controller","M":"Found orphaned PVC, triggering replace node","member":"sct-cluster-us-east1-b-us-east1-2","_trace_id":"-EnpIp3fQx6ekZoZhmqfhA"}
{"L":"DEBUG","T":"2021-01-26T10:12:50.482Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"32460","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.254.211","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.254.211"},"_trace_id":"-EnpIp3fQx6ekZoZhmqfhA"}
{"L":"INFO","T":"2021-01-26T10:12:50.621Z","N":"cluster-controller","M":"Found orphaned PVC, triggering replace node","member":"sct-cluster-us-east1-b-us-east1-2","_trace_id":"nPuNdFMzT-CO_SlnpkPOUA"}
{"L":"DEBUG","T":"2021-01-26T10:12:50.622Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"32460","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.254.211","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.254.211"},"_trace_id":"nPuNdFMzT-CO_SlnpkPOUA"}
# It didn't finished (lack of log message) but new one is triggered
{"L":"DEBUG","T":"2021-01-26T10:13:09.534Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"32518","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.250.193","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.250.193"},"_trace_id":"vknRfjhrSJe3o6nN9G_1sw"}


```

**Comment by dkropachev** [comment]
> You're using automatic orphaned node cleanup and you're initiating a replacement via command line with --overwrite parameter.
> This leads to following scenario:
> 
> 1. Node is terminated
> 2. Operator detects that and starts replacing `10.3.254.211`
> 3. Pod doesn't exists, PVC and old service is removed
> 4. New pod and service `10.3.250.193` is created
> 5. Scylla starts joining the cluster with intent to replace `10.3.254.211`
> 6. Manual replacement is triggered with --overwrite flag
> 7. Operator find outs that `10.3.250.193` needs replacement
> 8. Pod, PVC and Service is deleted
> 9. New pod and service is created
> 10. Scylla starts joining the cluster with intent to replace `10.3.250.193`
> 
> It fails with above error because previous bootstrap did not finish, so address is not avaialble in gossip.
> 
> If you remove `--overwrite` flag from kubectl, this shouldn't happen because manual replacement wouldn't be scheduled until current one finishes.
> 
> Logs:
> 
> ```
> $ grep -E "(Adding member address to replace address list)|(Replace member Pod ready)|(Found orphaned)" scylla_operator.log
> # First replacement
> {"L":"DEBUG","T":"2021-01-26T10:03:33.051Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"28066","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.252.109","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.252.109"},"_trace_id":"txmuGWNsTjuDcZPYzDndxQ"}
> {"L":"DEBUG","T":"2021-01-26T10:03:34.075Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"28230","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.252.109","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.252.109"},"_trace_id":"K52zox-GRkKrxL4MQoTnyA"}
> # Finished
> {"L":"INFO","T":"2021-01-26T10:09:30.292Z","N":"cluster-controller.replace","M":"Replace member Pod ready, removing replace label","cluster":"scylla/sct-cluster","resourceVersion":"28271","member":"sct-cluster-us-east1-b-us-east1-2","replace_address":"10.3.252.109","_trace_id":"ze2-ZcB8RUySapYguzZqXQ"}
> 
> # Automatic replacement
> {"L":"INFO","T":"2021-01-26T10:12:50.371Z","N":"cluster-controller","M":"Found orphaned PVC, triggering replace node","member":"sct-cluster-us-east1-b-us-east1-2","_trace_id":"K09-q5Z3TseBaWdZ9REtag"}
> {"L":"DEBUG","T":"2021-01-26T10:12:50.385Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"31567","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.254.211","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.254.211"},"_trace_id":"K09-q5Z3TseBaWdZ9REtag"}
> {"L":"INFO","T":"2021-01-26T10:12:50.481Z","N":"cluster-controller","M":"Found orphaned PVC, triggering replace node","member":"sct-cluster-us-east1-b-us-east1-2","_trace_id":"-EnpIp3fQx6ekZoZhmqfhA"}
> {"L":"DEBUG","T":"2021-01-26T10:12:50.482Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"32460","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.254.211","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.254.211"},"_trace_id":"-EnpIp3fQx6ekZoZhmqfhA"}
> {"L":"INFO","T":"2021-01-26T10:12:50.621Z","N":"cluster-controller","M":"Found orphaned PVC, triggering replace node","member":"sct-cluster-us-east1-b-us-east1-2","_trace_id":"nPuNdFMzT-CO_SlnpkPOUA"}
> {"L":"DEBUG","T":"2021-01-26T10:12:50.622Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"32460","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.254.211","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.254.211"},"_trace_id":"nPuNdFMzT-CO_SlnpkPOUA"}
> # Still in progress (lack of log message about finish) but new one is triggered
> {"L":"DEBUG","T":"2021-01-26T10:13:09.534Z","N":"cluster-controller.replace","M":"Adding member address to replace address list","cluster":"scylla/sct-cluster","resourceVersion":"32518","member":"sct-cluster-us-east1-b-us-east1-2","ip":"10.3.250.193","replace_addresses":{"sct-cluster-us-east1-b-us-east1-2":"10.3.250.193"},"_trace_id":"vknRfjhrSJe3o6nN9G_1sw"}
> ```

@mmatczuk, thanks, I will apply it for sct, but should we just work this case around, or we should cover it in scylla-operator ?

**Comment by zimnx** [comment]
In my opinion we shouldn't complicate it. `--overwrite` is basically a force mechanism which could be useful in some recovery cases. 

@tzach any input?

**Comment by zimnx** [comment]
Although we could make Operator smarter and reject replace requests if address is not part of gossip. I think this info is avaiable via API.

**Comment by dkropachev** [comment]
> In my opinion we shouldn't complicate it. `--overwrite` is basically a force mechanism which could be useful in some recovery cases.
> 
> @tzach any input?

My concern is not about this particular case, there are many ways we can drive pod to exact same state.
