### ISSUE TITLE
docs: stable redirection broke branch links

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#350]
Links which were used in Release Notes, and other user facing communication doesn't work after #342 

These two should be redirected to the same content (at this moment), but first one returns 404
https://operator.docs.scylladb.com/v1.0/migration.html
https://operator.docs.scylladb.com/stable/migration.html

We cannot use `stable` links in release notes, because once tag is changed, old release notes will use new documentation page.

**Comment by zimnx** [comment]
@dgarcia360

**Comment by zimnx** [comment]
I reverted #342, please resend patch once this issue is solved.

**Comment by zimnx** [comment]
Note: Because live version already has revert of #342, situation from issue description is opposite. But with #342 v1.0 leads to 404, stable leads to v1.0 documentation.

**Comment by dgarcia360** [comment]
Thanks @zimnx , I've updated the ``sphinx-multiversion``.
I've submitted again the same PR: https://github.com/scylladb/scylla-operator/pull/353
