### ISSUE TITLE
Liveness probes failing for scylla operator statefulset

### ISSUE THREAD

**Issue by eljoth** [scylladb/scylla-operator#354]
**Describe the bug**
Installing the scylla operator via helm, the operator itself seems to be starting but the liveness and readyness probe fail with status 404

**To Reproduce**
1. Install the operator via helm
2. Wait for the pod to get ready
3. See error

**Expected behavior**
I expected the pod to become alive.

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.
```
 {"L":"INFO","T":"2021-01-30T15:59:59.248Z","M":"Operator started","version":"","build_date":"","commit":"","built_by":"","go_version":"","options":{"Name":"operator-scylla-operator-0","Namespace":"operator","LogLevel":"debug","Image":"","EnableAdmissionWebhook":true},"_trace_id":"taMaFImHSn-J_UbRdWVyhw"}
 {"L":"INFO","T":"2021-01-30T16:00:00.002Z","M":"Registering Components.","_trace_id":"taMaFImHSn-J_UbRdWVyhw"}
 {"L":"INFO","T":"2021-01-30T16:00:00.711Z","M":"Starting the operator...","_trace_id":"yWVbm3uRSFyFbZS5tIktVw"}
```
![grafik](https://user-images.githubusercontent.com/21229601/106361215-0a1ff500-631d-11eb-955f-6296d9961a2b.png)

**Environment:**
 - Kind
 - Kubernetes version: 1.18.8
 - Scylla version: not yet installed, same version as in helm chart.
 - Scylla-operator version: v1.0.0 (Helm)

**Additional context**
- cert-manager-controller:v1.1.0
- cert-manager-cainjector:v1.1.0
- cert-manager-webhook:v1.1.0

First I tried installing via the pulumi helm integration, then I just installed via helm without pulumi. In both cases this is happening

**Comment by eljoth** [comment]
I further tried deploying the helm chart and noticed, that using the nightly tag for the controller just works.

**Comment by zimnx** [comment]
@eljoth Looks like you're using master Helm chart with 1.0.0 image which doesn't support new liveness/readyness probes. Indeed you should use nightly image until new release is out.

**Comment by eljoth** [comment]
@zimnx okay, many thanks. Then I will close this ticket
