### ISSUE TITLE
Specific release name breaks manager helm chart

### ISSUE THREAD

**Issue by eljoth** [scylladb/scylla-operator#363]
**Describe the bug**
Releasing the manager Helm Chart with specific Releasename breaks consistency of the helm chart:

```sh
helm install scylla-manager-ch scylla-operator/scylla-manager --create-namespace --namespace infra-scylla-manager
```

What happens:
The Scylla Rack's service is then named "scylla-manager-ch-manager-dc-manager-rack-0.infra-scylla-manager.svc"
but the config for the manager points to "scylla-manager-ch-scylla-manager-dc-manager-rack-0.infra-scylla-manager.svc"

**To Reproduce**
1. Install cert-manager
2. Install operator
2. Install manager with release name as shown above
3. Compare rack service name and manager-config

**Expected behavior**
Release naming should not affect behavior of the chart itself in this case.

**Environment:**
 - Platform: Kind
 - Kubernetes version: v1.18.8
 - Scylla version: 4.3.0
 - Scylla-operator version: master

**Additional context**
Release names I've tried:
- scylla //works
- manager-ch //works
- scylla-manager-ch //does not work

**Comment by zimnx** [comment]
Should be fixed by https://github.com/scylladb/scylla-operator/pull/358 i just merged.

**Comment by eljoth** [comment]
Looks good, many thanks !

**Comment by eljoth** [comment]
It is now the other way round:

![grafik](https://user-images.githubusercontent.com/21229601/108167470-06021e80-70f6-11eb-8e96-07668eb2abe7.png)

![grafik](https://user-images.githubusercontent.com/21229601/108167445-fbe02000-70f5-11eb-8d6a-846572565a29.png)

![grafik](https://user-images.githubusercontent.com/21229601/108167403-ee2a9a80-70f5-11eb-81c6-543d0f0af605.png)

For the manager there are no values set.
