### ISSUE TITLE
AWS IRSA for Scylla manager agent to access S3 for backups

### ISSUE THREAD

**Issue by pavankumar-go** [scylladb/scylla-operator#367]
Is it possible to use [AWS IRSA ](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/)  for Scylla Manger Agent to access S3 instead of aws access and secret keys ?

**Comment by jwsomis** [comment]
@pavankumar-go  Why was this closed? I'm currently running into this and the scylla-manager-agent ignores the serviceAccount role and uses the hostnodes role instead. That is less than ideal.
