### ISSUE TITLE
Wrong resource reservation logic

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#384]
**Describe the bug**
scylla-operator exposes resource reservation options at racks[n].resources
Currently these options are passed without changes on scylla container

At the same time scylla-operator deploys two more containers with following resources:
        cpu: "1"
        memory: 200M

Result of this is that if you want to have scylla scheduled with maximum possible resources you need to go to the node status, get cpu and memory units from there, than  you need to go deploy scylla-operator, deploy scylla cluster, look at how much cpu and memory reserved for sidecars, sum them up and reduce node values by values you got in pod.

It produces bad user experience and also creates a possibility of having non-schedulable pods after scylla-operator upgrade if by any reason resources needed for sidecars are increased.

**Comment by tnozicka** [comment]
there are now dedicated resources for the manager and some are fixed
