### ISSUE TITLE
Change how we load scylla-monitoring dashboards

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#40]
We have thus far used the script `load-grafana.sh` that is part of the scylla-monitoring distribution.
This is no longer the preferred way but to load the files from a directory.
That means we can mount the files in the relevant pod and have the dashboards be loaded from there.

**Comment by amnonh** [comment]
when loading the grafana dashboard from a file, there is a loader file that we create based on the current version that is being used.
the dashboard themselves are pre-created in the repository.

**Comment by dahankzter** [comment]
So how can we create this file @amnonh? Is there a standalone script at the ready for this?

**Comment by dahankzter** [comment]
When I load the dashboards using the load script @amnonh it seems to only load Scylla 3.0 version and Manager 1.3.

**Comment by dahankzter** [comment]
I guess this comes from `versions.sh` which seems to match with:
```sh
LATEST="3.0"
ALL="2.1,2.2,2.3,master"
DEFAULT_VERSION="3.0,2.3"
MANAGER_VERSION="1.3"
```
