### ISSUE TITLE
IOTune propagation

### ISSUE THREAD

**Issue by ezbz** [scylladb/scylla-operator#401]
Take iotune results from one node and inject it to the other nodes

**Comment by tzach** [comment]
@ezbz is it done? please add relevant commit

**Comment by ezbz** [comment]
duplicate of #146

**Comment by LeifW** [comment]
#146 doesn't seem to mention anything about "Take iotune results from one node and inject it to the other nodes", but rather, re-using an existing iotune result on the same box on reboots?

**Comment by zimnx** [comment]
Other nodes might have different hardware so copying it from other isn't a good idea. Operator now caches result in Scylla data directory (on volume where iotune was run) and reuses it after restarts.

If you have uniform hardware in each rack, you can mount your precomputed io_properties.yaml using Volume and VolumeMounts fileds in rack spec. IOTune is skipped if this file is present in right location.
