### ISSUE TITLE
Package up a helm chart

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#42]
We should be able to create a general helm chart from the examples we have. This chart needs parametrization for resources and perhaps a switch for enabling monitoring.

**Comment by dahankzter** [comment]
Do we really need this? For example Istio uses an operator without Helm, just clone the repo and apply the files https://banzaicloud.com/blog/istio-operator/ .

**Comment by kfox1111** [comment]
Yes, this is needed. Some of us deploy everything in their cluster with helm to make configuration and upgrades easier. Its rare that we hit a static manifest that works unchanged. Often you need to mirror a container to your own repo and at minimum update the image fields in the manifests. Doing so with helm is very easy for end users to manage.

**Comment by dahankzter** [comment]
Thanks for this feedback @kfox1111 and it makes good sense.

**Comment by Hashfyre** [comment]
Hey folks if you need help with this, I can take this issue up and package up a chart.

**Comment by zimnx** [comment]
@Hashfyre any contributions are much appreciated :+1:

**Comment by marazt** [comment]
Hi, we are in the same situation right now. Please, is there any progress/branch with it? @Hashfyre . Thanks a lot :).

**Comment by markallanson** [comment]
We would really appreciate a helm chart too!  The one in the sample code is inadequate as it is, and it would be great to have an official one that packages up all the best practices for running scylla nodes in kube.
