### ISSUE TITLE
Expose Scylla Cluster for Clients Residing Outside Kubernetes Cluster

### ISSUE THREAD

**Issue by ezbz** [scylladb/scylla-operator#423]
There are at least two relevant types of use cases:

- A simple CQLSH session connecting to any node (can expose any one node)
- A service client performing read/write workloads (need persistent addresses for all nodes for load balancing and shard awareness)

**Comment by tnozicka** [comment]
already done https://operator.docs.scylladb.com/v1.13/exposing.html
