### ISSUE TITLE
[helm charts] There is no way to match published helm charts and the repo tag/commit appropriate for it

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#433]
**Describe the bug**
Not having direct reference to the "scylla-operator" repo state in it's charts info we cannot correctly indentify it
to be able to pick up appropriate "examples" files such as "monitoring" ones.
So, for the moment, end user must guess the proper repo state to pick the "monitoring or other examples" files up.

Use case:
1) QA team going to test installation of scylla operator and monitoring for it.
2) "monitoring" files specific for the "scylla-operator" are located in the "examples/common/monitoring" directory
of the "scylla-operator" Github repo.
3) QA team picks up any of the published charts and have no "monitoring" files there as well as proper reference to it.

**To Reproduce**
1. Install "scylla-operator" and "scylla-manager" charts
2. Look at it's info

**Expected behavior**
In the chart info we can see the "scylla-operator" commit/tag used for it.

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.

**Environment:**
 - Platform: (GKE, Azure, minikube, custom...) 
 - Kubernetes version: 
 - Scylla version:
 - Scylla-operator version: e.g.: master, 8e155d0...

**Additional context**

**Comment by zimnx** [comment]
As disscussed offline, charts version contain a commit hash from which it was build in git describe format.
