### ISSUE TITLE
Add a demo for EKS (AWS)

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-operator#44]
* Feature Request

**What should the feature do:**
We already have a demo for GKE and the community loves it. 
**What is use case behind this feature:**
Talking to members of the community there is a lot of interest in using the operator on AWS so we should try ourselves and see if it works flawlessly and maybe add some best practices just like we did for GKE.

**Comment by tzach** [comment]
@dahankzter lets push this to 1.x

**Comment by dahankzter** [comment]
This would essentially be another docs file with specific commands for EKS and (optionally?) a complete example like we have for GKE.

**Comment by mutabletao** [comment]
Looking forward to seeing these example files and testing them.
