### ISSUE TITLE
Automatic cleanup and replacement in case when k8s node is lost does not work

### ISSUE THREAD

**Issue by munjalpatel** [scylladb/scylla-operator#446]
A few hours ago one of my AKS node went down and then a new node was added to the cluster by autoscaler.

However, the old node was hosting one of `Scylla` node: `c001-seattle-z1-0` out of 3.
Old node was also hosting `scylla-manager-cluster-manager-dc-manager-rack-0`
Note that the `management-cluster` is currently configured to have only 1 node.

Now, `c001-seattle-z1-0` is failing from starting up properly with an error:
```json
{
  "L": "INFO",
  "T": "2021-02-28T16:19:34.673Z",
  "N": "member_controller.scylla_client",
  "M": "HTTP retry backoff",
  "operation": "StorageServiceHostIdGet",
  "wait": "28.805187806s",
  "error": "dial tcp 10.10.33.144:10001: connect: connection refused"
}
```

**Comment by tnozicka** [comment]
Closing as stale and and AKS is not supported yet.
