### ISSUE TITLE
Automatic "cleanup" after scale up

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#46]
After scaling up a cluster it is prudent to run a cleanup which now isn't possible.

**Comment by dahankzter** [comment]
Perhaps this is a job for Scylla Manager instead?

**Comment by mykaul** [comment]
@tnozicka this has to be prioritized. Need to run cleanup after every node addition. You could delay it a bit, but you must not scale down and certainly hope you do not run out of disk before running cleanup.

**Comment by mykaul** [comment]
> you are right, but we need it planned as the bigger "scaling audit" and follow with a revised design. At this point we take the snapshot and next operation is allowed when all nodes become ready/available (which just check native transport and decommissioning). We either need an extra probe or state machine around it, that we don't have at this point.

Agreed.

> 
> Somehow feels like this could be automated in Scylla core who knows best about taken ranges and which parts need cleanup then an external component that has to build a state machine and deal with complex corner cases when one shot commands fail in the middle (in the better case they are reentrant). But yeah, we need to do the audit first and look for the best path forward.

Yes, and that's the long term plan. But for the time being, we need to work on ensuring we follow the correct procedure for node operations (add, replace, rebuild, remove). Hopefully, via direct calls to the REST API and not via nodetool...
