### ISSUE TITLE
Make sure helm charts don't get out of sync with our deployment manifests

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#482]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Make sure helm charts don't get out of sync with our deployment manifests. Like https://github.com/scylladb/scylla-operator/pull/480

**What is use case behind this feature:**
When editing manifests it's easy to overlook a change that wasn't reflected in helm manifests.

**Additional Information:**
As the helm manifests are templated we can't easily use the same source. We can create a verify/update job to keep the diff between a regular and helm manifest committed as generated file. When changing a manifest without a corresponding helm edit, or the other way around, verify won't pass until both manifests are properly edited or the diff is updated.

**Comment by zimnx** [comment]
The other solution is to generate static files from helm chart templates and default values.
