### ISSUE TITLE
Linkerd sidecars fails due to invalid resolv.conf on generated pods

### ISSUE THREAD

**Issue by flotothemoon** [scylladb/scylla-operator#484]
**Describe the bug**
When applying linkerd service mesh to pods generated with this operator, the linkerd sidecars error during startup because of an invalid resolv.conf file. This also causes Scylla manager to fail (since it relies on a Scylla cluster). This may be due to a conflict in sidecar injection between Scylla operator and Linkerd. This might be a variant/regression of a bug that was reported and fixed earlier (#176 Pods generated by the Scylla operator cause runtime errors in linkerd sidecars). 

**To Reproduce**
The steps to me are identical to that in the referenced issue - simply use `linkerd inject` (or manually annotate generated pods with `linkerd.io/inject: enabled`). See the referenced issue #176.

**Expected behavior**
Linkerd should operate transparently, meshing the Scylla generated pods without any errors.

**Config Files**
- 

**Logs**
```
time="2021-03-10T11:05:47Z" level=info msg="running version stable-2.9.4"
time="2021-03-10T11:05:47Z" level=info msg="Found pre-existing key: /var/run/linkerd/identity/end-entity/key.p8"
time="2021-03-10T11:05:47Z" level=info msg="Found pre-existing CSR: /var/run/linkerd/identity/end-entity/csr.der"
[     0.000824s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
thread 'main' panicked at 'system DNS config must be valid: ResolveError { kind: Io(Custom { kind: Other, error: "Error parsing resolv.conf: InvalidOption(1)" }), backtrack: None }', linkerd/app/core/src/dns.rs:21:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Environment:**
 - Platform: minikube
 - Kubernetes version: 1.20 
 - Scylla version: 4.2.0
 - Scylla-operator version: master

**Additional context**
-

**Comment by flotothemoon** [comment]
@tzach sorry to ping directly, looking to get this resolved or move on. Is this an issue with Scylla, the operator or some other setup? Any ideas for a workaround if there is no easy fix in sight?

**Comment by tnozicka** [comment]
> error during startup because of an invalid resolv.conf file

Can you exec into the sidecar that is failing and attach the invalid resolv.conf? Also possibly some other random pod that is working to have a baseline and see the diff.

Also `kubectl get scyllaclusters,statefulsets,controllerrevissions,pods,services,configmaps -o yaml` from the namespace where it is failing. Thanks.

**Comment by tnozicka** [comment]
Also on the node where this pod landed, what's the /etc/resolv.conf there?

**Comment by tnozicka** [comment]
If it's the DNSPolicy defaulting issue (https://github.com/scylladb/scylla-operator/pull/512), you should be able to workaround it with setting explicit DNSPolicy to `ClusterFirstWithHostNet` (or `ClusterFirst` but the first one works for both).

**Comment by flotothemoon** [comment]
Setting `dnsPolicy: ClusterFirstWithHostNet` in `Network` in my `ScyllaCluster` definition indeed solved the issue, so I'm happy to close this issue as this workaround is good enough for me. 

For reference, this is the `resolv.conf` that works with Linkerd (the one you get when `dnsPolicy` is `ClusterFirst*`):
```
nameserver 10.96.0.10
search scylla.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

And this is what it looks like without, which `linkerd-proxy` errors on:
```
nameserver 192.168.49.1
options edns0 trust-ad ndots:0
```

**Comment by flotothemoon** [comment]
Unfortunately, it seems this doesn't completely fix the issue after all. 
While all seems green according to linkerd, my clients are unable to actually connect to the Scylla cluster now.
I'm getting `Connection refused` errors on the `linkerd-proxy` sidecar on my Scylla pods:
```
[   110.495467s]  INFO ThreadId(01) inbound:accept{peer.addr=172.17.0.34:44396 target.addr=172.17.0.15:9042}: linkerd2_app_core::serve: Connection closed error=Connection refused (os error 111)
```
but the service is started up and `172.17.0.15:9042` is open, ready and healthy according to linkerd & prometheus. 

It's possible I'm doing something else wrong that's got nothing to do with the Scylla operator, but I have no clue what that might be and the other non-Scylla operated components are connecting fine.

**Comment by loopingrage** [comment]
@flotothemoon, I'm running into a similar issue truing to get envoy/istio working. I think the issue has to do with the `listen_address` being set on each Scylla member by the operator.

Sidecars like linkerd work by communicating with other containers in the pod (e.g. scylla) via the loopback interface (127.0.0.1). However, Scylla Operator is setting the `listen_address` to the pod's cluster IP. This prevents linkerd from communicating with Scylla since it's not even listening on 127.0.0.1.

I found this great blog post that [explains the procedure to fix it](https://aspenmesh.io/running-stateless-apps-with-service-mesh-kubernetes-cassandra-with-istio-mtls-enabled/). Unfortunately, there doesn't seem to be a way to override the listen_address set by Scylla Operator via config because the command line switch being used takes precedence:

> /usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-7 --smp 6 --listen-address 10.244.9.12 --rpc-address 10.244.9.12 --seed-provider-parameters seeds=10.10.100.112,10.10.31.171 --broadcast-address 10.10.100.112 --broadcast-rpc-address 10.10.100.112 --blocked-reactor-notify-ms 999999999

@tnozicka any suggestions would be super since this is blocking us from going into production with our cluster.

**Comment by tnozicka** [comment]
I'll see if we can just bind to 0.0.0.0 by default and get back to you.

**Comment by tnozicka** [comment]
We are discussing the config options with scylla engineering but I think #529 might be it. If you want to try a cutting edge image from the PR level it can be downloaded on https://github.com/scylladb/scylla-operator/suites/2367615878/artifacts/50169805 
Don't use it anywhere else then on a toy cluster that you wouldn't mind throwing away.

**Comment by loopingrage** [comment]
Thanks. I'll give it a go. Any clue when to expect 1.2 to be released?

**Comment by tnozicka** [comment]
nothing is set in stone but the rough schedule is here https://operator.docs.scylladb.com/master/releases.html#schedule
