### ISSUE TITLE
scylla-manager chart applies affinity, tolerations and nodeSelector rules only to 1 of 3 pods it deploys

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#496]
**Describe the bug**
Deploying "scylla-manager" chart providing "nodeSelector", "tolerations" and "affinity" rules user expects that it will be applied for every pod this chart deploys.
In fact, these rules get applied only to  "scylla-manager" pod, but "scylla" and "scylla-manager-controller" get created anywhere.

It is sensitive bug just because "scylla" pod requires pretty big resources "1 CPU" and "4Gb mem"

**To Reproduce**
1. Deploy scylla-operator chart
2. Deploy scylla-manager chart specifying affinity rules
3. See that 2 from 3 pods  may get scheduled anywhere

**Expected behavior**
"nodeSelector", "tolerations" and "affinity" rules gets applied to all 3 pods.

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.

**Environment:**
 - Platform: GKE (tested here, affected any)
 - Kubernetes version: v1.17.15-gke.800
 - Scylla version: 4.2.0
 - Scylla-operator version: v1.1.0-rc.4-1-g83412a8

**Additional context**

**Comment by zimnx** [comment]
Just to make it straight, `scylla-manager` chart deploys three pods:

1. Scylla Manager
1. Scylla
1. Scylla Manager Controller

Scylla Manager placement can be configured using exsiting `nodeSelector`, `tolerations` and `affinity`.
To set up placement for Scylla you have to overwrite default definition by provioding your own values.yaml. Check out the defaults we provide: https://github.com/scylladb/scylla-operator/blob/abd76ee6ff057ad429e4d5e1a5d1d604b392e6d1/helm/scylla-manager/values.yaml#L55
We are missing parameters to control Scylla Manager Controller, so this should be added as a part of this issue.

**Comment by zimnx** [comment]
Closed by https://github.com/scylladb/scylla-operator/pull/572

**Comment by vponomaryov** [comment]
Related issue for scylla pod part: https://github.com/scylladb/scylla-operator/issues/631
