### ISSUE TITLE
scylla-manager integration

### ISSUE THREAD

**Issue by jwnx** [scylladb/scylla-operator#5]
Scylla Manager has many nice features that help us handle Scylla clusters, such as repairs and backup/restore. Would be nice to have the option to deploy it alongside the Operator.

**Possible solution**
Once dockerized, Scylla Manager can be deployed as an outside service that is able to communicate with the cluster. Its key-pair can be generated as a secret upon cluster creation. 

**Other Alternatives**
??

**Additional context**
This feature depends on scylla-manager working on docker.

**Comment by dorlaor** [comment]
How will the manager connect to the k8s cluster? Through the seed IPs?
Normally it generates ssh keys for the nodes. Same in this case?

**Comment by yanniszark** [comment]
Having read the [scylla manager setup](https://docs.scylladb.com/operating-scylla/manager/1.3/add-a-cluster/) guide, let me share some thoughts:
* The Manager can use the A Records from the  [Headless Service](https://www.cyberciti.biz/faq/howto-linux-unix-setup-nginx-ssl-proxy/) the operator deploys for each cluster, which [correspond to healthy Scylla instances](https://github.com/scylladb/scylla-operator/blob/f080f7d888c57736c097623b7cb1b7de9ecd26ac/docs/quickstart.md#accessing-the-database). Then it should discover the rest of the cluster by querying for the cluster state.
* We should decide what the deployment model is. Should we deploy a manager per Scylla Cluster or just one for all of them? In the second case, we either need something to watch for new Scylla Clusters and add them to the Manager or a way to explicitly add them.
* It seems that currently, Scylla Manager works only by SSH'ing into a user in each Member and executing commands. We could make it work for Kubernetes by setting up an SSH server with keypair on each Member on startup. However, the operator will also need to use administrative commands to remote Members and it would be nice if we could just secure the REST API and use that for everything. Currently, the Scylla REST API cannot be secured with a client certificate. Maybe we could use something like NGINX for SSL termination.

**Comment by dorlaor** [comment]
@mmatczuk should respond to it.
In general, a single manager should control multiple Scylla clusters.
We rather minimize the manager changes for k8s and in general minimize work related to it until we get the other  high priority tasks for k8s/operator completed first. Agree there is plenty of room for improvement

**Comment by mmatczuk** [comment]
Scylla Manager 1.3.x (up to date) does NOT require SSH. In such case the requirement is that API port is available on the node's broadcast address. This will change in 1.4 because we would need to execute commands on the nodes. Not sure yet if ssh will become a requirement or requirement for some functions, but it seems that option 1 is better.

At Scylla Manager, for testing, we have a docker image of Scylla supplemented by sshd, this could be an option too.

**Comment by jwnx** [comment]
@mmatczuk yes, it doesn't require, but we need API encryption in order to expose it. Do you have any info on that?

@yanniszark 
- The manager is able to discover the cluster through an add cluster procedure. This is fairly easy to do, given that we use a StatefulSet with predictable DNS records. We can run a simple script for each new cluster and GG.
- We should deploy one scylla-manager per operator and let scylla-manager handle cluster and node info. Its easier (: 
- As written before, scylla-manager works using the API. The problem is: we need encryption to secure the API connection. One thing that came to mind is: we can selectively enable port/service access on Kubernetes through annotations (I remember doing something like this on a very old Redis deployment. Don't ask). Is it possible to do this using the Operator? If it is, we can annotate which clusters we want to communicate with scylla-manager and scylla-manager can access their API ports.

**Comment by jwnx** [comment]
@mmatczuk Yep, that was my first thought as well. Setting up a SSH key-pair is not very hard on Kubernetes, albeit not pretty. Please do send! (:

**Comment by jwnx** [comment]
> @mmatczuk It should be easy enough to add sshd. However, we should also change the open-source official docker images, as scylla manager is supposed to soon be available for small open source clusters.
> 
> To add a cluster, you just run a `sctool` command. (the ssh setup will be done on each member's startup)
> There are two ways to go about this:
> 
>     1. Have a process watch the Kubernetes API and run sctool for new clusters. This process should be in the manager pod, otherwise sctool has to be secured.

This one sounds better.

> 
>     2. Add an option for scylla manager to use a config file. We can make that config file be a ConfigMap in Kubernetes. The operator will update it with new clusters and the changes will be propagated to the file. This requires scylla manager to check the config file periodically for changes or to restart scylla manager for each new cluster added. Btw, I assume that when a cluster is added with sctool, it is persisted in the manager's database.
> 
> 
> Also, we haven't discussed about where the manager will store its data.

Scylla-manager stores data on scylla. We can have a small cluster for it.

> Reliability seems to be the main focus here, so I propose using a standalone scylla instance with networked, replicated storage (eg EBS, GPD)

**Comment by yanniszark** [comment]
This is an overview of the solution I'm proposing. Once we agree, we should write a more formal design doc about it. 

```
         +--------------------------+
       +--------------------------+ |
       |                          | |
       |    Cluster Instances     | |
       |                          | |
       |                          | +
       +------------^-------------+
                    |
                    |watch
                    |
+---------------------------------------+
|                   |                   |
|                   |                   |
|    +-----------------------------+    |
|    |              |              |    |
|    |    +---------+----------+   |    |
|    |    |Watch & Add Clusters|   |    |
|    |    +---------+----------+   |    |
|    |              |              |    |
|    |              |sctool        |    |
|    |              |              |    |
|    |    +---------v----------+   |    |
|    |    |   Scylla Manager   |   |    |
|    |    +--------------------+   |    |
|    |                   Container |    |
|    +-----------------------------+    |
|                                       |
|                                 Pod   |
+---------------------------------------+

```

The solution is comprised of a Scylla Manager Pod, with only 1 container, containing two processes:
1. Scylla Manager
2. A small controller that will watch the Kubernetes API for Scylla Cluster Custom Resources and for each one it finds, it will add it to the manager via sctool.

The small controller binary will be injected into the Scylla Manager container via an initContainer.
It will also be used for the health check of the Pod, so that if the controller or Scylla Manager fails, the Pod is restarted. 

An alternative would be to have them in separate containers and provide the controller with the sctool binary via a shared volume.

Some other remarks:
* The `sctool cluster add` command should be idempotent, or a way must be provided to check if a cluster is already managed by Scylla Manager. 
* The user scylla manager will use / ssh keys will be setup on each Scylla Pod's startup. The SSH keypair will be generated by the operator and stored in a Secret when creating a Scylla Cluster for the first time.
* The small controller binary that adds clusters to Scylla Manager will retrieve the SSH keys by getting the aforementioned Secret from the Kubernetes API.

**Comment by jwnx** [comment]
> This is an overview of the solution I'm proposing. Once we agree, we should write a more formal design doc about it.
> 
> ```
>          +--------------------------+
>        +--------------------------+ |
>        |                          | |
>        |    Cluster Instances     | |
>        |                          | |
>        |                          | +
>        +------------^-------------+
>                     |
>                     |watch
>                     |
> +---------------------------------------+
> |                   |                   |
> |                   |                   |
> |    +-----------------------------+    |
> |    |              |              |    |
> |    |    +---------+----------+   |    |
> |    |    |Watch & Add Clusters|   |    |
> |    |    +---------+----------+   |    |
> |    |              |              |    |
> |    |              |sctool        |    |
> |    |              |              |    |
> |    |    +---------v----------+   |    |
> |    |    |   Scylla Manager   |   |    |
> |    |    +--------------------+   |    |
> |    |                   Container |    |
> |    +-----------------------------+    |
> |                                       |
> |                                 Pod   |
> +---------------------------------------+
> ```
> 
> The solution is comprised of a Scylla Manager Pod, with only 1 container, containing two processes:
> 
>     1. Scylla Manager
> 
>     2. A small controller that will watch the Kubernetes API for Scylla Cluster Custom Resources and for each one it finds, it will add it to the manager via sctool.
> 
> 
> The small controller binary will be injected into the Scylla Manager container via an initContainer.
> It will also be used for the health check of the Pod, so that if the controller or Scylla Manager fails, the Pod is restarted.
> 
> An alternative would be to have them in separate containers and provide the controller with the sctool binary via a shared volume.

Yes, but I don't think there are many pros in this. Both in the same container seems simpler. 

> 
> Some other remarks:
> 
>     * The `sctool cluster add` command should be idempotent, or a way must be provided to check if a cluster is already managed by Scylla Manager.

Ok

> 
>     * The user scylla manager will use / ssh keys will be setup on each Scylla Pod's startup. The SSH keypair will be generated by the operator and stored in a Secret when creating a Scylla Cluster for the first time.

Ok

> 
>     * The small controller binary that adds clusters to Scylla Manager will retrieve the SSH keys by getting the aforementioned Secret from the Kubernetes API.

What you mean by retrieving? It's a secret, we can mount it. (: 

Overall, I agree with this solution @yanniszark . It's what I had in mind!

**Comment by dahankzter** [comment]
We will not have time to implement this until the new agent based Scylla Manager is out which makes it much easier I think. We just need to ensure that the agent is running on every node which it probably should out of the box in the newer scylla docker containers. If not we need to bake one which also shouldn't be that hard.

**Comment by dahankzter** [comment]
I think this design seem good @yanniszark with the exception that we need to inject the Scylla Manager Agent into the Scylla. No SSH is needed but a secret is required to talk to the agent nonetheless so mounting it like @jwnx said should be fine right? The same mount is needed where the scylla agent runs. Alternatively we can use the Scylla Manager API but perhaps sctool is easier.

**Comment by ketul93** [comment]
> Scylla Manager has many nice features that help us handle Scylla clusters, such as repairs and backup/restore. Would be nice to have the option to deploy it alongside the Operator.
> 
> **Possible solution** Once dockerized, Scylla Manager can be deployed as an outside service that is able to communicate with the cluster. Its key-pair can be generated as a secret upon cluster creation.
> 
> **Other Alternatives** ??
> 
> **Additional context** This feature depends on scylla-manager working on docker.

We are trying to configure the pilot scylladb manager ... These are the configuration we are trying to get it
Scylladb with scylladb - agent - IP1
Scylladb manager - IP2
Using the Dockerized env as mentioned here - https://manager.docs.scylladb.com/stable/docker/index.html
When I am trying to add the cluster of IP1 using sctool at Scylla-manager [bash] running in IP2 ... Getting the following error as shared in the screenshot ....
I have already whitelisted and exposed these ports at agent side ...
     - "9042:9042"  # CQL native transport port
      - "19042:19042"  # Internode communication (non-SSL)
      - "7199:7199"  # JMX management port
      - "9180:9180"  # Prometheus metrics port
      - "10001:10001" # Scylla Manager agent port
      - "9100:9100"
Also generated and added TLS cert.
Also tried connecting the agent with GET req and seems it is able to respond but yet failed to be added as cluster

![image](https://github.com/scylladb/scylla-operator/assets/10497402/b05b053c-b34b-4a6d-a9d1-68bbd63c83e8)
![image](https://github.com/scylladb/scylla-operator/assets/10497402/e1ea914e-b6c2-43e9-ab64-bcacde518295)

**Comment by mykaul** [comment]
@ketul93 - is the above different than https://github.com/scylladb/scylla-manager/issues/3672 ? Are you running this in K8S, or plain container runtime, such as Docker/Podman?

**Comment by ketul93** [comment]
> @ketul93 - is the above different than [scylladb/scylla-manager#3672](https://github.com/scylladb/scylla-manager/issues/3672) ? Are you running this in K8S, or plain container runtime, such as Docker/Podman?

Yes it's same and running it with docker... thanks
