### ISSUE TITLE
scylla-jmx failing to start on latest docker images on 3.2

### ISSUE THREAD

**Issue by maxfofocker** [scylladb/scylla-operator#50]
I got a error on GKE cluster and use scylladb/scylla:3.2.1 docker image ,

log: errorVerbose: "open /usr/lib/scylla/jmx/scylla-jmx: no such file or directory

I find a similar error issue in [scylladb/scylla issues](https://github.com/scylladb/scylla/issues/5542).

I find a error point on [scylla-operator sidecar/config] (https://github.com/scylladb/scylla-operator/blob/master/pkg/sidecar/config/config.go#L30) , use it scyllaJMXPath on [L195](https://github.com/scylladb/scylla-operator/blob/master/pkg/sidecar/config/config.go#L195) and [L205](https://github.com/scylladb/scylla-operator/blob/master/pkg/sidecar/config/config.go#L205)

**Expected behavior**

I expected this path can be config from outer yaml setting or environment variable to change it.

**Comment by dahankzter** [comment]
Ouch! Thanks for reporting this. There are a few things to keep in mind for this one. The operator needs to support several versions of scylla and in this case it means handling both of these transparently.
If one doesn't exists then we use the other.
Second it that we are moving it away from jmx altogether and we will replace it with an HTTP REST API call once the agent is in place.

How urgent is this for you @maxfofocker?

**Comment by justdomepaul** [comment]
My system will production by the end of March.

I still test use scylla-operator or cassandra cluster to deploy my database cluster.

I want to know what time is expected to be upgrade this operator?

**Comment by dahankzter** [comment]
Fixing this issue for now will be quick. The next release is not that quick but not far off either.
Is your intention to use Scylla if it works on Kubernetes otherwise go for Cassandra? Then of course we will try our best to help you but I cannot guarantee it. It works pretty well but hasn't seen much production use that we know of.

Feel free to vote for the issues or add anything you miss! All input from users are super valuable and we really can't get enough of that.

**Comment by justdomepaul** [comment]
I will do my best to use scylladb works on Kubernetes.

But, I need high stability in my database cluster, 
if I still can't deploy successfully scylladb cluster, I will choice Cassandra to cover my system.

**Comment by dahankzter** [comment]
Can you try now @justdomepaul @maxfofocker ?
