### ISSUE TITLE
CpuSet research

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#508]
Despite following comment around enabling cpuset for Scylla I tried setting in on environment with non-static CPU policy and Scylla did not crash even when cpuset was counting CPUs not allocated by the kubelet. 
https://github.com/scylladb/scylla-operator/blob/74caca42dd9d27650e9fe2ce8079b815f2835928/pkg/controllers/sidecar/config/config.go#L235-L236

Maybe we should enable it by default and depracate switch in CRD. 
Before doing that, we should check whether setting it always affect anyhow performance or stability of the cluster.

**Comment by tnozicka** [comment]
@zimnx something to consider for #1978 ?

**Comment by zimnx** [comment]
Yes, it's going to be deprecated. All it does today, it enables stricter validation, which is unnecessary.
