### ISSUE TITLE
Scylla Operator Helm 404 error

### ISSUE THREAD

**Issue by srfaytkn** [scylladb/scylla-operator#515]
I get this error when I follow the [document](http://operator.docs.scylladb.com/v1.1/helm.html) 

⇒  helm repo add scylla https://scylla-operator-charts.storage.googleapis.com/stable

Error: looks like "https://scylla-operator-charts.storage.googleapis.com/stable" is not a valid chart repository or cannot be reached: failed to fetch https://scylla-operator-charts.storage.googleapis.com/stable/index.yaml : 404 Not Found

Note: Health probes returns 404 error when I use 1.0 chart

What should I do?

**Comment by tnozicka** [comment]
try latest, we haven't released 1.1 (and helm chart support) yet

**Comment by tnozicka** [comment]
we'll try to make the repo accessible and explicitly empty in the meantime

**Comment by tnozicka** [comment]
added an empty index, hopefully that will give a better message before 1.1 lands
