### ISSUE TITLE
Problems running Scylla Enterprise

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#52]
Reported:
```
Readiness:  exec [/bin/bash -c exec /opt/ready-probe.sh] delay=15s timeout=5s period=10s #success=1 #failure=3
```

We need to check that the Enterprise version works well and is supported by the Operator.

**Comment by mmatczuk** [comment]
Should be resolved by now needs to be validated @bentsi do you have any insights?

**Comment by ezbz** [comment]
@bentsi is this resolved

**Comment by zimnx** [comment]
Dmitry confirmed on QA meeting that Enterprise works fine.
