### ISSUE TITLE
Scylla Cluster pods fails to come up when kubernetes node where it was scheduled is terminated

### ISSUE THREAD

**Issue by Pavankumar6997** [scylladb/scylla-operator#521]
**Describe the bug**
On an EKS node where all the scylla cluster pods are scheduled is terminated, scylla cluster fails to start up on a new EKS node 

**To Reproduce**
1. Create Operator, Manager & Cluster 
2. Perform this action : delete a kubernetes node where scylla `Cluster` pods are scheduled
3. See error: Scylla Cluster Fails to recreate the statefulset pods on a new node 

**Expected behavior**
Expected to See Scylla Cluster Pods start up successfully in ordered manner 

**Logs**

```
kubectl get pods -n scylla-cluster
NAME                                      READY   STATUS    RESTARTS   AGE
scylla-cluster-ap-south-1-ap-south-1a-0   1/2     Running   1452       7d19h
```
```
± kubectl get svc  -n scylla-cluster                                                                        
NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                           AGE
scylla-cluster-ap-south-1-ap-south-1a-0   ClusterIP   172.20.25.149    <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9042/TCP,9142/TCP,9160/TCP   15d
scylla-cluster-ap-south-1-ap-south-1a-1   ClusterIP   172.20.178.195   <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9042/TCP,9142/TCP,9160/TCP   15d
scylla-cluster-ap-south-1-ap-south-1a-2   ClusterIP   172.20.239.102   <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9042/TCP,9142/TCP,9160/TCP   15d
scylla-cluster-client                     ClusterIP   None             <none>        9180/TCP
```

Logs from pod `scylla-cluster-ap-south-1-ap-south-1a-0`
[scylla-cluster-ap-south-1-ap-south-1a-0.txt](https://github.com/scylladb/scylla-operator/files/6194998/scylla-cluster-ap-south-1-ap-south-1a-0.txt)

**Environment:**
 - Platform: AWS EKS
 - Kubernetes version: 1.17
 - Scylla cluster version: 4.3.0
 - Scylla-operator version: `scylladb/scylla-operator:v1.0.0`

**Comment by tnozicka** [comment]
Did you use `scylla/replace=""` label to replace a node? This isn't automated.
https://operator.docs.scylladb.com/stable/node_operations.html#replacing-a-scylla-node

**Comment by tnozicka** [comment]
> delete a kubernetes node where scylla Cluster pods are scheduled
If all of your scylla pods are on the same node, there won't be any scylla node left to stream the data to he replacement nodes.
