### ISSUE TITLE
examples/gke/cpu-policy-daemonset.yaml removed from folder but still in documentation

### ISSUE THREAD

**Issue by danias** [scylladb/scylla-operator#527]
Hi @zimnx ,

I am a Scylla noob and I saw that you removed examples/gke/cpu-policy-daemonset.yaml a few days ago. Nonetheless, the [GKE instructions](https://github.com/scylladb/scylla-operator/blob/master/docs/source/gke.md) have not been updated accordingly. Is this still required as a step? If not, it would have been useful to include in the comments why it has been removed or maybe to remove the CPU policy section from the [instructions](examples/gke/cpu-policy-daemonset.yaml). 

Thanks!
Vasilis

**Comment by danias** [comment]
I saw that systemconfig.yaml was added which is referenced by gke.sh and in general gke.sh seems to have updated information (e.g. no gcloud beta etc.) which means that the documentation is outdated. I will test the steps and submit a PR with the updated documentation if I manage.

**Comment by zimnx** [comment]
Thanks for noticing, contributions are welcomed. 
`master` documentation may be not always synced with the code. 
I would suggest to use latest release branch and documentation.
