### ISSUE TITLE
scylla-cluster connection in k8s

### ISSUE THREAD

**Issue by srfaytkn** [scylladb/scylla-operator#532]
How can I connect to scylla-cluster with port forwarding?

i tried this commands

```shell
kubectl -n scylla port-forward --address 192.168.13.179 pod/scylla-us-east-2-us-east-2a-0 9042
kubectl -n scylla port-forward pod/scylla-us-east-2-us-east-2a-0 9042
```

**Comment by tnozicka** [comment]
It used to listen only on the clusterIP in the pod and I don't think `kubectl port-forward` can specify that - the `--address` flag is for your machine. Using `kubectl port-forward svc/<name>` also goes to `127.0.0.1`.

Fixed in https://github.com/scylladb/scylla-operator/pull/529
