### ISSUE TITLE
Helm repo with latest charts does not work

### ISSUE THREAD

**Issue by van-vliet** [scylladb/scylla-operator#566]
**Describe the bug**
The readme describes how to use the [latest repo](https://github.com/scylladb/scylla-operator#latest) for latest helm charts, but when using the repo, it seems empty.

**To Reproduce**
1. Add repo: `helm repo add scylla-operator https://storage.googleapis.com/scylla-operator-charts/latest`
1. Update repo: `helm repo update`
1. 
    1. Install scylla operator: `helm install scylla-operator scylla-operator/scylla-operator`
    Note that this return `Error: failed to download "scylla-operator/scylla-operator" (hint: running `helm repo update` may help)`
    1. Search for charts in repo:  `helm search repo scylla`  
    Note that this returns `No results found` 

**Expected behavior**
In scenario 3i, I expected the latest version of the helm chart to install.
In scenario 3ii, I expected a result list similar to the following:
```
NAME                           	CHART VERSION	APP VERSION	DESCRIPTION
scylla-operator/scylla         	v1.1.0       	1.1.0      	Scylla is a close-to-the-hardware rewrite of Ca...
scylla-operator/scylla-manager 	v1.1.0       	1.1.0      	Scylla Manager automates database operations.
scylla-operator/scylla-operator	v1.1.0       	1.1.0      	Scylla Operator is a Kubernetes Operator for ma...
```

**Environment:**
 - Helm version v3.5.4

**Additional info0** 
[This issue](https://github.com/scylladb/scylla-operator/issues/461) seems related.
Consider deleting the latest helm chart info if it is not maintained.

**Comment by zimnx** [comment]
@van-vliet make sure to add `--devel` flag to helm commands when using latest repo.

**Comment by van-vliet** [comment]
That solved the issue. I wasn't aware the --devel flag was needed.
