### ISSUE TITLE
Operator installed using helm times out on webhook requests

### ISSUE THREAD

**Issue by van-vliet** [scylladb/scylla-operator#567]
**Describe the bug**
Install the operator using Helm. When applying a ScyllaCluster, the webhook defined in the mutatingwebhookconfiguration times out after 30 seconds.

**To Reproduce**
1. Install the operator:
    ```
    helm repo add scylla-operator-stable https://storage.googleapis.com/scylla-operator-charts/stable
    helm repo update
    
    kubectl create namespace scylla-operator
    helm install scylla-operator scylla-operator-stable/scylla-operator --namespace scylla-operator --version 1.1.0
    ```
1. Wait until operator pod is ready
1. Apply a ScyllaCluster:
    ```
    kubectl create namespace scylla
    kubectl apply -f cluster.yaml 
    ```
1. See error: 
    ```
    Error from server (InternalError): error when creating "cluster.yaml": Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": Post "https://scylla-operator.scylla-operator.svc:443/mutate-scylla-scylladb-com-v1-scyllacluster?timeout=30s": context deadline exceeded
    ```

**Expected behavior**
I expected the ScyllaCluster CR to be installed on my Kubernetes cluster. Afterwards, I expected the operator to build the cluster by starting pods and creating services.

**Config Files**
[cluster.yaml.txt](https://github.com/scylladb/scylla-operator/files/6389965/cluster.yaml.txt) (Remove txt suffix - Github prevents me from uploading yaml files directly.

**Logs**
```
$ kubectl logs -n scylla-operator scylla-operator-0
{"L":"INFO","T":"2021-04-28T07:31:48.595Z","M":"Operator started","version":"v1.1.0-rc.5-0-g42a0f1e","build_date":"2021-03-18T12:04:16Z","commit":"42a0f1e3","go_version":"go1.15.7","options":{"Name":"scylla-operator-0","Namespace":"scylla-operator","LogLevel":"debug","Image":"","EnableAdmissionWebhook":true},"_trace_id":"daEa_Zd3Te6kF5brY7489A"}
I0428 07:31:49.645947       1 request.go:621] Throttling request took 1.041283963s, request: GET:https://172.20.0.1:443/apis/getambassador.io/v1beta1?timeout=32s
{"L":"INFO","T":"2021-04-28T07:31:49.999Z","M":"Registering Components.","_trace_id":"daEa_Zd3Te6kF5brY7489A"}
{"L":"INFO","T":"2021-04-28T07:31:51.411Z","M":"Starting the operator...","_trace_id":"-fYVdkJfTGu6hDXthRyodA"}
```
Note that the operator seems to log the names of other CRDs installed in the cluster. `getambassador.io` is a different CRD group name.

**Environment:**
 - Platform: AWS EKS
 - Kubernetes version: v1.19.8-eks-96780e
 - Scylla version: 
 - Scylla-operator version: scylladb/scylla-operator:1.1.0
 - Helm chart version: 1.1.0
 - Cert manager: v1.3.1 

**Additional context**
Cluster.yaml used was copied from Helm chart. StorageClass used maps to GP3 EBS volumes.

**Comment by ronanbarrett** [comment]
I have had the exact same issue when creating scylla clusters on GKE when using a GKE Private Cluster. This is a known issue and can be worked around. See https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#api_request_that_triggers_admission_webhook_timing_out for the description and resolution.

Basically a firewall rule must be added to allow access from the master nodes to port 9443 inside the private cluster.

**Comment by tnozicka** [comment]
+1, it looks like networking when kube apiserver (living on a master) is trying to reach out to the operator deployment (on a node) serving the webhook. Also operator 1.1 is out of support https://github.com/scylladb/scylla-operator/blame/ec543ea/docs/source/releases.md#L17 so I'll close this one. Feel free to create a new issue if you try with a supported release and networking doesn't fix your issue.
