### ISSUE TITLE
Run containers (operator/controller/manager/member) as non root

### ISSUE THREAD

**Issue by niels-s** [scylladb/scylla-operator#570]
* Feature Request

**What should the feature do:**

Update the helm charts for the operator/manager/cluster to deploy the statefulsets/deployments to run as a non root user using a security context like for example:

```
securityContext:
  runAsUser: 999
```

**What is use case behind this feature:**

We use a [Lokomotive Kubernetes](https://github.com/kinvolk/lokomotive) distribution which likes to promote a security approach of least privilege, so by default, the containers aren't allowed to run as root. 
I'm not familiar with the details of the deployment but it would be a good approach to run the containers as a specific user instead of root.

**Additional Information:**

Currently, without defining additional permission to the default set of rules in the ClusterRole the pods won't be able to start because they lack the permissions to start the pods as root user.
```
Error: container has runAsNonRoot and image will run as root
```

**Comment by tnozicka** [comment]
We certainly want to run as non-root where that's not needed. OpenShift enforces a random userid, so I'd just like to come up with something that works for both.

**Comment by tnozicka** [comment]
We have fixed the ports so running as non-root should be an issue. But if we specify the UID manually that's gonna be prone to collisions and still a privileged operation - MustRunAsRange vs. RunAsAny.

**Comment by niels-s** [comment]
I'm open to any suggestion as long as the final results mean the containers aren't running as root anymore where possible. I'll leave that over to the Scylla team to make that judgment what the best approach for that would be.
Obviously, we have to ensure it runs on all platforms, or at least provide the ability to make it work 👍

**Comment by tnozicka** [comment]
Would an optional `securityContext` in the helm chart work for you? User on distros that generate random UID wouldn't be affected by such change.

**Comment by niels-s** [comment]
Yes, sure if we can configure it ourselves with an optional `securityContext` that would be great 👌

**Comment by niels-s** [comment]
@tnozicka if we can agree this is the path forward, I can start working on making the changes in the helm charts.
Would this be a simple templating change or would this require other work like e2e tests?

**Comment by tnozicka** [comment]
Sure, if that works for you we'd be happy to accept the contribution!

I think you'd be good without an e2e test. It's not easy to add optional changes without duplicating it.

I think you'd be good for 1.3, we'll officially set the schedule when 1.2 goes GA, but it can be estimated based on https://github.com/scylladb/scylla-operator/blob/f773712/docs/source/releases.md#schedule

**Comment by niels-s** [comment]
Great thanks 👍 I've opened a PR #574, this only tackles the `securityContext` for the operator, manager, and manager controller but not for the Scylla cluster members.
