### ISSUE TITLE
scylla-manager: doesn't work with non-default TLD (.cluster.local)

### ISSUE THREAD

**Issue by kjetijor** [scylladb/scylla-operator#575]
**Describe the bug**
Assumption that your k8s cluster TLD is cluster.local, i.e [here](https://github.com/scylladb/scylla-operator/blob/cf9147012f80e784d1ac43cf0780b90c2681b086/pkg/naming/names.go#L58)

**To Reproduce**
1. Deploy k8s cluster with "non-default" TLD, i.e. k8s.somewhere.tld
2. Deploy scylla-operator/manager, deploy a cluster
3. scylla-manager-controller fails to connect to <cluster>-client.<namespace>.svc.cluster.local failing to look up the IP via DNS

**Expected behavior**
scylla-manager-controller successfully connects to client.

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
{"L":"ERROR","T":"2021-04-30T22:16:51.151Z","N":"scylla-manager-controller","M":"Failed to execute action","cluster":"namespace/somecluster","action":"add cluster \"\"","error":"[POST /clusters][500] PostClusters default  &{Message:create cluster: status: giving up after 1 attempts: dial tcp: lookup somecluster-client.somenamespace.svc.cluster.local on someip:53: no such host - make sure the IP is correct and access to port 10001 is unblocked TraceID:Yd3peCwmTAextAZR0WfOjw}"}

**Environment:**
 - Platform: N/A
 - Kubernetes version:  N/A
 - Scylla version: 4.2.0
 - Scylla-operator version: master-ish

**Additional context**
Likely - if you dropped the .cluster.local alltogether, this should work. Typically .svc.$TLD is injected into DNS search path. I haven't checked yet if I'd be able to configure myself out of this.

**Comment by tnozicka** [comment]
you are correct, we should only use `.svc`
