### ISSUE TITLE
Unify scylla version for v1.3 release

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#582]
With the beginning of the release cycle, the current latest scylla version is `4.4` which is also the one we should bump the operator to. Latest z-stream is `4.4.1` which we should set up as the primary version in manifests, e2e and QA test. As there is the nodetool bug we'd bump to a later z-stream with the fix during the release cycle, at least in the affected tests.

cc: @zimnx @vponomaryov @tzach

**Comment by tnozicka** [comment]
e2e tests are switched already https://github.com/scylladb/scylla-operator/pull/579

**Comment by vponomaryov** [comment]
@tnozicka better to add links for bugs you are referring to.
It is public place and not all of the interested people are aware about [1], [2] and [3].

[1] https://github.com/scylladb/scylla-tools-java/commit/3eca0e35
[2] https://github.com/scylladb/scylla/issues/7930
[3] https://github.com/scylladb/scylla-tools-java/pull/232

**Comment by tnozicka** [comment]
@vponomaryov we are bumping in https://github.com/scylladb/scylla-operator/pull/609 - hopefully QA tests with the defaults, otherwise please bump yours.
