### ISSUE TITLE
Issue in page Scylla Operator Documentation

### ISSUE THREAD

**Issue by lsnovich** [scylladb/scylla-operator#590]
I would like to report an issue in page https://operator.docs.scylladb.com/v1.1/index

### Problem
1.2 version is not on the site

###  Suggest a fix

**Comment by tzach** [comment]
Good catch @lauranovich 
Lets fix this *before* we send the release notes

**Comment by tnozicka** [comment]
@tzach it is waiting for your approval - https://github.com/scylladb/scylla-operator/pull/581
