### ISSUE TITLE
Feature request: Add sidecar to scylla pod

### ISSUE THREAD

**Issue by c0ffeec0der** [scylladb/scylla-operator#614]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add additional container to scylla pod

**What is use case behind this feature:**
Add kube-rbac-proxy to secure prometheus metric

**Additional Information:**
Currently the prometheus port is not secured. By adding kube-rbac-proxy it can be secured

**Comment by tnozicka** [comment]
the prometheus TLS is partially done, the rest is tracked in https://github.com/scylladb/scylla-operator/issues/1186
