### ISSUE TITLE
Remove the use of tini

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#64]
Tini is a neat init system but apparently kubernetes has this covered for quite a few versions using shared pid namespaces.

**Comment by dahankzter** [comment]
What do you think @yanniszark?

**Comment by dahankzter** [comment]
I have tried it and it seems to work fine but perhaps there is something else needed?

**Comment by yanniszark** [comment]
@dahankzter why use shared PID namespaces?
Is there a benefit or a reason to break the current status quo?
Having seperate PID namespaces provides an extra layer of isolation.
Perhaps I am missing something here :thinking:

**Comment by dahankzter** [comment]
I think moving parts are troublesome but you are right that it doesn't affect much. It does however mimic more how the agent and scylla runs in the normal case. Normally they run completely colocated on the same machine.

**Comment by zimnx** [comment]
Removed as a part of migration to kubebuilder v2
