### ISSUE TITLE
Dynamic config of scylla client

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#65]
Currently a change in configuration requires restart of the cluster. This is probably unacceptable for something as simple as a configuration change. The simplest way to accomplish this is to just recreate the client every time it is used. It can be stashed somewhere for shorter times of course but reloading it from time to time is an easy solution.

**Comment by gnumoreno** [comment]
I don't understand the problem statement.

**Comment by dahankzter** [comment]
The problem is that the scylla client config is only read once on startup. This means that we need to restart the whole cluster in order to for example modify the authentication settings. With a more dynamic approach (many possible ways) the client config would be applied automatically when a configuration change is made. @gnumoreno

**Comment by tzach** [comment]
@dahankzter to validate: 
do the current version supporting rolling restart after config change?

**Comment by dahankzter** [comment]
I don't follow @tzach in case the config is change a restart is needed to make the client use the new config. The idea here is to just let the client/operator reload the config regularly and completely avoid a cluster restart.

**Comment by tzach** [comment]
Scylla do support dynamic update of  a subset of the config parameter, so in theory we can allow this.
I do not think its a must for 1.0
