### ISSUE TITLE
Creating a cluster attempts to reach a webhook at the wrong location

### ISSUE THREAD

**Issue by dvaldivia** [scylladb/scylla-operator#657]
**Describe the bug**
When creating a `scylla.scylladb.com/v1` the following error is thrown

```
Error from server (InternalError): error when creating "/Users/dvaldivia/dev/tdev/devops/persistent-services/scylla-cluster.yaml": Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": Post "https://scylla-operator-webhook-service.scylla-operator-system.svc:443/mutate-scylla-scylladb-com-v1-scyllacluster?timeout=30s": service "scylla-operator-webhook-service" not found
```

which indicates an attempt to reach the service at the `scylla-operator-system` namespace, where the operator version `v1.3.0` installs to `scylla-operator`

what could be causing this discrepancy? upgrading from an older operator of scylla? I already removed all traces of it

**Comment by dvaldivia** [comment]
for any other web travelers, the problem is the upgrade process, remove the mutating webhook and validation webhook as well

**Comment by tnozicka** [comment]
yep, as per https://operator.docs.scylladb.com/stable/upgrade.html
