### ISSUE TITLE
Ability to opt-out from Cert Manager dependency and certificates as a whole

### ISSUE THREAD

**Issue by cortopy** [scylladb/scylla-operator#679]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

AFAIK, currently:

- scylla operator has cert manager as a hard dependency. It has to be deployed in the cluster for the operator to be deployed successfully with helm
- new scylla clusters will make requests to the operator to get the certificate. If the certificate is wrong, scylla won't start

However, encryption and authentication may be managed elsewhere in a k8s cluster. For example:

- CNI may already provide encryption (e.g.: Cilium, Calico)
- Service meshes can handle both encryption and authentication (Istio, linkerd)

I would like to opt out from all encryption and authentication and not having to deploy cert manager when I have my own solution for it.

It's great that scylla operator is secure-by-default, as users have to opt-out from encryption by setting `server_encryption_options` in the config file.

However, it would be great for users to opt out from certificate management altogether when the host k8s cluster already has the infrastructure to manage encryption separately

**What is use case behind this feature:**

Reduce operations complexity for features that are not needed

**Comment by tnozicka** [comment]
> new scylla clusters will make requests to the operator to get the certificate. If the certificate is wrong, scylla won't start

Scylla clusters don't requests certificates through the operator. We use cert-manager only to generate the certificate for the CRD webhooks (for kube apiserver to talk to scylla-operator), if you edit the manifests and provide the certificate on your own, you shouldn't need cert-manager.

Although, we want to get rid of the cert-manager dependency eventually https://github.com/scylladb/scylla-operator/issues/383

**Comment by tnozicka** [comment]
We are tracking cert-manager removal in #383, closing it as dupe.
