### ISSUE TITLE
Support node-to-node encryption

### ISSUE THREAD

**Issue by jwnx** [scylladb/scylla-operator#7]
Scylla supports node-to-node encryption through self-signed certificates. This secures communication between nodes, which is specially important in a plural Kubernetes environment. 

**Possible solution**
Generate a self-signed certificate upon cluster creation and attach it to each node. 
https://docs.scylladb.com/operating-scylla/security/node_node_encryption/

**Comment by epsniff** [comment]
A possible alternative is to off-load encryption to Istio's mTLS.  https://istio.io/docs/concepts/security/#mutual-tls-authentication

**Comment by ezbz** [comment]
duplicate of #255
