### ISSUE TITLE
Error for tailler version

### ISSUE THREAD

**Issue by jxie418** [scylladb/scylla-operator#70]
**Describe the bug**

when I run following command:
helm upgrade --install scylla-graf --namespace monitoring stable/grafana -f examples/gke/grafana/values.yaml

I got following error

Error : Chart incompatible with Tiller v2.9.1
 
Even I run helm init –upgrade, it didn’t help. 

**To Reproduce**
1. helm upgrade --install scylla-graf --namespace monitoring stable/grafana -f examples/gke/grafana/values.yaml
2. See error : Error : Chart incompatible with Tiller v2.9.1

**Environment:**
 - Platform: (GKE) 
 - Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"} 
 - Scylla version: 3.2.2

**Comment by dahankzter** [comment]
Thanks for reporting this. Is there no other error message or is that one all of it?

**Comment by jxie418** [comment]
No other errors.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gnumoreno** [comment]
@jxie418 I took a look at the grafana helm chart (note this is not developed by scylla, we just use it) and found this:

https://github.com/helm/charts/blob/master/stable/grafana/Chart.yaml#L19

`tillerVersion: ">=2.12.0"`

So I think you need 2.12 at least, if you are on 2.9 it is not going to work.

**Comment by dahankzter** [comment]
Aha good catch @gnumoreno I seem to have no problems running it locally either. Can you upgrade Tiller @jxie418 ?

**Comment by jxie418** [comment]
I will do that and try it again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jxie418** [comment]
I run helm init --upgrade 

It says 

Tiller (the helm server-side component) has been upgraded to the current version.

After I run 
Helm version 
but Client and Server version both are v2.9.1

How to upgrade Tiller version to 2.12.0 ?

**Comment by dahankzter** [comment]
I can't reproduce this @jxie418 did you manage to upgrade tiller and try again? Also I run Helm 3 which doesn't use tiller at all anymore. Perhaps that's an option for you?

**Comment by jxie418** [comment]
after， I updated the helm version. It fixed tiller error. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dahankzter** [comment]
Excellent!
