### ISSUE TITLE
Alternator Deployment

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-operator#71]
* Feature Request

Scylla 3.2 introduce Alternator, a AWS DynamoDB compatible API.
As such, it will be useful for Operator to allow an easy deployment of Alternator on K8s. This includes:
1. Open (and close) relevant ports for REST (close for CQL)
2. Implement a K8s LB (more than one option)
3. Doc the option and build example

**Comment by dahankzter** [comment]
So it's either or? Can't an Alternator instance also act as a regular Scylla instance at the same time?

**Comment by tzach** [comment]
Technical it can, but its unlikely

**Comment by nyh** [comment]
As @tzach said, we do **allow** using both CQL and DynamoDB API at the same time. We open listening sockets for both, and handle both protocols. However, we do not want to **support** this use this.

To understand the difference, consider what would happen if we told users they can access Alternator tables through CQL: We would then need to write documents explaining what the data model looks like for Alternator tables, and if later we decide to change this data model users may complain because their CQL application suddenly has problems accessing it.

If users want to use both APIS (CQL and DynamoDB) on **different** tables, that's more reasonable to allow, but I don't think we should worry about this until we have a user which needs it. I think it's pretty unlikely, considering that most applications will have either a CQL or a DynamoDB code - not a mixture of both.

**Comment by dahankzter** [comment]
I think we can cater to all the scenarios either by a switch in the crd.
That way it can later be changed as well in case the user changes his mind.

**Comment by tzach** [comment]
Sounds good. 
I do not think we need to support switch Scylla from Alternator to CQL and back, even if its technically possible.

**Comment by dahankzter** [comment]
So @nyh the only difference from operator perspective between regular scylla and alternator is the ports which is used. Correct? We now need to expose 8000 instead of the cql ports (and thrift I guess).

**Comment by dahankzter** [comment]
So this seems to work now but so far no way to configure the Alternator port. Is this something we want to support? I mean other than in the general "configuration is good" kind of way? @tzach

**Comment by nyh** [comment]
@dahankzter yes, you need to expose the ports ("8000" is just an example number, it can be anything... Amazon uses the traditional HTTP ports: 80, and 443 for SSL). I don't know if I would go as far that that's "the only difference" - another important operational issue mentioned above is the need for a load balancer. I will give a presentation about exactly this issue in about an hour in the daily call, I hope it will clarify things.

**Comment by dahankzter** [comment]
Aha yes it's very stateless so a load balancer makes sense. Ok so making the port configurable with some sensible default is probably good as well.

**Comment by nyh** [comment]
Currently there is no "default" before the port, because setting the port number is the way to enable Alternator (the default is that it's disabled).

**Comment by dahankzter** [comment]
Aha I get it. The conundrum I have is mostly a UX issue. If I expose the port as "alternatorPort" and at the same time use that as an activation of "alternator mode" which disables the other APIs it's maybe easy for the user to think "Oh I should have alternator as well". If I use a boolean "alternator" I would still need a port somewhere to allow for configuration.

It's not a huge problem but still...

**Comment by nyh** [comment]
I  need to clarify - the "--alternator-port" option **does not** disable CQL. I'm not even sure we have an option to do that (we probably should! I'll open an issue!). It opens an Alternator port (which means enabling Alternator) in addition to the CQL port.

**Comment by nyh** [comment]
I just found there is a "start_native_transport" option to disable CQL if we want - we don't need to add an option for this. I'll need to document it in docs/protocols.md.

**Comment by nyh** [comment]
Yikes, I see "start_native_transport" isn't actually supported, I can't figure out why... It's in the code....

**Comment by dahankzter** [comment]
Ah yes I know it doesn't disable cql. I meant that the presence of this
flag would make the operator simply avoid exposing the cql port in favor of
the alternator port.

Being able to disable it in Scylla would maybe be good too but perhaps it's
good to be able to use the cql interface locally on the node for debugging
purposes?
