### ISSUE TITLE
Multi region support.

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla-operator#72]
It would be convenient have the operator support deploying in multiple regions. This would allow deploying a DC on the US west and east coast plus as many other locations around the world as the cloud provider supports.

Currently k8s doesn't support and previous implementations like https://github.com/Orange-OpenSource/casskop and CockroachDB uses multiple k8s clusters and establishes networking between them.

**Comment by tnozicka** [comment]
manual multiDC has already landed https://operator.docs.scylladb.com/stable/multidc/index.html
