### ISSUE TITLE
Add e2e for monitoring

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#747]
**What should the feature do:**
Add at least some basic coverage that deploys monitoring in the CI and tests it can collect some data.

**What is use case behind this feature:**
Stability.

**Comment by rzetelskik** [comment]
@tnozicka should we close this one? We have https://github.com/scylladb/scylla-operator/blob/master/test/e2e/set/scylladbmonitoring/scylladbmonitoring.go now
