### ISSUE TITLE
 A busy scyllacluster doesn't shutdown cleanly in time and is force terminated with SIGKILL

### ISSUE THREAD

**Issue by ajmaidak** [scylladb/scylla-operator#805]
**Describe the bug**
If you update the scylla operator sidecar image string scylla operator will trigger a rolling update of the statefulset(s) that compose the scylla cluster.  This will trigger a restart of the pods in the statefulset(s).  This doesn't trigger any "upgrading status" as the scylla version has not changed.  Thus a simple SIGTERM is sent to the scylla process followed 30 seconds latter by a SIGKILL (default termination grace period).  On a busy scylla node this will likely result in a unclean shutdown. 

**To Reproduce**
1. Have a busy scylla cluster running under scylla operator
2. Update the scylla-operator image which is used as an init container in scylla
3. Watch scylla take more then 30s to shutdown after SIGTERM (termination grace period) and get SIGKILLED

**Expected behavior**
The scylla replica is drained before it is sent a SIGTERM.  This could be achieved via a prestop hook and/or potentially a longer terminationgraceperiod for the Scylla pod.

**Environment:**
 - Scylla-operator version: v1.4 (should affect master and v1.5 as well)

**Comment by tnozicka** [comment]
Thanks for the report, I assume this could be reproduced by just deleting a scyllacluster pod in a busy cluster, right?

(Even with a preStop hook we'd need to adjust the terminationGracePeriod as preStop hook time is accounted into it.)

It looks like we don't set terminationGracePeriod at all which defaults to 30 seconds. For servers this is usually set to the longest running call and some space to cover for the LB - we need to look up the limits for scylla but it's gonna be harder to guess if it's configurable.
