### ISSUE TITLE
Docs: Compatibility table

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-operator#81]
* Which version of 
  - Scylla, 
  - Scylla Enterprise, 
  - Scylla Monitoring 
  - Scylla manager (Agent) 

are supported, or at least tested?

* Which version of K8s are supported?

**Comment by tnozicka** [comment]
we have it for a while https://github.com/scylladb/scylla-operator/blob/7bcebc4/docs/source/releases.md#support-matrix
