### ISSUE TITLE
Include upgrade path from v1.3.0 -> v1.4.0 and from v1.4.0 -> v1.5.0

### ISSUE THREAD

**Issue by lucmargui** [scylladb/scylla-operator#823]
Update the path to the relevant Doc page: https://operator.docs.scylladb.com/stable/upgrade.html

Problem
Operator docs pages does not mention upgrade path from v1.3.0 -> v1.4.0 and from v1.4.0 -> v1.5.0

Suggest a fix
Include upgrade path from v1.3.0 -> v1.4.0 and from v1.4.0 -> v1.5.0 with the relevant steps (as in the previous upgrade paths in the same doc)

**Comment by tnozicka** [comment]
there are no steps necessary. just update the deployment files with `kubectl apply -f`, `helm` or which ever way you've deployed it :)

**Comment by tnozicka** [comment]
there is a new section for generic upgrades
