### ISSUE TITLE
multiple --alternator-encryption-options configured in scyllaArgs will be malformed.

### ISSUE THREAD

**Issue by congguosn** [scylladb/scylla-operator#829]
**Describe the bug**

**To Reproduce**
1. configure scyllaArgs in the cr file like below:
    scyllaArgs: "--alternator-encryption-options certificate=/etc/scylla/cert/db.crt --alternator-encryption-options keyfile=/etc/scylla/key/db.key"
2. Restart the scylla cluster.
3. Log into one pod, run ps aux|grep scylla, will see the arguments of --alternator-encryption-options be malformed.
4. root    386  115 28 01:14 ?    00:00:06 /usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-15 --smp 15 --overprovisioned --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=10.100.170.224 --broadcast-address 10.100.170.224 --broadcast-rpc-address 10.100.170.224 --blocked-reactor-notify-ms 999999999 --prometheus-address=0.0.0.0 **--alternator-encryption-options=keyfile=/etc/scylla/key/db.key**

**Expected behavior**
keyfile and certfile are both in the application argument list.

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**
Please, provide `kubectl get events`, `kubectl logs -n scylla pod-name` and other relevant information.

**Environment:**
 - Platform: EKS
 - Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
 - Scylla version: 4.5.1
 - Scylla-operator version: 1.5

**Additional context**

**Comment by tnozicka** [comment]
There is now a proper Alternator API support in v1.12, including certificates
https://github.com/scylladb/scylla-operator/blob/51bf0f4/enhancements/proposals/1405-alternator/README.md
