### ISSUE TITLE
Scylla Manager task startDate is constantly updated 

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#838]
**Describe the bug**
Manager tasks defined in CRD having default startDate (`now`) are being rescheduled on every reconcilation. This is because `now` value is evaluated and compared with manager state. Of course it has a different value on each evaluation, hence task is updated.

**To Reproduce**
1. Define repair/backup task with default startDate
2. Update ScyllaCluster to trigger informers notification
3. Created task is updated with new startDate

**Expected behavior**
Start date `now` should be evaluated only on task creation.

**Comment by soyacz** [comment]
update: we still hit it in 1.10

**Comment by soyacz** [comment]
update: we still hit it in 1.11
