### ISSUE TITLE
Scylla Pod get restarted when node is overloaded

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla-operator#844]
**Describe the bug**
Scylla may get restarted when it's overloaded due to timeouts on liveness and readiness probes

![Selection_004](https://user-images.githubusercontent.com/3951334/142844015-17cd9650-cc79-4461-a10b-4a931db5c907.png)

**To Reproduce**
1. Deploy Scylla cluster
2. Overload it to 100%
3. Scylla is getting restarted due to timeouts on probes

**Expected behavior**
Scylla Pods survives overload

Liveness probe doesn't need to determine address to connect to, it's already available in Prober. 
Readiness probe is getting unnecessary information, like host ID or datacenter. 
Figure out if it's possible to determine UN state using single API call instead 4.

**Comment by zimnx** [comment]
AFAIR this was related to routing probes via Scylla Manager Agent container, which had low resources. We got rid of this routing long time ago, so issue shouldn't persist anymore.

**Comment by rzetelskik** [comment]
@zimnx [this TODO](https://github.com/scylladb/scylla-operator/blob/d4da9dfe44e55d7dd674a3d0394eafb5f309af2f/pkg/controller/scylladbdatacenter/resource.go#L784) references this issue - should we revert it?

**Comment by zimnx** [comment]
lowering them to previous values should be fine
