### ISSUE TITLE
Scylla cluster fails to be rolled out after operator upgrade

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#863]
**Describe the bug**
If we upgrade operator from the v1.5.0 version to the v1.6.0-rc.0 one. Then existing Scylla clusters fail to be rolled out with the following error:

```
I1129 09:31:21.061931       1 operator/sidecar.go:218] "Waiting for single service informer caches to sync"
I1129 09:31:21.162317       1 operator/sidecar.go:235] "Waiting for Service" Service="scylla/sct-cluster-us-east1-b-us-east1-2"
I1129 09:31:21.166368       1 operator/sidecar.go:269] "Waiting for Pod To have scylla ContainerID set" Pod="scylla/sct-cluster-us-east1-b-us-east1-2"
E1129 09:31:21.170105       1 cache/reflector.go:138] k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1.Pod: unknown (get pods)
I1129 09:31:21.170175       1 operator/sidecar.go:323] "Waiting for NodeConfig's data ConfigMap " Selector="scylla-operator.scylladb.com/config-map-type=NodeConfigData,scylla-operator.scylladb.com/owner-uid=ac58be37-ed23-454f-8267-f34ae09ef5fe"
I1129 09:38:13.055910       1 signals/signal.go:26] Received shutdown signal: terminated; shutting down...
Error: can't wait for optimization: timed out waiting for the condition
```

**To Reproduce**
1. Deploy operator v1.5.0 (latest stable)
2. Deploy a Scylla cluster
3. Upgrade operator to v1.6.0-rc.0

**Expected behavior**
Scylla cluster must successfully get rolled out after operator upgrade.

**Logs**
[EKS logs](https://cloudius-jenkins-test.s3.amazonaws.com/8cd4b20d-dd42-48eb-99c3-46da6f12817e/20211129_093839/kubernetes-8cd4b20d.tar.gz)
[GKE logs](https://cloudius-jenkins-test.s3.amazonaws.com/1a3969dc-fded-46d5-8eaa-34dcfe6f195f/20211129_094625/kubernetes-1a3969dc.tar.gz)

**Environment:**
 - Platform: EKS, GKE
 - Kubernetes version: v1.20 (may be any version)
 - Scylla version: 4.4.5
 - Scylla-operator version: v1.6.0-rc.0

**Additional context**

**Comment by tnozicka** [comment]
```
E1129 09:38:38.914013       1 cache/reflector.go:138] k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ScyllaOperatorConfig: failed to list *v1alpha1.ScyllaOperatorConfig: the server could not find the requested resource (get scyllaoperatorconfigs.scylla.scylladb.com)

have you installed https://github.com/scylladb/scylla-operator/blob/v1.6.0-rc.0/deploy/operator/00_scylla.scylladb.com_scyllaoperatorconfigs.yaml ?

**Comment by vponomaryov** [comment]
> ```
> E1129 09:38:38.914013       1 cache/reflector.go:138] k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ScyllaOperatorConfig: failed to list *v1alpha1.ScyllaOperatorConfig: the server could not find the requested resource (get scyllaoperatorconfigs.scylla.scylladb.com)
> ```
> 
> have you installed scyllaoperator config crd? https://github.com/scylladb/scylla-operator/blob/v1.6.0-rc.0/deploy/operator/00_scylla.scylladb.com_scyllaoperatorconfigs.yaml

If we use helm chart v1.6.0-rc.0 to install operator from scratch then everything works, 
but if we use this chart for upgrade then reported error appears.
Then, the asked resource is not expected to be created manually. So, the bug is in either helm charts or operator code.
I assume that the problem is in the helm chart.
