### ISSUE TITLE
Incorrect svc name for webhook

### ISSUE THREAD

**Issue by gecube** [scylladb/scylla-operator#904]
Hello!

I'm installing scylla-operator with the help of fluxv2 tooling.
The description of HelmRelease as follows:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scylla-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: scylla-operator
      sourceRef:
        kind: HelmRepository
        name: scylla
      version: '*'
  install:
    createNamespace: true
  targetNamespace: scylla-operator
  interval: 1m0s
```

Everything looks fine:
```bash

$ kubectl get -n scylla-operator pods                          
NAME                               READY   STATUS    RESTARTS   AGE
scylla-operator-7fcbcbc68d-b47rs   1/1     Running   0          5m1s
scylla-operator-7fcbcbc68d-rzw8x   1/1     Running   0          5m1s
webhook-server-7c5989d8d4-5sz8r    1/1     Running   0          5m1s
webhook-server-7c5989d8d4-cfmbb    1/1     Running   0          5m1s
$ kubectl get -n scylla-operator svc 
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
scylla-operator-webhook   ClusterIP   10.245.139.248   <none>        443/TCP   5m22s
```

But I couldn't install manager as it failes with the next issue:
```
Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": Post "https://scylla-operator-scylla-operator-webhook.scylla-operator.svc:443/validate?timeout=10s": service "scylla-operator-scylla-operator-webhook" not found
```

I think that the issue is because the webhook is incorrectly configured:

```
 kubectl get validatingwebhookconfigurations scylla-operator  -oyaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: scylla-operator/scylla-operator-serving-cert
    meta.helm.sh/release-name: scylla-operator-scylla-operator
    meta.helm.sh/release-namespace: scylla-operator
  creationTimestamp: "2021-12-29T11:52:33Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: scylla-operator
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: scylla-operator
  resourceVersion: "139536465"
  uid: dfbfcf5d-611c-493b-bb13-cea83144d9ae
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ...
    service:
      name: scylla-operator-scylla-operator-webhook
      namespace: scylla-operator
      path: /validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: webhook.scylla.scylladb.com
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - scylla.scylladb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scyllaclusters
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```

I think it happens because of this line https://github.com/scylladb/scylla-operator/blob/aebf760bda6831eac6ce0a8388c0b4fcf8e78464/helm/scylla-operator/templates/validatingwebhook.yaml#L12
In the same time the service name is hardcoded:
https://github.com/scylladb/scylla-operator/blob/67ccefa132eb8887e888431fa29ff33abd33f78a/helm/scylla-operator/templates/webhookserver.service.yaml#L5

### Expected behaviour:

The webhook is created with `scylla-operator-webhook` service name.

**Comment by gecube** [comment]
BTW, it must be changed also here: https://github.com/scylladb/scylla-operator/blob/6e9424fa2c4206c1e3e6fd74b9398e5a36d91f26/helm/scylla-operator/templates/certificate.yaml#L9

**Comment by gecube** [comment]
Another interesting observation - webhook-server from scylla-operator doesn't reload updated certificate from filesystem when it is reissued by cert-manager. I worry because every certificate has it's own expiration date. Of course, deletion of webhook-server helps...

**Comment by tnozicka** [comment]
I guess it's best not to play with the names, but someone will look into fixing it, or feel free to send a PR.

You are right about the live reload, that's already being worked on in https://github.com/scylladb/scylla-operator/pull/764

**Comment by gecube** [comment]
The bug is still actual. I faced with it again on v1.7.2 helm release.
