### ISSUE TITLE
Ability to customize the port Scylla's probes listen on from 8080

### ISSUE THREAD

**Issue by ChristopherCharlesTodd** [scylladb/scylla-operator#908]
**Feature Request**
Allow individuals to change the port Scylla's probes listen on. Currently, you are forced to use 8080, and adapt your existing app's configurations around Scylla. It should be the other way around.

**What is use case behind this feature:**
While implementing Scylla in our QA envs, we received the following error:
`[operator/sidecar.go:422] ListenAndServe failed: %vlisten tcp :8080: bind: address already in use`

The fix was to move an existing capability from 8080, so it would free the port up for Scylla. For our specific codebase, this was not an issue. However, I can envisage it causing more trouble in other customers bespoke codebases.

**Comment by tnozicka** [comment]
Just noting down here that this is an issue when using hostNetworking as the probe then listens on the node network.

**Comment by rverma-nsl** [comment]
Is there any fix for this? Even in nightly builds?

**Comment by rzetelskik** [comment]
@rverma-nsl the port is not customizable at the moment, but it shouldn't cause any issues as long as you're not using hostNetworking

**Comment by tnozicka** [comment]
> Wdyt about disabling the host networking here

This is the way.

https://github.com/scylladb/scylla-operator/issues/1378
