### ISSUE TITLE
Add additional labels to resources created

### ISSUE THREAD

**Issue by piclemx** [scylladb/scylla-operator#918]
* Feature Request
Add additional labels to resources created by the operator. 

**What should the feature do:**
This feature should add the labels on the resources that will be created by the operator.

**What is use case behind this feature:**
Often, company have business rules that verify the presence of specific labels for tracking purpose. This block the creation of the resources by the operator itself.

**Additional Information:**

**Comment by containeers** [comment]
This use case is needed even for cost tagging labels.

**Comment by pawankkamboj** [comment]
Any update on this feature?

**Comment by tnozicka** [comment]
tracked in https://github.com/scylladb/scylla-operator/issues/1590
