### ISSUE TITLE
no longer able to set these annotations

### ISSUE THREAD

**Issue by ricardoborenstein** [scylladb/scylla-operator#932]
Hello,
A customer has updated their Scylla operator to 1.7.0. However, the new behavior of the operator, in regards to it now handling the cluster-member SAs for the other components, seems to have broken their implementation.
Previously, their Scylla cluster's SAs (including the manager's own) contained the following annotations (configured by an own chart)
`
eks.amazonaws.com/role-arn: arn:aws:iam::<aws.account.id>:role/<cluster name>-member
`
These annotations allowed access to the s3 buckets
However, now that the operator is automatically managing these SAs, it seems I am no longer able to set these annotations.
is there a way to either override this behavior at all?

**Comment by tnozicka** [comment]
Hi @ricardoborenstein, we are sorry this happened. Unfortunately, our QA uses different storage setup that kept working and nobody has reported back any issues on https://github.com/scylladb/scylla-operator/tree/v1.7.0-rc.0 We are working on a fix to allow setting an extra annotation on the managed account.

**Comment by tnozicka** [comment]
You can fix the issue by just adding the annotation back on the SA. It's gonna be kept until we need to update (change) the SA but we'll fix the logic by then to tolerate it.

**Comment by ricardoborenstein** [comment]
Thank you team! I already notified the customer

**Comment by ricardoborenstein** [comment]
Hi, 
We will need to have a backport for the customer, he cannot wait until the 1.8 release

**Comment by zimnx** [comment]
@ricardoborenstein 1.7.1 is on the way
