### ISSUE TITLE
Add support for restore from backup for FULL cluster (clone) with initial tokens (much faster than sstableloader)

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-operator#940]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
support restore of full cluster (clone)
by using initial token ranges

**What is use case behind this feature:**
clone of a cluster / migrate of existing operator managed cluster

**Additional Information:**

This playbook basically describes what is happening :
https://github.com/scylladb/scylla-manager/tree/master/ansible/restore

scylla manager supports this, it was performed few times for various customers (on-prem, field cloud, scylla cloud), just operator support is kinda missing

**Comment by tarzanek** [comment]
expected performance bonus is like 3x when compared to sstable

the drawback is of course downtime

**Comment by rzetelskik** [comment]
On of the Operator meetings we discussed implementing this using Scylla's [load and stream feature](https://github.com/scylladb/scylla/pull/7846). Not a high priority for now though.

**Comment by mykaul** [comment]
I'm not sure that's a 1.9 material. I'd defer.
