### ISSUE TITLE
Error in `xfs-formatter`  in GKE

### ISSUE THREAD

**Issue by javiramos1** [scylladb/scylla-operator#946]
**Describe the bug**
`xfs-formatter` is failing with the latest cluster version in GKE.

**To Reproduce**
- Follow [guide](https://operator.docs.scylladb.com/stable/gke.html#) step by step
- Once you get to `install-xfs-formatter-daemonset` Run:
- `kubectl apply -f examples/gke/xfs-formatter-daemonset.yaml`

**Expected behavior**
Daemon set deploys without error

**Actual behavior**
Error in Pods.

It used to work fine.

**Logs**
```
+ cp -r /usr/local/lib/scylla-operator/gke/xfs-formatter /host/var/lib/
+ [[ ! -d /host/usr/local/lib/systemd ]]
+ mkdir /host/usr/local/lib/systemd
mkdir: cannot create directory '/host/usr/local/lib/systemd': No such file or directory

```

**Environment:**
 - Platform: GKE
 - Kubernetes version:  1.22.6-gke.300
 - Scylla version: master
 - Scylla-operator version: e.g.: master

**Comment by tnozicka** [comment]
> Scylla version: master
> Scylla-operator version: e.g.: master

what's your operator version?

**Comment by javiramos1** [comment]
Hi, I found the issue. I changed the image to `COS_CONTAINERD`. Reverting to `UBUNTU_CONTAINERD` fixed the issue.

I just suggest making it clear that you need to use that particular image in the documentation.
