### ISSUE TITLE
Pod PreStop hook failed on Scylla 4.6.0

### ISSUE THREAD

**Issue by rueian** [scylladb/scylla-operator#954]
**Describe the bug**

The operator use the name `scylla` with the supervisorctl:

https://github.com/scylladb/scylla-operator/blob/44dcc72c09e65ff82dea5db44e62439304d0e636/pkg/controller/sidecar/sync.go#L46

https://github.com/scylladb/scylla-operator/blob/18f9c04f0a1aa0ea54714a21492f808f7ff5903e/pkg/controller/scyllacluster/resource.go#L412

However, in the scylla 4.6.0 docker image, the name should be `scylla-server`

As a result, the PreStop hook will just fail to stop the scylla process.

**Comment by zimnx** [comment]
Ref: https://github.com/scylladb/scylla/issues/10269
