### ISSUE TITLE
docs: update theme to 1.2.1

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/scylla-operator#963]
Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/310

ScyllaDB Sphinx Theme 1.2.1 is now released 🥳 

We’ve added automatic checks for broken links and introduced numerous UI updates.

You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/stable/upgrade/CHANGELOG.html#march-2022).

## Upgrade guide

For most repositories, we are sending pull-requests with new updates. Unfortunately, we cannot do this for this project since the [docs workflows](https://github.com/scylladb/sphinx-scylladb-theme/tree/master/.github/workflows) shared between all projects to build the docs [were highly modified](https://github.com/scylladb/scylla-operator/tree/master/.github/workflows).

> **TIP:** If you modify these workflows in your repository, you will need to maintain the changes. So instead, we recommend you to open an issue / pull-request in the [sphinx-scylladb-theme repository](https://github.com/scylladb/sphinx-scylladb-theme) so that all projects can benefit from the improvements you made.

Here you have resources to help you upgrade the docs toolchain to the latest version:

- [Migrating from 1.1 to 1.2](https://sphinx-theme.scylladb.com/master/upgrade/1-1-to-1-2.html)
- [Example pull-request](https://github.com/scylladb/scylla-monitoring/pull/1709/files)
- [CHANGELOG](https://sphinx-theme.scylladb.com/stable/upgrade/CHANGELOG.html#march-2022)

Do not hesitate to contact me (@dgarcia360 in Slack) if you face any issues during the process.

**Comment by annastuchlik** [comment]
Hello, could you merge this PR to update the theme?
It's getting urgent because currently, the documentation search does not show results for Operator, so it's hard for the users to find information.
The new theme includes the required updates to make the Operator docs searchable.
