### ISSUE TITLE
AWS: build EKS AMI for Scylla nodes

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#97]
Scylla AMI provides performance features for Scylla, among other things disks are joined into a RAID array, but it's not limited to that. It is not possible to use Scylla AMI directly as a Kubernetes Node. Kubernetes in AWS needs a special AMI, [this guide](https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/) describes how to build one using packer. In [scylla-machine-image](https://github.com/scylladb/scylla-machine-image) we have AMI that are Scylla AMIs.

For this task we need to 
* Copy the scylla setup scripts from scylla
* Build EKS AMI that runs a variation of https://github.com/scylladb/scylla-machine-image/blob/master/aws/ami/files/scylla_install_ami on boot

**Comment by mmatczuk** [comment]
Relates to #93

**Comment by tzach** [comment]
@penberg should this be an issue in https://github.com/scylladb/scylla-machine-image ?

**Comment by dahankzter** [comment]
> @penberg should this be an issue in https://github.com/scylladb/scylla-machine-image ?

I think it does belong in packaging rather than in the operator repo.

**Comment by slivne** [comment]
Hm ...

Its not clear to me who is responsible to patch the instances for security risks - does AWS provide any info on that

**Comment by mmatczuk** [comment]
There is a work around using CloudFormation userdata, this is what I use now.

> Its not clear to me who is responsible to patch the instances for security risks - does AWS provide any info on that

You can run a managed nodes or unmanaged (manage yourself) 

https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html

Instances in a managed node group use the latest version of the Amazon EKS-optimized Amazon Linux 2 AMI for its cluster's Kubernetes version. You can choose between standard and GPU variants of the Amazon EKS-optimized Amazon Linux 2 AMI.

If we want managed this is probably not an option.

**Comment by tnozicka** [comment]
We have already implemented generic and multiplatform tuning without custom AMIs.
