### ISSUE TITLE
Revert conntrack-cleaner DaemonSet addition

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#975]
We had to add [conntrack-cleaner ](https://github.com/hanamantagoudvk/conntrack-cleaner) in #973 as a workaround for #971. Since the issue has apparently been fixed by a kernel patch added in linux-5.14, we should revert it and remove related TODOs after our CI switches to a higher kernel version.

**Comment by zimnx** [comment]
Looks like kernel is already updated:
```
$ cat cluster-scoped-resources/nodes.yaml | grep kernel
      kernelVersion: 5.15.0-1023-azure
