### ISSUE TITLE
perf: Investigate CPU pinning for in nodes

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#98]
* https://builders.intel.com/docs/networkbuilders/cpu-pin-and-isolation-in-kubernetes-app-note.pdf
* https://www.alibabacloud.com/blog/kubernetes-cpu-management-policies_595205
* https://www.percona.com/blog/2019/05/09/measuring-mysql-performance-kubernetes/

**Comment by gnumoreno** [comment]
https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#cpu-management-policies
https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed
https://docs.openshift.com/container-platform/3.9/scaling_performance/using_cpu_manager.html

**Comment by mykaul** [comment]
Can we update the status of this issue?

**Comment by tnozicka** [comment]
I think this is done. @zimnx do you agree or do you recall something missing?

**Comment by zimnx** [comment]
yes, feature-wise it's done. There're couple of followups to it though: #1151, #1147. We could also invest some time veryfing whether tuning for bigger multi numa instances is correct.

**Comment by tnozicka** [comment]
Given we track those separately, I'll close this one.
