### ISSUE TITLE
the operator installed namespace shouldn't be fixed to scylla-operator

### ISSUE THREAD

**Issue by songdongsheng** [scylladb/scylla-operator#987]
The current Helm Chart used a hard coded namespace name `scylla-operator`, e.g.

https://github.com/scylladb/scylla-operator/blob/161d249ee97fd905987255017df29225dbe99ed5/helm/scylla-operator/templates/operator.deployment.yaml#L5

The operator installed namespace should be changed if the user want, e.g. install to namespace `scylladb` instead of `scylla-operator`.

**Comment by tnozicka** [comment]
it is intentional, reasons are given in https://github.com/scylladb/scylla-operator/pull/667
