### ISSUE TITLE
syncing key 'scylla/sct-cluster' failed: No Major.Minor.Patch elements found

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-operator#998]
### Installation details
Kernel version: `5.4.196-108.356.amzn2.x86_64`
Scylla version (or git commit hash): `5.1.dev-0.20220702.4fd289a78ca3 with build-id c283da9c1dcf5cb79aad53e1781c6a9443dece6c`
Cluster size: 3 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   sct-cluster-us-east1-b-us-east1-0 (10.0.2.5 | 10.0.1.113): 15 shards
   sct-cluster-us-east1-b-us-east1-1 (10.0.2.34 | 10.0.0.119): 15 shards
   sct-cluster-us-east1-b-us-east1-2 (10.0.2.224 | 10.0.0.13): 15 shards
Scylla running with shards number (terminated nodes):
   sct-cluster-us-east1-b-us-east1-3 (10.0.3.220 | 10.0.3.203): 15 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-3h-eks`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a870cc521c8b68088a3128c0ed96bd299a805e7e/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)

### Issue description

change of the CPUs, with patching the scylla cluster values:
```python
        self.log.info(
            "Update the cpu count to '%s' CPUs to make Scylla start "
            "the resharding process on all the nodes 1 by 1", cpus)
        self.tester.db_cluster.replace_scylla_cluster_value(
            "/spec/datacenter/racks/0/resources", {
                "limits": {
                    "cpu": cpus,
                    "memory": self.cluster.k8s_cluster.calculated_memory_limit,
                },
                "requests": {
                    "cpu": cpus,
                    "memory": self.cluster.k8s_cluster.calculated_memory_limit,
                },
            })
```

failed with the following error in operator:
```
E0703 00:09:43.565569       1 scyllacluster/controller.go:213] syncing key 'scylla/sct-cluster' failed: No Major.Minor.Patch elements found
```

Restore Monitor Stack command: `$ hydra investigate show-monitor 739a395f-86c3-487a-99a6-804b6e7b4601`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=739a395f-86c3-487a-99a6-804b6e7b4601)
Show all stored logs command: `$ hydra investigate show-logs 739a395f-86c3-487a-99a6-804b6e7b4601`

Test id: `739a395f-86c3-487a-99a6-804b6e7b4601`

### Logs
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220702_235605/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220702_235718-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220702_235605/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220702_235718-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220702_235605/grafana-screenshot-overview-20220702_235605-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220702_235605/grafana-screenshot-overview-20220702_235605-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_000320/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_000357-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_000320/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_000357-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_000320/grafana-screenshot-overview-20220703_000320-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_000320/grafana-screenshot-overview-20220703_000320-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_011454/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_011530-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_011454/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_011530-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_011454/grafana-screenshot-overview-20220703_011454-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_011454/grafana-screenshot-overview-20220703_011454-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_013341/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_013420-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_013341/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_013420-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_013341/grafana-screenshot-overview-20220703_013341-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_013341/grafana-screenshot-overview-20220703_013341-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_014528/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_014603-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_014528/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_014603-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_014528/grafana-screenshot-overview-20220703_014528-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_014528/grafana-screenshot-overview-20220703_014528-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_022700/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_022735-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_022700/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_022735-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_022700/grafana-screenshot-overview-20220703_022700-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_022700/grafana-screenshot-overview-20220703_022700-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_023350/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_023425-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_023350/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_023425-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_023350/grafana-screenshot-overview-20220703_023350-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_023350/grafana-screenshot-overview-20220703_023350-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_025026/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_025102-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_025026/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_025102-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_025026/grafana-screenshot-overview-20220703_025027-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_025026/grafana-screenshot-overview-20220703_025027-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_025716/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_025753-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_025716/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_025753-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_025716/grafana-screenshot-overview-20220703_025717-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_025716/grafana-screenshot-overview-20220703_025717-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_030006/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_030043-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_030006/grafana-screenshot-longevity-scylla-operator-3h-eks-scylla-per-server-metrics-nemesis-20220703_030043-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_030006/grafana-screenshot-overview-20220703_030007-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_030006/grafana-screenshot-overview-20220703_030007-longevity-scylla-operator-3h-master-monitor-node-739a395f-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/db-cluster-739a395f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/db-cluster-739a395f.tar.gz)
kubernetes - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/kubernetes-739a395f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/kubernetes-739a395f.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/loader-set-739a395f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/loader-set-739a395f.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/monitor-set-739a395f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/monitor-set-739a395f.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/sct-runner-739a395f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/739a395f-86c3-487a-99a6-804b6e7b4601/20220703_031058/sct-runner-739a395f.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-eks/9/)

**Comment by vponomaryov** [comment]
The problem is with the Scylla versioning, it is not semver-like.
See history: [1] and [2]

Scylla-operator won't make any changes to Scylla pods with non-semver tags.
So, upgrade and restart of Scylla pods won't work. It is expected.

So, it comes out that not all new Scylla docker images have proper semver-like tags.

[1] https://github.com/scylladb/scylla-operator/issues/180
[2] https://github.com/scylladb/scylla/issues/9543

**Comment by fruch** [comment]
> The problem is with the Scylla versioning, it is not semver-like. See history: [1] and [2]
> 
> Scylla-operator won't make any changes to Scylla pods with non-semver tags. So, upgrade and restart of Scylla pods won't work. It is expected.
> 
> So, it comes out that not all new Scylla docker images have proper semver-like tags.
> 
> [1] #180 [2] [scylladb/scylla#9543](https://github.com/scylladb/scylla/issues/9543)

@vponomaryov could be that since we are using `latest` tag it doesn't work ? i.e. for functional test we hit it straight up, and the longevity, we didn't don't replace the tags (like I was planning todo for the functional test

**Comment by vponomaryov** [comment]
> > The problem is with the Scylla versioning, it is not semver-like. See history: [1] and [2]
> > Scylla-operator won't make any changes to Scylla pods with non-semver tags. So, upgrade and restart of Scylla pods won't work. It is expected.
> > So, it comes out that not all new Scylla docker images have proper semver-like tags.
> > [1] #180 [2] [scylladb/scylla#9543](https://github.com/scylladb/scylla/issues/9543)
> 
> @vponomaryov could be that since we are using `latest` tag it doesn't work ? i.e. for functional test we hit it straight up, and the longevity, we didn't don't replace the tags (like I was planning todo for the functional test)
> 
> **Edit** here's the PR for doing exactly this [scylladb/scylla-cluster-tests#4971](https://github.com/scylladb/scylla-cluster-tests/pull/4971)

` 5.1.dev-0.20220702.4fd289a78ca3` is not semver-like. So, specific Scylla tags still violate semantic versioning.
